### ISSUE TITLE
Better validation

### ISSUE THREAD

**Issue by jlambe** [themosis/framework#102]
Enhance the current validation class. Allow developers to associate error messages to inputs if not valid.

Also, in place of creating an `$errors` variable in a local scope, give the validation class the responsability to check if there are no errors. This also means that in place of returning an array with, valid or not, data, a validation instance is returned when calling `Validator::multiple()`.

Note: Perhaps keep the `Validator::single()` to return the data or not. It might be used for specific or out of context validation.

**Comment by cdarken** [comment]
I was wondering, why didn't you just fork the validation library from laravel?

**Comment by jlambe** [comment]
Well the difference is that the validation class returns a sanitized version of the data which the laravel class do not. But I might fork it in a next release and provides a separate class which will sanitize data.

**Comment by cdarken** [comment]
Well, a fork would not be required after all, you can just pull it as a dependency and just extend it. That's what I'm doing now in a project that I'm working on, because I believe that the Validator class from Themosis acts more like a sanitizer.

**Comment by jlambe** [comment]
We're going to implement the `illuminate/validation` class and deprecate our own class.
