### ISSUE TITLE
Filter media only for the current post

### ISSUE THREAD

**Issue by ogorzalka** [themosis/framework#107]
Hi,

Is this possible to restrict media the media only for those attached to the post in the collection and media field ?

I haven't found an argument for it inside the method.

Thanks for your answer and congratulation for your work.

**Comment by jlambe** [comment]
Hi,

I don't understand what you're trying to achieve. You have assigned media files using the Collection field inside a post then what restrictions do you need ?

**Comment by frontherd** [comment]
Hi,

Media from other posts also appear when I open the media modal box. When there is media hugely on the site, the organization becomes complicated.

Thanks!

**Comment by jlambe** [comment]
Currently it's not "possible". So the idea would be to upload new files and when editing, view only those files when opening the media window. Might be useful but I'll need to digg into the Media API. Perhaps on a future update...
