### ISSUE TITLE
admin folder, DirectoryIterator not loading in alphabetical order. [Theme specific helpers file]

### ISSUE THREAD

**Issue by cdarken** [themosis/framework#108]
Hi.
I'm trying to find a file where to include my own helpers file. I found bootstrap/start.php but I don't know if that's the right location. I would like my file to be inside my theme, but if there's no other way I can put it in the bootstrap dir.

**Comment by jlambe** [comment]
You can insert it inside the `app/admin` directory. All files located at the root of this folder are auto-loaded by alphabetical order.

**Comment by solverat** [comment]
true, in some environments the alphabetical ordering will not work. you have to be sure, that the right ordering will be dispatched before the foreach loop is loading the php files. to do so, you need to update the **Loader.php** which is located under

```php
htdocs/content/mu-plugins/themosis-framework/src/Themosis/Core/Loader.php
```
and replace the *protected static function append($path)* with that:

```php
protected static function append($path)
    {
		if (is_dir($path))
        {
			$dir = new \DirectoryIterator($path);

            $files = array();

			foreach ($dir as $file)
            {
				if (!$file->isDot() || !$file->isDir())
                {
					$file_extension = pathinfo($file->getFilename(), PATHINFO_EXTENSION);

					if ($file_extension === 'php')
                    {

						static::$names[] = $file->getBasename('.php');
                        $files[] = array( 'name' => $file->getBasename('.php'), 'path' => $file->getPath().DS.$file->getBasename() );

					}
				}
			}

            if( !empty( $files ) ) {

                usort($files, function($a, $b) {
                    return strnatcmp($a['name'],$b['name']);
                });

                foreach( $files as $file ) {

                    include_once $file['path'];

                }
            }

			return true;
		}
		
		return false;
	}
```
