### ISSUE TITLE
Upgrading Example

### ISSUE THREAD

**Issue by nathanaelphilip** [themosis/framework#112]
Can we get an example on how to upgrade to 1.1.3. I just tried running composer update and it erases all the files in my themesos-theme folder.

**Comment by jlambe** [comment]
Normally you have to `rename` the `themosis-theme` regarding your project. So if it is done, you're running `composer update` your theme won't be replaced.

`themosis-theme` is the default name for the theme package used by composer. So if composer finds it in your application and make an update, it will update the package...your theme. That's one reason why it is best to change your theme name. So when you run `composer update` you get your theme and new `themosis-theme` installed back and you can check differences or copy/paster bits of code.

Or you can simply remoce the call to `themosis/theme` inside the `composer.json` file so it won't try to update the theme.

1.1.3 is a minor update so there is nothing to change in your theme it work. Only when there is a major update like the next one 1.2.0, perhaps your theme will need so tweaks. But if there are changes to make, I'll write a documentation for that. Hope this helps.

**Comment by nathanaelphilip** [comment]
perfect. thank you.
