### ISSUE TITLE
Error when removing a field from Field::infinite after it was saved

### ISSUE THREAD

**Issue by cdarken** [themosis/framework#114]
If I remove a field that is inside an infinite field that was previously saved, I get this error:
```
Argument 1 passed to Themosis\Core\Wrapper::parseValue() must be an instance of Themosis\Field\Fields\FieldBuilder, null given, called in htdocs/content/mu-plugins/themosis-framework/src/Themosis/Core/Wrapper.php on line 118 and defined
```
This does not happen if I remove a field outside of an infinite one.

**Comment by jlambe** [comment]
Will merge this on next major release. Thanks for catching this one.

**Comment by cdarken** [comment]
I reviewed this and it seems that is not a fix, because the compiler will complain that the argument cannot be null. The correct fix will require setting the default value for the first parameter of parseValue() method to null. Is this acceptable? If so I will create a new pull request or maybe you will find a better solution for this.

**Comment by jlambe** [comment]
You can rewrite your patch by proposing a default value and we'll look at
it later on. Thanks.

2015-03-20 13:34 GMT+01:00 Cătălin Georgescu <notifications@github.com>:

> I reviewed this and it seems that is not a fix, because the compiler will
> complain that the argument cannot be null. The correct fix will require
> setting the default value for the first parameter of parseValue() method to
> null. Is this acceptable? If so I will create a new pull request or maybe
> you will find a better solution for this.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/themosis/framework/issues/114#issuecomment-84003822>.
>



-- 
[image: Logo][image: Marge]

*JULIEN LAMBE*
Founder
[image: BgInfos][image: Marge]

15, Rue Godefroid-Kurth
B-6700 Arlon
+32 488 32 39 94
http://www.themosis.com
