### ISSUE TITLE
Add Actions API

### ISSUE THREAD

**Issue by jlambe** [themosis/framework#116]
Allow developers to use controller classes to perform any actions in WordPress as well as closures by default.

Developers will be able to write actions like below:

```php
Action::add('init', function($args)
{
    // Action code using a closure.
});

// Will use an instance of "MyClass" and its "init" method
Action::add('init', 'MyClass');

// Or by defining a method
Action::add('init', 'MyClass@myInitMethod');
```

**Comment by dotMastaz** [comment]
Thank you for this feature !!

**Comment by jlambe** [comment]
:+1: Note that the AJAX class is not yet updated. The View API is already up to date using this Action API for `View::composer` methods ;)
