### ISSUE TITLE
File validator

### ISSUE THREAD

**Issue by cdarken** [themosis/framework#118]
If I set the validator for a media field like this: `'image' => ['file:jpg, jpeg, png']` and then choose a media file from the library, on save it disappears. What am I doing wrong?

**Comment by jlambe** [comment]
The media field is saving an **attachment_id**, so you don't need to use a validation.

By default the media field will take only images from the library. But if you want to select only documents (pdf, ...), you set the type attribute to `application` like so:

```php
Field::media('the-files', array('type' => 'application'))
```

Hope this helps. Here the fields doc: [http://framework.themosis.com/docs/field/](http://framework.themosis.com/docs/field/)

**Comment by cdarken** [comment]
And the validator by extension can be used in normal form, for file uploads, right?

**Comment by jlambe** [comment]
Yes it can. The file validation/sanitization check the file extension of filename basically. If the extension is found on the filename string then it passes otherwise it returns an empty string.

**Comment by cdarken** [comment]
Ok, I understand. Thanks.
