### ISSUE TITLE
Form checkable items not very flexible

### ISSUE THREAD

**Issue by cdarken** [themosis/framework#119]
Form::checkbox, radio does not accept a label text and cannot set attributes to the generated label element.

Maybe the private function makeGroupCheckableField should check for an attribute named label or labels in the attributes array and set that instead of ucfirst($choice), only using that when there are no labels provided.
This method could also work for label attributes, for setting classes for instance.

**Comment by jlambe** [comment]
Hi,

yes, I'm aware of this issue. There is pull request pending for this #87. The 1.2.0 version should fix this ;)

**Comment by cdarken** [comment]
I've made a commit on my fork for this. I can't see how pull request #87 can be useful to me.
This is the commit: https://github.com/cdarken/themosis-framework/commit/17bc5002cf0c5c5d1cc1f7bc02df5bf1f47c42a3
Check it out, if needed I can make a pull request.

This would have been easier if FormBuilder had the macro capability of Laravel's form builder.

**Comment by jlambe** [comment]
Well in this pull request, you can add custom labels to checkable fields this way:
```php
Form::checkbox('agree1', 'Terms of application', null, array('label'=>'<a href="route to .pdf">Terms of application</a>'));
```
You can pass a 4th argument and set a custom label using the `label´ key.

**Comment by cdarken** [comment]
In my version you can add labels even to multiple checkboxes, by using their names from the second argument.

**Comment by jlambe** [comment]
Please make a pull request with your code and I'll check both.

**Comment by cdarken** [comment]
I will try when I get some time, as I'm a bit busy at the moment.

**Comment by cdarken** [comment]
Done. I have the one related to the labels (#125) and another one for better radio input (#125).

**Comment by jlambe** [comment]
This has been merged on current master branch. The syntax has slightly changed but will be documented in new documentation very soon. Thanks
