### ISSUE TITLE
Admin page for Wordpress directed to home page

### ISSUE THREAD

**Issue by springgrass** [themosis/framework#122]
Hi,
I'm not sure it's a bug or a wrong configuration, I could not get to the WP admin page by going to siteurl/cms/wp-admin/ .  It redirect to home page.  Any other page resulted a 404 error.

Thanks.

**Comment by jlambe** [comment]
Hi,
by default the `cms/wp-admin` URI is not accessible for **non-logged** users. The first time you connect, you have to use this URI `cms/wp-login.php`

Also, when you change the permalink structure to something else than default, you'll be able to access the login form by using this URI `/login`

Regards,

**Comment by springgrass** [comment]
Thanks much Julien.  
Changing the permalink structure to something else than default does the trick.

**Comment by jlambe** [comment]
Cool. Glad it works.
