### ISSUE TITLE
Custom post meta fields get combined

### ISSUE THREAD

**Issue by cdarken** [themosis/framework#128]
When saving a custom post type from backend, it gets the metas for all other custom post types included after it.

**Comment by jlambe** [comment]
Not sure to understand your issue. Can you post your custom post type code and metabox/fields and give step by step instruction to replicate your issue?

**Comment by cdarken** [comment]
You create 2 files in app/admin/ to define 2 custom post types with at least one field:
post_type_1.php
```
$type1 = PostType::make('type1', 'Types', 'Type')->set([
  'show_ui' => true,
  'rewrite'   => [
    'slug'      => 'type1',
    'with_front' => false,
  ],
  'supports'  => ['title'],
]);

Metabox::make(__('Type 1'), 'type1')->set([
  Field::text('type1-field1')
]);
```
post_type_2.php
```
$type2 = PostType::make('type2', 'Types', 'Type')->set([
  'show_ui' => true,
  'rewrite'   => [
    'slug'      => 'type2',
    'with_front' => false,
  ],
  'supports'  => ['title'],
]);

Metabox::make(__('Type 2'), 'type2')->set([
  Field::text('type2-field1')
]);
```

If you save Type 1 you can see that it will have type2-field1 meta key in wp_postmeta

**Comment by jlambe** [comment]
Not sure this is an issue related to the framework. When you click on "Publish" when saving a custom post type, WordPress is calling the "save_post" action hook. WordPress will run all code attached with that hook. So it seems normal for me that you get the `type2-field1` meta saved in the DB with an empty value.

But we should probably share this issue with other WordPress devs in order to be sure.

**Comment by cdarken** [comment]
What do you think about testing if the current post submitted should be tested  in \Themosis\Metabox\MetaboxBuilder::save at line 203?
More precisely this
```
        if ($this->check && $this->datas['postType'] === $_POST['post_type'])
        {
            if (!$this->user->can($this->capability)) return;
        }
```
becoming this
```
        if ($this->check && $this->datas['postType'] === $_POST['post_type'])
        {
            if (!$this->user->can($this->capability)) return;
        }

        if ($this->datas['postType'] !== $_POST['post_type']) {
            return;
        }
```
It looks like it's working for me. Can you please run a quick test?

**Comment by jlambe** [comment]
Will test it this week. So it seems we can avoid to rewrite every time all post types data with this check. This will probably boost performance a little with less write operations on db.

**Comment by cdarken** [comment]
This is the right way to do it, and using instead get_post_type should be more secure that accessing $_POST, like in CMB2:
https://github.com/WebDevStudios/CMB2/blob/master/includes/CMB2_hookup.php#L339
