### ISSUE TITLE
Attachment routes

### ISSUE THREAD

**Issue by cdarken** [themosis/framework#130]
I didn't find in documentation how an attachment route is supposed to work. I did this:
```
Route::get('attachment', [function($a) {
  td($a);
}]);
```
But it still says no route defined.

**Comment by jlambe** [comment]
The route is correct.
But I noticed a typo in your code, you surrounded the closure in an array, only use an array if you need to specify a first argument otherwise simply pass the function without the array. like this:

```php
Route::get('attachment', function($a) {
    td($a);
});
```

If the issue persists, let me know.

**Comment by cdarken** [comment]
It's working for media attached to normal posts and also unattached media. But not working for attachments belonging to custom post types.

**Comment by jlambe** [comment]
Hmmm bizarre. Normally WordPress doesn't make a difference whether the attachment is in a post or custom one. How do you save/link the attachments to your custom post type?

**Comment by cdarken** [comment]
wp_insert_attachment($attachment, $file_name, $parent_id);

**Comment by jlambe** [comment]
Did you generate attachment metadata as well like described in the `wp_insert_attachment` function documentation?
https://codex.wordpress.org/Function_Reference/wp_insert_attachment
 
Can you also try with this function in place and let me know if the attachment is found correctly by the WordPress query: https://codex.wordpress.org/Function_Reference/media_handle_upload

**Comment by cdarken** [comment]
Yup, I did it the right way, in the wp admin interface they appear as attached to the right post. Though, does the parent post need to be published for the attachment to be accessible? I can't confirm that it's the case, I don't have my dev machine now. It's just a hunch, I will look at it tomorrow morning.

**Comment by cdarken** [comment]
Indeed, it looks like you need the post to be published for the attachment to be accessible.

**Comment by jlambe** [comment]
Ok that's good to know. Thanks for testing it.
