### ISSUE TITLE
Route 'front' not working as expected

### ISSUE THREAD

**Issue by infinitation** [themosis/framework#132]
WP 4.2.2 and Themoisis 1.1.3. I have set in my reading settings a page as my homepage. In my routes.php I have set the following:

Route::get('front', 'PagesController@homepage'); 

Which I have the controller and function setup. I get a no routes defined when I visit my site. All other routes for singular, and templates, are working without a hitch. The 'home' route when nothing is specified in the WP setting. 

Any suggestions or help would be appreciated. I don't know if I need to reload something through terminal, or what other settings to check.

**Comment by infinitation** [comment]
Ok, I isolated the issue, if you set a page as a 'front' and it has a 'Themosis Template' with it, it will not display. Once the template is not on the page, it works. Unfortunately, I need to have the front page be templated. Any help would be appreciated for a workaround, or help identifying where I can override this function intelligently.

**Comment by jlambe** [comment]
The routes are listened in the order you write them. If there is a match, then the route is used. If your front page needs a template, I suggest you to move the `Route::get('template',...)` statement before the front route (or simply remove the front route call).

Let me know how it goes.

**Comment by infinitation** [comment]
Gotcha! When added as a template route, it now works. Good simple solution. I would suggest a documentation update though. "When using a Themosis Template as a Front, use the template route instead of front".

Thanks so much for the quick feedback!

**Comment by jlambe** [comment]
No problem ;) Glad it is solved.
