### ISSUE TITLE
Customize metabox field templates

### ISSUE THREAD

**Issue by cdarken** [themosis/framework#133]
How can I customize the metabox field templates to be able to link to the attachments for instance? I want to be able to view files attached from frontend for custom post types.
If I add some options to the Field::media method to be able to specify other partial,  would you consider accepting a pull request?

**Comment by jlambe** [comment]
Describe the API using dummy code so I can see what exactly you want to do. One thing to keep in mind is that Field class must be compatible for use in posts, options, users meta, taxonomy metas, etc. Currently it is only use for posts and options but for next release all fields must work for user metas as well.

**Comment by cdarken** [comment]
That would not be necessary if I can overwrite the FieldFactory in the IoC. How can I do that?

**Comment by cdarken** [comment]
Actually, knowing how to access the container and overwrite providers in it would be a very valuable information.

**Comment by jlambe** [comment]
Actually you can't overwrite the class. You could probably extends it:
```php
class MyFieldFactory extends \Themosis\Field\FieldFactory {}
```

then use it to create your custom field or call the media field like so:
```php
$factory = new MyFieldFactory();
$factory->media('mediaName', $args, ...);
```

The IoC class is the \Themosis\Core\Container class but you can't access its instance inside the theme or plugin. One thing that could be possible in a future release is to create your own IgniterService (ServiceProvider) from where you can get access to the IoC class and add functionality but you can't register those IgniterService right now as there are no filters to add your own. You'll need to hardcode it into the main framework plugin which is not great when you update.

Again, I still don't understand what you're trying to do. Perhaps give more details about what you want to do with the attachments and probably there is another way for a solution.

**Comment by cdarken** [comment]
For now I just want to add a link to the file uploaded for a media field for easy access. Now there's just the id in a readonly input.

**Comment by jlambe** [comment]
And this link should be rendered/used in the front-end or back-end?

**Comment by cdarken** [comment]
In the admin section, where you have now the Attachment ID

**Comment by jlambe** [comment]
What I suggest you, is then duplicate the `Themosis\Field\Fields\MediaField` and its view file. Modify them as you want to display the attachment URL (normally it is just the view file to alter for this).

Let's say your field class name is now `MyCustomMediaField`. Modify the `metabox` or `page` methods to use your custom view file.

Then when using the `Field` class inside the Metabox, use it like so:

```php
// Properties for your media field.
$fieldProperties = [
    'name'    => 'someCustomName',
    'type'      => 'image' // or 'application', 'video',...
    'title'       => 'Attachments'
];

Metabox::make('Infos', $cpt->getSlug())->set([

    Field::make('MyCustomMediaField', $fieldProperties)

]);
```
This will allow you to use a custom field. Let me know how it goes.

**Comment by cdarken** [comment]
Yeah, this is a good idea. I should have taken the short path, as this is what you do in FieldFactory::media. Thanks a lot for the suggestion.

**Comment by cdarken** [comment]
I got it working satisfactory enough for now.

**Comment by jlambe** [comment]
Great, glad it is working. Don't hesitate to give me more feedback on how the API is running for custom work. Perhaps more enhancements can emerge from real situations. Thanks.
