### ISSUE TITLE
Accessible Template 

### ISSUE THREAD

**Issue by solverat** [themosis/framework#135]
sometimes it's necessary (i'm using acf pro heavily :) ) to get the list of available templates, because themosis avoids the default page templates. currently, there is i no way to get them.

```php
$t = new Themosis\Configuration\Template();
print_r( $t::names() ); // not possible, names() is private - and its a wrong naming to get them anyway i think
```

so the workaround for now is to get the config file directly:
```php
 $templates = include( themosis_path('app').'config'.DS.'templates'.CONFIG_EXT );
```

**Comment by jlambe** [comment]
Hi, yes the config file values are not accessible. Only the `application.config.php` file through the `App` alias.
For next release, it is planned to rewrite the config API, check this issue #106 

You'll be able to access each config file values like so:

```php
// Get the templates.config.php file array
Config::get('templates');

// Or single value
Config::get('templates.custom`)
```

**Comment by solverat** [comment]
perfect, thank you!
