### ISSUE TITLE
Post Type getSlug() Fallback

### ISSUE THREAD

**Issue by solverat** [themosis/framework#136]
while creating a new post type, it's possible to add a rewrite slug:
```php
 $pt = PostType::make('books', 'Books', Book')->set(array(

            'public'        => true,
            'menu_position' => 20,
            'rewrite'       => array('slug' => 'special_book_slug'),
            'query_var'     => false,
            'has_archive'   => false

));

add_action('init', function() use ( $pt )
{

       echo $pt->getSlug(); // echo "books", should echo "special_book_slug" (?)

});
```

what do you think? or, maybe a method like ```$pt->getRewriteSlug()``` would be nice?

**Comment by jlambe** [comment]
Normally the rewrite slug property is only used to change the permalink structure. Perhaps it's the name of the method which may confuse people as it is used only to retrieve the post type name value.

Currently the post type class keeps a record of all passed/defined data on a private instance property. Perhaps we could open the class so you can retrieve any values from your custom post type.

**Comment by solverat** [comment]
you're right, ```$pt->getSlug()``` treaded as $name is a little bit confusing. maybe it would be better to add an ```$pt->getName();``` method, which returns the cpt-Name and a ```$pt->getSlug();``` method for the recent slug.

```php
add_action('init', function() use ( $pt )  {

            //that looks good to me, but actually wont work properly.
            add_rewrite_rule($pt->getSlug() . '/page/([0-9]+)?$', 'index.php?page_id=xxx&paged=$matches[1]', 'top');

});
```

**Comment by jlambe** [comment]
Will probably change the method name or propose a method to get any defined property on the custom post type so there will be no need to hardcode values.

**Comment by solverat** [comment]
:+1:
