### ISSUE TITLE
Get name in Meta::get

### ISSUE THREAD

**Issue by ribeiroevandro** [themosis/framework#143]
In the loop `{{ Meta::get(Loop::id() 'types') }}` have the value of the return, not the custom title that declared using  `'flat' => 'Flat'` I would like to get the final name, "Flat".

```
#Example code
$house_type = array(
  Field::select('types', array(
      'flat' => 'Flat'
  ))
);

Metabox::make('Information - type', 'houses')->set($house_type);
```

**Comment by jlambe** [comment]
I think there is a type in your Field::select code. Try this:
```php
$house_type = [
    Field::select('types', [
        [
            'flat' => 'Flat'
        ]
    ])
];
```
Check the select field documentation - Basic Select field with custom values: http://framework.themosis.com/docs/field/
You need to pass an **array of array** for your select options.

**Comment by ribeiroevandro** [comment]
My question is how being called "Flat" in my view, the way shown in ducumentação, just got the return of "flat".

**Comment by jlambe** [comment]
Sorry, the array key is the value. Your 'Flat' value is for display only and is not saved in the DB. So if you want automatically a `Flat` value in your view, you have to change your array key name.

**Comment by ribeiroevandro** [comment]
Got it, it was something that was waiting, understanding the return that I am having, thank you.

**Comment by jlambe** [comment]
That's because it's only the value attribute of the option tag that is saved. From your code, here is the output of your select field option:
```html
<option value="flat">Flat</option>
```
I can't see a way to retrieve in a view the "Flat" text from the attribute. Glad it's working for you now.
