### ISSUE TITLE
Themosis and WP plugins.

### ISSUE THREAD

**Issue by demitrol** [themosis/framework#145]
Hi! How can i use wp plugins, BuddyPress and bbpress, for example, in project on themosis?
Or, can i use themosis for create only plugins for wordpress, and how can i do this?

**Comment by jlambe** [comment]
Hi,

first thing to keep in mind is that working with the Themosis framework, it is still WordPress development and all WordPress tools, plugins, themes work.

If you want to install WordPress plugins you can do it in several ways:
1. From the Plugins menu inside the WordPress "wp-admin"
2. By manually copying and pasting the plugin folder into the `htdocs/content/plugins` directory
3. Or, as we suggest **as best practice**, by defining your plugin as a dependency in the `composer.json` file located at the root of your project. Checkout [wpackagist.org](http://wpackagist.org/) for more info on how to load WordPress plugins and [getcomposer.org](https://getcomposer.org/) for more explanations about the `composer.json` file.

Currently there is no clear API for creating plugins that depend on the Themosis framework main plugin. It is coming along with next release and I will provide a plugin boilerplate code to start of with.

We already tested BuddyPress and BBPress with the framework and everything is working correctly so you're good to go.

**Comment by demitrol** [comment]
I installed BuddyPress and BBPress, and it working well with all themes, but how integrate it with themosis-theme, maybe it's question of routing, or something else. I can't find the way for do this.

**Comment by jlambe** [comment]
BuddyPress add some pages. Simply write a route to those pages and you're good to go.

You can also add specific routes like so:

```php
// Add this code to the application.php file located inside the admin folder for example
// A custom condition function.
function is_test()
{
    // Some logic that returns true or false.
    return true;
}

// Then add the conditional function to the Route class.
add_filter('themosisRouteConditions', function($conds)
{
    $conds['test'] = 'is_test';
    return $conds; // Always return an associative array.
});
```

Then in your `routes.php` file, you can listen to it like so:

```php
// In routes.php
Route::get('test', function()
{
    return "Hello from the test route.";
});
```
Check the **Routing** documentation, there is also an example with a WooCommerce route: [http://framework.themosis.com/docs/routing/](http://framework.themosis.com/docs/routing/)

**Comment by demitrol** [comment]
I wrote routes
 for buddypress pages:

    Route::get('page', array('activity', function(){

    return 'Hello world';

    }));


    Route::get('page', array('members', function(){

    return 'Hello world';

    }));

output was Hello world

 for bbpress pages:

    Route::get('page', array('forums', function(){

        return 'Hello world';

    }));
output: No route defined for this request...

**Comment by jlambe** [comment]
Yes this is normal. BBPress is using another conditional query than page to retrieve the forums.

Check the list of conditional queries on the BBPress codex and add the ones you need: [https://codex.bbpress.org/bbpress-conditional-tags/](https://codex.bbpress.org/bbpress-conditional-tags/)

The forum list should be the `bbp_is_forum_archive` condition I suppose. So you can add this route like this:

```php
// Then add the conditional function to the Route class.
add_filter('themosisRouteConditions', function($conds)
{
    $conds['forum'] = 'bbp_is_forum_archive';
    return $conds; // Always return an associative array.
});
```

Then in the `routes.php` file:

```php
Route::get('forum', function()
{
    return "Hello Forum!";
});
```

Let me know if it works!

**Comment by demitrol** [comment]
Yes, it works, thanks for your help!
