### ISSUE TITLE
Scout and AngularJS

### ISSUE THREAD

**Issue by rluders** [themosis/framework#149]
Hi,

I don't know if it is really a inssue but there's any way to change scout template tags?
I'm having some problems to use it with AngularJS.

**Comment by jlambe** [comment]
Hi,

I suppose you need the double curly braces `{{ }}`. 2 ways to make it work:
1. You can prefix curly braces with `@` symbol like so: `<h1>Hello @{{ yourName }}!</h1>`
2. If you don't need the scout compiler for a specific view, simply set the view file extension to `.php` only.

Check out the view documentation with a list of Scout templates: http://framework.themosis.com/docs/views/

Let me know if it does the trick.
