### ISSUE TITLE
No input file specified on Homestead

### ISSUE THREAD

**Issue by bjorntheart** [themosis/framework#154]
Hi there.

I am running Themosis inside the Laravel Homestead VM, but get a `No input file specified` when accessing the site url and the cms url.

This is my Nginx config file.

```
server {
    listen 80;
    server_name themosis.dev;
	  root /home/vagrant/sites/themosis-wordpress
    
		index index.html index.htm index.php;

    charset utf-8;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt  { access_log off; log_not_found off; }

    access_log off;
    error_log  /var/log/nginx/themosis.dev-error.log error;

    error_page 404 /index.php;

    sendfile off;

    location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass unix:/var/run/php5-fpm.sock;
        fastcgi_index index.php;
        include fastcgi_params;
    }

    location ~ /\.ht {
        deny all;
    }
}
```

**Comment by bjorntheart** [comment]
There was a bug in my Nginx config file. the line
` root /home/vagrant/sites/themosis-wordpress` 
should be
` root /home/vagrant/sites/themosis-wordpress/htdocs;`

**Comment by bjorntheart** [comment]
@jlambe Maybe a section in the documentation using the Homestead VM for running Themosis would be helpful? I'd be happy to do it. Just let me know where and under what section.

**Comment by jlambe** [comment]
Hi,
glad you resolved your issue. 

Regarding the Homestead VM not sure it is relevant to add it to the documentation as I don't specifically encourage people to use it. People are free to use whatever dev tools they want and same goes for their web server configuration.

Currently I encourage you to write a blog post on how to install WordPress with Themosis on the Homestead vm.

**Comment by bjorntheart** [comment]
Vagrant, amongst others, is well adopted for development to quickly spin up dev environments without affecting their systems. Personally I thought it would've made a great addition to evangelise dev best practices and compliment the use of Themosis. Of course your users don't have to use it, but would be nice as an option to add it. 

Surely, you've picked this up by using Laravel. I mean you didn't choose any other framework to base your theme on? Laravel uses it, but also leaves you open to use your own. 

Spin up a dev environment, do some stuff, throw it away again. Use it, don't use it. No harm, no fowl :-)

**Comment by jlambe** [comment]
In fact, I haven't fully reviewed the Homestead VM but (let me know if I'm wrong) I think it is provisioned with tools tailored for the Laravel framework. (not sure if I'm clear...)

Perhaps it will be best to setup a VM provisioned for WordPress and Themosis. Because any VM with a web server and mysql will work by default.

**Comment by bjorntheart** [comment]
Ah yes. I see what you're getting at here. You are absolutely right. Homestead is tailored for Laravel. I didn't think about that bit :P Perhaps a VM that is customised for Themosis and Wordpress, like you suggested, would be beneficial?

**Comment by jlambe** [comment]
It will be great indeed :+1:

**Comment by bjorntheart** [comment]
I'll try and get one working for Themosis & Wordpress :-)

**Comment by jlambe** [comment]
That is awesome and then we can provide a step by step documentation in order to setup a local dev environment. :+1:

**Comment by bjorntheart** [comment]
Sounds great!

**Comment by bjorntheart** [comment]
@jlambe Sent you a mail regarding the progress I've made on a VM for Themosis
