### ISSUE TITLE
Project Structure Overview

### ISSUE THREAD

**Issue by bjorntheart** [themosis/framework#155]
Hi @jlambe 

Can you please give an overview/description of what each of these folders contain in the project structure. I've taken a stab at this myself, but please feel free to correct me.
I would like to update the documentation [Installation > Project Structure](http://framework.themosis.com/docs/installation) after I've gathered the necessary information here with your help.

Directory | Sub Directory | Description
------------ | ------------------ | ---------------
bootstrap | | The `bootstrap` directory is where the framework paths, Composer autoloading, framework environment, constant declarations, and shared configurations are setup
config | | The `config` directory is where environments such as `local` and `production` are defined and configured
 | environments | The `environments` directory is where your `local` and `production` configuration files belong
htdocs | | The `htdocs` directory is the web root directory
 | cms | The `cms` directory is where the framework installs the latest WordPress version
 | content | The `content` directory is where your WordPress plugins and themes get installed
library | | ???
vendor | | The `vendor` directory is created by Composer and is where package dependancies for the framework is stored

**Comment by jlambe** [comment]
Hi,

the `library` directory contains a custom class that handles the loading of the environment. It's another framework dependency and may later contains other classes to help bootstrap the framework.

> Note: it could have been written in a separate package and loaded inside the `vendor` directory as well.

I'm glad you update to documentation. Just make a pull request on the `themosis/documentation` project. I'll review your contribution and merge it.
Thanks.

**Comment by bjorntheart** [comment]
Great, thanks @jlambe Will update the docs when I get a chance

**Comment by duniadua** [comment]
Did we need to change htdocs folder name to public_html in bootstrap/start.php file ?, i was stuck in installation production

**Comment by jlambe** [comment]
You can change the `htdocs` name. Simply update the `$webroot_path = $root_path.DS.'htdocs';` variable inside the `start.php` file located at the `bootstrap` root directory.

**Comment by jlambe** [comment]
@bjorntheart For release 1.2.0, we need to add the `storage` directory at project root ;) Will update the docs anyway for soon to be release 1.2.0 version.
