### ISSUE TITLE
Relationship between tags and Field::select

### ISSUE THREAD

**Issue by ramon-villain** [themosis/framework#157]
Hi, I'm trying to make a relationship between post_tags and a Field::select, so I'll feed my post with tags, and select some for displaying in a page. I'm using tags for everything, so let me illustrate it better.
![screencapture-modulo-sys-cms-wp-admin-post-php-1435069256713](https://cloud.githubusercontent.com/assets/1520006/8308209/fc267992-1999-11e5-8e7f-20245f5008a1.png)

```
        $tags_arr = [ ];
            $tags = wp_get_post_tags( $_GET['post']);
            foreach ($tags as $tag) {
                $tags_arr[] = $tag->name;
            }
        }
        $projeto_infos = [
            Field::select( 'city', [ $tags_arr ] ),
            Field::select( 'country', [ $tags_arr ] ,false,['title'  => 'Country']),
            Field::select( 'year', [ $tags_arr ] ),
        ];
        Metabox::make( 'Description', 'projects' )->set( $projeto_infos );
```
The select field is retrieving all the post's tags, but it's no saving the selected option.

**Comment by jlambe** [comment]
Hi,

I think the issue is with your `$_GET['post']` use. Because when saving, you're doing a `$_POST` request. So you should check for both `$_GET['post']` and `$_POST['post_id']` so the select field options are correctly populated.

Also, I suggest you to add the tag ID as the key: `$tags_arr[$tagKey] = $tag->name;` Because it's the key that is saved and not the value as you might expect. The value is only use for display. 

> Note: use `td()` function to check available keys inside the $_POST variable.

Let me know how it goes.

**Comment by ramon-villain** [comment]
Sorry I hide this piece of code, still not working. :(
```
if (isset( $_GET['post'] ) && in_array( $_GET['action'], [ 'edit' ] ) || isset( $_POST['post_ID'] )) {
…
}
```

**Comment by jlambe** [comment]
But there is still this line of code which is wrong:
```php
$id = (isset($_GET['post'])?$_GET['post']:'');
```
When saving, the $id is always an empty string.
Try this perhaps:

```php
$id = '';
if (isset($_GET['post'])
{
    $id = $_GET['post'];
}
elseif (isset($_POST['post_ID']))
{
    $id = $_POST['post_ID'];
}
```

**Update:** it's `$_POST['post_ID'];

**Comment by ramon-villain** [comment]
Yeah, I saw this issue seconds ago and it fixes. :D 
thank you, as always, julien :+1:

**Comment by jlambe** [comment]
Cool, glad it's working. Hope to see a live version soon ;)

**Comment by ramon-villain** [comment]
Hi Julien, let me make another question, it's 'related' to this subject.

It's possible to retrieve a taxonomy for a field in a post_type? I wanna do exactly what I did in this screenshot above, but i'm not using 'post_tags' anymore, so i'm trying this:

```
//Projetos
PostType::make( 'projetos', 'Projetos', 'Projeto' )->set( [
    'public'        => true,
    'menu_position' => 20,
    'supports'      =>  [ 'title', 'editor', 'thumbnail' ],
    'labels'        => [
        'all_items' => __( 'Todos Projetos' ),
        'add_new'   => __( 'Adicionar Projeto' )
    ]
] );

//Tags
Taxonomy::make('tags', 'projetos', 'Tags', 'Tag')->set([
    'public'        => true,
    'query_var'     => true,
]);

//Relationship
if (isset( $_GET['post'] ) || isset( $_POST['post_ID'] )) {
    $id = '';
    if (isset( $_GET['post'] )) {
        $id = $_GET['post'];
    } elseif (isset( $_POST['post_ID'] )) {
        $id = $_POST['post_ID'];
    }
    $tags_arr = [ ];
    $tags_arr[0] = '';
    if (get_post_type( $id ) == 'projetos') {
        $tags = wp_get_post_terms( $id, 'tags');
        foreach ($tags as $tag) {
            $tags_arr[$tag->term_id] = $tag->name;
        }
    }
    $projeto_infos = [
        Field::select( 'cidade', [ $tags_arr ] ),
        Field::select( 'pais', [ $tags_arr ], false, [ 'title' => 'País' ] ),
        Field::select( 'ano', [ $tags_arr ] ),
        Field::select( 'p1', [ $tags_arr ], false, ['title'    => 'Palavra-Chave 1'] ),
        Field::select( 'p2', [ $tags_arr ], false, ['title'    => 'Palavra-Chave 2'] ),
        Field::select( 'p3', [ $tags_arr ], false, ['title'    => 'Palavra-Chave 3'] ),
    ];
    Metabox::make( 'Informações', 'projetos' )->set( $projeto_infos );
}
```

**Comment by jlambe** [comment]
Well you've just changed the function name. I think the `wp_get_post_tags` function is a shortcut for the tags taxonomy on WordPress core posts while `wp_get_post_terms` is the generic one for any taxonomy.
I won't be surprised id the `wp_get_post_tags` is using the `wp_get_post_terms` function internally. So yes, it is possible to retrieve taxonomy to populate a custom field.

As an advice and for better code "management", I would create a model class for your custom post type and write a method that retrieve your custom taxonomy so at the end, you only have a method to call to populate your field and you can re-use that method somewhere else in the site.

**Comment by ramon-villain** [comment]
I tried this before, it's not working, it's returning 'Invalid taxonomy', but if I do the same after the 'boot/init', it works… I guess that it's to early to call the taxonomy, that metabox would be called later. Do you have any suggestion?

**Comment by jlambe** [comment]
The thing is that the Taxonomy class uses the init hook to register the taxonomy and your code below is read before the taxonomy is registered. So I suggest you to use the `init` hook and just wrap your code within it, don't you?
```php
add_action('init', function()
{
    // Your field and metabox code...
});
```
Is it working now?

**Comment by ramon-villain** [comment]
like a charm. 👌🏻

**Comment by jlambe** [comment]
On release 1.2.0, there is a nice action wrapper so you'll be able to manage your action code with a class method, closure or named function.

```php
Action::add('init', 'MyClass');

// The action will use the "MyClass->init()" method
MyClass
{
    public function init()
    {
        // Your init action code... 
    }
}

// Or custom method name...
Action::add('init', 'MyClass@customMethod');
```

Glad it works now :+1:
