### ISSUE TITLE
Slug rewrite breaks routing

### ISSUE THREAD

**Issue by keliix06** [themosis/framework#159]
When setting up permalinks, if a CPT has slug rewriting that breaks it and sends to page not found.

Simple setup: 

```php
$solutions = $args;
$solutions['menu_icon'] = 'dashicons-cart';
$solutions['rewrite'] = array('slug' => 'plans');
$solutions['public'] = true;
$solutions['supports'] = array('title');
PostType::make('hosting-solutions', 'Hosting Solutions', 'Hosting Solution')->set($solutions);
```

If I comment out the rewrite line then it works without any problems. The solution in my case will be to change the post type to just use the rewritten slug as it's slug, but it won't always be that easy. 

I did have both cases accounted for in my routes

```php
Route::get(
    'singular',
    array('hosting-solutions', 'uses' => '***\Controllers\FlexibleController@index')
);
Route::get(
    'singular',
    array('plans', 'uses' => '***\Controllers\FlexibleController@index')
);
```

**Comment by jlambe** [comment]
Hi,

you can also write this route to respond to both slugs:

```php
Route::get('singular', [['hosting-solutions', 'plans'], 'uses' => '***\Controllers\FlexibleController@index']);
```

Let me know how it goes.

**Comment by rluders** [comment]
Hey...

I have a similar problem. I have created a custom post with rewrite parameter, but when I try to route it always get 404 page.

**Comment by jlambe** [comment]
Can you post the custom post type and route code?

**Comment by jlambe** [comment]
Even using the rewrite property, you have to keep using the default custom post type slug name. If you define a custom rewrite rule, update the permalink structure by visiting the `permalink` settings page in WordPress and click update/save settings in order to get them working correctly. Always perform permalink udpate if you write custom rewrite rules within WordPress.

**Comment by rluders** [comment]
custom-post.php

```php
PostType::make('case', 'Cases', 'Case')->set([
    'labels' => [
        'name'          => __('Cases'),
        'singular_name' => __('Case')
    ],
    'public'    => true,
    'rewrite'   => ['slug' => 'clientes'],
    'supports'  => ['title', 'editor', 'thumbnail']
]);
```

rotes.php

```php
Route::get('single', [['case', 'clientes'], function() {
    return View::make('pages.case');
}]);
```

**Comment by jlambe** [comment]
Your route is wrong, use the `singular` key in place of `single`. Update the permalink structure and visit your custom post type once again and you should be good to go:

```php
Route::get('singular', ['case', function()
{
    return View::make('pages.case');
}]);
```

Let me know how it goes!

**Comment by rluders** [comment]
@jlambe, yeap... I just fixed it, and the problem continue. So I try to save my permalink config again an 'voilà'. It's working. Ty...

**Comment by jlambe** [comment]
@rluders Glad it's working! Themosis framework 1.2.0 will be released this thursday, don't forget to update :smile:
