### ISSUE TITLE
Collection limit option doesn't work

### ISSUE THREAD

**Issue by chrislam** [themosis/framework#163]
`Field::collection('pics', array('limit' => 5));` does not work, comparing the Collection and Infinite code within `_themosis-core.js`, the Collection code doesn't seem to be implementing the limit at all.

In my case, I am using the Collection field within an Infinite field but it doesn't look like this should be an issue?

**Comment by jlambe** [comment]
Hi,
the collection has a limit attribute in its html but I'll have to look after the js file, perhaps there is an issue there. Yes, you can use collection fields inside an infinite field.
