### ISSUE TITLE
How to load custom object

### ISSUE THREAD

**Issue by aguidis** [themosis/framework#164]
Hi (again ^^),

I would like to have your opinion about the way to load/access custom object. You are using Composer, which is a great thing because we can autoload  classes easily thanks to the composer.json. You precisely used it for registering your Environment class which is in the "library" directory.

So I am wondering two things :

- Should I simply create a specific folder (called "services" for example) in the "library" directory and register it in my composer.json so I could easily load it in a Controller (if I include the namespace of my service).

- I noticed you have a class called Container in your "Core" folder. Does this DI container is only available in core files or I can use it in my theme or my future plugins ?

Thanks :)

**Comment by jlambe** [comment]
Hi, composer is used to autoload the framework classes but is not well used for the theme or plugins currently. PSR-4 autoloading is coming to the next release which will be way better.

Regarding your questions:
- Are your classes going to use WordPress functions? If no, you can add your own classes inside the `library` directory with your own namespace. If yes, I suggest you to put your classes inside your theme but autoloading is not efficient, you have to manually add your classes to the `loading.config.php' file. (Or you can load the master branches of both the framework and theme where you can use PSR-4 autoloading. The next release is on branch master.)
- Yes you can use it but I haven't written any documentation on it nor provide a facade to it.

**Comment by aguidis** [comment]
Ok I see, It will be a little bit hard for me to use your DIC correctly... I will waiting for the next release ^^

Maybe I could use an external DIC like Pimple to load my custom services ?

**Comment by jlambe** [comment]
Sure, simply add it to your composer.json file and you're good to go. I provide structure in order to better develop the WordPress part but you're free to go to use any other php library in order to complete your project.

I can also provide support in french, si c'est plus simple pour toi ;)

**Comment by aguidis** [comment]
Ok i'll do some tests :) 

J'essaie d'être le plus clair possible en anglais mais parfois ce n'est pas toujours évident, je le note si vraiment j'ai un soucis spécifique !
