### ISSUE TITLE
Class 'Route' not found

### ISSUE THREAD

**Issue by aguidis** [themosis/framework#165]
I tried to install a new theme : I downloaded a zip of your themosis-theme, I renamed it, changed the styles.css comments and then I re-activated this new one but I had this error message : 

Class 'Route' not found in /htdocs/content/themes/custom-name-theme/resources/routes.php

I don't get it

**Comment by jlambe** [comment]
The main framework is not loaded so the class aliases aren't too.

**Comment by aguidis** [comment]
I try to activate the default theme (https://github.com/themosis/theme). Once done I still have the error... I missed something...

**Comment by jlambe** [comment]
Can you give me more details and a step-by-step of what you did please?

**Comment by aguidis** [comment]
I succeed in activating a copy of the default themosis theme but the problem cames from the difference between the theme installed when we do a "composer create-project themosis/themosis my-project-name" and the theme I downloaded at https://github.com/themosis/theme.

I thought It was a same files but no, the files structure is different: 

Theme installed with composer : 
- app/
- functions.php
- index.php
- screenshot.png
- styles.css

Theme from the github repo : 
- bootstrap/
- ressources/
- storage/views/
- tests/
- functions.php
- index.php
- screenshot.png
- styles.css

**Comment by jlambe** [comment]
Ah yes, the master branch on the `themosis/themosis` package is loading the latest stable libraries.

To test the latest version, simply download the zip file of the `themosis/themosis` package and change its composer.json file to load the `dev-master` branch for both the `themosis/framework` and `themosis/theme` packages. (or simply update your current composer.json file)

**Comment by aguidis** [comment]
I see... so in the future the structure of the theme will change and the framework will take these changes into consideration right ?

I'm going to code finally :) thanks for your support.

**Comment by jlambe** [comment]
Yes. The structure is changed because I'll provide a code structure for plugin development as well in a near future :)
Happy coding and don't hesitate to post your issues ;)
Cheers
