### ISSUE TITLE
Action not fired in application.php

### ISSUE THREAD

**Issue by aguidis** [themosis/framework#168]
Hi,

I tried to add an action (hook "after_setup_theme") in the admin/application.php file (because the doc says "This folder is an extension of the classic functions.php"). But it seems that I call the remove_action functions too early, it would mean that the actions I'm trying to remove don't exist because they are added later.

```php
/**
 * Remove some WP tags from the document header
 */
function clean_header() {
    remove_action('wp_head', 'wp_generator');
    remove_action('wp_head', 'wlwmanifest_link');
    remove_action('wp_head', 'rsd_link');
    remove_action('wp_head', 'wp_shortlink_wp_head');

    remove_action('wp_head', 'adjacent_posts_rel_link_wp_head', 10);

    add_filter('the_generator', '__return_false');
    add_filter('show_admin_bar','__return_false');

    remove_action( 'wp_head', 'print_emoji_detection_script', 7 );
    remove_action( 'wp_print_styles', 'print_emoji_styles' );
}
add_action('after_setup_theme', 'clean_header');
```

**Comment by jlambe** [comment]
Probably but what you're trying to achieve is already done by the framework theme by default:
https://github.com/themosis/theme/blob/master/bootstrap/start.php#L138

You should use the `init` hook for this habitually.

**Comment by aguidis** [comment]
Indeed but I started working with the old version of the theme... so I have to update the framework's composer.json right ?

```json
	"require": {
		"php": ">=5.4",
		"johnpbloch/wordpress": ">=4.1",
		"themosis/framework": "dev-master",
		"themosis/theme": "dev-master"
	},
```

instead of : 

```json
	"require": {
		"php": ">=5.4",
		"johnpbloch/wordpress": ">=4.1",
		"themosis/framework": "1.1.*",
		"themosis/theme": "1.1.*"
	},
```

**Comment by jlambe** [comment]
The old is doing the same in a different way but yes `dev-master` for latest version.

**Comment by aguidis** [comment]
I have to update the framework and the theme to dev-master ?

**Comment by jlambe** [comment]
Yes, if you use the new theme, I suggest you to update to the framework latest version as a lot has changed. You'll be safe and if you want, you can test the custom post type custom statuses API: https://github.com/themosis/documentation/blob/master/posttype.md#2register-custom-status

**Comment by aguidis** [comment]
Nice feature !

Ok now I have to convert my old theme structure to the new one ;) Thanks a lot

**Comment by jlambe** [comment]
My pleasure ;)
