### ISSUE TITLE
No loading.config file in the latest version of the theme

### ISSUE THREAD

**Issue by aguidis** [themosis/framework#169]
I updated the framework and the theme to dev-master. But I noticed there was no loading.config.php file in the resources/config directory so I couldn't register my custom Controller. I tried to create the file manually but I still have the error...

Then I read the doc of the theme : https://github.com/themosis/documentation/blob/master/configuration.md#2list-of-the-configuration-files

So I supposed the loading.config.php no longer existed so I created a controllers.config.php with the same content : 

```php
return array(

    /**
     * Mapping for all classes without a namespace.
     * The key is the class name and the value is the
     * absolute path to your class file.
     *
     * Watch your commas...
     */
    // Controllers
    'BaseController'        => themosis_path('theme').'controllers'.DS.'BaseController.php',
    'HomeController'        => themosis_path('theme').'controllers'.DS.'HomeController.php',

    // Models
    'PostModel'             => themosis_path('theme').'models'.DS.'PostModel.php',

    // Miscellaneous

);
```

But the error message still there : 

```
Unhandled Exception

Message:

Class HomeController does not exist
Location:

/var/www/htdocs/content/mu-plugins/themosis-framework/src/Themosis/Core/Container.php on line 282
Stack Trace:

#0 /var/www/htdocs/content/mu-plugins/themosis-framework/src/Themosis/Core/Container.php(282): ReflectionClass->__construct('HomeController')
#1 /var/www/htdocs/content/mu-plugins/themosis-framework/src/Themosis/Core/Container.php(163): Themosis\Core\Container->build('HomeController', Array)
#2 /var/www/htdocs/content/mu-plugins/themosis-framework/src/Themosis/Route/ControllerDispatcher.php(62): Themosis\Core\Container->make('HomeController')
#3 /var/www/htdocs/content/mu-plugins/themosis-framework/src/Themosis/Route/ControllerDispatcher.php(47): Themosis\Route\ControllerDispatcher->makeController('HomeController')
#4 /var/www/htdocs/content/mu-plugins/themosis-framework/src/Themosis/Route/Router.php(199): Themosis\Route\ControllerDispatcher->dispatch(Object(Themosis\Route\Route), Object(Themosis\Core\Request), 'HomeController', 'index')
#5 [internal function]: Themosis\Route\Router->Themosis\Route\{closure}(Object(WP_Post), Object(WP_Query))
#6 /var/www/htdocs/content/mu-plugins/themosis-framework/src/Themosis/Route/Route.php(222): call_user_func_array(Object(Closure), Array)
#7 /var/www/htdocs/content/mu-plugins/themosis-framework/src/Themosis/Route/Router.php(271): Themosis\Route\Route->run()
#8 /var/www/htdocs/content/mu-plugins/themosis-framework/src/Themosis/Route/Router.php(249): Themosis\Route\Router->dispatchToRoute(Object(Themosis\Core\Request))
#9 /var/www/htdocs/content/mu-plugins/themosis-framework/src/Themosis/Core/Application.php(242): Themosis\Route\Router->dispatch(Object(Themosis\Core\Request))
#10 /var/www/htdocs/content/mu-plugins/themosis-framework/src/Themosis/Core/Application.php(225): Themosis\Core\Application->dispatch(Object(Themosis\Core\Request))
#11 /var/www/htdocs/content/mu-plugins/themosis-framework/src/Themosis/Core/Application.php(208): Themosis\Core\Application->handle(Object(Themosis\Core\Request))
#12 /var/www/htdocs/content/mu-plugins/themosis-framework/src/Themosis/Action/Action.php(109): Themosis\Core\Application->run('', NULL)
#13 /var/www/htdocs/content/mu-plugins/themosis-framework/src/Themosis/Action/ActionNotifier.php(28): Themosis\Action\Action->run()
#14 /var/www/htdocs/content/mu-plugins/themosis-framework/src/Themosis/Action/ActionSubject.php(27): Themosis\Action\ActionNotifier->update()
#15 /var/www/htdocs/content/mu-plugins/themosis-framework/src/Themosis/Action/Action.php(96): Themosis\Action\ActionSubject->notify()
#16 [internal function]: Themosis\Action\Action->action('')
#17 /var/www/htdocs/cms/wp-includes/plugin.php(496): call_user_func_array(Array, Array)
#18 /var/www/htdocs/content/themes/project-n-theme/bootstrap/start.php(223): do_action('themosis_run')
#19 /var/www/htdocs/content/themes/project-n-theme/index.php(9): themosis_start_app()
#20 /var/www/htdocs/cms/wp-includes/template-loader.php(74): include('/var/www/htdocs...')
#21 /var/www/htdocs/cms/wp-blog-header.php(16): require_once('/var/www/htdocs...')
#22 /var/www/htdocs/index.php(11): require('/var/www/htdocs...')
#23 {main}
```

**Comment by jlambe** [comment]
Yes it's using PSR-4 autoloading. Simply modify the path the your theme's
controller directory inside the `vendor/composer/autoload_psr4.php` file.
This is not best practice yet because there is no custom installer but for
the release it will be there ;)

2015-07-17 15:31 GMT+02:00 Adrien Guidis <notifications@github.com>:

> I updated the framework and the theme to dev-master. But I noticed there
> was no loading.config.php file in the resources/config directory so I
> couldn't register my custom Controller. I tried to create the file manually
> but I still have the error...
>
> Then I read the doc of the theme :
> https://github.com/themosis/documentation/blob/master/configuration.md#2list-of-the-configuration-files
>
> So I supposed the loading.config.php no longer existed so I created a
> controllers.config.php with the same content :
>
> return array(    /**     * Mapping for all classes without a namespace.     * The key is the class name and the value is the     * absolute path to your class file.     *     * Watch your commas...     */    // Controllers    'BaseController'        => themosis_path('theme').'controllers'.DS.'BaseController.php',    'HomeController'        => themosis_path('theme').'controllers'.DS.'HomeController.php',    // Models    'PostModel'             => themosis_path('theme').'models'.DS.'PostModel.php',    // Miscellaneous);
>
> But the error message still there :
>
> Unhandled Exception
>
> Message:
>
> Class HomeController does not exist
> Location:
>
> /var/www/htdocs/content/mu-plugins/themosis-framework/src/Themosis/Core/Container.php on line 282
> Stack Trace:
>
> #0 /var/www/htdocs/content/mu-plugins/themosis-framework/src/Themosis/Core/Container.php(282): ReflectionClass->__construct('HomeController')
> #1 /var/www/htdocs/content/mu-plugins/themosis-framework/src/Themosis/Core/Container.php(163): Themosis\Core\Container->build('HomeController', Array)
> #2 /var/www/htdocs/content/mu-plugins/themosis-framework/src/Themosis/Route/ControllerDispatcher.php(62): Themosis\Core\Container->make('HomeController')
> #3 /var/www/htdocs/content/mu-plugins/themosis-framework/src/Themosis/Route/ControllerDispatcher.php(47): Themosis\Route\ControllerDispatcher->makeController('HomeController')
> #4 /var/www/htdocs/content/mu-plugins/themosis-framework/src/Themosis/Route/Router.php(199): Themosis\Route\ControllerDispatcher->dispatch(Object(Themosis\Route\Route), Object(Themosis\Core\Request), 'HomeController', 'index')
> #5 [internal function]: Themosis\Route\Router->Themosis\Route\{closure}(Object(WP_Post), Object(WP_Query))
> #6 /var/www/htdocs/content/mu-plugins/themosis-framework/src/Themosis/Route/Route.php(222): call_user_func_array(Object(Closure), Array)
> #7 /var/www/htdocs/content/mu-plugins/themosis-framework/src/Themosis/Route/Router.php(271): Themosis\Route\Route->run()
> #8 /var/www/htdocs/content/mu-plugins/themosis-framework/src/Themosis/Route/Router.php(249): Themosis\Route\Router->dispatchToRoute(Object(Themosis\Core\Request))
> #9 /var/www/htdocs/content/mu-plugins/themosis-framework/src/Themosis/Core/Application.php(242): Themosis\Route\Router->dispatch(Object(Themosis\Core\Request))
> #10 /var/www/htdocs/content/mu-plugins/themosis-framework/src/Themosis/Core/Application.php(225): Themosis\Core\Application->dispatch(Object(Themosis\Core\Request))
> #11 /var/www/htdocs/content/mu-plugins/themosis-framework/src/Themosis/Core/Application.php(208): Themosis\Core\Application->handle(Object(Themosis\Core\Request))
> #12 /var/www/htdocs/content/mu-plugins/themosis-framework/src/Themosis/Action/Action.php(109): Themosis\Core\Application->run('', NULL)
> #13 /var/www/htdocs/content/mu-plugins/themosis-framework/src/Themosis/Action/ActionNotifier.php(28): Themosis\Action\Action->run()
> #14 /var/www/htdocs/content/mu-plugins/themosis-framework/src/Themosis/Action/ActionSubject.php(27): Themosis\Action\ActionNotifier->update()
> #15 /var/www/htdocs/content/mu-plugins/themosis-framework/src/Themosis/Action/Action.php(96): Themosis\Action\ActionSubject->notify()
> #16 [internal function]: Themosis\Action\Action->action('')
> #17 /var/www/htdocs/cms/wp-includes/plugin.php(496): call_user_func_array(Array, Array)
> #18 /var/www/htdocs/content/themes/project-n-theme/bootstrap/start.php(223): do_action('themosis_run')
> #19 /var/www/htdocs/content/themes/project-n-theme/index.php(9): themosis_start_app()
> #20 /var/www/htdocs/cms/wp-includes/template-loader.php(74): include('/var/www/htdocs...')
> #21 /var/www/htdocs/cms/wp-blog-header.php(16): require_once('/var/www/htdocs...')
> #22 /var/www/htdocs/index.php(11): require('/var/www/htdocs...')
> #23 {main}
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/themosis/framework/issues/169>.
>



-- 
[image: Logo][image: Marge]

*JULIEN LAMBE*
Founder
[image: BgInfos][image: Marge]

15, Rue Godefroid-Kurth
B-6700 Arlon
+32 488 32 39 94
http://www.themosis.com

**Comment by aguidis** [comment]
I had to update the composer.json instead (the extra parameter). Because the `composer dump-autoload` seems to be check the 'extra' parameter for generating autoload_ps4.php file.

Before : 

```json
"extra":{
	"installer-paths":{
		.
		.
		"htdocs/content/themes/themosis-{$name}/": ["themosis/theme"],
		.
	},
	"wordpress-install-dir": "htdocs/cms"
}
```

After

```json
"extra":{
	"installer-paths":{
		.
		.
		"htdocs/content/themes/my-custom-{$name}/": ["themosis/theme"],
		.
	},
	"wordpress-install-dir": "htdocs/cms"
}
```

**Comment by jlambe** [comment]
Yes way better to do this :)
