### ISSUE TITLE
Slug rewrite

### ISSUE THREAD

**Issue by bobbygrossmann** [themosis/framework#170]
Normally i want to rewrite some of my slugs with out the slug prefix. /books/test = /test
I tried with your framework but cloud not get it working. Is is possible ?

**Comment by jlambe** [comment]
Is it working locally but not on production? Can you provide a more detailed code sample?

**Comment by bobbygrossmann** [comment]
So default Wordpress it works.
I use this plugin: https://wordpress.org/plugins/remove-slug-from-custom-post-type/  to rewrite /books/test to /test but in your system "front" route catch the url.

**Comment by jlambe** [comment]
If `front` route is catching the URL, are you visiting the `test` url? It would be great to know what the plugin is doing with the rewrite rules.

Otherwise, routes work in order of "appearance". First match, first catch. Try to put your custom post type route before the `front` one.

**Comment by bobbygrossmann** [comment]
I tried that to..

Route::get('singular', ['destination', function() {
    return 'Hello World!';
}]);

This is my only route now for testing but i still get route not found. Mayby you have another trick to rewrite how to remove slug "custom post type"

**Comment by jlambe** [comment]
Can you post the code of your custom post type? With explanations of what're trying to achieve. Then provide all your routes code please.

**Comment by bobbygrossmann** [comment]
The code is extremely simple. Create one custom post type with slug and try to access the route with out slug prefix.

Plugin i normally use:  https://wordpress.org/plugins/remove-slug-from-custom-post-type/ This access custom post type with ut slug prefix for instance: slug = books      /books/test-book  = /test-book

**Comment by jlambe** [comment]
I don't have time to test this right now, will try later. But there must a conflict in urls if your custom post type do not have its slug in the URL as URLs without slug are used by WordPress pages and posts. Will look into it and let you know.
Which file template do you use in "default" WordPress installation to display content for your custom post type?

**Comment by bobbygrossmann** [comment]
Good, everything is basic setup. I just install it and tried.
