### ISSUE TITLE
Check if the current request is an Ajax call with the Scout engine

### ISSUE THREAD

**Issue by aguidis** [themosis/framework#171]
I'm trying to develop an infinite scroll for loading my posts. My goal is to change the template extended by my view if it is an ajax request.

I used to work with Symfony2 (and Twig) and it's possible to do it : 

```twig
{% extends app.request.xmlHttpRequest 
         ? '::ajax-layout.html.twig'
         : '::full-layout.html.twig' 
%}
```

Can we use a "global request" variable with the Scout engine ?

The method only checks if the response contains a specific header : 

```php
public function isXmlHttpRequest() {
    return 'XMLHttpRequest' == $this->headers->get('X-Requested-With');
}
```

I would prefer to use a global request variable instead of writing a php condition in my template.

**Comment by jlambe** [comment]
Well there is the `Input` instance which is a Symfony Request instance. I suppose you could pass this to your view:
```php
Route::get('home', function()
{
    return View::make('someview')->with([
        'is_ajax' => Input::header('X-Requested-With')
    ]);
});
```
Then in your view compare the `$is_ajax` value to extend it. Haven't tested it but let me know how it goes.

**Comment by aguidis** [comment]
Nice I'll do that :D thanks

Ps: I just created a little PR for getting the author's name with the View Helper
