### ISSUE TITLE
Access Constants config file at run-time

### ISSUE THREAD

**Issue by aguidis** [themosis/framework#173]
There is the file *constants.config.php* which is dedicated to register my application's constants but I can't access it : 

> Sometimes you may want to access configuration values at run-time. But you're constrained to only access the values of the application.config.php.

This file is very useful for making our code readable. For example I created a custom taxonomy in the admin/application.php and I wanted to access my constants... There is no way ?

Thanks,
Adrien

**Comment by jlambe** [comment]
On release 1.2.0, you can access properties of all config files using this syntax:
```php
// constants is equal to constants.config.php file and key is the name of one of its property.
$value = Config::get('constants.key');
```
But the constant file, like his name suggests, is creating PHP constants on both old and latest version of the framework:
```php
[
    'SOME_KEY' => 'A custom value'
]
```
Then you can access it like so:
```php
$value = defined('SOME_KEY') ? SOME_KEY : 'A default value';
```

**Comment by aguidis** [comment]
I'm looking forward to test it :)

Ok thanks for your solution !
