### ISSUE TITLE
Conditional tag for custom taxonomy

### ISSUE THREAD

**Issue by aguidis** [themosis/framework#175]
Hello,

I created a custom taxonomy and I wanted to create a specific route but I didn't find the way to do it.

I know there is a conditional tag **postTypeArchive** but what is the good way to handle custom taxonomy ? Do I have to register a custom route conditions ?

**Comment by jlambe** [comment]
No, simply use the `tax` route like so:
```php
Route::get('tax', ['taxonomy-slug', function()
{
    return 'My taxonomy archive view.'
}]);
```

**Comment by aguidis** [comment]
Sorry for this useless issue :/

**Comment by jlambe** [comment]
No problem ;)
