### ISSUE TITLE
Add post formats

### ISSUE THREAD

**Issue by aguidis** [themosis/framework#176]
Hello,

I tried to add some post formats with : 

```php
function add_post_formats() {
    add_theme_support( 'post-formats', array( 'gallery', 'quote', 'video' ) );
}
 
add_action( 'after_setup_theme', 'add_post_formats', 20 );
```

I added this code to the ressources/admin/actions.php. I checked if this code was correctly executed with XDEBUG and it was the case. But I don't see the new formats in the post edition page.

Any idea ?

**Comment by jlambe** [comment]
You don't need to write this code. Simply specify your post formats inside the `supports.config.php` file of your theme. 

Otherwise I don't think you're using the right hook. You might be too late with the `after_setup_theme` hook.

**Comment by aguidis** [comment]
It's better indeed with a config file.

I find this snippet in a "tutorial"... but it seems to be wrong... Thanks for your explanation (I still learn your framework ^^)
