### ISSUE TITLE
How to update symfony/http-foundation (or any other package)

### ISSUE THREAD

**Issue by jozan** [themosis/framework#177]
I'd like to use `illuminate/session` package in my project. `symfony/http-foundation` is `v2.4.2` while I need the latest stable version `v2.7.2`.

```
$ composer show -i
[...]
symfony/class-loader                v2.5.0  Symfony ClassLoader Component
symfony/http-foundation             v2.4.2  Symfony HttpFoundation Component
themosis/framework                  1.1.3   The Themosis framework.
themosis/theme                      1.1.3   The Themosis framework theme.
```

I tried to update it by running the following command in project root:

```
$ composer require symfony/http-foundation
Using version ^2.7 for symfony/http-foundation
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - themosis/framework 1.1.3 requires symfony/http-foundation 2.4.2 -> no matching package found.
    - themosis/framework 1.1.3 requires symfony/http-foundation 2.4.2 -> no matching package found.
    - themosis/framework 1.1.3 requires symfony/http-foundation 2.4.2 -> no matching package found.
    - Installation request for themosis/framework == 1.1.3.0 -> satisfiable by themosis/framework[1.1.3].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.
```

**Comment by jlambe** [comment]
Haven't look into but as it says, the `themosis/framework` package needs v2.4.2 because it is written in its composer.json file. I suppose that if you open the `composer.json` file located inside the `themosis-framework` plugin of your project, you can specify the latest stable version of symfony.

Then go back to the root of your project and run a `composer update` command. Let me know how it goes!

**Comment by jozan** [comment]
It doesn't update it. Maybe it just doesn't read local `themosis/framework` `composer.json` but the packagist.org one?

```
$ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files
```

**Comment by jlambe** [comment]
And if you remove the composer.lock file located at the root? I forgot also that the plugin is inside the `mu-plugins` folder.

Else, you can still fork the `themosis/framework` repository, change its composer.json file and specify your repo in your project.

**Comment by jozan** [comment]
Removing `composer.lock` and running `composer update` did nothing as well. I'll just fork `themosis/framework` and wait for the next release. :baby_chick:

https://twitter.com/Themosis/status/623960920155389953
