### ISSUE TITLE
How to pass View object to a custom package?

### ISSUE THREAD

**Issue by jozan** [themosis/framework#179]
I'm creating a simple wrapper for `mailgun/mailgun-php` package and I want to reuse it in another project as well. I'm using `View::make` inside my package to render html emails.

The framework initialises the View already so I rather not initialise it again in my package but use the same instance. For me it's not necessary to use facades. Thanks. =)

**Comment by jlambe** [comment]
Not sure to follow along but `View::make` will create a `Themosis\View\View` instance with your passed view file. Then you want it to be rendered/compiled and call the `render()` method in order to retrieve your email/html code.

```php
// I expect you're building a HTML email but the same works for text message only.
// You can also pass variables to it by chaining the `with()` method before the `render()` method.
$message = View::make('emails.confirmation')->render();

// Then use the mailgun API to build your email and pass your message into it...
// Don't know mailgun but I just grabbed a code sample from their docs.
$mgClient = new Mailgun('YOUR_API_KEY');
$domain = "YOUR_DOMAIN_NAME";

// Make the call to the client.
$result = $mgClient->sendMessage($domain, [
    'from'        => 'Excited User <YOU@YOUR_DOMAIN_NAME>',
    'to'            => 'foo@example.com',
    'cc'           => 'baz@example.com',
    'bcc'         => 'bar@example.com',
    'subject'   => 'Confirmation Message',
    'text'         => 'Some basic text (or use the View API to build it as well),
    'html'        => $message
]);
```
Hope this helps. Let me know.

**Comment by jozan** [comment]
To clarify a bit: I've made a composer package and I'd like to use `Themosis\View\View` in the package. 

The code you posted works and I've made a wrapper around the same code: https://gist.github.com/jozan/d0c06eafc2d96c31d7aa#file-mail-php-L37 (Line 37)

So, are there any changes to use View inside a package? :baby_chick:

**Comment by jlambe** [comment]
Your package is for use as a WordPress plugin? If so, you could let it that way if you are sure the `View` alias won't be changed. Otherwise use `Themosis\Facades\View::make()` to be safe.

**Comment by jozan** [comment]
It's not WP plugin. Anyways, I got it working, thanks a lot!

https://github.com/jozan/themosis-mailgun-wrapper

:baby_chick:

**Comment by jlambe** [comment]
Interesting ;) Note that for a future release, I will "open" the provider/igniter service for better extension.

**Comment by ramon-villain** [comment]
When you say future, you're talking about ±1.3 release? 
In my mind this kind of support (for extension development) and a deeper documentation, are the final touch for getting more developers.

Actually I 'do', sometimes, a themosis' support for brazilian developers that don't talk english and either those that don't find something in the documentation

:) I really like this project

**Comment by jlambe** [comment]
Thanks for your help @ramon-villain and your support.
I haven't defined the feature list for 1.3 but it might be. The sooner the better :)

**Comment by jozan** [comment]
Nice to hear that extending the framework will get better in the future. It's very needed to attract more developers if there is even a little bit of ecosystem building up. :baby_chick:
