### ISSUE TITLE
Return a JsonResponse in the controller

### ISSUE THREAD

**Issue by aguidis** [themosis/framework#183]
I know you have used some Symfony2 components like HttpFoundation and I would like to know if you implemented the Response class ?

I am working on an infinite scroll : when we are on a post page if you scroll at the bottom I display the next article... On PHP side I would like to return a JsonResponse (Symfony2 style https://github.com/symfony/HttpFoundation/blob/master/JsonResponse.php) but before starting coding a light version of this class, I wanted to have your opinion, if you have a way to achieve that with the current state of the framework ?

**Comment by jozan** [comment]
This would be useful. I too have some use cases where I need to return JSON and but I just wrap my array or object into `Illuminate\Collection` as I use it already for other things.

```php
// In Post model
class Post {

    public static function all()
    {
        $query = new WP_Query(array(
            'post_type'         => 'post',
            'posts_per_page'    => -1,
            'post_status'       => 'publish'
        ));

        // Return Illuminate\Collection
        return collect($query->get_posts());
    }
}

// In routes.php
Route::get('page', ['posts', function()
{
    header('Content-Type: application/json');
    return Post::all()->toJson();
}]);
```
In the same vein, how to access Symfony's Request object inside a controller?

**Comment by aguidis** [comment]
as @jlambe explained me in this issue https://github.com/themosis/framework/issues/171, There is the ``Input`` class which is an instance of Symfony Request instance

@jozan Does the Illuminate\Collection class is already implemented ? If it's the case I'll use it for return a json :)

**Comment by jozan** [comment]
@aguidis Oh, I've already used `Input` but I didn't know it's actually an Symfony Request instance!

`Illuminate\Collection` is not implemented in Themosis Framework itself but you can install it by running `composer require illuminate/support` in your project root. It'll install bunch of other stuff as well but you don't have to use them. For documentation go to http://laravel.com/docs/5.1/collections.

Just for the heads up, you have to set headers yourself so it's not direct replacement for JsonResponse in HttpFoundation.

**Comment by aguidis** [comment]
Ok I see maybe I'll just use the json_encode function and set manually the header myself like you said... If in the future I need to manipulate array etc... I'll try this lib ;)

**Comment by jozan** [comment]
Cool, just be aware of issues when you're serializing PHP objects when using `json_encode()`. :)

https://secure.php.net/manual/en/jsonserializable.jsonserialize.php

:baby_chick:

**Comment by aguidis** [comment]
Nice tips I didn't know this interface thanks ;)

**Comment by jlambe** [comment]
@aguidis I do use the Symfony Response class inside the Router class but you don't have access to it as I use it to set the request. The SymfonyResponse class is available and you can probably implement another instance for your project.

I didn't know the `Illuminate\Collection` class but it might be a nice solution for your issue.
