### ISSUE TITLE
Metabox Custom Page Templates

### ISSUE THREAD

**Issue by djgadd** [themosis/framework#190]
So far as I can tell, there's no easy way to restrict Metaboxes to specific page templates (rather than all pages) a la Advanced Custom Fields. Would really like to see something like: -

```PHP
Metabox::make('Example', 'page', ['template' => 'custom-template'])
    ->set([
        Field::text('author')
    ]);
```

**Comment by jlambe** [comment]
That could be an option.
Currently we create a PageModel where we loop through the pages object and look if there is a value associated with the meta key `_themosisPageTemplate`. Then if there is match, add the metabox.
