### ISSUE TITLE
Dev-master questions

### ISSUE THREAD

**Issue by ramon-villain** [themosis/framework#192]
Hi Julien, I'm trying to implement the dev-master's repo to use the new User's class, but i'm facing some issues, wanna check the best way to upgrade my application. 

My main issues are: Neither the custom routing seems and the view share method doesn't work. I added the 'symfony/class-loader' dependency, and set both themosis/framework and theme to 'dev-master'. Am I missing something?

**Comment by jlambe** [comment]
I've just put a project on dev-master and haven't encounter any issues.
On the framework side, the route api hasn't changed. Using the new theme, all the paths have changed as the main directory is called `resources` in place of `app`.
Also, it uses PSR-4 loading so you shouldn't use the `symfony/class-loader` dependency. One issue might be if you have renamed your `themosis-theme` folder to a custom one. As when running `composer install/update`, it sets the theme paths with `themosis-theme`. So currently you have to manually update the `autoload_psr4.php` file inside the root vendor directory.

I know it's not good but for release, there will be a composer installer where it asks for your theme name before installation.

**Comment by ramon-villain** [comment]
Niceee! No more loading.config.php stuff 😀
Did some changes and it's working on the dev-master :)

**Comment by jlambe** [comment]
:grinning:
