### ISSUE TITLE
Best way of hiding default content editor?

### ISSUE THREAD

**Issue by girvo** [themosis/framework#196]
Hey there,

I'm curious as to what the idiomatic way of hiding the default content editor for a post/page in the Admin would be? I want to leverage the Fields API to build out our own custom data, but want to basically get rid of all of the Wordpress metaboxes for particular pages. Does that make sense?

Cheers,
Josh

**Comment by jlambe** [comment]
Hi,
you can remove the editor by calling the core function `remove_post_type_support`. Here is an example where I fetch a page with an URi of `my-page` and remove the editor. 

Check the codex for more information: [remove_post_type_support](https://codex.wordpress.org/Function_Reference/remove_post_type_support)

```php
$page = get_page_by_path('my-page');

add_action('init', function() use ($page)
{
    if (is_a($page, 'WP_Post') && themosis_is_post($page->ID))
    {
        remove_post_type_support('page', 'editor');
    }
});
```
