### ISSUE TITLE
esc_html on Custom Fields

### ISSUE THREAD

**Issue by tomhking** [themosis/framework#197]
Hello,
I have set up a series of custom fields using 'textarea' and 'editor' that I am trying to display as html. I'm assuming I need to write it using the esc_html function, which would look something like this:
```
{{ esc_html(the_field(Meta::get(Loop::id(), 'the-custom-text-field'))) }}
```
However, this is basically getting ignored and rendering the following:
```
<p>This is a test.</p>
```
Any help would be appreciated.

**Comment by jlambe** [comment]
Hi,
there is no functions `the_field` available. I assume this is from the plugin Advanced Custom Fields...
To retrieve your post meta data, simply use the `Meta` class like so:
```php
{{ esc_html(Meta::get(Loop::id(), 'the-custom-text-field')) }}
```
Hope this works.

**Comment by tomhking** [comment]
Thank you for the prompt response. It unfortunately did no work. It still displays as:
```
<p>Amazing</p> <p>It works!</p> 
```

Here's what my metabox looks like in admin:
```
Metabox::make('Split Copy Secton 1', 'page')->set(array(
	Field::editor('body-copy',
		$settings = array(
			'media_buttons' => false,
			'textarea_rows' => 10
		),
		$extras = array(
			'title' => 'Body Copy'
	))
));
```

Here's what it looks like on the front-end:
```
{{ esc_html(Meta::get(Loop::id(), 'body-copy')) }}
```

I'm not passing any validation to it. Would this matter? Thanks!

**Comment by jlambe** [comment]
I don't understand what you expect the output to be? The output you have is as expected. If you want your html to output as html, don't use the `esc_html` function but the `wpautop` function.

**Comment by tomhking** [comment]
Oh, okay! I misunderstood the <pre>esc_html</pre> function as I've never had to use it. Thank you for clarifying!

On a related note, when I'm wanting to display text something gathered from a specific meta field, is it generally best practice to be written with three brackets like so:
<pre>{{{ Meta::get(Loop::id(), 'text-field') }}}</pre>

**Comment by jlambe** [comment]
The `{{{ $string }}}` curly braces escape characters. In fact it's like doing `<?php echo(htmlentities($string)); ?>`.

So I won't say it is generally best practice but if you need to escape characters, sure do it, you'll write less code.

**Comment by tomhking** [comment]
Thanks for the info! I'm somewhat familiar with how Laravel's shorthand and love how lightweight it is, I just wasn't sure if I should be using two or three braces. Most of the time I see if written as two, but in the Themosis examples I've seen three. I wasn't sure if there was a reason and which was best practice.

**Comment by jozan** [comment]
@tomhking Nowadays Laravel does escape `{{ $name }}` using `htmlentities`. `{!! $name !!}` is unescaped.

**Comment by jlambe** [comment]
@jozan Means the scout engine API must be updated for me :smile:
