### ISSUE TITLE
Laravel Eloquent Support

### ISSUE THREAD

**Issue by tahertechs** [themosis/framework#198]
How can I integrate Eloquent to Themosis.? Is there anything wrong pulling laravel's whole framework (via composer ) on top of Themosis.

**Comment by jlambe** [comment]
Hi,

I suggest you to follow this article to load Eloquent with the framework:
- http://lauhakari.com/2015/adding-eloquent-themosis-wordpress/

**Comment by tahertechs** [comment]
Thank you for the link...Am taking a look on it.

**Comment by tahertechs** [comment]
It worked , Thank you.
