### ISSUE TITLE
Question: Does the metabox functionality require the metabox wordpress plugin?

### ISSUE THREAD

**Issue by anakinjay** [themosis/framework#199]
Forgive the probably incredibly stupid question.  I'm a 10 year Drupal developer, who's been wanting to get into wordpress, and this framework is very attractive to me as a programmer because everything just makes more sense this way.

Anyway, I've been able to follow the documentation up to the metabox section, but can't get it to work.  After some googling I found there was a metabox plugin for wordpress I don't have, but I couldn't find mention of it being a requirement in the themosis documentation.

So do I need it?  or am I just doing something wrong? haha.

**Comment by jlambe** [comment]
No you don't need it at all.

Metaboxes in WordPress are visual "sections" or "containers" of data into your posts (Posts, Pages, Custom Post Type, ...).

If you want to display a metabox for WordPress Posts, type this code:
```php
Metabox::make('A title', 'post')->set();
```
The code above creates an empty metabox for your WordPress Posts.

Then if you want to add custom fields/data to this metabox, simply pass an array of those fields through the metabox `set()` method like so:
```php
Metabox::make('A title', 'post')->set([
    Field::text('author')
]);
```
This code adds a text field with a name of `author`.

Hope this helps, don't hesitate to ask any questions :wink:

**Comment by anakinjay** [comment]
I forgot to thank you for this, that worked for me :)  Sorry for leaving it open.

**Comment by jlambe** [comment]
No problem at all ;)
