### ISSUE TITLE
Query top level of taxonomy for custom post type

### ISSUE THREAD

**Issue by dougking** [themosis/framework#200]
Hi! What would be the best way to list a custom category for a custom post type? For example if I had a PostType of 'vets' and a Taxonomy of 'animals', how could I display posts only from within 'animals' on a page?

e.g. here's my vets.php located in admin:
```
$vets = PostType::make('vets', 'Vets', 'Vet')->set(array(

	'public' => true,
	'rewrite' => array(
		'slug' => 'vets'
	),
	// http://codex.wordpress.org/Function_Reference/register_post_type -> supports section
	'supports' => array('title', 'editor', 'thumbnail', 'excerpt')

));

Taxonomy::make('animals', 'vets', 'Animals', 'Animal')->set(array(
	'public' => true,
	'rewrite' => false,
	'query_var' => false,
	'hierarchical' => true,
));
```

Here's my query:
```
<?php
	$i = 0;
	$modulo = 3;
?>

@if($vets->have_posts())
	@while($vets->have_posts())
		<?php $vets->the_post(); ?>
		<li <?php if($modulo - 1 == $i % $modulo ){ echo('class="last"'); } ?>>
			<h3>{{ Loop::title() }}</h3>
			<a href="{{ Loop::link() }}">
				{{ Loop::thumbnail() }}
			</a>
			<p>{{ Loop::excerpt() }}</p>
		</li>
		<?php
			$i++;
		?>
	@endwhile
@endif
```

This keep returning the error <code>Call to a member function have_posts() on array</code>

**Comment by jlambe** [comment]
Hi, normally you have to use the `tax` route:
```php
Route::get('tax', ['animals', function()
{
    return View::make('taxonomyView');
}]);
```

So this is a core WordPress behavior, if you visit the URL for one of `animals` terms, the WordPress main loop will grab the posts associated with that term only so you don't have to run a custom query.

In your view, simply use the `@loop/@endloop` syntax:
```php
<ul>
    @loop
        <li>
            <h3>{{ Loop::title() }}</h3>
            <a href="{{ Loop::link() }}">
                {{ Loop::thumbnail() }}
            </a>
            <p>{{ Loop::excerpt() }}</p>
        </li>
    @endloop
</ul>
```

Now regarding your custom query, you're calling instance methods on an array. Apparently you already passed to the view the list of posts and not the query instance. So simply make a `foreach` on your `$vets`.

**Comment by dougking** [comment]
Thank you! Do you mean like so:
```
@if($vets->have_posts())
    @while($vets->have_posts())
       @foreach($vets AS $vet)
        <li <?php if($modulo - 1 == $i % $modulo ){ echo('class="last"'); } ?>>
            <h3>{{ Loop::title() }}</h3>
            <a href="{{ Loop::link() }}">
                {{ Loop::thumbnail() }}
            </a>
            <p>{{ Loop::excerpt() }}</p>
        </li>
        @endforeach
    @endwhile
@endif
```

**Comment by jlambe** [comment]
No, PHP will trigger the same error during the statement `if($vets->have_posts())`, that's where you're calling an instance method for the first time on an array.

Only use this code:
```php
<ul>
    @loop
        <li>
            <h3>{{ Loop::title() }}</h3>
            <a href="{{ Loop::link() }}">
                {{ Loop::thumbnail() }}
            </a>
            <p>{{ Loop::excerpt() }}</p>
        </li>
    @endloop
</ul>
```

Also, little tip, if you just want to specify a different style for the `last <li>` tag, simply use a CSS rule:
```css
li:nth-last-of-type {
 /* Rules */
}
```

**Comment by dougking** [comment]
Beautiful! Thank you! Okay, now for my final question: How would I display only the top level categories in the 'animals' taxonomy?

**Comment by jlambe** [comment]
I suppose you mean the `parent` term for the taxonomy. You could check if the current term the query is running has children inside your route callback or controller method and return a different view depending on if the condition is true or not.

Tip: Each route callback or controller method has the main `$post` and `$query` instances as arguments.

Example using route callback. Tested with WordPress 4.1.7+:
```php
Route::get('tax', ['animals', function($post, $query)
{
    // Check for children: Parent view
    $queries  = $query->tax_query->queries;
    if ($queries[0]['include_children'])
    {
        return View::make('parentView');
    }

    // Child view
    return View::make('childView');
}]);
```
