### ISSUE TITLE
CMB2 compatible?

### ISSUE THREAD

**Issue by sb-lc** [themosis/framework#203]
Hi, I am new to this framework and would like to know if there is any integration with CMB2

https://github.com/WebDevStudios/cmb2

thanks

**Comment by jlambe** [comment]
Hi,

no the CMB2 plugin is not used in the framework. The framework provides its own API to handle metaboxes and custom fields:
- http://framework.themosis.com/docs/field/
- http://framework.themosis.com/docs/metabox/

**Comment by sb-lc** [comment]
ok, i swa this, basically I want to migrate an existing wp website over to themosis but the fields / metaboxes are created with CMB2 so it would be a huge task to convert, making it not worth changing over. have you any thoughts on how it would be best to go about integrating cmb2 with themosis? thanks

**Comment by jlambe** [comment]
Keep in mind that working with the framework Themosis is working like "usual" with WordPress. You can still install any WordPress plugins with your project:
- By copy/pasting to the `content/plugins` directory
- From the WordPress admin plugins tab
- By setting the plugin into your `composer.json` file

Now if you want your custom fields be compatible with those from the framework, the only thing you need to take care of is the key name used for each fields. Check the type of your fields and their names. Set the framework fields with same name and normally you get it "converted". Now I don't know which fields CMB2 has and which ones you need but this should work. Only the UI will change.

If you don't feel comfortable with this, just install CMB2 and nothing will change and you can still use the other framework features.

**Comment by sb-lc** [comment]
ok, thanks very much for the information, I will give it a try
