### ISSUE TITLE
Pagination helper for Loop?

### ISSUE THREAD

**Issue by girvo** [themosis/framework#206]
A feature I'd love to see is a simple way of handling pagination through the Loop class (perhaps, maybe there's a better way?) especially for postArchive pages. 

I believe that `next_posts_link()` should work anyway inside of an `@loop` -- is this correct? If so, something like `Loop::nextPage(string $titleText)` would be awesome :)

Cheers,
Josh

**Comment by jlambe** [comment]
Yes the idea is interesting. I always have to check the WordPress codex for pagination anyway ;) I think there are functions that work in the loop and outside the loop. As long as you have a current post id and the current `paged` value.
