### ISSUE TITLE
version 1.2 comming and preview?

### ISSUE THREAD

**Issue by dstollie** [themosis/framework#211]
Can you tell us something more about when v1.2 of themosis is comming and is it possible to see the current state of this version of themosis? Im really looking forward to this new version

**Comment by jlambe** [comment]
Hi, normally the release is coming soon. I need to setup a composer installer for the new version. If you want to test it now, you can download a copy of the package `themosis/themosis`, then update the composer.json file to grab the `dev-master` branch of each `themosis/framework` and `themosis/theme` packages. Run `composer install` and should be good to go for tests.

The next release is using PSR-4 autoloading, so if you change the theme name, you need to manually change the paths for the autoloading inside the `vendor/composer/autoload_psr4.php` file. That's the normally the role of the composer installer.

**Comment by jlambe** [comment]
Hi @dstollie,
latest commits on `themosis/themosis`, `themosis/framework` and `themosis/theme` master (**dev-master**) branches contain the stable code for release 1.2.0.
I gladly invite you to test it. Just note that I haven't yet written the documentation so you'll have to explore a little bit but full documentation will be available at public release ;)

**Comment by dstollie** [comment]
oh wow, sure thing im going to test it!
