### ISSUE TITLE
TaxField - Taxonomy Meta / Fields

### ISSUE THREAD

**Issue by thiagof** [themosis/framework#212]
Hi,

I'm checking the code in `Taxonomy/TaxField.php` and it looks promising, but I'm afraid it is not fully working. So it is not is the docs.

The question is, there is any on-going work (or plan) in Taxonomy Fields? How are you currently handling them?

Thanks again

**Comment by jlambe** [comment]
Hi,
the class allows the addition of custom fields for taxonomies. But it's currently not maintained and explained in documentation to avoid its use. 
I'm waiting the release of WordPress 4.4 before refactoring this class so this will come but not now.
