### ISSUE TITLE
TaxField::delete() thinks $term is an object.

### ISSUE THREAD

**Issue by phh** [themosis/framework#213]
Getting this error after using `TaxField::make()...`

`Argument 1 passed to Themosis\Taxonomy\TaxField::delete() must be an instance of stdClass, integer given`

Due to:
`public function delete(\stdClass $term, $term_id)`

Looking at the documentation:
`https://developer.wordpress.org/reference/hooks/delete_term/`

First argument is an integer. Not a \stdClass as you are expecting. This results in an error on every term delete action. I know this "feature" is still waiting for 4.4 to roll out term meta, but for now, could you not just remove the bug?

**Comment by jlambe** [comment]
Hi,

you find corrected files in the following gist:
- https://gist.github.com/jlambe/fc4f23a580f9fe3c74fd

Replace both files inside your framework `src` directory. This only works with current master branch normally and handles only the `text` and `media` custom fields.

As you mentioned, yes custom fields for taxonomies are coming in future release.

Hope this helps,

**Comment by phh** [comment]
As I'm using composer to fetch the framework, just replacing the files is not fixing the problem.

And the gist version og delete looks pretty much the same to me:

https://gist.github.com/jlambe/fc4f23a580f9fe3c74fd#file-taxfield-php-L230

https://github.com/themosis/framework/blob/master/src/Themosis/Taxonomy/TaxField.php#L230

**Comment by jlambe** [comment]
Currently I don't have time to test and fix this issue. If the triggered error is to look after an integer, try to update the `delete` method like so:

```php
public function delete($term_id)
{
    $key = $this->slug.'_'.$term_id;
    delete_option($key);
}
```

Test this code locally and let me know if it works. If your tests are correct, can you please fork the framework, update the code and submit a pull request? I will simply merge it so you can update the framework package correctly.

**Comment by phh** [comment]
I guess thats how it should look like. I will test the code later today. Thanks!
