### ISSUE TITLE
Activating theme causes all sub-sites to redirect to the welcome page

### ISSUE THREAD

**Issue by otherjohn** [themosis/framework#216]
When following the http://framework.themosis.com/docs/multisite/ instructions on a wordpress 4.3.1 install locally on MAMP, when you visit the main directory (domain.dev) everything seems fine. If you create a site (site1.domain.dev) without activating the themosis theme, the new site works fine. 
As soon as you activate the themosis theme on the sub site (site1.domain.dev) any attempts to log into the wp-admin results in a redirect back to the root. So site1.domain.dev/wp-admin/ --> site1.domain.dev. 

This only happens when you activate the theme!

Seems like something in the theme routes is redircting all wp-admin traffic to  
return View::make('welcome');

**Comment by jlambe** [comment]
Hi,
by default the framework blocks access to `wp-admin` URI if you're not logged in. Try to login using the `wp-login.php` address or `login` URI. Let me know how it goes!
