### ISSUE TITLE
undefined role index in configuration:restrict() method

### ISSUE THREAD

**Issue by solverat** [themosis/framework#219]
Hey, i had some troubles with the `Themosis\Configuration\Configuration->restrict();` method.

if you create an custom role with the wp `add_role()` function, sometimes the index of `$user->roles` is not always `0`. 

so, i changed

```php
$role = (count($role) > 0) ? $role[0] : '';
````
to 
```php
$role = (count($role) > 0) ? current($role) : '';
````
or even better:
```php
$access = Application::get('access');
$user_roles = $user->roles;

$valid_role = (bool) array_intersect($access, $user_roles);

if (!$valid_role && !(defined('DOING_AJAX') && DOING_AJAX)  && !(defined('WP_CLI') && WP_CLI)) {
    wp_redirect(home_url());
    exit;
}

````
version 1.1.3: 
https://github.com/themosis/framework/blob/1.1.3/src/Themosis/Configuration/Configuration.php#L84

In version 1.2 (i think): 
https://github.com/themosis/theme/blob/master/bootstrap/start.php#L165

**Comment by solverat** [comment]
problem still exists in 1.2.2, i had to fix it manually.

**Comment by jlambe** [comment]
@solverat How can I reproduce the issue so I can test your fix? Can you create a PR from the theme repository so I can easily track this for later merge? Thanks

**Comment by solverat** [comment]
at the moment, i'm not sure, why this is happening but i think its related with the role management:

1. create a user called `test`
2. assign admin as role to user `test`
3. create a custom role `add_role('test','test');`
4. add the role to user `test`
5. remove the role with `remove_role('test');`
6. assign admin again to user `test`
7. repeat step 3 and 4.
8. try to login with user `test`, but before you need to debug the role-array in the `themosisThemeRestrict()` function =>  the $role index is not `0` anymore:

```php
$user = wp_get_current_user();
$role = $user->roles;
print_r($role);
die();
````

**Comment by solverat** [comment]
i've created a pull request: https://github.com/themosis/theme/pull/8

**Comment by jlambe** [comment]
@solverat Thanks, will test it asap and merge it.

**Comment by jlambe** [comment]
Merged.
