### ISSUE TITLE
Gravity Forms not working

### ISSUE THREAD

**Issue by dstollie** [themosis/framework#220]
For most of our projects we use gravity forms to create our forms. But when using themosis together with it. The editor of Gravity Forms suddenly breaks. Can someone help us out?

**Comment by jlambe** [comment]
Do you have any error message in the console, log files or on screen when using Gravity?

**Comment by dstollie** [comment]
Thats the problem, no I havent. Activiting of the plugin goes just succesfully. Creating a new form also. But whenever I go to the editor the right sidebar is not showing up. In Gravity Forms its also possible to import existing forms but chaning those fields (in the main part, not the sidebar) is also not possible

**Comment by jlambe** [comment]
I've never used Gravity forms. What happens if your remove the framework from the `mu-plugins`? is the gravity form plugin working correctly after that?

**Comment by dstollie** [comment]
yes it is

**Comment by jlambe** [comment]
I was thinking the same. Version 1.1.3 is using some actions/filters to bootstrap which may create conflicts.
For next release 1.2.0, all these filters/actions are removed. This next release is currently on master branches. Which version do you use? If you can, perhaps test with current master branch version of the framework and see if there are still conflicts with Gravity forms.

**Comment by dstollie** [comment]
Weve fixed it! The problem was completely our fault:

We had this in our supports.config.php

``` 
	/* --------------------------------------------------------------- */
	// Enable post thumbnails
	/* --------------------------------------------------------------- */
	'post-thumbnails',
	/* --------------------------------------------------------------- */
	// Enable post formats (aside, gallery, link, image, ...)
	/* --------------------------------------------------------------- */
	'post-formats',
```

But this causes problems. This fixes it:

``` 
	/* --------------------------------------------------------------- */
	// Enable post thumbnails
	/* --------------------------------------------------------------- */
	'post-thumbnails' => [],
	/* --------------------------------------------------------------- */
	// Enable post formats (aside, gallery, link, image, ...)
	/* --------------------------------------------------------------- */
	'post-formats' => [],
```

Maybe adding a check if these keys do have arrays, will be a good improvement?

**Comment by jlambe** [comment]
Glad the issue is solved. I have to check if all keys need an array or not. If there is a change it could come to version 1.2.1 as a minor fix.
