### ISSUE TITLE
Register service providers aka IgniterService

### ISSUE THREAD

**Issue by jlambe** [themosis/framework#221]
Currently the framework is more or less "closed" regarding custom service providers which are called IgniterService in the core.

You can follow this package in order to build your own classes and register them with the framework:
- https://github.com/ithinkdancan/framework

Using the package above, all classes are autoloaded using the PSR-4 method. So if we take the `PostModel` class, you can easily call it like so:
```php
$model = new \Springbox\Models\Post\PostModel();
```
Now the developer has created a service provider (igniter service) for its `SpringboxAsset` class which adds a localize method by extending the default Themosis Asset class. Looking at the ` SpringboxAssetIgniterService.php` file, its asset API use the key `springboxasset` which instantiate a factory class that need the core asset finder class.

Then everything happens Inside the Facade class `\Spingbox\Façades\SpringboxAsset `:

1. Tell the facade which class to instantiate by using the facade accessor method and return the previously registered igniter service key 'springboxasset'.
2. The author created the static method `load` Inside its facade so he can register its igniter service (as you can't simply add it to an array now).

The load method simply retrieves the main application instance and use the `register` method to register its service.

Now somewhere in your application code, you first need to register your service. So call the static method `load`:

```php
// code Inside the admin/application.php file
\Springbox\Facades\SpringboxAsset::load();

// Then use the service igniter class like so:
\Springbox\Facades\SpringboxAsset::add('handle', 'some-path');
```
Normally this should work but I haven't had the time to test it. Register custom classes through igniter service is planned but only comes in release 1.3.0. So you have to use this hack.

Hope this helps.

**Comment by thiagof** [comment]
Yah it helps!

Not sure if too ambitious, but I'm trying to extend Metabox and Fields..

**Comment by jlambe** [comment]
@thiagof Try to extend using the code inside the master branch as the field api has changed for the better ;)

**Comment by dstollie** [comment]
Thanks for your explanation @jlambe! Really appreciate your effort you put in this project

**Comment by jlambe** [comment]
This is now available. The Illuminate Container is used and a `register()` allows you to register a ServiceProvider class.
in order to retrieve the ServiceContainer, use the `container()` function to get it and call the register method like so.
```php
$ioc = container();
$ioc->register('My\Service\ProviderClass');
```
Currently there won't be any theme config to quickly add ServiceProviders as I expect them to be defined in plugins only. More about a plugin boilerplate later on with release 1.3.0.

**Comment by jlambe** [comment]
Available in current master branch. The "stable" version of the framework is not yet released.
