### ISSUE TITLE
Using themosis templates in ACF

### ISSUE THREAD

**Issue by dstollie** [themosis/framework#222]
We are using ACF to create custom fields. ACF has a feature where you can bind a group of custom fields to a wordpress template. But Themosis templates aren't normall WP templates so ACF does not know what the Themosis templates are. We are using the following gist to fix this problem: https://gist.github.com/dstollie/a5641375c5cbe784d6c8 This gist simple gist will add the themosis templates to the templates dropdown in ACF. 

Idk if this would be something to add right into the core framework but the problem of the missing templates might seem like a bug to newcomers. I think this solution should be pointed out somewhere, maybe this issue would be enough but Ill leave that up to you

**Comment by jlambe** [comment]
Perhaps add a note in the documentation regarding the templates. Thanks for this!

**Comment by Braus** [comment]
Based on that link, for that code (in the link above) to work, it is important to know that you should register your template in templates.config.php with the slug only .

Just in case someone else try this and face the same as I did, where the template would display it in "location -> Rules' (when you create the custom field), but when you select the template in the 'page' the assigned custom fields would not appear. 

The trick is you should only add the template slug.

This will NOT work 
``` 'standard-template' => 'Standard Template' ```

but this will 

``` 'standard-template' ```

I hope it make sense to you all.

**Comment by dstollie** [comment]
@Braus Good thing, I didnt even thought about the possiblity the give a name and a slug to the template, makes sense though. Good that you pointed this out.

**Comment by jlambe** [comment]
At the end, the script should be updated and check if there is a display name defined during the `foreach` loop.

**Comment by sergiohidalgo** [comment]
Hi, I updated the gist of dstollie that do not work in Themosis version 1.2.3

Update: https://gist.github.com/sergiohidalgo/b42db9a78065c23ed845c6584c869885
