### ISSUE TITLE
Asset::add fatal error

### ISSUE THREAD

**Issue by corsairdnb** [themosis/framework#227]
For example, I write such code:
`<?php Asset::add('main', 'css/style.css', false, '1.0', 'screen'); ?>`

And if file style.css does not exist, this call will cause fatal error.

Wordpress function `wp_enqueue_style` doesn't have such problem.

Screenshot:
![fatal-error](https://cloud.githubusercontent.com/assets/4211598/11061833/d70f0860-87ba-11e5-93cb-c5a54cd14cce.png)

**Comment by jlambe** [comment]
Hi,
this is normal as you're developing on a local development where all errors are displayed. This exception is triggered on purpose. 
On production, you'll get a blank screen for example if you let that error in your code. Simply fix it or remove the code line if you don't want to use the asset file.

**Comment by corsairdnb** [comment]
Ok, but I think muting the errors is not correct solution in this case.

**Comment by jlambe** [comment]
No indeed, I should also add a message into the log, at least for production.
