### ISSUE TITLE
getting errors after composer update

### ISSUE THREAD

**Issue by rovillesarate** [themosis/framework#229]
Hi! I am getting the following errors after updating composer.json

The "http://wpackagist.org/packages.json" file could not be downloaded: php_network_getaddresses: getaddrinfo failed: No such host is known.
failed to open stream: php_network_getaddresses: getaddrinfo failed: No such host is known.
http://wpackagist.org could not be fully loaded, package information was loaded from the local cache and may be out of date
The "https://packagist.org/packages.json" file could not be downloaded: php_network_getaddresses: getaddrinfo failed: No such host is known.
failed to open stream: php_network_getaddresses: getaddrinfo failed: No such host is known.
https://packagist.org could not be fully loaded, package information was loaded from the local cache and may be out of date
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package themosis/framework could not be found in any version, there may be a typo in the package name.
  Problem 2
    - The requested package themosis/theme could not be found in any version, there may be a typo in the package name.

this is my composer.json
{
	"name": "themosis/themosis",
	"description": "The Themosis framework. A framework for WordPress developers.",
	"keywords": ["themosis", "framework", "WordPress"],
	"license": "GPL-2.0+",
	"authors": [
		{
			"name": "Julien Lambé",
			"email": "julien@themosis.com",
			"homepage": "http://www.themosis.com/"
		}
	],
	"type": "project",
	"repositories":[
		{
			"type": "composer",
			"url": "http://wpackagist.org"
		}
	],
	"autoload": {
		"psr-0": {
			"Thms": "library"
		}
	},
	"config": {
		"preferred-install": "dist"
	},
	"require": {
		"php": ">=5.4",
		"johnpbloch/wordpress": ">=4.1",
		"themosis/framework": "~1.2.0",
		"themosis/theme": "~1.2.0",
		"michelf/php-markdown": "~1.5.0"
	},
	"extra":{
		"installer-paths":{
			"htdocs/content/mu-plugins/themosis-{$name}/": ["themosis/framework"],
			"htdocs/content/plugins/{$name}/": ["type:wordpress-plugin"],
			"htdocs/content/themes/themosis-{$name}/": ["themosis/theme"],
			"htdocs/content/themes/{$name}/": ["type:wordpress-theme"]
		},
		"wordpress-install-dir": "htdocs/cms"
	}
}

**Comment by jlambe** [comment]
Try this for each repository version: "themosis/framework": "1.2.*" and "themosis/theme": "1.2.*" and let me know.

**Comment by rovillesarate** [comment]
I also tried with installing a new themosis package via composer create project and also getting errors php_network_getaddresses: getaddrinfo failed: No such host is known.

**Comment by rovillesarate** [comment]
still getting the same error after changing "themosis/framework": "1.2." and "themosis/theme": "1.2."

**Comment by rovillesarate** [comment]
This is what i get if i try to install a new package of themosis via composer create-project

D:\EasyPHP-DevServer-14.1VC11\data\localweb\my portable files>composer create-project themosis/themosis themosis_new
The "https://packagist.org/packages.json" file could not be downloaded: php_network_getaddresses: getaddrinfo failed: No such host is known.
failed to open stream: php_network_getaddresses: getaddrinfo failed: No such host is known.
https://packagist.org could not be fully loaded, package information was loaded from the local cache and may be out of date
Installing themosis/themosis (1.1.3)
  - Installing themosis/themosis (1.1.3)
    Downloading: 100%
    Downloading: 100%
    Downloading: 100%
    Failed to download themosis/themosis from dist: The "https://api.github.com/repos/themosis/themosis/zipball/cf161084288c25ef03f2dc5f6275baeee5cd9520" file could not be downloaded: php_network_getaddresses: getaddrinfo failed: No such host is known.
failed to open stream: php_network_getaddresses: getaddrinfo failed: No such host is known.
    Now trying to download from source
  - Installing themosis/themosis (1.1.3)
    Cloning cf161084288c25ef03f2dc5f6275baeee5cd9520



  [RuntimeException]
  Failed to clone git@github.com:themosis/themosis.git, git was not found, check that it is installed and in your PATH env.
  'git' is not recognized as an internal or external command,
  operable program or batch file.

**Comment by jlambe** [comment]
Looks like network issues. Seem it can't reach packagist.org and download the latest packages. I've just tested on windows and mac and it directly grabs the latest version...

**Comment by rovillesarate** [comment]
weird. i can view packagist.org and its working fine. both update and new installation not working for me right now =(
