### ISSUE TITLE
getting errors after update in theme

### ISSUE THREAD

**Issue by rovillesarate** [themosis/framework#230]
Hi! I am having some problems with the theme after update. i tried activating the new themosis theme and still getting the same problem.

file_put_contents(D:\\views\2945c5556b58573eba2b3598be8a62bf): failed to open stream: No such file or directory

Location:

D:\EasyPHP-DevServer-14.1VC11\data\localweb\my portable files\tsc\htdocs\content\mu-plugins\themosis-framework\src\Themosis\View\Compilers\ScoutCompiler.php on line 58
Stack Trace:

#0 D:\EasyPHP-DevServer-14.1VC11\data\localweb\my portable files\tsc\htdocs\content\mu-plugins\themosis-framework\bootstrap\start.php(175): Themosis\Error\Error::native(2, 'file_put_conten...', 'D:\EasyPHP-DevS...', 58)
#1 [internal function]: THFWK_Themosis->{closure}(2, 'file_put_conten...', 'D:\EasyPHP-DevS...', 58, Array)
#2 D:\EasyPHP-DevServer-14.1VC11\data\localweb\my portable files\tsc\htdocs\content\mu-plugins\themosis-framework\src\Themosis\View\Compilers\ScoutCompiler.php(58): file_put_contents('D:\\views\2945c...', '...')
#3 D:\EasyPHP-DevServer-14.1VC11\data\localweb\my portable files\tsc\htdocs\content\mu-plugins\themosis-framework\src\Themosis\View\Engines\ScoutEngine.php(48): Themosis\View\Compilers\ScoutCompiler->compile('D:\EasyPHP-DevS...')
#4 D:\EasyPHP-DevServer-14.1VC11\data\localweb\my portable files\tsc\htdocs\content\mu-plugins\themosis-framework\src\Themosis\View\View.php(109): Themosis\View\Engines\ScoutEngine->get('D:\EasyPHP-DevS...', Array)
#5 D:\EasyPHP-DevServer-14.1VC11\data\localweb\my portable files\tsc\htdocs\content\mu-plugins\themosis-framework\src\Themosis\View\View.php(92): Themosis\View\View->getContent()
#6 D:\EasyPHP-DevServer-14.1VC11\data\localweb\my portable files\tsc\htdocs\content\mu-plugins\themosis-framework\src\Themosis\View\View.php(69): Themosis\View\View->renderContent()
#7 D:\EasyPHP-DevServer-14.1VC11\data\localweb\my portable files\tsc\htdocs\content\mu-plugins\themosis-framework\src\Themosis\View\View.php(278): Themosis\View\View->render()
#8 D:\EasyPHP-DevServer-14.1VC11\data\localweb\my portable files\tsc\vendor\symfony\http-foundation\Symfony\Component\HttpFoundation\Response.php(422): Themosis\View\View->__toString()
#9 D:\EasyPHP-DevServer-14.1VC11\data\localweb\my portable files\tsc\vendor\symfony\http-foundation\Symfony\Component\HttpFoundation\Response.php(202): Symfony\Component\HttpFoundation\Response->setContent(Object(Themosis\View\View))
#10 D:\EasyPHP-DevServer-14.1VC11\data\localweb\my portable files\tsc\htdocs\content\mu-plugins\themosis-framework\src\Themosis\Route\Router.php(299): Symfony\Component\HttpFoundation\Response->__construct(Object(Themosis\View\View))
#11 D:\EasyPHP-DevServer-14.1VC11\data\localweb\my portable files\tsc\htdocs\content\mu-plugins\themosis-framework\src\Themosis\Route\Router.php(271): Themosis\Route\Router->prepareResponse(Object(Themosis\Core\Request), Object(Themosis\View\View))
#12 D:\EasyPHP-DevServer-14.1VC11\data\localweb\my portable files\tsc\htdocs\content\mu-plugins\themosis-framework\src\Themosis\Route\Router.php(243): Themosis\Route\Router->dispatchToRoute(Object(Themosis\Core\Request))
#13 D:\EasyPHP-DevServer-14.1VC11\data\localweb\my portable files\tsc\htdocs\content\mu-plugins\themosis-framework\src\Themosis\Core\Application.php(238): Themosis\Route\Router->dispatch(Object(Themosis\Core\Request))
#14 D:\EasyPHP-DevServer-14.1VC11\data\localweb\my portable files\tsc\htdocs\content\mu-plugins\themosis-framework\src\Themosis\Core\Application.php(223): Themosis\Core\Application->dispatch(Object(Themosis\Core\Request))
#15 D:\EasyPHP-DevServer-14.1VC11\data\localweb\my portable files\tsc\htdocs\content\mu-plugins\themosis-framework\src\Themosis\Core\Application.php(207): Themosis\Core\Application->handle(Object(Themosis\Core\Request))
#16 D:\EasyPHP-DevServer-14.1VC11\data\localweb\my portable files\tsc\htdocs\content\mu-plugins\themosis-framework\src\Themosis\Action\Action.php(109): Themosis\Core\Application->run('', NULL)
#17 D:\EasyPHP-DevServer-14.1VC11\data\localweb\my portable files\tsc\htdocs\content\mu-plugins\themosis-framework\src\Themosis\Action\ActionNotifier.php(28): Themosis\Action\Action->run()
#18 D:\EasyPHP-DevServer-14.1VC11\data\localweb\my portable files\tsc\htdocs\content\mu-plugins\themosis-framework\src\Themosis\Action\ActionSubject.php(27): Themosis\Action\ActionNotifier->update()
#19 D:\EasyPHP-DevServer-14.1VC11\data\localweb\my portable files\tsc\htdocs\content\mu-plugins\themosis-framework\src\Themosis\Action\Action.php(96): Themosis\Action\ActionSubject->notify()
#20 [internal function]: Themosis\Action\Action->action('')
#21 D:\EasyPHP-DevServer-14.1VC11\data\localweb\my portable files\tsc\htdocs\cms\wp-includes\plugin.php(503): call_user_func_array(Array, Array)
#22 D:\EasyPHP-DevServer-14.1VC11\data\localweb\my portable files\tsc\htdocs\content\themes\tsc_theme\bootstrap\start.php(221): do_action('themosis_run')
#23 D:\EasyPHP-DevServer-14.1VC11\data\localweb\my portable files\tsc\htdocs\content\themes\tsc_theme\index.php(9): themosis_start_app()
#24 D:\EasyPHP-DevServer-14.1VC11\data\localweb\my portable files\tsc\htdocs\cms\wp-includes\template-loader.php(75): include('D:\EasyPHP-DevS...')
#25 D:\EasyPHP-DevServer-14.1VC11\data\localweb\my portable files\tsc\htdocs\cms\wp-blog-header.php(16): require_once('D:\EasyPHP-DevS...')
#26 D:\EasyPHP-DevServer-14.1VC11\data\localweb\my portable files\tsc\htdocs\index.php(11): require('D:\EasyPHP-DevS...')
#27 {main}

**Comment by jlambe** [comment]
You have to place the `storage` directory at project root. Or if you use classic wordpress, create it inside the `wp-content` directory. Also add a `views` folder in it.

**Comment by rovillesarate** [comment]
I have already placed the storage in the root folder of themosis on update. but when i try to check the front page i get the errors so i tried using the new theme but still getting the error.

**Comment by jlambe** [comment]
The path to your view directory is wrong. Have you updated the bootstrap code code? You need to have the `THEMOSIS_STORAGE` constant defined. Check this file: https://github.com/themosis/themosis/blob/master/bootstrap/start.php#L78

**Comment by rovillesarate** [comment]
Yes. I have but its ok now. I end up copying the new installation files to my previous project. Its working now. Thanks

**Comment by fatk** [comment]
I've run into the same issue, i was pretty sure that i had replaced the file content like the upgrade guide said. My ```themosis-theme/boostrap/start.php``` looked nothing like the one you liked to on the master.

I did a new install running ```composer create-project themosis/themosis my-project-name``` and it's not the one you linked to in your master. I don't have an explanation, but i think it's worth looking into because users won't be able to complete the upgrade.

After i managed to solve this issue copying the right content, I got this: 

```
Message:

Constant THEMOSIS_STORAGE already defined
Location:

/.../htdocs/content/themes/jacobsen-arquitetura/bootstrap/start.php on line 65
```

Turns out it's being defined by ```htdocs/content/mu-plugins/themosis-framework/themosis.php```. 

I'm not sure what's going on, if i missed something or the files being seeded for the update are not the right ones, but some light on this would be appreciated :+1: 

Thanks!

**Comment by jlambe** [comment]
The constant `THEMOSIS_STORAGE` is defined first inside the **root** project bootstrap folder and not the one from the theme.

Inside the theme, you have to update your `functions.php` file and also copy/paste the `bootstrap` folder from the new theme.

**Comment by fatk** [comment]
It makes more sense now, the files were indeed correct, i just got mixed up with the fact they had the same name.

Maybe the upgrade guide could mention that the root ```bootstrap/start.php``` needs to be manually updated too?

Thanks a lot and congrats on the new release!

**Comment by jlambe** [comment]
I've added it like just before you reported the issue. It is step 5 on the upgrade guide. Thanks for your support!
