### ISSUE TITLE
Options page checkfield not being saved

### ISSUE THREAD

**Issue by rovillesarate** [themosis/framework#231]
Hi! I created an options page that uses a checkfield if its enabled or not but it wont save the checkfield.

![image](https://cloud.githubusercontent.com/assets/2109352/11317319/dea100d4-9065-11e5-8283-0f2e94713779.png)

        $page = Page::make('Options', 'Options')->set([
            'capability'    => 'manage_options',
            'icon'          => 'dashicons-admin-site',
            'position'      => 20,
            'tabs'          => true
        ]);

        $sections[] = Section::make('registration-settings', 'Registration Options');
        $page->addSections($sections);

        $settings['registration-settings'] = [
        	Field::checkbox('enable_registration', 'Enable', ['title' => 'Registration Form']),
        	Field::checkbox('telephone_verification', 'Enable', ['title' => 'Phone Verification']),
        	Field::checkbox('email_verification', 'Enable', ['title' => 'Email Verification']),
        	Field::textarea('registry_notification', ['title' => 'Registry Notification Message']),
        	Field::textarea('registry_verification', ['title' => 'Registry Verification Notification']),
        ];
        $page->addSettings($settings);

        $page->validate([
        	'enable_registration'	=> ['bool'],
        	'telephone_verification'	=> ['bool'],
            'registry_notification-address'    => ['textfield'],
            'registry_verification'         => ['textfield']
        ]);

**Comment by rovillesarate** [comment]
Both Radio and checkbox field not saving

**Comment by rovillesarate** [comment]
I check the database if the checkbox are being saved. It seems it is saving the checkbox field but is setting a value of 0 instead of 1
![image](https://cloud.githubusercontent.com/assets/2109352/11317450/79b438bc-906a-11e5-9e87-5e52f774c2c6.png)
If I try to save the form with checkbox not checked. It removes the checkbox field value
![image](https://cloud.githubusercontent.com/assets/2109352/11317462/bf307e64-906a-11e5-912b-07a15f77a016.png)

somehow if saving both checkfield or radio field it always store a 0 value on the database. and the checkbox and radio field remain unchecked because of the value being saved is 0 instead of 1

**Comment by rovillesarate** [comment]
Already found the solution
![image](https://cloud.githubusercontent.com/assets/2109352/11317679/d89b6192-9070-11e5-81e8-627de0f2571f.png)
comment out the $this->defaultValue();

since saving both the checkbox and radio result to a value of 0 instead of 1

the function defaultValue will always result to empty since '' and 0 will always be empty
commenting out the $this->defaultValue(); seems solve the problem

![image](https://cloud.githubusercontent.com/assets/2109352/11317689/3d8ff716-9071-11e5-9acf-ac0140e1b21f.png)

**Comment by jlambe** [comment]
But there is still an issue. Indeed, the saved value should be 'Enable' for your checkbox and looking at the database, it keeps it at '0'. The checkbox field works correctly for posts and custom post types but the save mechanism for pages has an issue. I'm looking into it and keep you posted.

**Comment by jlambe** [comment]
In fact the behaviour is correct, but it treat a string "0" as empty. I need to update the defaultValue method check. Bugs are so stressful, let you know when it's fixed.

**Comment by rovillesarate** [comment]
Thanks! Julien. I appreciate the fast support. I am trying to make reusable addons like contact forms, registration and login form and other useful stuff to speed up project development. Themosis have really helped me a lot in terms of learning how to code and become a better programmer. Its because of themosis that i start learning mvc and also tried to lean laravel. I hope I will be able to contribute here as well. Again thank you for all the hard work you have put in this framework. Before I used to rely on using plugins but now i think i can develop apps with out using any plugins like gravity forms and advanced custom fields. =)

**Comment by rovillesarate** [comment]
When will the add-on feature be available. Right now i am just making reusable add-on by just following the structure of the theme and just dropping files to the theme since classes are already loaded automatically.

**Comment by rovillesarate** [comment]
I found another bug with the option field. Since option field is given a value of 0 if enabled and no key and value if not enabled. 

when trying to get the option using
$option = Option::get('option', 'key');

This will have no problem if the checkbox is enabled but will result to Undefined index: key

**Comment by jlambe** [comment]
The issues are now solved into the master branch. Just wait a little so I can setup new release 1.2.2. with the fix.

Thanks again for reporting these issues.

Regarding add-on, normally you just need to call any core functions into a plugin and you should be good to go. There some stuff to look at like assets paths but in general you should be able to write a custom plugin if the framework is correctly loaded from the `mu-plugins` directory.

I don't know if you subscribed to the newsletter but plugins (add-ons) and IgniterService (serviceProviders) are coming with the next major release 1.3.0. But before that, there will be a focus on documentation website with fresh re-design (responsive) and a dedicated forum.
