### ISSUE TITLE
Trying to symfony yaml

### ISSUE THREAD

**Issue by rovillesarate** [themosis/framework#232]
Hi! I am trying to load syfomy yaml from the vendor folder of the theme.
I tried loading it via the loading config file but I cant seem to make it to work.
''  => [themosis_path('theme').'controllers', themosis_path('theme').'models', themosis_path('base').'vendor/symfony/yaml']

Should i load it via loading config file or via composer?

**Comment by jlambe** [comment]
How do run the framework? With the classic WordPress structure or the one coming with the framework?

Note that symfony components are all namespaced. In your config, you defined an empty namespace so you can't find your symfony classes. Check the symfony component namespace and add its own rule like so:

```php
'Symfony\\Component' => themosis_path('base').'vendor/symfony'
```

If you defined it through composer, it is best to let composer handle it.

**Comment by rovillesarate** [comment]
Nice it worked. Wow. I am really amazed with this.
If its loaded via composer how should i use it?
use Symfony\Component\Yaml\Yaml;

**Comment by jlambe** [comment]
Yes. Whatever autoloading process you use, the class name is the same.

If you tell at the top of your php file this statement:
```php
<?php

use \Symfony\Component\Yaml\Yaml;

// Call the class this way:
$yaml = new Yaml();
```

The `use` keyword allows you to define "alias" on a per file usage. 

> Note: the framework also use composer for the autoloading process. Keep in mind that composer is also a php package with autoloading classes. In the theme, we use the `Composer\Autoload\ClassLoader()` class for example.
