### ISSUE TITLE
a question regarding storage view? can storage act as a way of caching the full page html of a page?

### ISSUE THREAD

**Issue by rovillesarate** [themosis/framework#237]
Hi! I have been trying to analyze on how storage views work and how they are generated. checking the themosis core class it falls under the compiler view using scout templates and it just basically compiles the scout views into a readable one page template.

I am just wondering if this can also be used as a form of caching / full page cache to be exact. instead of just compiling the views into a readable php template, can it be compiled into an full html page cache to lessen database queries. and maybe a function to delete the compiled view if a page have been updated. and store it in an html folder inside storage?

I am not really that knowledgable when it comes to using wordpress object cache, transient or even redis. I just use wordpress plugins before to cache my website.

But after i started using themosis I end up not relying too much on using plugins and instead try to build everything straight from the theme. After using Themosis i have already stopped using gravityforms and advanced custom fields. Themosis makes it easy to develop this functionalities. So I am just wondering if caching can also be done without using plugins through themosis.

What would be the ideal for full page caching? wp_object_cache, transients or using redis with object cache? or should i stick with caching plugins? I know that this might be a silly question but please do bare with me since im not that of a brilliant coder. Hope you can enlighten with this. Thanks!

**Comment by jlambe** [comment]
The `storage` directory can indeed serve to store any files you want. Now regarding full page caching -  keep the generated html file and serve it in place of running through WordPress process - you can store the html files inside the storage directory. However you need to define extra rules in your `.htaccess` (not sure what to modify for nginx) file and modify the bootstrap code of WordPress.

Now using the cache functions from WordPress will also boost page requests. Store the view in a transient or store your large db query results in a transient will make your application performs way faster.

**Comment by rovillesarate** [comment]
for the storage. what hook functions are available for use. Like for example if i would like to store the whole html page. How would i do it? I was fiddling with the scout compiler files but is clueless on how i will be able to implement this. what do you mean by modify the bootstrap code of WordPress.

When storing the view in transient is it possible to replace it when a page or post has been updated? I have been reading some articles about transient and wp_object_cache. Other say that its better to use wp_cache_add or set instead of transient coz most of the time those cached using transient wont be updated when a post / page gets updated.
Is it possible to delete first the transient before saving the post / page then create a new view and store the new view on transient.

**Comment by jlambe** [comment]
`wp_cache_add` keeps information in memory during a request. For example, let's say your query your db to grab a list of all your users. Then later in your request, you need to re-use the same list, with `wp_cache_add`, you can retrieve your list without doing a second query to the database. This means it is not persistent. If you do a redirect or a new request, your data is lost.

The transient, on the contrary will store the data in the database within a defined duration. The data is persistent then. In place of doing a large query and calculation to get your users, it will do a simple query to retrieve the saved results.

You can delete any transients/cache data using core hooks like `save_post` or `save_post_{$customposttype}`.

**Comment by rovillesarate** [comment]
How do i store the html views? Is there a function for this after compiling the scout view?

**Comment by jlambe** [comment]
Use the render() method to get generated html code of your view then I suppose you should use some default php functions like file_put_content for example.
