### ISSUE TITLE
How do you extend the FormBuilder to add new form methods?

### ISSUE THREAD

**Issue by rovillesarate** [themosis/framework#239]
Hi! How do you add your own Form method types?
In the documentation it says that you can create a custom form field using
Form::input($type, $name, $value = null, array $attributes = [])
but what if i want a form input like a switch that uses html and javascript.

I could probably type everything in everytime i am doing a project but it would be faster if i can just call it using Form::switch(), Is there a way to add a switch method to work with the Form::
I was doing some reasearch about adding method to a class but it requires a pecl extension runkit.
I am just wondering if its possible to add new form field types without touching the core or its currently not possible right now?

**Comment by jlambe** [comment]
The `Form::input` gives you the possibility to create other input type - alias the standard html input tag. Here is a list of standard types you can use with the input: https://developer.mozilla.org/fr/docs/Web/HTML/Element/Input

If you want to create a custom element, why not simply create a custom view with only the appropriate tags, associate the JS script to it trough a view composer and then simply include your view each time you need it.
