### ISSUE TITLE
 compatiability issue with Laravel 5

### ISSUE THREAD

**Issue by mithublue** [themosis/framework#242]
Both Themosis and themosis framework are having problem to be included in laravel 5 , both of these two requires http-foundation 2.4.* but laravel 5 has that of version 2.7.* or something like so (i could not remeber that version correctly at this moment). On the other hand laravel 5 can not have http-foundation of 2.4.*, that's why themosis integratiion fails. Will you please check the issue and try to fix that please ?
Thank you.
Another thing to let me know kindly, which previous version of themosis framework works perfecly as plugin development framework. As far i know, 'themosis_bootstrap' or 'themosis_bootstrap_plugin' does not work perfectly in the current version to develop plugin.

**Comment by jlambe** [comment]
Why would you include Themosis inside a Laravel 5 project? The framework makes use of WordPress functions that will trigger only errors inside a non WordPress project. You're doing it wrong actually, Themosis framework has the same code syntax as Laravel but it's not compatible with Laravel.
For plugin development it's not yet defined, there are hooks in both 2 latests versions but none of them are useful right now and if you're using the framework as a `mu-plugin`, you won't need them for development.

**Comment by mithublue** [comment]
Actually since themosis comes with a wordpress inside, i was wondering if it would be possible to integrate wordpress with laravel including themosis in laravel and having the feature/syntax of themosis as well there.
