### ISSUE TITLE
Removing 'htdocs' from the url 

### ISSUE THREAD

**Issue by mithublue** [themosis/framework#244]
Themosis default installation comes with the frontend url like 'base/htdocs/anyslug' . What i actually needed to know, if there is a way to remove the 'htdocs' from the url
Thank you.

**Comment by jlambe** [comment]
The `htdocs` folder is your webserver public directory. Always setup your server or virtualhost base directory to the `htdocs`.

The structure is in place in order to put sensitive credentials like database access in the parent/base directory which is not accessible to the public.

**Comment by mithublue** [comment]
But as far i know, both these two ways need dedicated hosting. Any other way there to remove the 'htdocs' from url ?

**Comment by jlambe** [comment]
If your host provider cannot offer you this kind of structure per default, you'll need to stick with a "classic" WordPress installation. Install the `framework plugin` into a `mu-plugins` directory and your theme...inside the `themes` directory. Finally, add `storage/views` folder into `wp-content` and you should be good to go.
