### ISSUE TITLE
Fatail error when storage is not existing

### ISSUE THREAD

**Issue by mariusvw** [themosis/framework#249]
When you remove the storage or views directory this results in a fatal error.

I'm willing to help fixing this but I wonder about the 2 options I can come up with.

1. Add line to gitignore file so the views directory will be added to the repository of the project.
2. Create directories when not existing from the compiler.

Which option do you prefer?

**Comment by jlambe** [comment]
I think the simpler the better. I suggest to update the gitignore file so the storage directory and its sub-folders are added in the project (at the the folders, not the files.)

**Comment by mariusvw** [comment]
This has been solved in the template repository.
The framework it self does not contain the storage.
