### ISSUE TITLE
Taxonomy term metadata

### ISSUE THREAD

**Issue by Rhymond** [themosis/framework#253]
I want to add image to category
https://make.wordpress.org/core/2015/09/04/taxonomy-term-metadata-proposal/

**Comment by jlambe** [comment]
Currently the framework hasn't implemented the custom field API to the taxonomy. You'll have to wait for the next major release 1.3.0 for this, at least for using the  `Field` class.

You have to define your fields using default WordPress functions for the moment.

**Comment by jlambe** [comment]
On current master branch, the api allows you to add custom fields to terms using the WordPress term meta api.

How to use it?
1- With a defined custom taxonomy object:
```php
$tax = Taxonomy::make('my-tax', 'post', 'Genres', 'Genre')->set();
$tax->addFields([
    Field::text('publisher'),
    Field::radio('align', ['left', 'right'])
]);
```
2- On a core or existing taxonomy:
```php
Taxonomy::addFields([
    Field::text('website')
], ‘category’);
```

Sanitization is available as well:
```php
// Using tax from above
$tax->sanitize([
    'publisher' => ['min:3']
]);
```
