### ISSUE TITLE
Error during installation: [ Undefined index: host ]

### ISSUE THREAD

**Issue by heikobihlmaier** [themosis/framework#256]
When I try to install wordpress with german language package I get the following error:

https://gist.github.com/heikobihlmaier/9d5d784d3f9a8d143a11

When I use the default language (english) all works fine.

It seems, that he could not find the german language.

**Comment by jlambe** [comment]
Hi,
this is a WordPress core issue and it has been already reported. The core fix is coming with WordPress 4.5 so we need to be patient.

By default, the framework is using the `local` environment configuration where it is displaying all errors. Open the `config/environments/local.php` file and set the `THEMOSIS_ERROR_REPORT` value to `0`. No more errors will be displayed. Install WordPress then reset the value to `-1` to get back error reporting during local development.

**Comment by heikobihlmaier** [comment]
Thanks a lot.
