### ISSUE TITLE
Question: Using of Polylang

### ISSUE THREAD

**Issue by heikobihlmaier** [themosis/framework#258]
Can I use "Polylang" within the views of Themosis ?

With your TODO Application I insert the following line:

`{{ __('Meine Aufgaben', THEMOSIS_TEXTDOMAIN) }}`

But within Admin Panel of Polylang I don't get this text.

Is that not possible to do ?

**Comment by jlambe** [comment]
Unfortunately Polylang needs you to wrap your gettext function within `<?php ?>` tags in order to find your translation.

Because the compiled PHP file is outside of the WordPress theme, it cannot find it.

**Comment by heikobihlmaier** [comment]
Okay thanks. And how I can use visual composer  ?

**Comment by jlambe** [comment]
Never use it but like usual I suppose... Your view certainly only need to call a WordPress loop and it should be good to go. If you need help for visual composer, I suggest you to check their docs and support forum ;)
