### ISSUE TITLE
Form action always appended with slash

### ISSUE THREAD

**Issue by johnnypea** [themosis/framework#259]
```php
// This will output <form action="http://myapp.local/wp-login.php?action=lostpassword/" method="POST">
{{ Form::open(wp_lostpassword_url(),'post') }}
    // Form inputs
{{ Form::close() }}
```

The problem is this request is not processed by a browser in a right way. Why we need to always append the slash?

**Comment by jlambe** [comment]
No the form should not append a slash all the time. It is a case that has not been taken into account. We should fix this and allow URL with query parameters.
