### ISSUE TITLE
Register custom exception handlers

### ISSUE THREAD

**Issue by dstollie** [themosis/framework#260]
Today I wanted to implement a fancier exception handler than the stock PHP one. I figured out Themosis registers it's own exception handler in "bootstrap.php" inside de framework.

```php
/*----------------------------------------------------*/
// Handle errors, warnings, exceptions.
/*----------------------------------------------------*/
set_exception_handler(function($e)
{
    Themosis\Error\Error::exception($e);
});

set_error_handler(function($code, $error, $file, $line)
{
    // Check if the class exists
    // Otherwise WP can't find it when
    // constructing its "Menus" page
    // under appearance in administration.
    if (class_exists('Themosis\Error\Error'))
    {
        Themosis\Error\Error::native($code, $error, $file, $line);
    }
});

if (defined('THEMOSIS_ERROR_SHUTDOWN') && THEMOSIS_ERROR_SHUTDOWN)
{
    register_shutdown_function(function()
    {
        Themosis\Error\Error::shutdown();
    });
}
```
The excpetion handler i wanted to use instead is: [flip/whoops](https://github.com/filp/whoops).

These three simple lines should activate this exception handler

```php
$whoops = new \Whoops\Run;
$whoops->pushHandler(new \Whoops\Handler\PrettyPageHandler);
$whoops->register();
```
Unfortunately this is not working once the themosis exception handlers are being registered.There is also no way to modify the exception handling of themosis with some kind of hook or extension of the Error facade (because the error class is not loaded as a facade).

I Think it would be a good feature to be able to override themosis' way of error handling with a custom one.

edit
==========

After changing the "THEMOSIS_ERROR_SHUTDOWN" option to false:

```php
define('THEMOSIS_ERROR_SHUTDOWN', false);
```
My custom error handler was working. This some my initial problem. Though it would be better to be able to replace themosis' exception handler because exceptions which get triggered between: the registration of exception handler of themosis and the registration of my custom exception handler are still not being shown using the own custom exception handler.

**Comment by jlambe** [comment]
I think it'll be best to put the Whoops package as a dependency and use this as the default in place of my simple custom error handler. Let's look for this on release 1.3.0!

**Comment by jlambe** [comment]
The Whoops package is now fully integrated in the framework. Activate it be setting the `THEMOSIS_ERROR` to `true` in your environment file (master branch and release 1.3.0 +)

**Comment by ribeiroevandro** [comment]
Seizing the opportunity, I'm having problems, not sure if he has a relationship.
It's a new installation, and I tested it on the URL and it did not return the error, is that correct?
![screen shot 2017-01-18 at 02 32 49](https://cloud.githubusercontent.com/assets/943553/22050951/70d38e50-dd26-11e6-8031-630feba1da77.png)
