### ISSUE TITLE
return content of wordpress page

### ISSUE THREAD

**Issue by waqasraza123** [themosis/framework#261]
Hi, can i return(show) a wordpress page as it is user made in the wordpress editor?
like user hits website/contact and contact page contained a short code of contact form, so user will be displayed a page with form?

**Comment by jlambe** [comment]
That's the default behavior. In order to output the editor content, you have to define a WordPress loop inside your view. You can use the scout template shorter version like so:

```php
@loop
    <div id="content">
        {{ Loop::content() }}
    </div>
@endloop
```

**Comment by waqasraza123** [comment]
and one more thing, do I have to handle all urls of my website, or is it like i have to define those urls in my routes page for which i do not want a default behaviour and want to return my own content? @jlambe

**Comment by jlambe** [comment]
The routes behaves like WordPress templates except that you handle them programmatically in place of putting files at the root of your theme.

So if you write the following page route:
```php
Route::get('page', function()
{
    return View::make('common.pages');
});
```

This route will be triggered for all WordPress pages, whatever their urls are. Also note that routes are read from top to bottom in the file. So if you define a route and that there is a match, other routes rules are ignored. Always defined specific routes first then more general routes. Hope this help.

**Comment by waqasraza123** [comment]
@jlambe
can i use an external wordpress theme for design but my own functionality in the themosis framework? is that possible?
and for the routes do I have to make every route, like if there are 100 pages, posts i will be writing routes myself? and if I use an external plugin what about that plugin's routes?

**Comment by jlambe** [comment]
You can use your own theme with your own code structure. The given theme only makes use of classes from the framework. The `themosis-framework` cannot be altered but you can add any code inside your theme for sure.
Like I said, `Route::get('page')` is triggered for your 100 pages and the same goes for posts, or custom post types. Make sure to read the routing documentation:
- http://framework.themosis.com/docs/routing/

It works just like default WordPress.

If plugins define custom routes, you can add them thanks to the route conditions filter: `themosisRouteConditions`
