### ISSUE TITLE
Allow no version on assets

### ISSUE THREAD

**Issue by kraymond70** [themosis/framework#262]
In Asset Class, when registering script or style, the version number is "a string" or false.
```php
$version = (is_string($args['version'])) ? $args['version'] : false;
```
This leads to have assets links like : 
> http://url_to_assets/asset.js?ver=WORDPRESS_VERSION
or
> http://url_to_assets/asset.js?ver=OUR_STRING

But what if we want no version at all ? 
According to the codex, we should call the function with null as version number.
From the Wordpress documentation : https://codex.wordpress.org/Function_Reference/wp_register_script

> $ver 
> (string) (optional) String specifying the script version number, if it has one, which is concatenated to the end of the path as a query string. If no version is specified or set to false, then WordPress automatically adds a version number equal to the current version of WordPress you are running. If set to null no version is added. This parameter is used to ensure that the correct version is sent to the client regardless of caching, and so should be included if a version number is available and makes sense for the script.
Default: false

I shoul propose to have this : 
```php
$version = !isset($args['version']) ? null : ( (is_string($args['version'])) ? $args['version'] : false );
```
I've tested it and it is working locally.

**Comment by jlambe** [comment]
Good catch, I'll update the Asset class to support null values and avoid a version number. I'm going to put this for release 1.3.0 but if I have time, I'll do it sooner.

**Comment by kraymond70** [comment]
Cool :) 
Waiting for it.
