### ISSUE TITLE
Accessing container

### ISSUE THREAD

**Issue by mwerezi** [themosis/framework#263]
Is there a way to access the container to resolve bindings ? I basically want to do something like this (laravel style)

app()->singleton('foo', function ($app) {
    return new Foo;
});

$foo = app()->make('foo')

I can see that the Themosis\Core\Application is instantiated in bootstrap/start.php, but i can't seem to access that variable.

**Comment by jlambe** [comment]
Hi,
currently it's not available but this should come with version 1.3.0.
