### ISSUE TITLE
Add an .editorconfig file

### ISSUE THREAD

**Issue by mwerezi** [themosis/framework#269]
Would be great to have .editorconfig file so that contributions use the same coding style

**Comment by jlambe** [comment]
It could be useful indeed. Can you start this?

**Comment by jlambe** [comment]
A [php-cs-fixer](https://cs.sensiolabs.org/) configuration is now setup at project root for php coding style. This will be available on release 2.0.

Once the tool is installed on your machine, run `php-cs-fixer fix` at project root.
