### ISSUE TITLE
Field::media failing to open file dialog

### ISSUE THREAD

**Issue by apisandipas** [themosis/framework#27]
I've added a Field::media to a PostType. When attempting to add a file, I click the button 'Add', but nothing occurs.

I see the following in the JS Console in Chrome:

```
Uncaught TypeError: Cannot read property 'id' of undefined                   media-audiovideo.js?ver=4.0:90
Uncaught TypeError: Cannot read property 'limitExceeded' of undefined           media-views.js?ver=4.0:1868
```

But the output in Firefox is probably more helpful:

```
TypeError: wp.media.view.settings.post is undefined       media-audiovideo.js:90
TypeError: wp.Uploader is undefined                                media-views.js:1868
```

This happens both on new post screen and in edit screen for post as well. Wordpress v4.0

**Comment by lauhakari** [comment]
I'm getting this same error now on a custom-post-type.
I've created a custom-post-type Called slides and have this code trying to add media field, but getting that 'id' undefined.
```
$fields = [ Field::media('Picture', ['type' => 'image']) ];
$metabox = Metabox::make('Bildspel', 'slides',
	array(
		'context'   => 'normal',
		'priority'  => 'high'
	));

$metabox->set($fields);
```
Now, the thing is if I activate theme_support for "post-thumbnails" on the post-type then the metabox works, But I'd rather not do that as I want to use the custom metabox instead.

**Comment by jlambe** [comment]
Hi,

when you use a custom post type, you need at leat the 'editor' or as you said the 'post-thumbnails' supports so WordPress will automatically load the media assets which are used by the `Field::media`.

If you do not want to support those 2 properties on your custom post type, manually load the media assets in the wp-admin by adding this code inside your `application.php` file:

```php
add_action('admin_enqueue_scripts', function()
{
    wp_enqueue_media();
});
```

This will fix your issue.
