### ISSUE TITLE
Taxonomy and PostType labels

### ISSUE THREAD

**Issue by jlambe** [themosis/framework#277]
Need testing, seems there is an issue with default labels and registered ones when wrapped in translation functions: `__('Category')`

**Comment by ewijdemans** [comment]
Hi, please use array_replace_recursive in favor of wp_parse_args because parts of the array, e.g. 'labels', won't be merged and replaced this way. 

This prevents creating post types with custom labels.

**Comment by jlambe** [comment]
@ewijdemans Can you create a pull request so I can check it?

**Comment by ewijdemans** [comment]
Done that, please check https://github.com/themosis/framework/pull/338.
