### ISSUE TITLE
Provide count callback for custom taxonomy on custom post type with custom statuses.

### ISSUE THREAD

**Issue by jlambe** [themosis/framework#278]
When adding a custom taxonomy to a custom post type with custom statuses, the count property in the table is not up to date. Core count functions look after posts with a `publish` status. If removed, then count display text stay `0`.
![count_taxonomy](https://cloud.githubusercontent.com/assets/1917490/12748089/5f4890e6-c9a8-11e5-837e-9e35f7aef35b.png)

**Comment by jlambe** [comment]
Using the `_update_generic_term_count` function do not work even when defined as `update_count_callback` property.

**Comment by jlambe** [comment]
Current fix has been to manually call the `_update_generic_term_count()` function during the custom post type save action `save_post_cpt-slug`.
Need more testing and a look at WordPress core trac.

**Comment by ciroluna** [comment]
I've been having the same problem here. I registered a custom taxonomy for attachments and the post count for the terms won't update.

How did you fix it?

Thanks in advance.
