### ISSUE TITLE
Themosis\Configuration\Template should hook into theme_page_templates filter

### ISSUE THREAD

**Issue by mwerezi** [themosis/framework#279]
Working with ACF plugin on a project, and came across an issue where adding a location rule group for page templates didn't show any of the ones registered in the templates.config.php

I propose that the Template::make method adds a hook to the theme_page_templates filter so page templates can be reflected in other plugins.

As an aside, i'm wondering whether its a good idea to have a separate page template since its such a core part of Wordpress

**Comment by jlambe** [comment]
The rewrite of the templates was to propose a programmatic way to handle templates for better management.
At that time I wasn't aware of this `theme_page_templates` filter so perhaps yes, the idea to merge themosis templates with core could be great. Definitely something to look at.
