### ISSUE TITLE
How to use themosis with a third party theme

### ISSUE THREAD

**Issue by rovillesarate** [themosis/framework#286]
Hi! I would like to use another theme but is wondering how i can use themosis features inside that third party theme like the views, assets, models and controllers.

There is a filter for assigning a views folder

add_filter('themosisViewPaths', function($paths)
{
    $paths[] = themosis_path('theme').'views'.DS;
    return $paths;
});

but how do i use it?

is this correct

apply_filter('themosisViewPaths', function($paths)
{
  $paths[] = themosis_path('theme').'mycustomviews'.DS;
    return $paths;
});

or should it be get_bloginfo('template_directory').'my_custom_view_folder'.DS;

**Comment by jlambe** [comment]
Write this inside your theme functions.php file:
```php
add_filter('themosisViewPaths', function($paths)
{
    $paths[] = get_template_directory().'/mycustomviews/';
    return $paths;
});
```
**Note:**
- **DS**: is a constant defined by the framework Themosis. Use it at your own risks outside full Themosis projects or check for its existence inside your theme before using it.
- **themosis_path('theme')**: is a path defined in a Themosis theme, so you don't have access to it inside your 3rd party theme.
