### ISSUE TITLE
Building a Relationship Field

### ISSUE THREAD

**Issue by iamkevingreen** [themosis/framework#29]
I have been building a relationship field similar to how the select dropdown works, but instead of an array you put in a post type that pulls in all the posts from that particular post type, I might add some custom options to it as well but I am having difficulty saving and I'm not sure what aspect I need to update to get it totally working... (once it works I'll probably set up a pull request since I think the relationship field is important enough to avoid the need for AFC)

I forked the framework and you can see my modifications here:

https://github.com/iamkevingreen/framework/compare/relationship-field

I don't have a total grasp of this framework since I've only been using it today but if anyone has some insight I would appreciate it, otherwise I'm sure I'll get it tomorrow, but thought other people might be interested in this as well regardless.

**Comment by rovillesarate** [comment]
Hi! I can't seem to view the code for building a relationship field. The website repo seems to have been deleted already. How do you make a relationship field?
