### ISSUE TITLE
Retrieve the URL from a Media field

### ISSUE THREAD

**Issue by APEWAW** [themosis/framework#290]
Hello, 

How can I retrieve the file URL from a Media field?

Here is my Media field (in types.php):
$fields = array(
  Field::media('file', array(
    'title' => __('Fichier à télécharger', THEMOSIS_TEXTDOMAIN),
    'type'  => 'application'
  ))

{{ Meta::get(Loop::id(), 'file') }} returns the file ID but not the URL. 

Thank you in advance,
Amandine

**Comment by jlambe** [comment]
Simply use the `wp_get_attachment_url()` function and pass it the media ID like so:

```php
$id = Meta::get(Loop::id(), 'file');
$mediaUrl = wp_get_attachment_url($id);
```

**Comment by APEWAW** [comment]
Hello Julien,

Thank you for your prompt reply! 
It works like a charm ;) 

Kind regards,
Amandine
