### ISSUE TITLE
Load a dynamic CSS inside PHP file

### ISSUE THREAD

**Issue by Neidra** [themosis/framework#294]
Hey everyone,
I'm a new user of Wordpress and I decided to begin this new adventure with your framework.
So in my project I wish to load dynamically a CSS which is inside a PHP (like you can see in the following link https://css-tricks.com/css-variables-with-php/). 
So i had a problem because the AssetFactorry::add just check the "css" extension .. (if it's not a css extension he set the type like "script")
So i just wanna know if there a trick to load my "style.css.php" file?
Or if you could advice me where can i patch it in my own project?

Thanks a lot.

Neidra

**Comment by jlambe** [comment]
Hi,

in fact you can force it if you use latest version (1.2.3) like so:

```php
Asset::add('my-asset', 'css/style.css.php', false, '1.0.0', 'screen', 'style');
```

Simply tell the type of your asset as a 5th parameter and it should work but this will output a link tag with your php file. Not sure it's the best hack.

**Comment by Neidra** [comment]
I just verify my version of Themosis and she's the 1.2.3.

And try your code, but i'm not sure than the following code is ok.

So the add function of the AssetFactory looking like that :
`// Check if asset has an extension.
        $ext = pathinfo($path, PATHINFO_EXTENSION);

        // If extension.
        if ($ext)
        {
            // Check the type of asset.
            $t = ($ext === 'css') ? 'style' : 'script';
        }
        elseif (!empty($type) && in_array($type, ['style', 'script']))
        {
            $t = $type;
        }`

So if we find an extension (in my case .php) we couldn't force the type.

Thanks for your answer.
Neidra

**Comment by jlambe** [comment]
Yes that's exactly what the code is doing?. It overwrite the default extension type if you add it. So even your php file will be output if you set the `style` argument.

**Comment by Neidra** [comment]
So when i use your solution, and i inspect the generated code, my php file is loaded but like a script even if I force
`Asset::add('my-style', 'css/style.css.php', false, '1.0.0', 'screen','style');`

So, like i said, in your code, if you find any extension in the $path, you never could force your type.

**Comment by jlambe** [comment]
Ok I just saw the issue. Right. Then perhaps make a pull request for this if needed and it'll be merged later.
In the meantime, why not use the `wp_head` hook to output your php stylesheet then, no?

**Comment by Neidra** [comment]
It's what i used, thanks.
So you said before that my hack is not the best way? What did you do in my place?

Thanks for your answers
Neidra

**Comment by jlambe** [comment]
Not sure what you're trying to achieve. Is it like a feature to update global colors for your theme?

**Comment by Neidra** [comment]
Not only the colors, but it's the purpose.

**Comment by jlambe** [comment]
Ok then. What I meant is that I think that the use of the `<link href="phpfile.php" />` is too hacky. I would have suggested to simply output some global CSS vars into the head tag thanks to the `wp_head` hook.

Now in order to be better organized and easily managed this, you can use a view file for your css (stored into 'views/myview.scout.php' ):

```php
<style>
    body {
        color: {{{ $colorVar }}}
    }
</style>
```

and output it like so:

```php
Action::add('wp_head', function()
{
    echo(View::make('myview')->with([
        'colorVar' => a_custom_function_to_retrieve_color()
    ]));
});
```

Finally, you could also use a View Composer in order to pass it variables each time the view is used. Check the documentation here: http://framework.themosis.com/docs/views/
I think this is prettier than the hack from css-tricks.

**Comment by Neidra** [comment]
Your solution looking good! I'll test it :)

Thanks,
