### ISSUE TITLE
Themosis with REST API

### ISSUE THREAD

**Issue by rluders** [themosis/framework#295]
Hello,

I have installed the WP REST API (http://v2.wp-api.org/) with Themosis Framework, but when I try to access the REST Endpoint it always fall into 'home' route.

My request:
`curl -X GET -H "Cache-Control: no-cache" -H "Postman-Token: 989f0ed9-7553-781e-6259-030e048c8eb3" "http://localhost/wp-json/wp/v2/posts"`

Please, I need help here. How do I create a route to access the REST endpoint?

**Comment by jlambe** [comment]
Hi,
in theory, the framework should not handle the rest endpoints as, for example, the `home` route is calling behind the scene the template function `is_home()` which, in theory should not be triggered on rest route.

So, the framework is not handling  REST routes at the moment. Have you checked this documentation ?:
- http://v2.wp-api.org/extending/adding/

**Comment by rluders** [comment]
Hi, Julien.

Yes. I already read this part of documentation, I don't think that will help me for what I need to do. Even if it help me, I think it'll be the hardest way.

There's any way to apply a filter to Themosis ignore some request based on his URI?

**Comment by jlambe** [comment]
No filters no. But you could use the `redirect_template` action hook to perform code before the template functions are called.
I'll try to test the wp-api plugin but it's strange you get the `home` route running for your API. Does WordPress do this on all API endpoints?
What's happening on the default endpoint: `domain.com/wp-json/wp/` ?

**Comment by rluders** [comment]
Yes. All the endpoints goes to 'home'. It's very strange. Do you have another response to REST's endpoint?

**Comment by jlambe** [comment]
Can you update to the latest 1.2.3?
Actually I'm working on a project with WordPress 4.4.2 and framework 1.2.3 and I access both my home route and the wp-api default endpoint without the wp-api plugin installed.
I'm currently out of solution as I haven't yet test the wp-api plugin but based on theory your issue is not expected.
Let's keep this issue open so I can check this later.

**Comment by rluders** [comment]
It works! Thank you, Julien.

**SOLUTION:**
Upgrade from 1.1.* to 1.2.3

**Comment by jlambe** [comment]
Cool :smiley: :+1:

**Comment by rovillesarate** [comment]
Hi! I am also trying to use the wp rest api with themosis but how do i use it with themosis? do i need to create routes for the rest api? I would also want to use angular js on the front end using the rest api. any suggestion on how i can do this? There is a youtube video that shows that angular js can be used with wordpress using the rest api. https://www.youtube.com/watch?v=OXylXQyFYig
