### ISSUE TITLE
CLI tool

### ISSUE THREAD

**Issue by jlambe** [themosis/framework#296]
Explore wp-cli packages and perhaps provide a `themosis` command...
- http://wp-cli.org/package-index/

What kind of commands (sub-commands) do you think would be interesting to develop?

**Comment by chefduweb** [comment]
Specifically for Themosis I'd love to see scaffolding commands to create overview and singular views, routing, a controller and a model for a specific post-type for instance...

**Comment by ramon-villain** [comment]
1. Enviroment:
``wp themosis env``
``wp themosis env --development='Home.lan'``
2. Htdocs renaming (https://github.com/themosis/themosis/issues/65)
3. Generate a new "themosis-theme"
4. Image size maker (images.config.php)
5. Namespace changer (application.config.php)
6. Supports Manager (supports.config.php)

**Comment by jlambe** [comment]
@chefduweb @ramon-villain This is out-of-scope, but I was thinking... would it be great, maybe better, to create custom post type by simply adding a model class? Then the scaffold would provide a class with extra methods to retrieve, update, delete custom post types.

@ramon-villain Generally perhaps provide a command to alter any config file value + an utility to re-calculate image sizes?

**Comment by ramon-villain** [comment]
Yes! This would help a lot!

**Comment by chefduweb** [comment]
Definitely helpful!
I get that doing file-creation is out-of-scope, but adding the methods would be a big win :)

**Comment by rovillesarate** [comment]
+1 for the scaffold via model class. This will be very useful.

**Comment by mickaelperrin** [comment]
I don't know if this the good place for this, but I was looking for a way to interact with a console controller like with the symfony console.

Does themosis already provides something or should we use wp-cli for this ?

**Comment by jlambe** [comment]
@mickaelperrin No there are no such class available.

Right now the WP-Cli has its own class in order to register commands. We suggest you to follow their guidelines if you want to write your own cli commands.

**Comment by terence1990** [comment]
Could also make it possible to publish vendor config files automatically, at the moment i'm just telling users to add the config file manually. Some great ideas here!

**Comment by jlambe** [comment]
@terence1990 Not sure to understand what you're looking for by "publish vendor config files automatically". Could you describe your feature in details ?

**Comment by terence1990** [comment]
Hey @jlambe, sorry for the lack of explanation.

Basically I am buildIng components for Themosis but these components often require config files to be placed in config folder of Themosis them. 

Instead of explicitly setting these config values in some kind of default in the Service Provider we could adopt the approach Laravel takes with its vendor publish commands:

php artisan vendor:publish

Which basically calls the ::boot method on the Service Provider where the Service Provider can call ::loadConfigFrom or ::loadViewsFrom. That's all part of Illuminate Support but we would need to patch it to place the files correct in the Themosis theme resources folder with the correct filename conventions.

More info on vendor:publish is below:

https://laravel.com/docs/5.0/packages

**Comment by jlambe** [comment]
@terence1990 Sounds like a great feature! A user might alter a plugin configuration by adding a configuration into the theme then, right ?

**Comment by terence1990** [comment]
@jlambe potentially, if ConfigFactory checks theme config first before plugin then that would work.

I'll take a look at artisan and see how it achieves what it does through the publish command and work out if we can do the same with a WP CLI command

**Comment by jlambe** [comment]
Well we've implemented the Illuminate\Console package (which leverages the Symfony Console class). We're going to provide a list of default commands with the next release. Probably we won't cover all your needs but if you have any other suggestions for commands to be bundled by default with the framework, just share them with us over here ;)

**Comment by marcwieland95** [comment]
Assely has already CLI commands in place:
[Assely WP-CLI](https://assely.org/docs/wp-cli/)

As @lucprincen suggested, some make command are really appreciated:
`wp assely:make posttype <classname>`

**Comment by jlambe** [comment]
@marcwieland95 This is planned, now that we have a central location for building the application, it is easier to provide those scaffolding helpers.
