### ISSUE TITLE
Integrating woocommerce with themosis

### ISSUE THREAD

**Issue by rovillesarate** [themosis/framework#299]
Hi! Is their a guide on how to fully integrate woocommerce with a themosis theme. How do we insert templates for the cart, checkout and account pages? do we do it manually by creating routes or do we just use a hook?

**Comment by jlambe** [comment]
Hi! Check out this issue for a starting point:
- https://github.com/themosis/themosis/issues/51

You can register WooCommerce routes by using the plugin template functions or use core template functions... For example, the `products` are custom post type, so a single product page could be found with the `Route::get('singular')`, ...
