### ISSUE TITLE
Gitter for direct communication

### ISSUE THREAD

**Issue by dstollie** [themosis/framework#301]
I was looking for a gitter chat room for themosis. Im currently extending themosis' router and it would be cool if I could ask questions directly to the themosis community. Could this be fixed?

**Comment by jlambe** [comment]
Why not indeed. But this will need to be moderated also and I won't have time to check this out a lot. Do you have experience with Gitter, can we easily block unfriendly users from a chat room?

**Comment by jlambe** [comment]
@dstollie any difference compared to Slack ?

**Comment by dstollie** [comment]
Not really but i didny knew there was a slack room for themosis :). Link?

**Comment by jlambe** [comment]
Currently there is none but I'm wondering if Slack is suitable for open-source projects, even if WordPress is using it now...

**Comment by jlambe** [comment]
@dstollie Normally you should have been invited to Gitter themosis/framework room ;)
