### ISSUE TITLE
Avoid wordpress default addslash behaviour

### ISSUE THREAD

**Issue by cdarken** [themosis/framework#307]
It seems that wordpress likes to do this:
http://stackoverflow.com/questions/8949768/with-magic-quotes-disabled-why-does-php-wordpress-continue-to-auto-escape-my
Any idea where I could use that workaround to avoid the symfony request using the already escaped input when creating an instance from globals?

**Comment by jlambe** [comment]
I would say to add this workaround in any of your files inside the `admin` directory. The request instance is only created after normally.

**Comment by cdarken** [comment]
It doesn't, I've used debug_backtrace to check, the hook is called after my controller

**Comment by jlambe** [comment]
and from the `functions.php` file?

**Comment by cdarken** [comment]
It works if I just call the function, as a hook it doesn't. I'll use it like this for now.

**Comment by jlambe** [comment]
Not sure to understand what you mean by using it as a hook ? But glad it works I guess :)

**Comment by cdarken** [comment]
Like this: add_action( 'init', 'unslash_gpc' )
Isn't this a 'hook' in WordPress speak?

**Comment by jlambe** [comment]
Yes it is :) But in the stackoverflow I haven't seen any call to an `init` hook to fix the magic quotes thing, that's why I was wondering.

**Comment by cdarken** [comment]
My bad, I was reading lower on the Stackoverflow page.
Thanks for the suggestion. I will close this now :)

**Comment by jlambe** [comment]
👍
