### ISSUE TITLE
User::update() Doesn't Update Meta

### ISSUE THREAD

**Issue by djgadd** [themosis/framework#311]
The User::update() method doesn't update user meta data because it uses wp_update_user. Could we possibly have an implementation that looks for a meta key in the array and passes that to update_user_meta()?

When I looked at the implementation I see that it also returns a WP_Error on fail, is there a reason it doesn't throw an Exception?

**Comment by jlambe** [comment]
If the update fails, no data is replaced and I found it a better experience to not throw an exception for this and leave the check to the developer. So if the returned value is a WP_Error, warn the user and keep the application running.

**Comment by jlambe** [comment]
I'm looking at this right now. On the refactoring, I'll finally throw an exception in case of a WordPress error. Regarding the meta data, I think it might be best to define a separate method to update them.
