### ISSUE TITLE
Gravity Form User Registration Add-On - Validation link

### ISSUE THREAD

**Issue by PierreLecigne** [themosis/framework#312]
Hello,

I have a problem with the add-on Gravity User Registration Form plugin. 
I use this plugin to allow users to sign up from the front office. After registration, the user receives an email with a validation link, like http://mydomain.com/?page=gf_activation&key=MY-KEY. 
But at the opening of the link, the Gravity Form plugin load a custom template, unable to load the header and footer files. The routes are not taken into account, loading the template before .

Do you have an idea on how to load a Scout template instead plugin template ? 
Thank you !

**Comment by jlambe** [comment]
Hi,
can you normally override the Gravity template from your theme by adding a file template at the root?

If so, simply add this code into your file:
```php
<?php
echo(View::make('your-view'));
```

**Comment by PierreLecigne** [comment]
Oh right, I did not put the View::make in an echo, it work now... Thank you !

**Comment by jlambe** [comment]
Also, if you need better error reporting for your view, you can also use the "long form" in order to output it:
```php
<?php
echo(View::make('your-view')->render());
```
Glad your issue is solved!
