### ISSUE TITLE
How to use composer to use the dev branch

### ISSUE THREAD

**Issue by rovillesarate** [themosis/framework#316]
Hi! How do you use the dev branch on composer?

composer create-project themosis/themosis:dev new_themosis

is this correct?

**Comment by jlambe** [comment]
I think I do this command:
```bash
composer create-project themosis/themosis:dev-dev new_themosis
```
The dev branch is not stable for production as everything has been changed/refactored. Don't hesitate to report any issues or if you have questions, ask them directly on Gitter.

**Comment by rovillesarate** [comment]
When i try this it does not work. it says Could not find package themosis/themosis with version dev-dev in a version installable using your PHP version 5.5  
  .29.

**Comment by jlambe** [comment]
You need at least PHP 5.6 in order to use the framework.
