### ISSUE TITLE
media / collection - allow multiple types

### ISSUE THREAD

**Issue by holgerhartmann** [themosis/framework#321]
Hi,
is it possible to allow images and PDFs on a media or collection field at a time.

Wasn't able to find anything.

Thanks for your help!

Best,
Holger

**Comment by jlambe** [comment]
Hi,
this is not possible right now. Or at least not thought about it. What's happening if you pass an array of types like so: `['type' => ['image', 'application']]` in third argument of your field? I suspect it to not work though. This can be a minor update for next release in any case.

**Comment by holgerhartmann** [comment]
Hi Julien,

when I pass an array only "images" are allowed. PDFs are just being ignored. Would be great to have this feature in a future release.

Best, Holger

**Comment by jlambe** [comment]
Noted for next release ;) Cheers
