### ISSUE TITLE
Install themosis in ongoing wordpress multisite

### ISSUE THREAD

**Issue by hamza-d52** [themosis/framework#328]
Hi , I want to install themosis as a plugin in already running wordpress multisite. I have gone through the documentation for themosis site there i came to know it installs wordpress in the framework it self i don't want to do that. can any one please guide me how i can add themosis as a wordpress pluign on multisite

**Comment by jlambe** [comment]
For using it as a plugin, simply install the `themosis/framework` package (repository) as a plugin. The `themosis/themosis` package is the custom structure for the full stack. Using Themosis as a plugin you don't have multiple environments management for example, ...

Simply clone this repository as a plugin: https://github.com/themosis/framework

**Comment by hamza-d52** [comment]
After doing the above thing i am getting this fatal error-: "Fatal error: Class 'Themosis\Foundation\Application' not found in /foo/XAMPP/xamppfiles/htdocs/themosis/wp-content/plugins/framework-master/themosis.php on line 152"

**Comment by jlambe** [comment]
You also need to run `composer install` into the plugin so it installs the dependencies.

**Comment by hamza-d52** [comment]
Thanks a lot the plugin is activated now. 

But I am still facing issues regarding how to use this plugin into my existing multi-site wordpress website.

Is there a documentation which can explain how to use this plugin when activating it in a wordpress site and not using the whole framework ? I am not able to find the similar structure for htdocs , resources etc.  Please guide me how i can get the same structure in the wordpress multisite

**Comment by jlambe** [comment]
You won't be able to get the same structure by using a regular WordPress installation then dropping the plugin into it. For this, you need to use the "full stack" framework with its default structure.

But now you can have your theme structure as equal to the one from the `themosis/theme` theme. I suggest you to read the code inside the theme repository `themosis/theme`, check the `functions.php` and `bootstrap/start.php` files for tips on this: https://github.com/themosis/theme

Note that current version is not optimized for plugin development, only for custom themes.
