### ISSUE TITLE
Problem with scout

### ISSUE THREAD

**Issue by Saeed-Pooyanfar** [themosis/framework#329]
Hi,

```php
// resources/routes.php
Route::get( 'home', function() {
     
     return View::make( 'test' );
});

```

Will return nothing for me!
In " resources/views " folder i have " test.scout.php " file.
Also if i remove " .scout " from the view file name it will work !!
Why? :(

**Comment by jlambe** [comment]
Do you have the `storage/views` directory available in your installation?
Also, for debugging, can you replace your code with this one:
```php
Route::get('home', function () {
    return View::make('test')->render();
});
```

**Comment by Saeed-Pooyanfar** [comment]
Yes, i have " storage/views " folder and it has one file inside itself ( " .gitignore " )
I added ->render(); but problem still exists ...

**Comment by jlambe** [comment]
You don't have any errors displayed on screen? Is your local environment setup to display errors? Can you post your environment/local.php file as well as your "scout" template file code.

**Comment by Saeed-Pooyanfar** [comment]
No, I have no error displayed on my screen,

/var/www/html/project-folder/.env.local.php:
`<?php

/*----------------------------------------------------*/
// Local environment vars
/*----------------------------------------------------*/
return [

    'DB_NAME'       => 'wf',
    'DB_USER'       => 'root',
    'DB_PASSWORD'   => 'my root password',
    'DB_HOST'       => 'localhost',
    'WP_HOME'       => 'http://localhost/project-name/htdocs',
    'WP_SITEURL'    => 'http://localhost/project-name/htdocs/cms'

];`

/var/www/html/project-folder/config/environment.php:
`<?php

/*----------------------------------------------------*/
// Define your environments
/*----------------------------------------------------*/
return [

    'local'         => 'local',
    'production'    => 'production'

];`

/var/www/html/project-folder/config/environments/local.php:
`<?php

/*----------------------------------------------------*/
// Local config
/*----------------------------------------------------*/
// Database
define('DB_NAME', getenv('DB_NAME'));
define('DB_USER', getenv('DB_USER'));
define('DB_PASSWORD', getenv('DB_PASSWORD'));
define('DB_HOST', getenv('DB_HOST') ? getenv('DB_HOST') : 'localhost');

// WordPress URLs
define('WP_HOME', getenv('WP_HOME'));
define('WP_SITEURL', getenv('WP_SITEURL'));

// Development
define('SAVEQUERIES', true);
define('WP_DEBUG', true);
define('SCRIPT_DEBUG', true);

// Themosis framework
define('THEMOSIS_ERROR_DISPLAY', true);
define('THEMOSIS_ERROR_SHUTDOWN', true);
define('THEMOSIS_ERROR_REPORT', -1);`

/var/www/html/project-folder/htdocs/cms/wp-content/themes/themosis-theme/resources/views/test.scout.php:
`{{ 'Some text' }}`

**Comment by jlambe** [comment]
Ok and from your php log file, anything ?
I see that you're not working with a vhost which might cause issues regarding project path.
What happens be typing a character string without the curly braces inside your view, is it showing anything?

**Comment by Saeed-Pooyanfar** [comment]
> Ok and from your php log file, anything ?

where can i find the php log file ?

> I see that you're not working with a vhost which might cause issues regarding project path.

I'm using lamp in ubuntu

> What happens be typing a character string without the curly braces inside your view, is it showing anything?

While file name is test.scout.php nothing will return, the file content is not important,
But when i rename it to test.php it will return the content, for instance, it will return {{ 'some text' }} without compiling.

**Comment by jlambe** [comment]
Not sure but there is probably a `/log/php/` paths on your system.
If you visit the `storage/views` directory, is there any file other than the `.gitignore` one? If not, there is an issue regarding view compiling which might be caused by your configuration as you don't use a vhost, so paths are probably "broken".

**Comment by Saeed-Pooyanfar** [comment]
So, how can i fix it ?

**Comment by jlambe** [comment]
I'm not used to Ubuntu but here is an example of a Apache vhost configuration (Windows): https://stackoverflow.com/questions/35314640/themosis-doesnt-run-on-localhost

Look after Apache Vhost on ubuntu in order to get help and also find the `httpd-vhosts.conf` file on your system as well as defining a local domain address. The official docs of Apache can also be useful as well as the `man` command on Linux for rapid documentation.

**Comment by Saeed-Pooyanfar** [comment]
I wonder why it doesn't generate error!

**Comment by Saeed-Pooyanfar** [comment]
My guest about this problem:

I installed themosis as plugin for wordpress and wordpress disabled error reporting ! :|

**Comment by jlambe** [comment]
When Themosis is installed as a plugin, error reporting is no longer defined by default and WordPress do not set it to true by default.

**Comment by Saeed-Pooyanfar** [comment]
Ok, uninstalled everything and started from scratch !!

Steps that i did : 

First create VirtualHost in apache config file located at `/usr/local/apache2/conf/httpd.conf`
```
<VirtualHost *:80>
     DocumentRoot "/var/www/html"
     ServerName localhost
     <Directory /var/www/html>
        Options FollowSymlinks Indexes MultiViews
        AllowOverride All
        Require all granted
     </Directory>
</VirtualHost>
```
Restart apache by running `sudo /usr/local/apache2/bin/apachectl restart`
then:

1- remove wordpress and its database
2- install wordpress with new database ( in `/var/www/html/wp` )
3- download [this repo](https://github.com/themosis/framework) as zip
4- install the zip file as plugin ( `http://localhost/wp/wp-admin/plugin-install.php?tab=upload` )
5- run " composer install " in the plugin folder ( `/var/www/html/wp/wp-content/plugins/framework-master` )
6- active the plugin ( `http://localhost/wp/wp-admin/plugins.php` )
7- in this step if i go to `http://localhost/wp` i will recive this error:

> <b>Fatal error</b>:  Uncaught Symfony\Component\HttpKernel\Exception\NotFoundHttpException in /var/www/html/wp/wp-content/plugins/framework-master/vendor/illuminate/routing/RouteCollection.php:161
Stack trace:
#0 /var/www/html/wp/wp-content/plugins/framework-master/vendor/illuminate/routing/Router.php(821): Illuminate\Routing\RouteCollection-&gt;match(Object(Themosis\Foundation\Request))
#1 /var/www/html/wp/wp-content/plugins/framework-master/src/Themosis/Route/Router.php(46): Illuminate\Routing\Router-&gt;findRoute(Object(Themosis\Foundation\Request))
#2 /var/www/html/wp/wp-content/plugins/framework-master/vendor/illuminate/routing/Router.php(691): Themosis\Route\Router-&gt;findRoute(Object(Themosis\Foundation\Request))
#3 /var/www/html/wp/wp-content/plugins/framework-master/vendor/illuminate/routing/Router.php(675): Illuminate\Routing\Router-&gt;dispatchToRoute(Object(Themosis\Foundation\Request))
#4 /var/www/html/wp/wp-content/plugins/framework-master/themosis.php(291): Illuminate\Routing\Router-&gt;dispatch(Object(Themosis\Foundation\Reques in <b>/var/www/html/wp/wp-content/plugins/framework-master/vendor/illuminate/routing/RouteCollection.php</b> on line <b>161</b><br />

8- download [this repo](https://github.com/themosis/theme) as zip
9- install the zip file as plugin ( `http://localhost/wp/wp-admin/theme-install.php?upload` )
10- and when i active the theme , i will recive this error:

> <b>Fatal error</b>:  Uncaught Themosis\Finder\FinderException: File or entity &quot;loading&quot; not found. in /var/www/html/wp/wp-content/plugins/framework-master/src/Themosis/Finder/Finder.php:125
Stack trace:
#0 /var/www/html/wp/wp-content/plugins/framework-master/src/Themosis/Finder/Finder.php(102): Themosis\Finder\Finder-&gt;findInPaths('loading', Array)
#1 /var/www/html/wp/wp-content/plugins/framework-master/src/Themosis/Config/ConfigFactory.php(32): Themosis\Finder\Finder-&gt;find('loading')
#2 [internal function]: Themosis\Config\ConfigFactory-&gt;get('loading')
#3 /var/www/html/wp/wp-content/plugins/framework-master/src/Themosis/Facades/Facade.php(66): call_user_func_array(Array, Array)
#4 /var/www/html/wp/wp-content/themes/theme-master/bootstrap/start.php(17): Themosis\Facades\Facade::__callStatic('get', Array)
#5 /var/www/html/wp/wp-content/themes/theme-master/functions.php(162): require_once('/var/www/html/w...')
#6 /var/www/html/wp/wp-settings.php(369): include('/var/www/html/w...')
#7 /var/www/html/wp/wp-config.php(89): require_once( in <b>/var/www/html/wp/wp-content/plugins/framework-master/src/Themosis/Finder/Finder.php</b> on line <b>125</b><br />

11- and when i open `http://localhost/wp`, it says:

> <p>The <strong>Themosis theme</strong> can't work properly. Please make sure the Themosis framework plugin is installed. Check also your <strong>composer.json</strong> autoloading configuration.</p>

12- I can't access to `http://localhost/wp/wp-admin` unit rename theme folder ..

Any idea to fix this?

**Comment by jlambe** [comment]
Your vhost is overwriting the default localhost. Let's say you're trying the framework and you want to access it on your browser at this local address: `http://themosis.dev` (which is the vhost address) on your machine. And that you want to store your project files at this location: `/Users/yourname/Sites/mythemosisproject`

Your vhost configuration cannot be under the `httpd.conf`, that's the main configuration file for Apache. Inside that file you probably have a commented line in order to load vhosts configuration. Search for that file `httpd-vhosts.conf` and uncomment the line (remove the `;` on front) then open that `httpd-vhosts.conf` file (by following the path indicated in main config file).

In your `httpd-vhosts.conf` file, add a local vhost in order to listen to the `http://themosis.dev` URL:
```bash
<VirtualHost *:80>
     DocumentRoot "/Users/yourname/Sites/mythemosisproject/htdocs"
     ServerName themosis.dev
     <Directory /Users/yourname/Sites/mythemosisproject/htdocs>
        Options FollowSymlinks Indexes MultiViews
        AllowOverride All
        Require all granted
     </Directory>
</VirtualHost>
```

Then before it works, you need to also add a registry into your `hosts` file, probably defined at this location: `/etc/hosts/`. Open the file and add the following line in it:
```bash
127.0.0.1 themosis.dev
```
Save and close the file. Restart Apache.

Finally your local config file looks like this:
```php
<?php
return [
    'DB_NAME'       => 'wf',
    'DB_USER'       => 'root',
    'DB_PASSWORD'   => 'my root password',
    'DB_HOST'       => 'localhost',
    'WP_HOME'       => 'http://themosis.dev',
    'WP_SITEURL'    => 'http://themosis.dev/cms'
];
```

Visit the `http://themosis.dev/` URL in your browser, install WordPress and let me know if this has solved the `Scout` issue. Hope this clarifies things a bit.

**Comment by Saeed-Pooyanfar** [comment]
I removed everything again !! even composer cache !
When i run `composer create-project themosis/themosis themosis` i will recive:

>  [Composer\Downloader\TransportException]                                     
  Your configuration does not allow connections to http://wpackagist.org/pack  
  ages.json. See https://getcomposer.org/doc/06-config.md#secure-http for details.

Then i have to edit composer.json and add `"secure-http": false` and run `composer update`
I add `wp.dev` to point `127.0.0.1` and will create vh ...

**Comment by Saeed-Pooyanfar** [comment]
Nope!
The first problem still exists!
Renamed `welcome.scout.php` to `welcome.php` and here is the result:
<img src="https://s31.postimg.org/3z1t3ador/result1.png">
As i said, nothing will return for `welcome.scout.php`

**Comment by Saeed-Pooyanfar** [comment]
VH that i created:
```
<VirtualHost *:80>
     DocumentRoot "/var/www/html/themosis/htdocs"
     ServerName wp.dev
     <Directory /var/www/html/themosis/htdocs>
        Options FollowSymlinks Indexes MultiViews
        AllowOverride All
        Require all granted
     </Directory>
</VirtualHost>
```

**Comment by jlambe** [comment]
And any errors inside the browser inspector?

**Comment by jlambe** [comment]
Have you set read/write permissions to the `storage/views` folder?

**Comment by Saeed-Pooyanfar** [comment]
![screenshot1](https://cloud.githubusercontent.com/assets/8407855/16743635/925d07ee-47c2-11e6-824f-aa6e282c0754.png)

**Comment by Saeed-Pooyanfar** [comment]
No error will display, just a white page, as you can see in above screenshot ...

**Comment by jlambe** [comment]
it's odd it's working on a homestead vm using ubuntu but not an the system itself. I have to install a version of Ubuntu and test it myself. Which version are you using?

**Comment by Saeed-Pooyanfar** [comment]
Ubuntu 14.04 x64

**Comment by Saeed-Pooyanfar** [comment]
@jlambe Can you replace scout with laravel blade ?!

**Comment by Saeed-Pooyanfar** [comment]
> it's odd it's working on a homestead vm using ubuntu but not an the system itself. I have to install a version of Ubuntu and test it myself. Which version are you using?

@jlambe Please test scout when you install themosis framwork as wordpress plugin

**Comment by Saeed-Pooyanfar** [comment]
also check error reporting, please ...

**Comment by Saeed-Pooyanfar** [comment]
Yeah !!!!!! Problem solved !!
Just created `storage/views` in `wp-content` folder !! ^_^

**Comment by jlambe** [comment]
Aah I thought you had the full stack framework, not just the plugin installed on a WordPress classic installation 😶  So yes, the storage folder has to be inside the `wp-content` directory. As for error reporting, you won't have it as you don't use the full "stack" framework.

The next version has Scout removed (well it's still there for backwards compatibility) and has full Blade implementation as well as Twig. But that's for the next one ;)

**Comment by jlambe** [comment]
Glad your issue is solved.

**Comment by Saeed-Pooyanfar** [comment]
But still error reporting problem exists ...

**Comment by Saeed-Pooyanfar** [comment]
> As for error reporting, you won't have it as you don't use the full "stack" framework.

I don't know that how can i use the full "stack" framework!
I think your docs at http://framework.themosis.com/ is not clear enough ! :(

**Comment by jlambe** [comment]
When you start a new project, you should not have already WordPress installed. Simply start by typing the following command on your Terminal:
```bash
composer create-project themosis/themosis myfolder
```

This command installs WordPress and all other dependencies. So here you have the full "stack" framework with error reporting and other constants that you can define in `{location}.php` (local.php) files inside the config folder.

Then when everything is defined, you can process to the WordPress installation through your browser as usual and then develop your project.

What are the steps you've done in order to start a new project?

**Comment by Saeed-Pooyanfar** [comment]
Ok Ok !
Finally i installed themosis in the right way!
Tnx

**Comment by jlambe** [comment]
👍

**Comment by Saeed-Pooyanfar** [comment]
@jlambe 
Can you give us an ETA for next version?

**Comment by jlambe** [comment]
Only 2016, that's for sure but nope, no release date, you'll have to be patient. Now you can still test the dev branch but there is no documentation available for its use, you'll have to check the source code for it.
To test the next version in its current state:
```bash
composer create-project themosis/themosis yourfolder dev-dev
```
