### ISSUE TITLE
Passing parameters to controllers

### ISSUE THREAD

**Issue by LeRondPoint** [themosis/framework#330]
More of a question or a request than an issue.  How can one pass parameters to a controller during the Route::get call?

I have the following:
```
 Route::get('home', 'ResultsController@index');
 Route::get('search', 'ResultsController@query');
 Route::get('category', 'ResultsController@query');
 Route::get('tag', 'ResultsController@query');
 Route::get('author', 'ResultsController@query');
 ...
```

I'd like to pass the controller a parameter for each route that will be relayed to the view in order to set a decent title without creating a new function for each.  Possible?

Ideally, it would also be possible to intercept the route parameters to act on them.  For instance, get the author id/slug to put 'Posts by AUTHOR' as a title.

**Comment by jlambe** [comment]
1. If you have common parameters between all your routes, you can define those by setting them up in the controller `__construct` method for example.
2. All controller methods (and all routes callback) have 2 parameters/arguments: the first one is the `$post` object (WP_Post) and the second one `$query` is the current set WP_Query

**Comment by LeRondPoint** [comment]
Yes, I know that but the header text is different for each route, yet they basically have the same contents (a list of posts matching a given WP_Query).  The only thing that is different is the page header.

I guess creating a new function that calls the common code is the way to go?

It would be a nice improvement though

**Comment by jlambe** [comment]
Well I'm not sure how you would pass an author name or id to the controller on current version.
The next version has the `illuminate/router` package full integrated as well. I haven't yet tested but sure it has to be possible to type-hint dependencies on a controller method. So your case on next version would be to create a class with your custom code and simply type hinted it.

**Comment by LeRondPoint** [comment]
Yeah, I think I can use the setParameter on Laravel Route in 1.3.

**Comment by Saeed-Pooyanfar** [comment]
The routing in themosis is much like laravel, but have some major differents:

1- The first parameter for get method ( or other methods like post ) is the main route, not a conditional tag!
2- In laravel we can get parameters very very very easy by putting curly braces around route, for example:
```php
Route::get( '/username/{username}/email/{email}', 'index@testController' );
```
3- We can get parameters in controller:
```php
// testController.php
...
public function index( $username, $email ) {
     .....
}
...
```
4- As you can see, we write method name first in second parameter .

@jlambe  can you make themosis routing like laravel?

**Comment by LeRondPoint** [comment]
Because of pretty permalinks and the way WP routes are handled, I wonder how simple it will be...  Setting a standard independent of permalinks could do it.  I.E.  author/{slug}, tag/{slug}, etc.

Random parameters wouldn't work for built in routes but if I remember correctly, there is already a solution like you propose for custom routes, check the doc.

**Comment by jlambe** [comment]
@LeRondPoint It is on the next version. You'll be able to define custom routes but not for the WordPress ones as those do not accept extra parameters otherwise there are not recognized, but next version has the laravel router completely integrated, so you can also use middlewares for all routes, ...

**Comment by LeRondPoint** [comment]
Right, I had the custom conditions doc in mind!
