### ISSUE TITLE
miss symfony / http-foundation during themosis Installation

### ISSUE THREAD

**Issue by Bulldog-hub** [themosis/framework#332]
I'm just want to install themosis to start new project and i have some problem during installation.

`composer create-project themosis/themosis myProject`

and the installation fails because obviously missing a package symfony.
```

Installing themosis/themosis (1.2.3)
  - Installing themosis/themosis (1.2.3)
    Loading from cache

Created project in myProject
Loading composer repositories with package information
Warning: Accessing wpackagist.org over http which is an insecure protocol.
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - themosis/framework 1.2.3 requires symfony/http-foundation 2.4.2 -> no matching package found.
    - themosis/framework 1.2.2 requires symfony/http-foundation 2.4.2 -> no matching package found.
    - themosis/framework 1.2.1 requires symfony/http-foundation 2.4.2 -> no matching package found.
    - themosis/framework 1.2.0 requires symfony/http-foundation 2.4.2 -> no matching package found.
    - Installation request for themosis/framework 1.2.* -> satisfiable by themosis/framework[1.2.0, 1.2.1, 1.2.2, 1.2.3].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
```

I 'm new to this framework and have already done tests and everything worked on my local machine . Would you have a solution to continue the install of themosis

Thanks for your help.

**Comment by jlambe** [comment]
Hi,
can you first clone the `themosis/themosis` repository, tag `1.2.3`:
- https://github.com/themosis/themosis/tree/1.2.3

Open the folder inside your code editor or IDE and edit the default `composer.json`file. Replace `http://wpackagist.org` to `https://wpackagist.org`. Save and run `composer install` and let me know if this solve the issue.

The `symfony/http-foundation` requirement can be `^2.4.2` in the `requires` statement of the `composer.json` file.

**Comment by BullTheDog** [comment]
hello Julien,

it works perfectly via the repo and I also tested using composer.
I added an "s" in the URL , make  a  `composer install`  everything is ok.

I can now work with your framework

thanks for your help

**Comment by Bulldog-hub** [comment]
hello Julien,

it works perfectly via the repo and I also tested using composer.
I added an "s" in the URL , make a composer install everything is ok.

I can now work with your framework

thanks for your help

**Comment by jlambe** [comment]
Glad it is solved. Cheers,
