### ISSUE TITLE
Weird Install Problem

### ISSUE THREAD

**Issue by pandorawombat** [themosis/framework#333]
I got so excited to read about this because I wanted to Laravelize WordPress. However, trying to install, I at first got Composer errors because Composer didn't like the fact that the composer.json was trying to pull from http://wpackagist.org (not https), and it crapped out. So I edited the json to include https instead (since that's a viable protocol for that link) and reran install. It seemed to finish installing everything that time just fine, and then I set up all the config options, then tried to proceed to where you hit the url to force it to do the WordPress install. Problem is, I keep getting my Webuzo placeholder page instead of it trying to install WordPress. I double checked to make sure my server was set up correctly by quickly inserting an index.html with the words "Testing" in there, and when I did that, the placeholder page went away and it did show that placeholder page - so I know my server is hitting the correct directory. Deleted the test file and tried again, and the placeholder page came back. I then tried changing the environment.php to always return "local" instead of trying to guess the environment based on any hostname or anything else, just to make things as simple as possible. Then I put the credentials from that server in both the local and product env files (I'm not using a staging server - this server no one really knows about yet - I'm just using local env to turn debugging on and off quickly, really). Still no dice. I'm a big stumped. This is my own VPS, so I have a lot of control over server settings if you can suggest any NGINX or PHP settings I might need to examine. Much googling and wiki scanning seemed to turn up no one else with my problem of it simply ignoring the framework entirely even though all the files are there. Thanks.

**Comment by jlambe** [comment]
Not sure to know what's going on in your setup. Did you target the webserver to the `htdocs` directory and not the project root?
If you can pass config file and screenshots of how your directories are setup, perhaps it might help debug your issue.
In the environment documentation, there is a simple nginx config, it might help:
http://framework.themosis.com/docs/environment/

**Comment by jlambe** [comment]
Any news from your issue? Is is resolved or not?

**Comment by pandorawombat** [comment]
I finally redid my entire VPS using a LAMP stack instead of a LEMP stack and got it to install. Just never did get it to install with NGINX. It was definitely something about the server block I had set up in NGINX not liking the routing that was going on.

**Comment by pandorawombat** [comment]
However, now I can't get any routes other than my 'front' to work. I have no idea why. No 'page' general route works, no specific 'page' route works, just 404s all around. These three routing statements, for example, the top one works fine, the bottom one doesn't. They all point to valid functions in my MainController class that do almost identical things, just for the sake of testing. The first one gets me to the front page, the other two 404 no matter what. And yes, I checked the page slug and the rewrites in Apache. I just feel like I'm missing some piece of the puzzle here. A little frustrating because I really want this to work - I love the idea.
Route::get('front','MainController@homepage');
//Route::get('page','MainController@page'); //this one I had tried when the one below wouldn't work.
Route::get('page',['site-registration','uses'=>'MainController@siteregistration']);

**Comment by pandorawombat** [comment]
The all page route didn't work either. I got straight up 404s for every route I tried to define except "front." I didn't have permalinks set to anything other than /%postname% - but I gave up trying to implement this theme because I was on a tight deadline for this project, so I finally switched to a different theme. Thank you for your help though.
