### ISSUE TITLE
Method Themosis\View\View::__toString() must not throw an exception

### ISSUE THREAD

**Issue by harwin-borger** [themosis/framework#335]
Hello,

When working with Themosis we sometimes get the error:
`Method Themosis\View\View::__toString() must not throw an exception`

This mostly means that some variable doesn't exist. At the moment it doesn't show the location of the error. 

Is there any way to show the exact location of the error and also proving more information? This will save a lot of debugging time.  

Regards Harwin

**Comment by jlambe** [comment]
Hi, I'm aware of this issue as it happened a lot to me as well. This is fixed for the next release but in the meantime you can write this code instead for your views.
```php
return View::make('your.view')->render();
```

This tells the view to be rendered/compiled and return a string in place of the view instance. This will give you the error with debugging information if something is missing.

**Comment by harwin-borger** [comment]
Hi, Thank you for the quick response with a short term and long solution. I am looking forward for the next release. It's a great framework, which makes developing Wordpress websites real fun. Keep up the good work!

**Comment by jlambe** [comment]
Thanks 😄
