### ISSUE TITLE
Media Field: No Size Option

### ISSUE THREAD

**Issue by heikobihlmaier** [themosis/framework#339]
Hello,

I need a size option within the media field.

I have 2 custom images sizes. The customer only should choose these 2 sizes within the media file.

Is that possible ?

**Comment by dstollie** [comment]
Hey heikobihlmaier,

I'll try to help you. The default functionality of WordPress is that you just upload the image and in the code you define which image size you want to use on the page you are talking about. Isn't that what you also want? You can simply define 2 image sizes, the customer uploads it's media files without having to hassle with images sizes and you tell WordPress which image size you want to present on your page.

If this is not your case Im curious why you need something different.

Dennis

**Comment by jlambe** [comment]
@heikobihlmaier See your other issue [themosis/themosis#115](https://github.com/themosis/themosis/issues/115)
