### ISSUE TITLE
Feature request Action::remove()

### ISSUE THREAD

**Issue by Rhinni** [themosis/framework#342]
Hello,

I'd love the option to remove an action with Action::remove();

**Comment by dstollie** [comment]
Hey Rhinni, good feature request interesting this isn't implemented.

I will add this feature and submit al PR for you!

**Comment by dstollie** [comment]
Fixed in pull request: https://github.com/themosis/framework/pull/344

**Comment by Rhinni** [comment]
Cheer dstollie

**Comment by jlambe** [comment]
Will look after the PR from @dstollie
