### ISSUE TITLE
Looping out ACF fields with scout

### ISSUE THREAD

**Issue by Benjaminsson** [themosis/framework#349]
When trying to loop out my repeater fields from ACF the browser never stops loading. I'm guessing it goes into some kind of infinite loop. It works fine doing a normal while loop.

Doesn't work

```
@while (have_rows('the_field'))
    {{-- the_row() --}}
@endwhile
```

Work:

```
<?php
while (have_rows('the_field')) {
    the_row();
}
?>
```

**Comment by jlambe** [comment]
I haven't tested this but the call to `the_row()` function is a comment and is not executed. Change it to `<?php the_row(); ?>` or `{{ the_row() }}`. I suspect this function to alter an index of some sort. Let me know if it works, otherwise there is an issue with my current `@while` statement.

**Comment by Benjaminsson** [comment]
Sorry, bad example. Still the same error even if you just loop out some test echos.

**Comment by jlambe** [comment]
Weird. Will need to test this on next release as well. But presumably it will work as next version is using the full Blade engine.

**Comment by Benjaminsson** [comment]
Awesome! So there will be no Scout extension (.scout.php) at all?

**Comment by jlambe** [comment]
You could still use the `scout.php` file extension for backwards compatibility but it is converted to Blade at compilation. But yes, switch to `blade.php` is the way to go.
