### ISSUE TITLE
Populate the body_class() for custom routes

### ISSUE THREAD

**Issue by jlambe** [themosis/framework#350]
Populate the string returned by the `body_class()` function on custom routes. By default, is empty but might be useful to return class names based on the route URI parameter.

**Comment by guicara** [comment]
I think this is an **essential feature**. I strongly depend on the body classes to apply specific CSS styles.

Currently, as a workaround (but definitely not flexible), I use the `body_class` filter to manually add class depending on the URI.

**Comment by jlambe** [comment]
@guicara Do you have an example for which class name you apply for a custom route? What criteria do you choose to define the class name? The custom `uri`?

**Comment by guicara** [comment]
@jlambe For example, I have implemented a FAQ on the project I'm working on. The FAQ is a custom post type. Each question of the FAQ can be associated with a category and a subcategory (custom taxonomy "category").

On the frontend I want to have the following URI:

- /faq/
- /faq/category/
- /faq/category/subcategoy/
- /faq/page/2
- /faq/category/page/2
- /faq/category/subcategory/page/2

routes.php :

```
// FAQ
$faqSlug = \Acme\Theme\Controllers\FaqController::ARCHIVE_SLUG;
Route::get($faqSlug, 'Acme\Theme\Controllers\FaqController@archive');
Route::get($faqSlug . '/page/{page}', 'Acme\Theme\Controllers\FaqController@archive');
Route::get($faqSlug . '/{category?}/{subcategory?}', 'Acme\Theme\Controllers\FaqController@archive');
Route::get($faqSlug . '/{category?}/page/{page}', 'Acme\Theme\Controllers\FaqController@archive');
Route::get($faqSlug . '/{category?}/{subcategory?}/page/{page}', 'Acme\Theme\Controllers\FaqController@archive');
```
Instead of the usual:
```
Route::get('postTypeArchive', array(Faq::POST_TYPE, 'uses' => 'Acme\Theme\Controllers\FaqController@archive'));
```
I have (as a temporary workaround) simply registered this hook to add the custom class on the body element:
```
/**
 * Filter the classes that are assigned to the body HTML element.
 */
add_filter('body_class', function($classes) {
    if (strpos($_SERVER['REQUEST_URI'], '/' . FaqController::ARCHIVE_SLUG . '/') === 0) {
        $classes[] = 'post-type-archive';
        $classes[] = 'post-type-archive-cm-faq';
    }

    return $classes;
});
```

Another solution is to use Blade to manually define the class name with `@yield`:

header.blade.php
```
<body class="<?php echo implode(' ', get_body_class()); ?> @yield('bodyClass')">
```
faq_archive.blade.php
```
@extends('layouts.main')
@section('bodyClass', 'faq')
```


> What criteria do you choose to define the class name? The custom uri?

Yes.

`Route::get('foo')` could generate the class name `foo`.

And if we have "nested" route, why not do something like that?
`Route::get('foo/bar')` could generate the class class name `foo-bar`.

**Comment by guicara** [comment]
As @jlambe said on Gitter, we can also use `container('router')->getCurrentRoute()->getPath()` in the callback method of the route to get the URI and then append it to the body class.

**Comment by rumur** [comment]
@jlambe What if we place the filter to `App\\Hooks\\Application@register` method.

In `register` method add a new `Filter::add`

Like this 

```php
public function register()
{
      //...

      /*
        |--------------------------------------------------------------------------
        | Populate the body_class() for custom routes
        |--------------------------------------------------------------------------
       */
        Filter::add('body_class', function($classes) {
            return $this->populateBodyClass($classes);
        });

      //...
}
```

And add a method to the ```App\\Hooks\\Application::class```

something like this

```php
   /**
     * Populate the body_class() for custom routes
     *
     * @param array $classes
     * @return array
     */
    protected function populateBodyClass(array $classes)
    {
        /** @var Route $route */
        $route = $this->app->router->getCurrentRoute();

        // It's a custom route
        if (! $route->hasCondition()) {

            $route_tokens = array_reverse($route->getCompiled()->getTokens()); // Set the right order for tokens

            $class_based_on_params = array_filter( // Get rid off an empty class
                array_map(function ($token) use ($route) {

                    $class = false;

                    switch ($token_type = $token[0]) {
                        case 'variable':
                            if ($route->hasParameter($token_param_name = $token[3])) {
                                $param_class = $route->parameter($token_param_name);
                                $class = is_string($param_class) ? $param_class : false;
                            }
                            break;
                        case 'text':
                            $class = sanitize_title($token[1]); // Static route part
                            break;
                    }

                    return $class ? sanitize_html_class($class) : $class;

                }, $route_tokens)
            );

            $uri_class = join('-', $class_based_on_params);

            array_push($classes, $uri_class);
        }

        return $classes;
    }
```

**Comment by jlambe** [comment]
@rumur It's Ok to set the filter on the `Application` hook class but not writing all the logic into it. Somehow it will be best to extract the logic from the class, be it a Trait or a Class, dunno yet.

If a Trait, adding the functionnality is just a matter of calling `use CanFilterBodyClass;` and the feature is in. Using a class, it is a perhaps more verbose. Not sure if we need to instantiate the responsible class before after inside the filter:

```php
$filterClass = new BodyClassFilter();

Filter::add('body_class', [$filterClass, 'filter']);
```

or

```php
Filter::add('body_class', function ($classes) {
    $filter = new BodyClassFilter($classes);
    return $filter->get();
});
```

Finally, which class names are we going to generate ? I haven't yet looked at it deeply. I'm open to suggestions.

**Comment by rumur** [comment]
> it will be best to extract the logic from the class, be it a Trait or a Class
yes, I do agree that this approach is the better one.

> which class names are we going to generate? I haven't yet looked at it deeply.
me neither, I just wanted to help.

**Comment by jlambe** [comment]
@rumur I use your code and instead of setting the body class from a hook, I've built a `WordPressBodyClass` middleware. Thanks for your work ;)
