### ISSUE TITLE
Custom post type permalinks

### ISSUE THREAD

**Issue by romainhe** [themosis/framework#351]
Hi, I use this plugin [https://fr.wordpress.org/plugins/custom-post-type-permalinks/](url) to improve urls on my website. I have 2 tax and my post url is like that : `/post-type-slug/%tax1%/%tax2%/%postname%`

Everything works when I choose one term for each tax, but if I select 2 terms (so we get an url like `/post-type-slug/%tax1-term-1%/%tax1-term-2/%tax2%/%postname%`) the themosis route give me a 404 issue....

i'm going crazy :+1: 

Thx for help..

**Comment by jlambe** [comment]
Do not know this plugin but it looks like you're trying to reach an invalid URI where the tax2 term is not defined. I suppose that when your permalink is handling to taxonomy, you need to specify the tax slug + term slug for each one, no?

On a classic theme, which template file do you use to show content for the URL you're trying to reach? Have you tried with a default theme to access it?

**Comment by romainhe** [comment]
Hi, thx for your reply !

Yes, you must link slug taxonomy and url like that : [http://postimg.org/image/ub5x53635/](url)

Everything worked without themosis :( I never had problems with this plugin on a "classic" wordpress install

The template file to display content is the same -> single.php (In routes.php I try with single and singular slug...)

I just created a custom route to dump the query and I don't understand why but the returned sql request is : 
`["request"]=>
  string(161) "SELECT   wp_posts.* FROM wp_posts  WHERE 1=1  AND wp_posts.post_name = 'brochure-armani' AND wp_posts.post_type = 'attachment'  ORDER BY wp_posts.post_date DESC "`

Wtf \o/ ?

**Comment by romainhe** [comment]
note : I just saw that the second tax is a child of the first tax

**Comment by jlambe** [comment]
Normally the route to define is a singular one. As you mix post type and taxonomy, have you tried to put your singular post type route above the others (so it takes precedence over the others to make sure it hits your request) ?

Inside your `Route::get()` call, the second argument of your callback or controller method is the WP_Query object, is the above query results from your route?

**Comment by romainhe** [comment]
Yes I tried, the route system don't match anything and match the 404 route `Route::get('404','PagesController@notfound');`

Yes the sql request above is the result of the wp_query from route...

**Comment by jlambe** [comment]
Can you put a "single.php" or "singular.php" file at your theme root see it it works?

**Comment by romainhe** [comment]
In `\htdocs\content\themes\my-them\single.php` ? :o 

I try and nothing append... :/

**Comment by jlambe** [comment]
If you're using the framework version 1.2.3, then it should display something as the `single.php` template should be hit before the `index.php` file. This means that your route is not the correct one or if you have another plugin activated, something has altered the query.

**Comment by romainhe** [comment]
Hm, the plugin for custom permalinks is guilty, I know, but without themosis it works :( Maybe something on How themosis route work cause this error.. ?

**Comment by jlambe** [comment]
On version 1.2.3, the routing system is purely using the WordPress template functions like `is_single()` or `is_singular()`. The framework do not hook on `pre_get_posts()` to modify the WP_Query so, in theory, if it works on a classic installation, it has to work with it. One weird thing tough is your WP_Query which returns an `attachment` post in place of `imprimerie` one. This I can't explain... sorry :(

**Comment by romainhe** [comment]
Hm ok :/ thx for your help

I Will back here if i resolve this mystery...
