### ISSUE TITLE
Always redirect to a trailing slash problem

### ISSUE THREAD

**Issue by dstollie** [themosis/framework#352]
For some reason WordPress forces me by sending a 301 redirect to have a trailingslash in as my url. The problem is that it redirects in a very late stage which pratically causes the loadtime to double.

Simple examaple: `http://test.dev/test-page` will always be redirected to `http://test.dev/test-page/` I can seem to find the problem as fast as I want. Do you have any guess what could be the trouble maker?

Thanks

**Comment by jlambe** [comment]
Is this from a custom route or a WordPress page route?

**Comment by jlambe** [comment]
I'm testing right now the latest version with multiple custom routes and I haven't encounter any redirects to an URI with its trailing slash. Have you modified your own .htaccess file?

**Comment by dstollie** [comment]
.htaccess can not be the problem. The pageload untill the 301 redirect takes more than a second. If htaccess causes the redirect it would be way faster

**Comment by jlambe** [comment]
I can't reproduce your issue. Is there any other plugins installed within your project?
