### ISSUE TITLE
Model/template

### ISSUE THREAD

**Issue by romainhe** [themosis/framework#356]
I can't find a way to get if a page template is used, like `if(is_template('contact')`

Model created in `templates.config.php` are not wordpress templates page and so the body class display `page-template-default` ...

Any idea ? 

Thx !

**Comment by jlambe** [comment]
If you're using version 1.2.3 it's an issue. 1.2.3 defined a custom meta to set its template part but brings lot of confusion.
Hopefully this is fixed on next release (current master branch) as it uses the core WordPress template meta field.
Are you working on production site or just getting started? If you're just getting started and feel adventurous, you can try the current dev-master branch of the framework. It lacks documentation as it's not yet released (but coming very soon) but if you're confortable with code, it should be straight forward and you can still ask questions on Gitter anytime: https://gitter.im/themosis/framework

**Comment by romainhe** [comment]
Ok great !
Waiting for the fix, thx
