### ISSUE TITLE
Collection field - Media ordering doesn't work

### ISSUE THREAD

**Issue by guicara** [themosis/framework#357]
Hi Julien,

I use the `Collection` field to allows my users to manage a collection of media files (pictures).

`Field::collection('photos-gallery')`

The fild UI allows the user to (re)order the files. Unfortunately, after updating the post, the custom order is not saved.

When I look a the `POST` data sent to `post.php` by WordPress, the array of my Collection field is ordered correctly. So it must be a problem when the post meta is saved in database?

I don't know if the same issue occurs with Themosis Famework 1.2.x. We currently use Themosis Framework 1.3 (dev-master).

Thank you,

Guillaume

**Comment by jlambe** [comment]
@guicara Thanks for pointing that out. It's probably an issue with current dev version as I've modified the save process of meta. I'm going to look at it and let you know when it is solved.

**Comment by guicara** [comment]
@jlambe thank you for your quick answer!
