### ISSUE TITLE
Doubt loading.config.php

### ISSUE THREAD

**Issue by ribeiroevandro** [themosis/framework#358]
When configuring a controller or model using `'BaseController'        => themosis_path('theme').'controllers'.DS.'BaseController.php'` for example, I get the following error. I do not know if it's a silly mistake, but I'm starting now and I apologize if it's stupid.

![screenshot 2016-11-22 00 05 00](https://cloud.githubusercontent.com/assets/943553/20508246/5b3a7e52-b047-11e6-8e44-8aa2507dcd6b.png)

**Comment by jlambe** [comment]
hi,
the `loading.config.php` file is a utility to define paths for directories for class autoloading.
You don't have to define each class for autoloading.

In stable version 1.2.3, the classes do not use PHP namespaces, meaning there is no statement like this one on top of each class: `namespace Some\Directory\Name`. So the default loading config is like so: 
```php
<?php
return [
    /*
    * Edit this file in order to configure your theme's
    * classes autoloading. Classes are loaded using PSR-4.
    *
    * The key is the namespace and key's value contains one or more paths to your classes.
    */
    ''  => [themosis_path('theme').'controllers', themosis_path('theme').'models']
];
```

Meaning that all classes inside the `resources/controllers` and `resources/models` are auto-loaded and that they use no namespace (empty key).

If you want to define a namespace, set the key like so `Theme\\Controllers\\` and inside each controllers class files, add a namespace statement `namespace Theme\Controllers;`

The issue you have is stating that there is typo error in your key namespace, basically missing the double backslashes `\\` at the end. But do not use`BaseController` as a namespace, as it is a core class and it's not a compliant name.

And do not worry for your question, it's not stupid. For more information about namespacing, I encourage you to read over the PHP documentation, full of examples: http://php.net/manual/en/language.namespaces.php

**Comment by ribeiroevandro** [comment]
Thanks a lot for the attention, I'm at the beginning and migrating a project that was done using version 1.1.3 and some doubts arise in the middle of the way. I read that there are improvements in version 1.3.0, is there any prediction for it?

**Comment by jlambe** [comment]
Yes lots of improvement for release 1.3.0. There is no date yet announced but it will come right after the WordPress 4.7 release 😄

**Comment by jlambe** [comment]
In the meantime, you can test the next version if you want by cloning the `themosis/themosis` master branch. I'm in the middle of writing the documentation so you'll need to dig into source code some times for the APIs.

**Comment by ribeiroevandro** [comment]
Cool, I'm following the evolution closely. :slightly_smiling_face:

**Comment by Benjaminsson** [comment]
Sorry for using the issue tracking as a forum but i'm trying to get the autoloader to work with some helper classes. Where do i get of the tracks here?

In loading.config.php i do this:
```php
<?php
return [
    /*
    * Edit this file in order to configure your theme's
    * classes autoloading. Classes are loaded using PSR-4.
    *
    * The key is the namespace and key's value contains one or more paths to your classes.
    */
    ''  => [themosis_path('theme').'controllers', themosis_path('theme').'models'],
    'Jbenjaminsson\\' => [themosis_path('theme').'Helpers']
];
```

I create a folder called "Helpers" in "resources" and in there i create a file called `Parse.php`.
```php
<?php
namespace Jbenjaminsson\Helpers
class Parse
{
    static function helloString($myString) {
        $myString .= ' hello';
        return $myString;
    }
}
```
And in one of my Scout files i try to use it like this:
```php
    $test = Parse::helloString('hello');
    var_dump($test);
```

**Comment by jlambe** [comment]
@Benjaminsson I think you do get an error of class do not exists. Your current `Helpers` folder is assigned a `Jbenjaminsson` namespace from the `loading.config.php` definition. But your class is defined with "sub" namespace of `Jbenjaminsson\Helpers` which means that your class should be in a "sub" directory called `Helpers` from the current Helpers folder.

Rename your current `Helpers` directory as `library`, add a subdirectory called `Helpers` and update your `loading.config.php` definition tho this: `'Jbenjaminsson\\' => [themosis_path('theme').'library']`

Normally it should fix your issue.

**Comment by Benjaminsson** [comment]
@jlambe I made the changes but i'm still getting this error:
> Method Themosis\View\View::__toString() must not throw an exception, caught Error: Class 'Parse' not found

Should i add something like this? `use Jbenjaminsson\Helpers\Parse as Parse;`
That and doing it like this
```php
    $parse = new Jbenjaminsson\Helpers\Parse();
    $test = $parse::helloString('hello');
```

both generates:
> Method Themosis\View\View::__toString() must not throw an exception, caught ParseError: syntax error, unexpected 'class' (T_CLASS), expecting '{'

**Comment by jlambe** [comment]
@Benjaminsson your method is static so the best is to call it like this: `Jbenjaminsson\Helpers\Parse::helloString('hello');`

In your class namespace definition, you're also missing a `;`, it should be `namespace Jbenjaminsson\Helpers;`

**Comment by Benjaminsson** [comment]
Awesome! Thanks! Damn syntax errors :S.
