### ISSUE TITLE
problem du menu

### ISSUE THREAD

**Issue by yassinino** [themosis/framework#359]
j'ai créer un nouveau menu mais il ne s'affiche pas , il m'affiche le menu par defaut avec la page d'exemple, comment je peut activer le menu que je veux.

**Comment by jlambe** [comment]
Avec cette description je ne sais pas vous aider. Pouvez-vous expliquer les étapes que vous avez réalisées pour créer un menu dans l'administration de WordPress, avez-vous associé le menu à une "location/area" et est-ce que votre thème utilise la fonction `wp_nav_menu` pour afficher vos menus ? Merci d'ajouter des captures d'écran pour illustrer le problème.

**Comment by yassinino** [comment]
voici le menu
![capture](https://cloud.githubusercontent.com/assets/12089592/20669416/07c02680-b56c-11e6-8b4e-7711b8e7d3b0.PNG) qui m'affiche

et moi je voulais activer ce menu
![capture1](https://cloud.githubusercontent.com/assets/12089592/20669439/266898c4-b56c-11e6-8d96-8e782a556a3b.PNG)
et voici le code source 
![capture3](https://cloud.githubusercontent.com/assets/12089592/20669448/307fc080-b56c-11e6-8263-f65e3554cc4a.PNG)

**Comment by jlambe** [comment]
Normalement, sur la deuxième image, sous les liens, il doit y avoir une option à cocher pour la "location". Le menu doit présenter l'option "Primary" afin d'afficher le menu au bon endroit. Une fois l'option cochée, le menu défini s'affichera dans la "location" = "primary"

**Comment by yassinino** [comment]
ouiii j'ai ça

![capture5](https://cloud.githubusercontent.com/assets/12089592/20669769/d74c2434-b56d-11e6-85b8-d0ee31ee9bd6.PNG)

**Comment by jlambe** [comment]
Est-ce un thème développé sur base du thème fourni avec le framework Themosis? Est-ce que dans le fichier "menus.config.php", il y a une location définie avec "primary" => "Header navigation" ?

**Comment by yassinino** [comment]
oui j'ai intégrer mon thème sur base du thème de Themosis ,
Merci M.jlambre le problem est résolu :)
mais j'ai une petit questionne s'il vous plait, comment je peut insérer les champs post_type par ex:
![capture3](https://cloud.githubusercontent.com/assets/12089592/20670469/eb1c80be-b570-11e6-8153-da99c8211c0e.PNG)
dans une autre table a la base de donnes qui s'appel wp_categories.

**Comment by jlambe** [comment]
Si vous souhaitez créer une nouvelle table, il faudra employer la class `$wpdb` pour la créer et en second, il faudra utiliser un hook comme `save_post`  pour ajouter le code MySQL nécessaire pour ajouter vos données dans la nouvelle table.

**Comment by yassinino** [comment]
mais comment je peut envoyer les donnes du formulaire au contrôleur pour les insérer dans la table wp_catégories j’espère comprend ma questionne :)

**Comment by yassinino** [comment]
c'est pour cela je voudrais utilisé themosis pour travailler en MVC, par ce que je travaille bcp avec le framework laravel aussi

**Comment by jlambe** [comment]
La version stable 1.2.3 est "limitée" par rapport à Laravel. Cependant la version en cours de développement (master branch) intègre beaucoup de fonctionnalités de Laravel 5.3 dont l'implémentation de Eloquent, auto-instantiation des classes au niveau du controller, intégration complète de Blade, ... Vous pouvez tester la version en cours (master branch) du dépôt themosis/themosis, qui devrait proposer beaucoup plus de flexibilité mais il n'y pas encore de documentation disponible.

**Comment by yassinino** [comment]
ça marche, merci !

Le 28 novembre 2016 à 14:57, Julien Lambé <notifications@github.com> a
écrit :

**Comment by yassinino** [comment]
salut julien ,

j'ai un problem au niveaux des routes , est ce que il faut que je déclare les routes dans un autre fichiers ou bien juste dans le fichiers route.php car il me renvoi page not found meme si il est définer dans le fichier route.php ?!!

**Comment by jlambe** [comment]
Oui toujours dans le fichier `routes.php`. dans la version 1.2.3, un message "Page not found" apparait dès qu'il ne trouve pas la route adéquate. Notez que sur cette version, les routes ne fonctionnent pas de manière traditionnelle et ne gèrent que les "routes WordPress". Dans la nouvelle version nous avons le choix... Normalement si il ne trouve rien et que vous avez défini une route 404, la route 404 prend le relais.

**Comment by yassinino** [comment]
Mais dans l'application ToDo de la gestion des taches , Vous avez utilisé
les routes personnalisée post et get si j'ai bien comprée ?

mon problem c'est ça, qu'on j'ai utilisé cette route


Route::get('front', function(){
    return 'Hello World!';});

il me donne "page not found" ??

et tous mes questionnes par ce que il faut que je créer une application web
en utilisant wordpress mais c'est trés compliquer , c'est pour ça je
voulais utilisé themosis pour me facilité le travaille.

**Comment by jlambe** [comment]
Les méthodes "get" et "post" pour les routes sont accessibles. Quand je parle de "Route", c'est le paramètre URI habituelle que l'on ne peut pas utiliser comme dans les autres frameworks. C'est possible à l'aide de la Rewrite API de WordPress et de définir sa propre condition pour une route (ce qui est utilisé dans l'exemple ToDo).
Pour que la route "front" fonctionne, il faut créer une page WordPress dans l'administration, ensuite allez dans "Réglages->lecture" et définir cette page comme la page d'accueil. A ce moment-là, la route "front" fonctionnera.

**Comment by yassinino** [comment]
ça marche j'ai bien compris, une dernière questionne s'il vous plait,
comment je peut appeler URL de l'action de la balise <form> pour envoyer
les donnes des champs au contrôleur par ex: IndexControlleur@store !

Le 28 novembre 2016 à 20:54, Julien Lambé <notifications@github.com> a
écrit :

**Comment by jlambe** [comment]
En utilisant `Form::open('url/to/action')`, le premier argument de la fonction pour ouvrir un formulaire permet de définir l'URL de la requête avec l'envoi des données. Ici, même si une route serait nommée (version master branch), on ne peut pas juste donner le nom de la route. Il faut toujours préciser l'URL complète. Donc `$action` devrait être l'URL sur laquelle votre controller est associée.
