### ISSUE TITLE
Eloquent conflict with routes.

### ISSUE THREAD

**Issue by mdalke** [themosis/framework#361]
Hi,

I tried to be smart here, and include illuminate database in our model builds for database magic. However when I include 'illuminate/database' to the composer json file, it works perfectly fine and I can include them in my models and that works, however using template routes stops working.

Have you come across this before?

Cheers.

**Comment by jlambe** [comment]
Which version are you using? Version 1.2.3 or current master branch ? The current branch has Illuminate Database implemented where current "stable" released version has not.
On current master branch, I haven't met any issues yet.
