### ISSUE TITLE
Named route and implement the Laravel helper function route()

### ISSUE THREAD

**Issue by guicara** [themosis/framework#365]
Hi Julien,

As you said on Gitter today:
>  (...) named routes haven’t been tested yet as there is a mix between WordPress and classic routes.

It would be great if we can use [named route](https://laravel.com/docs/5.1/routing#named-routes) with the framework (>= 1.3) and then add support for the helper function `route()`. This helper uses the route's name to generate an URL.

```
Route::get('user/profile', ['as' => 'profile', function () {
    //
}]);
```

```
$url = route('profile');
```

Thanks,

Guillaume

**Comment by jlambe** [comment]
@guicara This is now implemented on the `develop` branch. Note that this feature can't return the correct URL for a WordPress based route as a `single` can point to multiple destinations based on the post ID.
