### ISSUE TITLE
Get woocommerce product thumbnail.

### ISSUE THREAD

**Issue by PauloSousapt** [themosis/framework#367]
Hello, congratulations for your work with this framework it's awesome.

I'm having trouble with something maybe you can help me, I've made a model that gets all the woocommerce products of one category and passes it to the view, until now everything works fine, I can show the products name using a foreach cicle, but now I want to display the products name and the thumbnail(featured image) of the product but I don't know how to return the image url using scout, it could be something like {{$product->post_thumbnail }} but it's not and when I make a var_dump on the returned products I can't see the image url anywhere. Can you help me?

Thanks a lot.

**Comment by jlambe** [comment]
Hi @PauloSousapt, the thumbnail (attachment post ID) is stored into another table. The default WP_Post object do not store the reference so you cannot make a call like `$product->post_thumbnail` as such property do not exists on the instance.

The simplest method would be to call the WordPress core function `get_post_thumbnail()` and pass it as first argument your `$product->ID`. The function if I remember returns an `img` tag for you.
