### ISSUE TITLE
Create a route for a URL which isn't associated with a WordPress page/post

### ISSUE THREAD

**Issue by lougreenwood** [themosis/framework#370]
Hello :)

Is there any simple method for creating a URL route where there is no WordPress page/post/content specifically created for it?

**Comment by jlambe** [comment]
Yes if using release 1.3.0 which is due this tuesday. For example you'll be able to write this:
```php
Route::get('page/about', function () {});
```
And it will listen to URI `domain.tld/page/about` like exepected. 2 days to wait to get it.

**Comment by lougreenwood** [comment]
ohh - nice - very exciting 👍
