### ISSUE TITLE
Set custom template as default?

### ISSUE THREAD

**Issue by KatarinaH** [themosis/framework#374]
Hi,

I can't find a way to replace the default page-template in worpress to my custom template. Does anyone have any tips on what is best practice for that?

Thanks in advance

/Katarina

**Comment by jlambe** [comment]
Hi,
you define your page templates inside the`templates.config.php` file located in the `resources/config` folder of your theme.
Current 1.2.3 version has its own template system which is very basic. From your pages, there should be a Template metabox with a select field that let you choose which defined template to use for a specific page. The select field list the templates registered in your configuration file.

Note: a new release of the framework, 1.3.0, will be released tomorrow and the templates will now use core WordPress apis and let you define custom templates for pages but as well for custom post types.

**Comment by KatarinaH** [comment]
Ok, in other words in version 1.2.3 you can't change it so your custom template will be set as the default template when you create a new page? (When I create a new page I want it to use template 'article' by default and not have to change it from default to article every time)

If that's the case I wait for the new release :)

Thanks for your quick answer! 

/Katarina

**Comment by jlambe** [comment]
In current version 1.2.3, you can change the template of a page yes as well as in the next release.

But for whatever versions, defining a default template for any pages you add from the WordPress admin is not possible.

If you have too many pages that need a default template, perhaps it is best to work with a custom post type, so there is no need to bother of a template and you can bring your own logic. If you have a template `article`, perhaps work with the default `post` type which are articles.
