### ISSUE TITLE
SubPage Route

### ISSUE THREAD

**Issue by niknickolas** [themosis/framework#376]
```php
function themosis_is_subpage( array $parent ) { // $parent  is always empty
		global $post; // I have had time when $post was empty, but now it is not
		/*
				$parentPage = get_post( $post->post_parent ); //for what purpose we have to retrieve parent page ?

				if ( is_page() && $post->post_parent && $parentPage->post_name === $parent[0] ) {
					return $post->post_parent;
				}
		*/
		/*
		 * First variant
		 * */
		if ( is_page() && $post && $post->post_parent ) {
			return true;
		}
		/*
		 * Second variant
		 * */
		if ( $post && $post->post_type == 'page' && $post->post_parent ) {
			return true;
		}


		return false;
	}
```

**Comment by niknickolas** [comment]
found out that $parent contains specified subpages names from route
Route::get( 'subpage', [ 'cities', 'uses' => 'CityController@find' ] );

I think after that as we detected that current item is subpage we should check  whether there set additional filters by subpages names
```
if(!empty($filtered)){
return in_array($post->post_name)
}
```

**Comment by niknickolas** [comment]
found out that $parent contains specified subpages names from route
Route::get( 'subpage', [ 'cities', 'uses' => 'CityController@find' ] );

I think after that as we detected that current item is subpage we should check  whether there set additional filters by subpages names
```
if(!empty($filtered)){
return in_array($post->post_name,$filered)
}
```

**Comment by jlambe** [comment]
I've just tested the current implementation of subpage route with the following data and I haven't had issues:

```php
// 3 pages.
+ Grand-Parent Page
+-- Parent Page
+---- Child Page
```

Current implementation of the `subpage` route only allows the use of one parent slug as parameter. For example, getting the `Parent Page`would be like so:

```php
Route::get('subpage', ['grand-parent-page', function ($post) {
    return $post->post_title;
}]);

// Returns the "Parent Page" title (and post).
```

Getting the `Child Page` would also work like so:

```php
Route::get('subpage', ['parent-page', function ($post) {
    return $post->post_title;
}]);

// Returns the "Child Page" title.
```

Could you give more details about your issue against this route ?

**Comment by niknickolas** [comment]
So as I understand, if I use ```page``` route it means 
```php
Route::get('page', ['any-pages', function ($post) {
    return $post->post_title;
}]);
``` 
but if I use  ```subpage```  route  it means any  child pages  but not parent`s pages

```php
Route::get('subpage', ['any-subpages', function ($post) {
    return $post->post_title;
}]);
``` 

for example

```php
// 3 pages.
+ Grand-Parent Page
+-- Parent Page
+---- Child Page

// by means of subpage route we can filter all pages that have parents

Route::get('subpage', ['parent-page', function ($post) {
    return $post->post_title; // Parent Page
}]);

Route::get('subpage', ['chiled-page', function ($post) {
    return $post->post_title; //Child Page
}]);

```
perhaps there is no fault in the behavior of the router, it all depends on how you understand its behavior 

I propose to add a new route 
```php
Route::get('subpageOf', [ 'paren-page' , function ($post) {
    return $post->post_title; // Child Page Of Parent Page
}]);

```
to be more specific

**Comment by jlambe** [comment]
Yes that's correct. Modify the route or perhaps be more explicit in the documentation with the given example.

**Comment by niknickolas** [comment]
It might be better to have two routes ```subpage``` and ```subpage-of ``` or   ```subpage_of ``` or ```subpageOf ```  or  ```subpageof ```  

```subpage``` will filter any pages that have parents

```subpageOf ``` will filter any pages that are children of particular parents

It might be useful.
