### ISSUE TITLE
.env setup

### ISSUE THREAD

**Issue by nathanaelphilip** [themosis/framework#377]
What about using this to set up environments? https://github.com/vlucas/phpdotenv
That would skip the step of having to define the env with a variable.

I don’t mind trying my hand at implementing :)

**Comment by jlambe** [comment]
By just using just the `.env` file you mean?

**Comment by nathanaelphilip** [comment]
@jlambe yes, instead of having to set the environment, you just have one on your local install, one on your staging install, etc – it’s what Laravel does.

**Comment by jlambe** [comment]
Normally you can return an empty string from the `config/environment.php` file to just use a `.env` file but it is still an operation to do.

**Comment by nathanaelphilip** [comment]
so it’s set up, but just not documented?

**Comment by jlambe** [comment]
Yes it works (used once) and yes it is not documented. Perhaps you can test it and let me know how it goes.

**Comment by nathanaelphilip** [comment]
ok! thanks @jlambe  :). excited to start using 1.3.

**Comment by nathanaelphilip** [comment]
Works perfectly! Just set `return false` in the environment.php file and change .env.local to just .env (incase anyone else wants to do this).

**Comment by jlambe** [comment]
👍  Probably going to document it. Or if you want to contribute to the documentation repository?

**Comment by nathanaelphilip** [comment]
i can!
