### ISSUE TITLE
Custom metabox

### ISSUE THREAD

**Issue by KevinBatdorf** [themosis/framework#379]
Is there a guide on making custom metaboxes? I would like to remove the titles and have the screens take the full width:

![screen shot 2017-01-19 at 9 43 30 pm](https://cloud.githubusercontent.com/assets/1478421/22111023/677a5922-de90-11e6-9c62-e1625f222454.png)

I'm using a custom view but not sure how to set it up to remove the space:
```
<!-- Default Themosis metabox view -->
<table class="form-table themosis-metabox">
    <tbody>
        @each('_themosisMetaboxRow', $__fields, 'field')
    </tbody>
</table>
```
Thanks!

**Comment by jlambe** [comment]
To build custom metabox, you have to define your own view for it and simply pass it when calling the `Metabox` class like so:

```php
$view = View::make('metabox.custom');
Metabox::make('Additional Fields', ['post'], [], $view)->set([...]);
```

Your metabox view must provide a container for the custom fields. Note that, currently, fields are using `tr` tags so they must be loaded into a `<table>` in order to display correctly. If you're looking at removing the title for all fields, it's the `_themosisMetaboxRow'  view that you need to replace. For example, pass your custom metabox view, which contains similar code than core except that in the `@each` statement, you pass another custom view that do not take care of the field title (basically is a row with one cell).

**Note**: the `Field::editor()` do not work in an `Infinite` field, you'll get issues when adding "sections".

**Comment by KevinBatdorf** [comment]
Yeah, just noticed that about the editor field. That's okay. 

If I follow your steps above I wind up with another issue. 

```
<!-- Default Themosis metabox view -->
<table class="form-table themosis-metabox">
    <tbody>
      <tr class="themosis-field-container">
        <td class="themosis-field">
            {!! $field->metabox() !!}
        </td>
      </tr>
    </tbody>
</table>
```
![screen shot 2017-01-19 at 10 14 58 pm](https://cloud.githubusercontent.com/assets/1478421/22112241/c8c9bde0-de94-11e6-9003-59633a81053f.png)

**Comment by jlambe** [comment]
Can you post the code?

**Comment by KevinBatdorf** [comment]
Sure, I have:
```
// jobs.php
[...]
$view = View::make('metabox.additional');
Metabox::make('Additional Field', $jobs->get('name'), ['priority' => 'low'], $view)->set([
  Field::text('af-title', ['title' => 'Title:']),
  Field::editor('af-content',
    ['title' => 'Content:'],
    ['textarea_rows' => 5, 'teeny' => true]
  )
]);
```
and
```
<!-- metabox/additional.scout.php-->
<table class="form-table themosis-metabox">
    <tbody>
        @each('metabox.noTitle', $__fields, 'field')
    </tbody>
</table>
```
and
```
<!-- metabox/noTitle.scout.php -->
<table class="form-table themosis-metabox">
    <tbody>
      <tr class="themosis-field-container">
        <td class="themosis-field">
            {!! $field->metabox() !!}
        </td>
      </tr>
    </tbody>
</table>

```

**Comment by jlambe** [comment]
Is it using the latest version of the framework 1.3.0? When looking at source code on your browser, is  the table html rendered properly?

**Comment by KevinBatdorf** [comment]
I'm probably on 1.2 actually. It's not a new project.

The rendered code isn't right actually. It's showing up outside the container.
![screen shot 2017-01-19 at 10 58 57 pm](https://cloud.githubusercontent.com/assets/1478421/22114139/ff053a46-de9a-11e6-8da5-a5c1ae53d790.png)

**Comment by jlambe** [comment]
Then it's probably the syntax `{!! !!}` the issue. You have to write it like so`{{ $field->metabox }}`, the other syntax is from the Blade engine and is used to print unescaped value. It's only available in release 1.3.0.

**Comment by KevinBatdorf** [comment]
Ah yeah! That's why. It work's as expected now. Thanks

**Comment by jlambe** [comment]
For information, the Themosis framework next release (1.4.0) will be focused on metabox, custom fields, ... if you have any features requests, you can post an issue.
