### ISSUE TITLE
Error due to Laravel 5.4 changes - Call to undefined method Themosis\Route\Route::getUri()

### ISSUE THREAD

**Issue by lerouxsteyn** [themosis/framework#381]
Hi  @jlambe 

Firstly I want to thank you for giving us such a great framework, and maintaining it like a boss. We've used Themosis (almost exclusively) for the last year and a half on about 30 projects and counting. There are some really awesome improvements in 1.3, looking forward to the Advanced documentation that is on the way as well :) Ok, let's get to it...

**Issue:**
The following error started showing up today on **Themosis 1.3** + **Laravel 5.4** on **PHP7** (running in Vagrant + Homestead):
`Call to undefined method Themosis\Route\Route::getUri()`

First I thought it was our custom theme, but after doing a `composer self-update` and then using the installation instructions on the Themosis website to do a fresh installation, I'm getting the same error.

**Temporary fix:**
If I delete the vendor folder, and change `"illuminate/database": "**^5.3**"` to `"illuminate/database": "**5.3**"` (just removing the caret), and run composer again, then it works fine. It seems they have removed the **getUri()** method in **Laravel 5.4**.

Hopefully Laravel 5.4 won't give you too many issues. Let me know if I can assist in any way or if you require any further information / testing on this.

**Comment by RachidLaasri** [comment]
Same issue here.

**Comment by ChenAlon** [comment]
I created a PR (#382) for this issue.
Just change the getUri() to uri() in the Themosis\Route\RouteCollection.php and will work.
It is a change in Laravel 5.4 version.

**Comment by jlambe** [comment]
Great @ChenAlon, I'll mark this PR for 1.3.1. I thought using the `^5.3` would stick to 5.3 and their minor version, I should revise my Composer.

**Comment by jlambe** [comment]
@lerouxsteyn Release 1.3.1 is out with compatibility fix with the Illuminate packages 5.4. Official announcement will be done during the week.

Also, thanks for supporting the Themosis framework. Do you think it will be possible to have a list of public projects you've built with the framework?

**Comment by lerouxsteyn** [comment]
Thanks for fixing this so quickly!

Here are some of the public projects that we have built on Themosis:
http://artificial.studio/
http://nederburg.com/
https://amarula.com/trust/
https://www.clickatell.com/
http://duneprop.com/
http://radar.co.za/
http://bokomo.co.za/

I also made our boilerplate theme public the other day. Maybe there are some other developers that are looking to assist on developing a base theme like this that provides a few functions straight out of the box in order to save time on common tasks in every project, without adding too much bloat.
https://github.com/artificialstudio/ai-themosis-theme
There are some things there that still needs cleaning up, as I only made this public last week.

There is another personal project that has been a huge time saver for me, that I'm also looking to get onto Github. Currently we're using Vagrant with Homestead as our local dev environment for Themosis sites. I wrote some bash scripts that does the installation, and with a few other options like exporting databases, syncing local with staging, importing projects, etc. The problem right now is that it's very opinionated to our workflow (Homestead locally and Forge/DigitalOcean for production). Would be interested to hear if anybody else would be interested in something like this, and whether it's worth my time to clean things up and make it public.

**Comment by jlambe** [comment]
Thanks for the references.

Sure you can share your ideas, I'm sure people will be interested into this starting by me ;)

**Comment by marcwieland95** [comment]
Thanks for open sourcing your boilerplate. It's always nice to have to reference.
According to the deployment, I would be interested in. I always struggling with this. Especially because Themosis doesn't support something like this out of the box.

**Comment by lerouxsteyn** [comment]
Thanks guys, I'll spend some time this week cleaning up the bash scripts and will put the project on Github. I'll drop a msg on here when I've done that.

@jlambe - I have two questions related to this:

1. I saw your project called box. Really cool that you are doing this for Themosis. I assume that this is still in development? Would you recommend Homestead as the best solution until box is ready or is there anything else I should have a look at?
2. What is the best practice way of installing a theme for a new Themosis installation? I prefer that the theme is packaged separately, and want the bash script to prompt you for a theme that you would like installed. That way you can paste the link to a repo containing the theme. After installation, the theme's .git folder is removed locally so that it is then packaged along with the rest of the framework. Thoughts?

**Comment by jlambe** [comment]
@lerouxsteyn 
1. Yes there is project to use Ansible in order to build local development box with configuration adapted to the framework. I can recommend Homestead or any Vagrant solutions to develop with the framework, Mamp, Xamp, ... until the box is complete and fully tested. If you want to dig into the themosis/box project you can as well.
2. I don't have particular advice regarding the theme. If you want to re-use the boilerplate theme of your own when starting a new Themosis project, you can fork the themosis/themosis repository, link it to packagist.org and set as a dependency your custom theme (also published to packagist.org). Then you can create new project using the `composer create-project` command and simply refer to your own repository like `astudio/themosis` for example.

**Comment by lerouxsteyn** [comment]
Perfect, thanks!
