### ISSUE TITLE
$wp_filesystem return Call to a member function put_contents() on null

### ISSUE THREAD

**Issue by bumbella** [themosis/framework#389]
Why don't work this code for me? Please help me.

in resources/admin/theme.php my code:

Action::add('publish_post',function() {
   global $wp_filesystem;    
    $wp_filesystem->put_contents(
        $file,
        'Example contents of a file',
        FS_CHMOD_FILE
    );
});

**Comment by jlambe** [comment]
Hi, not sure but sounds like the `$wp_filesystem` global var is not yet defined at a `publish_post` action.
The error message clearly tells that the var is `null`, which is not the expected object with a method `put_contents`.
