### ISSUE TITLE
User::make() Vulnerability

### ISSUE THREAD

**Issue by rumur** [themosis/framework#394]
`/**
     * Create a new WordPress user.
     *
     * @param string $username
     * @param string $password
     * @param string $email
     *
     * @return \Themosis\User\User | \WP_Error
     */
    public function make($username, $password, $email)
    {
        $this->parseCredentials(compact('username', 'password', 'email'));

        // Clean credentials.
        $username = sanitize_user($username, true);
        $password = sanitize_user($password);
        $email = sanitize_email($email);

        // Create a WordPress in the database.
        $user_id = wp_create_user($username, $password, $email);

        // If user created.
        if (is_int($user_id)) {
            return $this->createUser($user_id);
        } elseif (is_array($user_id->errors) && array_key_exists('existing_user_login', $user_id->errors)) {
            $user = get_user_by('login', $username);
            $registeredEmail = $user->data->user_email;

            // Compare the given email address before returning a user instance.
            if ($email === $registeredEmail) {
                return $this->createUser($user->ID);
            }
        }

        // WP_Error.
        return $user_id;
    }`

Hi @jlambe !

Today I've faced some interesting thing.
I work around the user registration and wanted to use **UserFactory::make**.

Everything works great, however I noticed that the UserFactory::make check existing user with email. 

I guess in this case we should compare the existing user by password not by email.

Because in case if someone just guess user's **_email_** and **_user_login_** we can overwrite existing user with wrong data.

Does it make sense?

**Comment by jlambe** [comment]
@rumur Yes it does, indeed we should inspect the given password with the one stored or if a user already exists with this email, we should not allow an update.

**Comment by rumur** [comment]
hi @jlambe 

I'm wondering if the `Themosis\User\UserServiceProvider::class` still be in your roadmap for 2.0? 

I've noticed that this provider is no longer in use for the 2.0, are you going to take it out of the framework?

**Comment by jlambe** [comment]
@rumur Yes a refactoring is planned but as you noticed, it has been deactivated. Also, I'm working on implementing the `illuminate/auth` package so we can benefit from an authentication system out of the WordPress User API.

**Comment by jlambe** [comment]
I'm currently looking at this and probably I'll remove the ability to return a user instance from the `make` method. The `make` method should only be a wrapper to create a new user. In the case of using current user, developers can use the `User::current()` method to fetch an instance of it.

Both `make` and `current` methods return the same instance type.

**Comment by jlambe** [comment]
New user API is merged on `master` branch. Documentation will be updated soon.
