### ISSUE TITLE
Ajax::listen not working for me

### ISSUE THREAD

**Issue by bumbella** [themosis/framework#398]
Please help me. I can't make ajax form with Themosis framework. admin-ajax php 200 OK
What is the problem? I make anything wrong?
Thanx for you.

resources/admin/ajax.php
Ajax::run('send_contact_mail', 'both', function(){
echo 'assad';
die();
});

javascript file:
$.ajax({
url: themosis.ajaxurl,
type: 'POST',
dataType: 'json',
data: {
action: 'send_contact_mail',
}
})
.done(function(data) {
console.log(data);
});

**Comment by jlambe** [comment]
Answered on the other post. Please do not duplicate issues all over the place. Stick to the `themosis/framework` repository.

Here is the Ajax doc in order to complete my answer on the other post:
- http://framework.themosis.com/docs/1.3/ajax/
