### ISSUE TITLE
WPML error

### ISSUE THREAD

**Issue by Benjaminsson** [themosis/framework#399]
When trying to activate WPML on a Themosis 1.3.1 site i get this error:
```
Whoops \ Exception \ ErrorException (E_COMPILE_ERROR)
main(): Failed opening required '/path/to/site.com/htdocs/content/plugins/sitepress-multilingual-cms/vendor/autoload.php' (include_path='.:/usr/share/php')
```
The line throwing the error looks like this:
`require_once $autoloader;`

It seems to collide with Themosis? Is this something that should be fixed on the Themosis end or the WPML end?

**Comment by jlambe** [comment]
WPML end unfortunately. May I suggest you the Polylang Plugin instead than WPML.
Now you can silent error reporting on your project to see how WPML performs its installation. Check if inside their plugin, there is a "vendor" directory with the `autoload.php` file.

**Comment by Benjaminsson** [comment]
Yes, this is the content of `autoload.php`
```php
<?php

// autoload.php @generated by Composer

require_once __DIR__ . '/composer' . '/autoload_real.php';

return ComposerAutoloaderInitb1106e192ecb659388bf2ada486be3cc::getLoader();
```
I've never used Polylang. I'll have to investigate if that cover my needs :)

**Comment by Benjaminsson** [comment]
I'm going to try work things out with WPML. Polylang needs the pro version for slug translation and i already have a WPML subscribtion.
