### ISSUE TITLE
Hooking filters themosis_service_providers

### ISSUE THREAD

**Issue by phoeniix07** [themosis/framework#403]
Hi,

Trying to Modify loaded service providers I try to hook "themosis_service_providers" filter, the issue, is that this hook is just very difficult to catch.

For that, I had to declare a Mu-pluggins, loaded before the themosis plugin. A very complex way to extend Themosis.

**Comment by jlambe** [comment]
Yes this hook is indeed loaded too early.
I've not looked at unregistering services providers. The plugin is only loading core ones.

You can register service providers inside your theme and custom plugin.
