### ISSUE TITLE
Checkable fields do not handle properly numeric values

### ISSUE THREAD

**Issue by jlambe** [themosis/framework#406]
If a list of numeric values with labels is defined, the checkbox or radio input use the label text as value instead of taking the passed key.

**Comment by tomasvanrijsse** [comment]
I just stumbled on this same error and found out it is caused in the `FromBuilder` in the `function makeGroupCheckableField`

on line 330 the numeric key is dismissed in favor of the label.

            $c = is_numeric($choiceVal) ? $choice : $choiceVal;

I have no clue why this is implemented like this.

**Comment by jlambe** [comment]
To be honest I can't remember also why I've implemented it like this but it definitely needs a fix :)
