### ISSUE TITLE
Foundation Application and Router

### ISSUE THREAD

**Issue by Givx** [themosis/framework#408]
Bonjour, 

je vais écrire en français si vous me permettez. Je trouve dommage que Foundation Application soit aussi éloigné de l'implémentation de laravel et que se ne soit uniquement un extend de IOC. 
On perd toute la partie middleware, qui est vraiment très utiles. 

De plus je trouve également dommage que la partie router soit allégé. On perd la possibilité d'utiliser des name dans nos routes et ensuite sur la partie front d'utiliser urlGenerator. 

Je vois que le roadmap de la version 1.4 se focalise uniquement sur la partie API field c'est bien dommage de ne pas en profiter pour améliorer le coeur. D'être plus proche des packages laravel pour faciliter la maintenance. 

Ce sont des remarques constructives l'idée n'est pas de dénigrer le travail déjà fait qui est très utile. 
Mais plutôt de faire évoluer ce projet afin qu'il soit encore meilleur. 

Pouvons nous imaginer collaborer pour améliorer le projet. 

Cordialement,

**Comment by jlambe** [comment]
Bonjour,

tout d'abord désolé pour la réponse tardive.

Oui il est tout à fait possible de collaborer. Le principe majeur du framework est de rester "open-source" afin de favoriser les contributions et suggestions sur le code source.

Je vous invite à faire un fork de la branche `master` de ce dépôt et de renvoyer les PR avec les modifications.

Par contre, avant de plonger dans le code pour l'une ou l'autre fonctionnalité, il faut garder à l'esprit que je me réserve le droit d'accepter ou non une PR. Pour éviter tout travail inutile et surtout toute frustration, je vous conseille d'ouvrir une issue, d'y **détailler** votre recherche et que nous discutions sur la ou les fonctionnalités à implémenter avant d'aller plus loin.

Bien à vous,
Julien
