### ISSUE TITLE
Custom Route and global post 

### ISSUE THREAD

**Issue by Givx** [themosis/framework#410]
Hello, 
When i use a custom route, the global post it's wrong ? it's normal or not ?

Thanks

**Comment by ramon-villain** [comment]
Wrong like what? Did you check the routing order, it really matters (http://framework.themosis.com/docs/1.3/routing/#routing-examples)?

**Comment by jlambe** [comment]
@Givx When defining a custom route, you need to understand that it is no longer handled by WordPress, so yes normally the default `$post` variable that you might expect you should not be a `WP_Post` instance so you can't leverage it.

A custom route will by default not tell WordPress to pre-populated data like the post or query as it does not recognize the rewrite rule. When working with custom routes, you have to work like in any framework and fetch your data (model) yourself.

Or you create a WordPress custom permalink structure using its rewrite API.
