### ISSUE TITLE
Metabox 

### ISSUE THREAD

**Issue by Givx** [themosis/framework#411]
how use with custom view without Field ?? 
For populate or mapping data ? 

Thanks

**Comment by Givx** [comment]
Some time you are a bug in this file Themosis/Metabox/MetaboxBuilder.php line 433

retrun $fieds;

remplace by : 

return is_null($fields) ? [] : $fields;

because some time $fields it's null

**Comment by jlambe** [comment]
Fixed on next release. You'll be able to define your own callback for a metabox and so control what you want to output inside a metabox. Soon to be merged on the `develop` branch.
