### ISSUE TITLE
Metabox field and section

### ISSUE THREAD

**Issue by Givx** [themosis/framework#414]
Hello, 

How use metabox with field section for save the multiple data of my metabox one meta key serialised ?

**Comment by jlambe** [comment]
Hi,
well it's bad practice in general to store your meta values into a one serialized as you won't be able to perform query against your data.

The framework does not provide such function and won't. Regarding creating visual sections, you'll have to pass a custom view to your metabox.

Currently you can define custom fields per `group` in a metabox by setting a key and attach an array of fields to it. For example:

```php
Metabox::make('Details', 'page')->set([
    'groupA' => [
        Field::text('author_name')
    ],
    'groupB' => [
        Field::select()
    ]
]);
```

Then from your custom view, you can get each group of fields like so using a Twig custom view:

```twig
<div class="section">
    <!-- Loop through the groupA fields -->
    {% for field in __fields.groupA %}
        {{ field.metabox()|raw }}
    {% endfor %}
</div>
<div class="section">
    <!-- Loop through the groupB fields -->
    {% for field in __fields.groupB %}
        {{ field.metabox()|raw }}
    {% endfor %}
</div>
```

**Comment by Givx** [comment]
Hi, 
Why it's the bad pratice to store one meta for multiple data ? Sometime it's better, you are only one query and not many query when i need the data on the same page.

**Comment by jlambe** [comment]
If you're doing a meta query, you won't be able to do so, things like sorting based on a meta value for example as everything is serialized (understand as not readable by SQL).

**Comment by Givx** [comment]
I know this, but when you use Page with themosis and you use section for your field. Your data it's serialized. It's depend of the context, some time you need one meta for one value, and some time you need one meta for multiple data.

**Comment by Givx** [comment]
Some time you use metabox only for configuration of your post, and i don't need to query on SQL.
