### ISSUE TITLE
Laravel Valet support for htdocs Folder

### ISSUE THREAD

**Issue by mapodev** [themosis/framework#416]
Hey there,

themosis is a great idea! I am a Laravel user, therefore I am used to develop with Valet. I would suggest to change the name of `htdocs` to `public`. Or do you have any idea to use themosis with valet?

**Comment by jlambe** [comment]
I think there is already a driver PR for Valet and Themosis.

**Comment by mapodev** [comment]
Ok, I will check it. But anyway, Themosis is great buddy, keep it alive!

**Comment by ramon-villain** [comment]
@mapodev Valet is always changing, so I don't know if you're using the oldest, the older, the newer or the newest version, hahaha. So I did 2 gists some time ago to run TH with Valet. Let me know if something is broken.

https://gist.github.com/ramon-villain/fa6a3098944d06f2d714e7457eb12ed3
https://gist.github.com/ramon-villain/3c7415e03dec407cc13b3c77ebe93cf2

**Comment by jlambe** [comment]
@mapodev Personally I won't work on a Laravel Valet implementation as it is only for Mac users. We're looking for Docker implementation instead.

**Comment by LukeAbell** [comment]
Has anyone gotten this to work with Valet? The two drivers linked above aren't working for me. Not redirecting to /cms/ in the multisite network admin panel.

**Comment by KevinBatdorf** [comment]
I have Valet set to work with mywebsite.test and the following driver in `~/.valet/Drivers`

https://gist.github.com/KevinBatdorf/67942f88ff4b5238b8dde4222472a2f4

On a new project, I usually just have to add a database, then start mysql `mysql.server start`

@jlambe I use [Laravel Homestead](https://laravel.com/docs/5.6/homestead) to develop with Themosis on both PC and Mac. It uses Vagrant, it's easy to use, and probably most importantly the documentation is always fresh.

**Comment by jlambe** [comment]
@KevinBatdorf I personnaly use Homestead as well or some Docker configuration.
