### ISSUE TITLE
Implement backend routing system for admin pages

### ISSUE THREAD

**Issue by jlambe** [themosis/framework#417]
Add a simple routing solution for backend admin pages created by Themosis Framework plugins in order to point admin pages to Controller methods (something like Herbert Plugin Builder)

@jlambe, as per your request, here is how I imagine the creation of backend pages:

Page::add([
    'type'   => 'parent-page', // Could be replace with parent => null
    'as'     => 'MyPluginMainPage', // Would be used to retrieve the Page URL with a helper
    'title'  => 'My Plugin Name',
    'slug'   => 'my-plugin',
    'icon'   => 'dashicons-format-aside',
    'order'  => '20',
    'uses'   => 'MyPluginController@defaultMethod', // Default method if no actions provided
    
    // Route mapping
    // In a way the URL would end with ?page=my-plugin-slug&action=actionName 
    'actions'    => [
        'index'    => 'MyPluginController@SomeMethod', // URL => ?page=my-plugin&action=index
        'add'   => 'MyPluginController@AnotherMethod',
        'edit'   => function(Request $request) { 
            // Some logic...
            //....
            // Return view or redirection 
            return view("some.view");
        },
    ]

]);
Page::add([
    'type'   => 'child-page', // Could be replaced with parent => parent-page-slug
    'parent' => 'MyPluginMainPage',
    'as'     => 'MyPluginSubPage',
    // Same for the parent-page type from above...
]);
I know it is kind of Herbert Panels declaration, but I think it is easy to use and time saving solution since we can't use Laravel like routes on backend. Please correct me if you think this doesn't make sense :)

**Comment by romainhe** [comment]
Any news from that ? It's a really great feature...

**Comment by jlambe** [comment]
@romainhe I can confirm you it is coming on the next release. No date yet defined.

**Comment by romainhe** [comment]
Cool ! Thx for your reply @jlambe

**Comment by jlambe** [comment]
Feature now merged on the `develop` branch.
