### ISSUE TITLE
admin bar missing when using multiple servers

### ISSUE THREAD

**Issue by swaraasolutions** [themosis/framework#419]
We have finally managed to get the themosis framework on a very large site.

There are couple of issues which i am not sure if they are server related to any configuration error

1. When the user is logged in the admin bar is missing on the frontend
2. Visual Editor is not working on the Posts page.

If someone can guide me through the correct steps. The WordPress cookies are set correctly but still the frontend can't see if the users are logged in and that's the reason no admin bar on the frontend any ideas how we can fix this

Help is much appreciated

Thanks
Varun V.

**Comment by jlambe** [comment]
@swaraasolutions We have never yet met this issue regarding the admin bar. I know there is a general parameter to display the admin bar from the users settings, perhaps it's off. If a user is logged in, you can also check if there is a body class of such from WordPress.

Regarding Visual Editor I don't know as I've never used this plugin. Perhaps check if there is a console error.

In theory, the framework do not alter settings of a WordPress instance so plugins are compatible, and specially in the WordPress administration.

I would suggest you to test the plugin on a local clean instance with the framework and Visual Editor only activated to see where the error might be. It can be a conflict with another plugin script as well.

Cheers,

**Comment by swaraasolutions** [comment]
Hi Julien,

Thanks for such a fast response.

I managed to fix the admin bar issue by disabling wp super cache.

But the issue still persist for the WYSWIG editor on Add Post page.

Somehow the tinymce is not loaded correctly also there is no console errors

Attached screenshot for your reference
![error](https://cloud.githubusercontent.com/assets/12116208/25840073/e382d026-34b7-11e7-8699-84b030194086.png)

if you see the visual tab is missing on the post page.

Your help is much appreciated.

**Comment by ramon-villain** [comment]
Have you checked your viewing preferences (near your name, up there)?
There are some plugins that disable the default editor in favor of its own.

**Comment by jlambe** [comment]
@swaraasolutions How does it behave on a clean Themosis/WordPress instance with only the Visual Editor plugin activated? Does it show the TinyMCE editor ?
