### ISSUE TITLE
No input type hidden in Field type ?

### ISSUE THREAD

**Issue by Amorfx** [themosis/framework#424]
Hello,

I want to create a specific field in my post edition with an input hidden and a search input. So i want to create my metabox with one field saved which is hidden and in my view i put the search field.

Is it possible to create an input hidden ?

Thanks.

**Comment by ramon-villain** [comment]
Did you try the Form::hidden ?

http://framework.themosis.com/docs/1.3/form/#text-password-email-number-date-hidden-inputs

**Comment by Amorfx** [comment]
I don't use Form object for Metabox object. Possible to use this object in Metabox ?

**Comment by ramon-villain** [comment]
Oh, you're right. There's no Field::hidden to be used, and the Form would not work. I'll try to make a PR later.

**Comment by jlambe** [comment]
@Amorfx Indeed, there is no way actually to pass a field with an input type of hidden. But one way to do it would be to pass a custom view to your metabox and from within your view, you can copy paste this snippet:

```php
<!-- Your custom hidden input -->
{!! Form::hidden('input-name', 'value') !!}

<!-- Add this snippet below to render core fields -->
<table class="form-table themosis-metabox">
    <tbody>
        @each('_themosisMetaboxRow', $__fields, 'field')
    </tbody>
</table>
```

@ramon-villain I would say that no UI should comes in the output except the input itself. So we need to be careful regarding the `<tr>` output .

**Comment by Amorfx** [comment]
Thanks for the reply !

**Comment by jlambe** [comment]
Feature available and is going to be merged on the `develop` branch very soon.
