### ISSUE TITLE
Repeater field / Relationship field

### ISSUE THREAD

**Issue by strarsis** [themosis/framework#425]
Would it be possible to use Themosis for adding a repeater field that contains items, 
each item with a relationship field (for assigning a post/post id from a list, by type (with autocompletion))?
I cannot find a relationship / posts selection field in Themosis framework documentation.

**Comment by jlambe** [comment]
yes, just get a list of your posts and pass them as options to a select field within the infinite one.
note that you can't just pass an array of `WP_Post` to a select field, you need to parse it and only return an array where keys are the posts `ID` and values are the post `post_title` property.

Check the [form](http://framework.themosis.com/docs/1.3/form/#select-field) and [field](http://framework.themosis.com/docs/1.3/field/#select-field) documentation for details on the select input/field.
