### ISSUE TITLE
Having problem installing themosis in MAMP PRO

### ISSUE THREAD

**Issue by rovillesarate** [themosis/framework#426]
Hi! I am stuck at the installation part of themosis in mamp pro. How do i define the db_port?
DB_USER = "root"
DB_PASSWORD = "password"
DB_HOST = "localhost"

already tried localhost:8889 but it is still not working.

I am getting an ERR_CONNECTION_REFUSED

**Comment by jlambe** [comment]
Hi,
look at the WordPress documentation on how to define a database host, you'll find your answer: https://codex.wordpress.org/Editing_wp-config.php#Set_Database_Host
