### ISSUE TITLE
Create an HTML based field type

### ISSUE THREAD

**Issue by rovillesarate** [themosis/framework#428]
Hi! Is there a way to make an html based field type so i can customize how a settings page would look like.

Lets say i would to it this way

html_field
field 1
field 2
html_field
field 3
field 4
field 5
field 6
html_field

**Comment by rovillesarate** [comment]
This would be helpful to create custom grids to the settings page.

**Comment by jlambe** [comment]
At the moment, this is do-able if you pass a custom view to handle your page settings. Check the core settings page view that is bundled with the framework in order to build your own.

You could create your own sections html with their inner fields then.

**Comment by rovillesarate** [comment]
Hi! Julien. I am aware of the custom view for the page view but what i am trying to accomplish is to add html code before and after a specific field. Altering the page settings view will only affect the wrapper being used by the page settings.

#page setting view
field 1
field 2
what if i want to put an html code here before another field
field 3
field 4
then end an html code after a specific field
field 5
field 6

#end of page setting view

It would be great if there is a way to create our own specific type of field maybe through a plugin and be able to extend the field factory

**Comment by ramon-villain** [comment]
@rovillesarate This is not full covered at the documentation for now, but you can build your own field on the fly, Julien also replied a issue with a "similar" subject at the themosis/themosis repo. (Btw there's a lot of examples about this, that you can find here and there at the issues section)

The answer reference: https://github.com/themosis/themosis/issues/163#issuecomment-305256149

**Comment by rovillesarate** [comment]
But what about the field type. Technically an html field would not return an input type instead will just echo the html element assigned to it.

**Comment by jlambe** [comment]
@rovillesarate Note that if your field contains `<input>`, those are rendered into the global `<form>` element defined by WordPress. So during save, the API would want to store it somewhere.

If you want to insert HTML between one or specific elements, you can use your custom page view and add `if ()` conditions and check for the field name. Based on that you can output any html you want.

Also, looks like you might want to define sections where you want to add custom html. You could also take advantage of the section class and define custom html into it before rendering its inner fields.

See [http://framework.themosis.com/docs/1.3/page/#define-sections](http://framework.themosis.com/docs/1.3/page/#define-sections)
