### ISSUE TITLE
Having a problem with browser-sync?

### ISSUE THREAD

**Issue by rovillesarate** [themosis/framework#430]
Hi! I am having a js problem of browser-sync.

Is it being called by the package.json

I never called a browser-sync js but it causing me some issues being auto loaded by themosis?

**Comment by jlambe** [comment]
Hi,

I've recently completed the theme documentation with details on the given command line tools though Browser Sync. Please check the guide to help fix your issue:
- [Theme Guide](http://framework.themosis.com/docs/1.3/theme/#browsersync)
