### ISSUE TITLE
Having issues with an infinite field inside an infinite field

### ISSUE THREAD

**Issue by rovillesarate** [themosis/framework#435]
Hi! Guys!. I am having a problem with using an infinite field inside another infinite field.
There is no error popping up but the infinite field inside is only storing 1 data. the other data are being discarded. I don't know what causing this to happen.

Here is the settings page i did.
```
$settings['home-option'] = [
	Field::text('header_headline', [
		'title' => 'Header Headline'
	]),
	Field::media('header_background', [
		'title' => 'Header Background'
	]),
	Field::textarea('intro_message', [
		'title' => 'Intro Message'
	]),
    Field::infinite('sections', [
	    Field::text('parent_category_name', [
	    	'title' => 'Parent Category Name'
	    ]),
            // This is where i am having the problem only 1 is being saved. other rows being discarded
	    Field::text('parent_category_link', [
		    'title'   => 'Link',
		    'default' => home_url() . '/page-name'
		]),
		Field::infinite('sub_cat', [
			Field::text('name'),
			Field::media('image'),
			Field::text('link',[
		    'title'   => 'Link',
		    'default' => home_url() . '/product-category'
			]),
		], [
			'title' => 'Sub Category Name',
			'limit' => 3
		]),
	]),	
];
```

**Comment by rovillesarate** [comment]
after more checking.. i check the chrome inspector and found out that the infinite field is having the wrong number on its array.

When you create another row.
instead of doing it this way
`<input type="text" name="home-option[sections][1][sub_cat][2][name]" value="" class="large-text" data-field="text" id="home-option[sections][1][sub_cat]-2-name-id">`
its outputting it this way
`<input type="text" name="home-option[sections][2][sub_cat][1][name]" value="" class="large-text" data-field="text" id="home-option[sections][1][sub_cat]-2-name-id">`

**Comment by jlambe** [comment]
It's a known issue and it has no fix at the moment. It's a naming issue.

http://framework.themosis.com/docs/1.3/field/#infinite-field

**Comment by rovillesarate** [comment]
What i don't get is the id's used on the input has the right numbering.
`home-option[sections][1][sub_cat]-2-name-id`

The only thing that is being messed up right now is the name value
checking the js right now but its somewhat hard to understand because it already had been minified already.

**Comment by jlambe** [comment]
@rovillesarate You have to check the core code from the master branch in order. I've started looking at it as it's mainly jQuery dom parsing issue first => making sure to grab DOM elements of currently edited Infinite field and then find a way to rename the name attributes of all sub-fields.

You can take a look around and propose a PR against the `1.3` branch.

**Comment by rovillesarate** [comment]
I am having a hard time understanding the themosis js file. but i think its happening somewhere here
```

                key: "rename",
                value: function() {
                    var e = this,
                        t = this.$el.children("tr.themosis-infinite-row");
                    f["default"].each(t, function(t, i) {
                        i = String(i + 1), t = (0, u["default"])(t);
                        var n = t.find("td.themosis-infinite-inner>table>tbody").first().children(),
                            o = t.children("td.themosis-infinite-order").children("span");
                        f["default"].each(n, function(t) {
                            t = (0, u["default"])(t);
                            var n = t.find("input, textarea, select"),
                                o = t.find("th.themosis-label>label"),
                                r = t.find(".themosis-collection-wrapper");
                            if (r.length) {
                                r.attr("data-order", i), e.renameCollectionField(r, i);
                                var s = r.find("ul.themosis-collection-list input");
                                s.length && f["default"].each(s, function(t) {
                                    var n = (0, u["default"])(t),
                                        o = e.renameName(n.attr("name"), i);
                                    n.attr("name", o)
                                }, e)
                            } else 1 < n.length ? f["default"].each(n, function(t) {
                                t = (0, u["default"])(t), e.renameField(t, o, i)
                            }, e) : e.renameField(n, o, i)
                        }, e), o.html(i)
                    }, this)
                }
            }, {
                key: "renameField",
                value: function(e, t, i) {
                    if ("button" != e.attr("type") || !e.hasClass("wp-picker-clear")) {
                        var n = e.attr("id"),
                            o = e.attr("name"),
                            r = this.renameId(n, i),
                            s = this.renameName(o, i);
                        t.attr("for", r), e.attr("id", r), e.attr("name", s)
                    }
                }
            }, {
                key: "renameId",
                value: function(e, t) {
                    var i = new RegExp("-([0-9]+)-");
                    return e.replace(i, "-" + t + "-")
                }
            }, {
                key: "renameName",
                value: function(e, t) {
                    var i = new RegExp("([0-9]+)]");
                    return e.replace(i, t + "]")
                }
```

**Comment by jlambe** [comment]
@rovillesarate Again, you should not try to read a minified file. Just work with the core files of the field located here. You can then re-compile the files to a minified version.

**Comment by rovillesarate** [comment]
Not really good with regex but if we can target the last number inside [].
i think that would do the trick.

**Comment by rovillesarate** [comment]
Finally Got it working! Wew...

```
    /**
     * Returns a new name attribute value.
     *
     * @param {String} currentName
     * @param {String} index
     * @return {String}
     */
    renameName(currentName, index)
    {
        // let regex = new RegExp("([0-9]+)\]");

        let regex = new RegExp("\\d\\]\\[\\w{1,100}\\]$");
        let match = new RegExp("\\]\\[\\w{1,100}\\]$");
        let mateched = currentName.match(match);

        //return currentName.replace(regex, index + ']');

        return currentName.replace(regex, index + matched);
    }
```

**Comment by jlambe** [comment]
Sounds like there is a typo in your code var names `mateched` vs `matched`.

If everything then is finally working, you can send a PR so we can test your code as well.

**Comment by rovillesarate** [comment]
I have already made it work but i think there is still something missing from the code.
If i try to add 1 section at a time and add fields inside it before creating another section.
The code seems to mess up the numbering.

What i did to make it work is first to create all the sections i needed without filling it anything yet, then saving it first before i fill up the fields and add rows on the infinite fields inside the sections.

![infinite-fields](https://user-images.githubusercontent.com/2109352/27464299-32ab6c5c-57ff-11e7-86fd-d1c0a5ea14b6.png)

**Comment by rovillesarate** [comment]
If i try to add another row after i have saved the first one.
The input name and id are missing the last names and ids
![infinite-add-row](https://user-images.githubusercontent.com/2109352/27464825-156bcc56-5802-11e7-9211-880ecdf52958.png)
If you have already saved a previous section and try to add.
the code somehow ends up having problems because of the label id.
![developer tools - http dev momentsdreamed com cms wp-admin admin php page momentsdreamed tab home-option](https://user-images.githubusercontent.com/2109352/27464842-36b99d52-5802-11e7-994f-20a44d7eded6.png)
a work around for this is to first create all the parent sections of the infinite field then save
then before you can create the child infinite field sections to have the correct numbering.

**Comment by jlambe** [comment]
@rovillesarate well you do have something. The issue remains regarding the names. You can look at the code during a clone and start from there. Do not hesitate to refactor stuff if needed. I do encourage you to dig deeper if you have time.
