### ISSUE TITLE
Routing a post request with is_template conditional tag yielding "MethodNotAllowedHttpException" error

### ISSUE THREAD

**Issue by ccambournac** [themosis/framework#436]
Hi all!

I am facing an issue I do not understand. 
Basically with a page containing a form which is post-submitted on the same page. 

While the following route works well:
```
Route::post('/contact', 'Page@contact_post');
```
the following throws a `MethodNotAllowedHttpException` exception...
```
Route::post('template', ['contact', 'uses' => 'Page@contact_post']);
```

The page makes use of a page template for which the GET route works well, i.e.:
```
Route::get('template', ['contact', 'uses' => 'Page@contact']);
```

Any idea why? Thank you :)

**Comment by noxify** [comment]
Does it work with

```
Route::any(....
```

Maybe this solves your problem.

I hope i unterstood your problem correctly.

You have two routes defined one for `POST` and one for `GET`.
Both have the same uri `contact`.

I know it from laravel routing. But in Laravel it works fine :)

**Comment by ccambournac** [comment]
PRobably I should post the issue here: https://github.com/themosis/themosis/issues
