### ISSUE TITLE
bbPress, WooCommerce or any other custom plugin that requires custom template

### ISSUE THREAD

**Issue by SamirAlexandru** [themosis/framework#437]
Hey and thank you for your help! 

We are developing a new custom theme using Themosis, and all we can say is that we are totally loving it,  but we got only 1 bottleneck: how can we don't overwrite the template engine for multiple plugins like bbPress or WooCommerce? 
To do each file again ( the template part ) will be pretty insane, another thing we could do is to execute shortcodes like [bbp-single-forum id=$forum_id] , where the route should be /forums/forum/$forum_id , but again, we should have like 50 routes for each request.

Any solution regarding this?

Thank you very much and keep up to good work!

**Comment by SamirAlexandru** [comment]
P.S: Let's take a look at the ending view as well, things like that won't work
```
@loop
    {!! Loop::content() !!}
@endloop
```

**Comment by noxify** [comment]
What do. you mean with "does not work"?

**Comment by SamirAlexandru** [comment]
That code will just return the page content, which in the bbPress single forum, is totally wrong ( they have their own callback for that ) .

**Comment by SamirAlexandru** [comment]
Currently, a single forum link will just load the simple page loop, and I am getting just the forum title + empty content ( nothing from bbPress behavior ).

**Comment by noxify** [comment]
I had not this kind of problems nur a similar one with the loop.

I solved it with extending the loop class to have a new method to get a custom field directly (without using `@query` or `@foreach`.

Maybe you can do it in the same way or creating your own `@loopbb` logic ;)

**Comment by noxify** [comment]
To your question about the routes.

Did you try to create a 'dynamic' route?
Something like this: https://laracasts.com/discuss/channels/general-discussion/routing-with-dynamic-number-of-params-in-laravel-5

Then you can do everything in the Controller which should be ok - or not?

**Comment by noxify** [comment]
Correction to my first comment:

I meant only the `@foreach` command.
I have checked my code and I'm using the `@query` command in the template.

Before I have extended the Loop logic I managed everything in my controller and ran then a `@foreach` but I had problems with the "read more" placeholder in the content.

**Comment by SamirAlexandru** [comment]
Yes I just did that, and it seems like its working! 

Second, a cool thing powered by bbPress is that they are giving shortcodes like [bbp-single-forum id=$forum_id] which can be very easily handled in the controller. 

I will come back with full code when its ready, hope it will helps someone else too! 

Thank you all for your input!

**Comment by jlambe** [comment]
@SamirAlexandru One thing to note is that you can override the routes system and keep using default WordPress way of calling templates.

Basically, the framework checks if a route exists for the request, if not it fallback to the theme default `index.php` file or any core templates set at the root of your theme.

I'm not sure regarding bbPress but for BuddyPress, I know that you can copy its templates and put them at theme's root which will be used in order to output everything.

> Also, if you start going that way, you'll probably need to set core theme files like `header.php`, `footer.php`, and so on...

In order to avoid a code duplicate, I suggest you to simply call your existing header or footer view from root theme files:

```php
<?php
// header.php
echo view('your.header');

```

**Comment by SamirAlexandru** [comment]
Hey @jlambe , thank you very much for your answer, can you give me an example of how to 

> override the routes system and keep using default WordPress? 

And also I think a much proper way to do this is the way I went since bbPress provides shortcodes, we can easily create the view now, but probably for other plugins that won't apply. 

> I know that you can copy its templates and put them at theme's root which will be used in order to output everything.
Yes, but it didn't worked ( tried with both, WooCommerce and bbPress ). 

Thank you again for your input!

**Comment by SamirAlexandru** [comment]
Oh I think I know what you mean by overriding the route system, but I think that shouldn't happen, it will lose the real purpose of the framework.

**Comment by ramon-villain** [comment]
@SamirAlexandru I don't think so. Imagine a situation where you have to create a specific solution like an SPA inside of a page, it's annoying to have to create a wordpress page without any content e put the logic in your controller/view, this is dangerous because any a unintentional modification could change the page or even delete it.

**Comment by SamirAlexandru** [comment]
@ramon-villain , I just don't prefer to disable this kind of routing, is just way better in my opinion than the default WP one, and since we have WP_Query and WP_Post, the logic behind controller will be very easily handling. 

Another cons is that you will have to load a header, footer and page files, which again is kind not wanted since we go with a MVC structure ( again, this is my opinion ).

**Comment by jlambe** [comment]
@SamirAlexandru If you wish to keep using the `routes.php`, you probably need to add the templates conditions to the route API by calling the `themosisRouteConditions` filter from the theme route service provider.

**Comment by SamirAlexandru** [comment]
@jlambe , I think I took a better approach. 

**routes.php**
`Route::get('/forums/forum/{name}',  'ForumController@single');`

**ForumController@single**
```
public function forum_single($name)
    {
        $args = [
            'post_type'      => 'forum',
            'posts_per_page' => -1,
            'post_name__in'  => [$name],
            'fields'         => 'ids'
        ];
        $forum_id = get_posts( $args );

        return view('forum.single', compact('forum_id'));
    }
```

In the view I am just doing the shortcode with the $forum_id and that's it. That approach applies to topic and replies as well, and basically at any custom post type.
Of course, the bbPress will be a must have plugin, so it won't be a problem to overwrite the default loop templates as well, adding right now a filter to overwrite the path to match our theme directory and that's it.

**Comment by jlambe** [comment]
Release 2.0 is going to be compatible with WooCommerce. Not yet tested with bbPress but it should work as WooCommerce by defining necessay `do_action` hooks in your views.
