### ISSUE TITLE
How to create database seeder with Themosis?

### ISSUE THREAD

**Issue by brucebrophy** [themosis/framework#438]
I currently don't see anything in the docs about Database seeding, but since Themosis uses Illuminate, is there anyway to create seeders with WordPress?

Thanks!

**Comment by jlambe** [comment]
@brucebrophy I've never used them but it should be doable.

Sounds like you need to create base seeder class and autoload it. Then call its `run` method to provide default tables data. One thing is that `artisan` is not available but I suppose that running a script from the cli, which calls your base seeder class should do it.

**Comment by AsfalothDE** [comment]
I'm trying to achieve a similar thing: start a Thruway websocket server via command line that listens for post updates. I just can't figure out where to place the command line script so it has access to the namespaces and classes/methods in my themosis plugin (it has to be in my plugin). Can you help me?

**Comment by jlambe** [comment]
Release 2.0 will have a `console` application. Seeders command are not yet available but should be quite easy to add. At the moment, only migrations commands are available.

**Comment by jlambe** [comment]
Database seed commands are available on the `master` branch as well as the Eloquent `factory` helper function. Coming in release `2.1`.
