### ISSUE TITLE
Request Facade inside a Controller issue

### ISSUE THREAD

**Issue by RavivCohen-BWEBI** [themosis/framework#439]
Encountered a problem while trying to access the Laravel Request object 
using Request Facade inside a Controller.
We have tried several ways of using the Request Facade
and the
`$request->method()`
output, each time printed out a GET method and not the POST as was expected.
and the Request attributes where empty.
The only way to access the Request parameters was through the Input Object.

Http request sent via Ajax of data type JSON (maybe related):
```
$.ajax({
            type: 'POST',
            url: url, // Route url parameter to the Method
            dataType: 'json',
            data: data, // Jquery serialize() data
            success: function (response) {
                if (response.success) {
                    if (response.data.callback) {
                        eval(response.data.callback);
                    }
                    if (response.data.view) {
                        $(response.data.view.target).html(response.data.view.content);
                    }
                } else {
                    showErrors(response.msg);
                }
            },
            error: function (error) {
                console.log('error');
                //window.location = location.href;
            }
        });
```

Controller basic code (Just for the Sample):

```
namespace Theme\Controllers;

use Themosis\Facades\Request;
// Also tried:
// use Illuminate\Http\Request
use Themosis\Route\BaseController;
class Calories extends BaseController
{
    public function register(Request $request)
    {
        var_dump($request->all()); // Empty
        $method = $request->method();
        dd($method); // Always GET
    }
}
```

Also tried outputing the Request directly on the Route and same result.

**Comment by AdrianKielbasa** [comment]
Try use Input Facade. 
 
![image](https://user-images.githubusercontent.com/14923258/27860438-ef25aa1a-617c-11e7-90de-7822613a2b3d.png)

**Comment by RavivCohen-BWEBI** [comment]
Thanks,

That's what i used eventually as a solution.
`use Themosis\Facades\Input;`
and accessed it like
`$data = Input::all();`

Just wanted to notify about the Request object issue.

**Comment by terence1990** [comment]
I think Controller methods should receive Request::capture() by default

**Comment by terence1990** [comment]
actually what @RavivCohen-BWEBI said - using `Themosis\Facades\Input` in the controller already receives the Request captured.

**Comment by jlambe** [comment]
Release 2.0 will correctly handle the Request instance with pre-populated data.
