### ISSUE TITLE
Index of / on Apache server

### ISSUE THREAD

**Issue by SamirAlexandru** [themosis/framework#440]
Hey, coming with a new problem which could help more people in future. 

We are facing with the next scenario: We just did a new installation of the framework on our server ( for the first time not locally ) and anything we are doing ( even bringing in an .htaccess in the root directory ) end us having a directory listing. 

Any idea why ?

**Comment by jlambe** [comment]
This is clearly an misconfiguration of your apache server. The default htacces file has no rules to show the directory listing.

This is not related to the framework. You should probably ask your question on [serverfault](https://serverfault.com) for help.
