### ISSUE TITLE
Implement ArrayAccess on ConfigFactory

### ISSUE THREAD

**Issue by terence1990** [themosis/framework#441]
Currently, in Laravel $this->app['config'] is bound to Illiminate/Config/Respository which has ArrayAccess, however in Themosis $this->app['config'] is a facade to Themosis/Facades/Config. 

I think perhaps it would be more streamlined to make $this->app['config'] bound to Themosis/Config/ConfigFactory and make ConfigFactory implement ArrayAccess so that we can easily integrate with other Illuminate packages such as Illuminate/Session where the SessionManager calls $this->app['config']['session'].

I could do some work and make a pull request if you like?

**Comment by jlambe** [comment]
@terence1990 Sure but perhaps look into existing pull request to see if what you're trying to achieve is not temporarily done.

**Comment by jlambe** [comment]
Also, have a look at this contribution guide before making any PR: http://framework.themosis.com/docs/1.3/contributing/

Thanks

**Comment by terence1990** [comment]
Hey!

It seems this guy read my mind!

https://github.com/themosis/framework/pull/393

**Comment by jlambe** [comment]
I can't give you an exact date for now.

If you need this for your project in a urgent manner, I suggest you to fork the repository and apply the changes on your own repository and use your repo inside your project.

**Comment by terence1990** [comment]
No worries for now, I created a SessionManager to reference config.factory anyway, works well for now!

https://github.com/wp-kit/session
