### ISSUE TITLE
Translate 'Insert media' of Field::collection?

### ISSUE THREAD

**Issue by CodeBrauer** [themosis/framework#443]
I've added a new PostType and passed 'labels' to it. However I can't find any option/key to translate the following buttons that are provided with `Field::collection`:

- "Insert media" title in modal
- "Insert"-Button at the bottom

![bildschirmfoto 2017-07-12 um 15 59 38](https://user-images.githubusercontent.com/2059754/28121391-3b70bbfa-671b-11e7-9f01-c6630a96011e.png)

**Comment by jlambe** [comment]
These are still probably hard-coded into the JS file handling the collection field.

The localization is missing for those 2 properties.

**Comment by CodeBrauer** [comment]
Yes, found it: [src/Themosis/_assets/components/fields/media/MediaView.js#L41-L44](https://github.com/themosis/framework/blob/333b45f42d1a498ba9cac3aa9b04f33942d78e1e/src/Themosis/_assets/components/fields/media/MediaView.js#L41-L44)

**Comment by jlambe** [comment]
@CodeBrauer If you would like to contribute, you can open a PR with a fix regarding this so I can review your code changes and perhaps merge it into main branch.
