### ISSUE TITLE
$post and $query globals in controller construct

### ISSUE THREAD

**Issue by simnom** [themosis/framework#445]
Hey,

Trying to inject the WP globals for $post and $query into my controller constructer so I can run some common functions and share the data across all views but I cannot seem to get this work.

Injecting to a standard controller function as follows works fine:

```
public function solution(Post $p, Testimonial $t, Cta $c, $post, $query) {
    $this->page = $post;
}
```

Trying the following in the constructor:

```
public function __construct(Post $p, Testimonial $t, Cta $c, $post, $query)
{
    dd($post);
}
```
Results in `Unresolvable dependency resolving [Parameter #3 [ <required> $post ]] in class Theme\Controllers\PageController`.  

Is there a way to resolve this?

**Comment by jlambe** [comment]
@simnom it's only resolved into the methods. For the constructor you have no choice than calling the good old `global $post, $wp_query;` to get them.

**Comment by simnom** [comment]
Ah cool OK.  That's all working merrily, thanks.
