### ISSUE TITLE
themosis/framework is no more installed in mu-plugins directory

### ISSUE THREAD

**Issue by mickaelperrin** [themosis/framework#448]
This issue follow our discussion at https://github.com/themosis/framework/commit/fa7875c3b37b7de563c5f5b87ce56860619dfde4.

composer-installer **needs** a supported package type to handle custom installation paths, even on packages name rules (see https://github.com/composer/installers/issues/308).

It looks like, the type "wordpress-plugin" should be reverted back in the composer.json file to resolve the issue.

**Comment by jlambe** [comment]
@mickaelperrin yes indeed. Will be fixed, thanks.
