### ISSUE TITLE
How to run tests on the theme?

### ISSUE THREAD

**Issue by bwrice** [themosis/framework#458]
I'm not sure how the namespacing works within the theme itself, as the composer.json has no auto-loader. How does someone go about allowing tests in the root directory to recognize classes inside the theme?

**Comment by LukeAbell** [comment]
@jlambe any idea here?

**Comment by jlambe** [comment]
@bwrice Classes are autoloaded from the theme's `functions.php` file using PSR-4.
If you want to run your tests in a theme, you'll have to include the `functions.php` file when setting up your test class or if you're the config file, require it over there.

One issue though is that it will use WordPress functions, so WordPress also needs to be loaded.

In the case where you have written custom classes, you can run `composer install` at your theme's root and install your theme dependencies there. Those you won't be loaded in your project as there is no call to the autoload file coming with Composer. Require the autoload file in your test config file and it should be good to go.

**Comment by bwrice** [comment]
@jlambe Thanks for the reply. I'm not sure of the process needed to require WordPress before loading functions.php. I've tried including index.php from the htdocs directory as well as including wp-blog-header.php and/or wp-load.php, however, when I do this, none of the tests are fired, including the environment ones that come with the themosis install.

**Comment by mpemburn** [comment]
This is still a work in progress, but we were able to run some basic tests agains Themosis theme and   WordPress native code by including the following in bootstrap.php with the /MyThemosis/Theme/tests directory:

`
$_SERVER['HTTP_HOST'] = 'macpa.laruta-refactor.dev';
$_SERVER['SERVER_PROTOCOL'] = 'HTTP/1.1';
$_SERVER['REQUEST_METHOD'] = 'POST';

// Define DS (directory separator) This is needed by bootstrap/autoload.
if (!defined('DS')) {
    define('DS', '//');
}

require __DIR__ . '/../../../../../bootstrap/autoload.php';
require __DIR__ . '/../vendor/autoload.php';
require __DIR__ . '/../../../../../htdocs/cms/wp-load.php';
`

**Comment by jlambe** [comment]
Note that from a theme perspective, what are the functions you would like to test. If those written functions use WordPress functions, like @mpemburn did, you have to load WordPress as well from a bootstrap phpunit file. Because when running tests through CLI, it doesn't hit the root `index.php` file of your project (=>not tested it but it could work as well to require your project root file). Anyone tested this as well?
