### ISSUE TITLE
Replacing the DI container?

### ISSUE THREAD

**Issue by lougreenwood** [themosis/framework#465]
I'd like to replace Illuminate's container with PHPDI (http://php-di.org) throughout the Themosis stack. Is it possible to replace the container which Themosis uses (and is available through `$GLOBALS['themosis']->container`) with a different, `container-interop`/PSR-11 compatible container?

https://github.com/container-interop/container-interop

**Comment by jlambe** [comment]
I don't know, I have not tested this. Just replacing the globals won't replace it into the stack though. The container is setup in the core plugin and there are no filters to define another one.

You can fork the framework and test it on your side and let us know how it goes.

**Comment by lougreenwood** [comment]
@jlambe Thanks - any suggestion on which files to start looking at for implementing this?

**Comment by lougreenwood** [comment]
I have progress...

Using the Acclimate library (https://github.com/AcclimateContainer), I was able to create a composite container which uses both Laravel and PHPDI (with PHPDI taking priority).

Unfortunately Acclimate doesn't expose anything like PHPDI or Laravels `make` methods, so it's not possible to use the container as a factory, but it's progress and means I can rely less on Laravel's funky/weird IoC container...

I bundled this into a service provider so it's available throughout the application:

```
<?php

namespace ...;

use Themosis\Foundation\ServiceProvider;

use Illuminate\Container\Container;

use Acclimate\Container\ContainerAcclimator;
use Acclimate\Container\CompositeContainer;

class CompositeContainerService extends ServiceProvider
{
    /**
     * Creates a composite container which allows use of both the Laravel and PHP DI container.
     */
    public function register() : void
    {
		$acclimator = new ContainerAcclimator;

		// Now, we will put these two containers together
		$this->app = new CompositeContainer([
			// PHP DI
			$acclimator->acclimate( ( new \DI\ContainerBuilder() )->build() ),

			// Laravel
			$acclimator->acclimate( Container::getInstance() ),
		]);
    }
}
```
