### ISSUE TITLE
Themosis Framework not working in shared server

### ISSUE THREAD

**Issue by yamilelias** [themosis/framework#466]
I just created a new wordpress where I installed a plugin that uses the Themosis Framework. I **don't have free access to all the server**, is a shared server, but I managed to install the themosis plugin in the mu-plugins directory and even run `composer install`. 

Now is working, but not completely, it seems there is an issue with the installation of Themosis because not everything is working. For example, it shows me **Post Types** created with the framework, but it doesn't show the **metaboxes** assigned to those Post Types. I know is working because in my localhost I'm running a full installation (just like in the [installation documentation](https://framework.themosis.com/docs/1.3/installation/)) and there is no problem.

I found that the log is outputting a warning every time I open a custom post type editor (where the metabox should be shown). I presume is because of this error. Here is the log:

```
[08-Nov-2017 20:00:53 UTC] PHP Warning:  file_put_contents(/views//dac4708fbc8dadd9b6c5e67df34be05981dda31a.php): failed to open stream: No such file or directory in /home/detalheadmin/public_html/wp-content/mu-plugins/themosis-framework/vendor/illuminate/filesystem/Filesystem.php on line 122
[08-Nov-2017 20:00:53 UTC] PHP Warning:  include(/views//dac4708fbc8dadd9b6c5e67df34be05981dda31a.php): failed to open stream: No such file or directory in /home/detalheadmin/public_html/wp-content/mu-plugins/themosis-framework/vendor/illuminate/view/Engines/PhpEngine.php on line 43
[08-Nov-2017 20:00:53 UTC] PHP Warning:  include(): Failed opening '/views//dac4708fbc8dadd9b6c5e67df34be05981dda31a.php' for inclusion (include_path='.:/opt/alt/php70/usr/share/pear') in /home/detalheadmin/public_html/wp-content/mu-plugins/themosis-framework/vendor/illuminate/view/Engines/PhpEngine.php on line 43
```

I believe is because some php modules are blocked because is a shared server, but I want to be completely sure if there is no possible solution for this than changing the server. The server where I have this issue is a Godaddy Hosting Server.

Thanks by the way.

**Comment by jlambe** [comment]
@yamilelias sounds like you're missing the root `storage/views` directory so compiled views can be stored before rendering. Try to add the missing folder and it should be good to go.

**Comment by yamilelias** [comment]
I tried to add that directory into `public_html` and into my root user directory, so now is something like this:
```
├── User root directory
       ├── storage
       |     └── views
       └── public_html
             ├── storage
             |     └── vies
             └── wp-content
                    ├── mu-plugins
                    └── themosis-framework
```

But this doesn't solve the problem. I don't know if is because I'm not running a full themosis installation, is that the cause? If that's it, then there is a way to use it in other hosts that don't have an installation?

**Comment by pagegwood** [comment]
@yamilelias If you're running themosis as a mu-plugin then you need to include storage/views under wp-content or whichever folder you have set as your wp-content directory

**Comment by yamilelias** [comment]
Thanks @pagegwood that solved my issue.

**Comment by simnom** [comment]
Just adding to this, running Themosis on WPEngine wasn't quite as simple as adding the `storage/views` folder to the root, this still fell foul of the file restrictions.  However, programatically adding `/tmp/storage/views` using `mkdir()` and setting the constant `define('THEMOSIS_STORAGE', '/tmp/storage');` does allow for the compiled blade files to be stored.
