### ISSUE TITLE
assets from plugin not loading

### ISSUE THREAD

**Issue by netdust** [themosis/framework#467]
Hi,

I am trying to use the espresso event plugin with themosis, but for some reason the assets from that plugin are not always added to the header and some pages give me js errors.
I tried a very simple setup with a route and a view just calling wp_header() and the css is not added to the header. Other css files are there.

If I switch to twentyseventeen theme from wordpress the styles are added like it should and there are no js errors. I am not sure what  I am doing wrong here, ... any help is appreciated.

thx
Stefan

**Comment by netdust** [comment]
Hi, 

I noticed that when I skip the routing and views of themosis and create a usual wordpress template  ( e.g. page-{id}.php } then the assets are added correctly. I don't understand why because all I do is call wp_head(). Any ideas?

stefan

**Comment by jlambe** [comment]
@netdust Perhaps the plugin is using the `template_redirect` action to load some stuff and if they priority is higher than the one used by the framework, it gets skipped.
This might be the only idea that comes to my mind. In order to be sure, we would need the plugin code.

**Comment by netdust** [comment]
jip, you were right, they are using template_redirect and if I change the priority to 10 ( from 999 ) it works again. one down, now the js errors :) thx
