### ISSUE TITLE
Save fields for existent user

### ISSUE THREAD

**Issue by ie76** [themosis/framework#468]
Hello,
i have an issue with saving fields for existent user, here's the snippet: 

```php
User::addFields([
        Field::text('facebook', ['info' => 'Your facebook page.']),
        Field::text('twitter', ['info' => 'Twitter account name.']),
        Field::text('user_role', ['info' => 'User Role.']),
        Field::checkbox("about", ["1" => "Show in About"], ['title' => '']),
]);
```

For new user, it works. But if it's an existent one, it can't be save. 

PS: I can't thank you much how you made my life easy with Themosis 🥂 @jlambe

**Comment by ramon-villain** [comment]
Weird, just tried the code right here and it's working in both situations.

**Comment by ie76** [comment]
Well, here's how i did to find out this issue. I had an existing wordpress database, i migrate it in order to work with Themosis. Once i did, i created some new fields for users. When i'm trying to store the fields, nothing. The fields comes empty.

**Comment by jlambe** [comment]
@ie76 Have you tried on a fresh install by any chance? If there are any other activated plugins, try perhaps to de-activate them and try again to store user data.
