### ISSUE TITLE
twig dump()

### ISSUE THREAD

**Issue by manniR** [themosis/framework#469]
i have it installed locally with WP_DEBUG = true

in twig template dump is not working:

{{ dump( my_var ) }} 

how to enable the twig dump extension?

**Comment by jlambe** [comment]
Normally, the local environment is already setup with all debugging options. Have you installed the full stack or just the framework plugin? Normally `{{ dump(some_var) }}` is working out of the box.

**Comment by manniR** [comment]
yes full stack version 1.3.0

**Comment by manniR** [comment]
vendor/twig/twig/lib/Twig/Extension/Debug.php

```php
//setting 'needs_context' from true to false
new Twig_SimpleFunction('dump', 'twig_var_dump', array('is_safe' => $isDumpOutputHtmlSafe ? array('html') : array(), 'needs_context' => false, 'needs_environment' => true)),
```
'needs_context' from true to false on line 30 and `{{ dump(some_var )}}` works - any idea why?

**Comment by jlambe** [comment]
It is enabled by default if your local environment has defined `WP_DEBUG` and is set to `true`:
* https://github.com/themosis/framework/blob/master/src/Themosis/View/ViewServiceProvider.php#L120

Can you check to get latest version 1.3.2 ? Like mentioned previously it is working out of the box. For why it doesn't work on your case, perhaps you can provide more context on where you use the `dump` function and provide more details about your application configuration.

Have you tried another installation without any code changes and tried to call the `dump` function from a view file?

**Comment by manniR** [comment]
hi julien,
upgrade to 1.3.2 fixed it for me - its working now
great - thx;)
