### ISSUE TITLE
Themosis not work

### ISSUE THREAD

**Issue by adrix71** [themosis/framework#470]
Simple and concise: it does not work on windows with wampp64 and linuxmint.

In both systems I tried:

1) Configure the .env file with my credentials and set 'return false' in the config/environment.php file. Result 'Can not contact the server'.

2) Set the local hostname in the config/environment.php file (I removed 'return false') and configure the .env.local file. Result "Can not contact the server".

3) Set 'SetEnv varName varValue' in the .htaccess file and use the closure in the config/environment.php file. Result "Can not contact the server".

VirtualHost works properly.

Some idea?

**Comment by jlambe** [comment]
Can you post screenshots with the exact errors you get on screen? The framework does not have such error message as "Can not contact the server". This sounds like a timeout issue to reach your local web server.

By default, you only use the `.env.local` file where you provide MySQL credentials. From the `config/environment.php` file, you can return this instead:
```php
return 'local';
```
This clearly tells the framework to use the `.env.local` file at the root.

**Comment by adrix71** [comment]
Thanks for the answer but also setting the "local" return does not solve the problem.

The error is not a themosis error but the screen that browsers (IE, Chrome, Firefox) show when they do not find a resource and I can not understand why; for example, fresh rock works smoothly.

This is the screenshot. VH and .htaccess seem to do their job.
![themosis](https://user-images.githubusercontent.com/14064365/33144497-96dbba8e-cfbd-11e7-8df7-97078bee0066.PNG)


And this is the content of .env and .env.local

`
DB_NAME = "themosis"
DB_USER = "XXXXXX"
DB_PASSWORD = "XXXXXX"
DB_HOST = "localhost"
WP_HOME = "http://themosis.dev"
WP_SITEURL = "http://themosis.dev/cms"
`

**Comment by jlambe** [comment]
I think you're definitely having a server issue. You can't reach your local virtual host `themosis.dev`.  You should provide all your steps of setting up your vhost and with which software/tool. You can also check this stackoverflow issue: https://stackoverflow.com/questions/35314640/themosis-doesnt-run-on-localhost

**Comment by adrix71** [comment]
The post that you've linked to is exactly my configuration and it does not work.

Virtualhost works correctly to the point I've tried on bedrock, a very similar framework, and it works smoothly.

Also in the logs I find no significant error.

Tomorrow I look back and let you know.

**Comment by adrix71** [comment]
I confirm that that post does not offer a solution to the problem and that configuration does not work.

My configuration is:

config / environment.php
```php
return [
    'local' => 'Neo',
    'production' => 'your-production-hostname'
];
```
.env / .env.local
```php
DB_NAME = "themosis"
DB_USER = "XXXXXX"
DB_PASSWORD = "XXXXXX"
DB_HOST = "localhost"
WP_HOME = "http://themosis.dev"
WP_SITEURL = "http://themosis.dev/cms"
```

windows \ system32 \ drivers \ etc \ hosts
```php
# Themosis
127.0.0.1	www.themosis.dev
```

virtualhost
```php
<VirtualHost *:80>
  ServerName themosis.dev
  ServerAlias www.themosis.dev
  DocumentRoot "${INSTALL_DIR}/www/themosis/htdocs"
  <Directory "${INSTALL_DIR}/www/themosis/htdocs">
    Options Indexes Includes FollowSymLinks MultiViews
    AllowOverride All
    Require all granted
  </Directory>
</VirtualHost>
```

**Comment by jlambe** [comment]
@adrix71 What about changing your `hosts` file to `127.0.01 themosis.dev` only for test.

**Comment by adrix71** [comment]
I changed but not work again. Same result, also themosis I had installed it a few months ago without problems and I had also made some tests after studying the documentation.

I do not really understand why he behaves this way.

**Comment by adrix71** [comment]
Ok now work. I put xampp in place of wampp and now it works. I have no idea why.

**Comment by jlambe** [comment]
The only thing I see is an error at some point on the server configuration as the application is never hit but it's not my confort area 😄 Glad your issue is solved.
