### ISSUE TITLE
Pagination in eloquent

### ISSUE THREAD

**Issue by iameronmosele** [themosis/framework#474]
When trying to use the eloquent builder's pagination method application fails everytime with the error
![screenshot from 2017-12-14 07-25-36](https://user-images.githubusercontent.com/8146143/33978440-0c8a7480-e0a0-11e7-8b7b-1f14daa27339.png)

**Comment by jlambe** [comment]
The pagination package is not installed with default dependencies. Please add it to your composer.json file and run a composer update. We have used it recently and it's working as expected:
- https://packagist.org/packages/illuminate/pagination

**Comment by iameronmosele** [comment]
Thanks just did that could have checked properly works fine now
