### ISSUE TITLE
views under the section tab does not display

### ISSUE THREAD

**Issue by Zorion-zozo** [themosis/framework#475]
How can i add a view under a section page?
The Section::make constructor seems to accept a view. But template doesn't show on the page.

My code like this:
`
$page_view1 = View::make('sections.section1');
$sections[] = Section::make('one', 'one Or two');
$page = Page::make('my-page', 'Theme options')->set();
$page->addSections($sections);
`

If the 'view' parameter of section:make() is not used currently in 1.30 version? Or anything wrong with my code？

Thank a lot.

**Comment by jlambe** [comment]
Hello, views under section are not handled by the framework. You can indeed add a view to it but it won't render.
