### ISSUE TITLE
FinderException when activate my own plugin

### ISSUE THREAD

**Issue by xXCrystalXx** [themosis/framework#476]
Hey,
I developed my own plugin for wordpress, by following the instructions in the themosis documentation. When I activate the plugin in wordpress I get the following error:

**Themosis \ Finder \ FinderException
File or entity "de_myfirst_loading" not found.**

Can anyone help me to solve the problem?

Best regards
xXCrystalXx

**Comment by jlambe** [comment]
Can you provide the plugin properties defined under the `$vars` variable at plugin root and your config file name?
