### ISSUE TITLE
Filter/Action accept array as first parameter

### ISSUE THREAD

**Issue by ramon-villain** [themosis/framework#477]
This could drive us to less repetition and duplication in situations when you use callbacks.

So instead of having to do.
```
Action::add('created_term', [$this, 'method']);
Action::add('edit_term', [$this, 'method']);

function method()
{
return;
}
```
or even
```
Action::add('created_term', function(){
return;
});
Action::add('edit_term', function(){
return;
});
```
we could just code

```
Action::add(['created_term', 'edit_term'], function(){
return;
});
```

**Comment by jlambe** [comment]
@ramon-villain Indeed nice feature to develop! I'll add this one for the `next` release 👍

**Comment by jlambe** [comment]
Feature now available into the `develop` branch.
