### ISSUE TITLE
How to run tests on plugin?

### ISSUE THREAD

**Issue by yamilelias** [themosis/framework#478]
I have been navigating through the issues to find if you already answered this question. There is one really similar: #458 but it talks about _Themes_ and that I need to include `functions.php`, which I don't have in a plugin. I also found you answered something similar about testing in plugins in #123 but its a bit old (2015) and you point out to use [WP CLI Plugin Unit Tests](https://make.wordpress.org/cli/handbook/plugin-unit-tests/). I tried it. 

First of all it doesn't give me the change due to that is not a **"correct WordPress installation"**. I have a [Themosis environment](https://framework.themosis.com/docs/1.3/environment/) installed and that's the reason to the error. Then when I managed to get the files from another WordPress installation (one I did with `wp core download`) I tried to run `phpunit` to start testing but it can't connect to the database because of a wrong `wp-config.php` configuration. I haven't modified that file, is the same one that came with the environment installation.

How you do plugin testing? You should have a way using the Themosis environment. If you could post a step-by-step or tell me what should I change to make it work, I (and maybe others too) will really appreciate it.

Thanks for taking your time in this question

**Comment by jlambe** [comment]
@yamilelias My current workflow is still indeed by using the plugin tests provided by the WPCLI tool. Basically, it provides some setup files (bash script) that will install a copy of WordPress into your machine `/tmp/wordpress-tests-lib` directory (unix machine -> does not work on Windows).

You have to use the PHPUnit configuration file `.dist.xml` and bootstrap the tests:
1. Provide a path to the WordPress installation located into your `/tmp` directory.
2. Include your plugin root file
3. Include WordPress unit tests functions

Here is a current setup working on our development:
```php
<?php
/**
 * PHPUnit bootstrap file
 *
 * @package Themosis_Framework
 */
$_tests_dir = getenv('WP_TESTS_DIR');
if (!$_tests_dir) {
    $_tests_dir = '/tmp/wordpress-tests-lib';
}

// Give access to tests_add_filter() function.
require_once $_tests_dir.'/includes/functions.php';

/**
 * Manually load the plugin being tested.
 */
function _manually_load_plugin()
{
    require dirname(dirname(__FILE__)).'/themosis.php';
}

tests_add_filter('muplugins_loaded', '_manually_load_plugin');

// Start up the WP testing environment.
require $_tests_dir.'/includes/bootstrap.php';
```

**Comment by jlambe** [comment]
@yamilelias At the moment, the workflow is to mock global functions that you may call in your plugin.
