### ISSUE TITLE
Save button for attachment custom tax field

### ISSUE THREAD

**Issue by KevinBatdorf** [themosis/framework#479]
The code:

```php
Action::add('init', function() {
  $cat_args = [
    'public'             => true,
    'show_in_nav_menus'  => false,
    'hierarchical'       => true,
    'show_tagcloud'      => false,
    'show_in_quick_edit' => false
  ];
  Taxonomy::make('inspirations-styles', ['attachment'], 'Styles', 'Style')
    ->set($cat_args)->bind()
    ->addFields([Field::media('featured_image', [
      'title' => 'Summary Page Image', 'type' => ['image']
      ])
    ]
  );
[...]
```
That works fine, but I don't see any way to add a save button.

![image](https://user-images.githubusercontent.com/1478421/36226241-da1b58c0-11ff-11e8-9bf1-f1ade996b8ab.png)

**Comment by jlambe** [comment]
You don't need to provide a "save button", the `Add New Category` button is the save one. If you add an image to your custom field, it will be saved with the term.

**Comment by KevinBatdorf** [comment]
I suppose that makes sense :)
