### ISSUE TITLE
Multisite with sub directories

### ISSUE THREAD

**Issue by toborinojg** [themosis/framework#480]
Hi,

I received a website developed with the Themosis framework/theme to install
http://procobre.com

This website is hosted at Digital Ocean with Forge install (Ubuntu 16+, NGiNX & MySQL)

My customer wants to use it in a sub directory multisite installation (I know you doesn-t recommend but it is a demand from the customer).
We will have the main website http://procobre.com and a portuguese version on http://procobre.com/pt

I followed the instructions at https://framework.themosis.com/docs/1.3/multisite/#cleanup-default-url and at https://github.com/themosis/themosis/issues/168 (the fix plugin)

I can access the Network admin and the main site admin, but I now can`t access the /pt admin
http://procobre.com/pt/cms/wp-admin/ and the client side could not be acessible either
- http://procobre.com (redirects to http://procobre.com/cms/) and http://procobre.com/pt

How can I fix that?

Please find below the .htaccess and network config.
Thanks in advance.

HTACCESS
# BEGIN WordPress
RewriteEngine On
RewriteBase /
RewriteRule ^index\.php$ - [L]

# uploaded files
RewriteRule ^([_0-9a-zA-Z-]+/)?files/(.+) wp-includes/ms-files.php?file=$2 [L]

# add a trailing slash to /wp-admin
RewriteRule ^([_0-9a-zA-Z-]+/)?wp-admin$ $1wp-admin/ [R=301,L]

RewriteCond %{REQUEST_FILENAME} -f [OR]
RewriteCond %{REQUEST_FILENAME} -d
RewriteRule ^ - [L]
RewriteRule ^[_0-9a-zA-Z-]+/(wp-(content|admin|includes).*) $1 [L]
RewriteRule ^[_0-9a-zA-Z-]+/(.*\.php)$ $1 [L]
RewriteRule . index.php [L]
# END WordPress

SHARED.PHP

define('WP_ALLOW_MULTISITE', true);
define('MULTISITE', true);
define('SUBDOMAIN_INSTALL', false);
define('DOMAIN_CURRENT_SITE', 'procobre.com');
define('PATH_CURRENT_SITE', '/');
define('SITE_ID_CURRENT_SITE', 1);
define('BLOG_ID_CURRENT_SITE', 1);

define('ADMIN_COOKIE_PATH', '/');
define('COOKIE_DOMAIN', '');
define('COOKIEPATH', '');
define('SITECOOKIEPATH', '');

**Comment by jlambe** [comment]
Normally the network admin URL should not change for your subdirectory installation. It should stick to `http://procobre.com/cms/wp-admin/`.

Only the "front-end" part is pointed to `http://procobre.com/pt`. Also, if your web server is Nginx, the configuration from the `.htaccess` file is not used -> it's an Apache web server configuration file.

Also not sure why you configure the cookie constants, you should remove them and stick to default just to be sure.

**Comment by toborinojg** [comment]
Hi Julien,

Thanks for your swift response.

Sorry, I`m not used to work with NGiNX.
I edited the shared.php to remove the cookies constants (thanks).

Normally at multisite with subdirectories the Admin URL includes the subdirectory
http://procobre.com/pt/wp-admin (or procobre.com/cms/pt/wp-admin)

I couldn`t find how to edit the NGiNX conf to insert the multisite rules as showed in
https://codex.wordpress.org/Nginx and https://www.nginx.com/resources/wiki/start/topics/recipes/wordpress/

Do you have this expertise?
I would like to ask you if you can do this install as a job to us. Is it possible?

Please let me know which is the better option for you.
Thanks again.

Jse Geraldo

**Comment by toborinojg** [comment]
Hi,

I changed the NGiNX config file to include the Wordpress Multisite config but it didn`t fix the Admin issue.
I can`t access the sub directory site admin.

http://procobre.com/wp-admin is the Network admin
http://procobre.com/cms/wp-admin is the main site admin
http://procobre.com/pt is the sub directory site
http://procobre.com/pt/cms/wp-admin is the sub directory admin <-- I can`t access this one.

Please find below the nginx config file (their .htaccess)

`# FORGE CONFIG (DOT NOT REMOVE!)
include forge-conf/procobre.com/before/*;

server {
    listen 80;
    listen [::]:80;
    server_name procobre.com;
    root /home/forge/procobre.com/htdocs;

    # FORGE SSL (DO NOT REMOVE!)
    # ssl_certificate;
    # ssl_certificate_key;

    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers 'I REMOVED THE CIPHERS';
    ssl_prefer_server_ciphers on;
    ssl_dhparam /etc/nginx/dhparams.pem;

    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-XSS-Protection "1; mode=block";
    add_header X-Content-Type-Options "nosniff";

    index index.html index.htm index.php;

    charset utf-8;

    # FORGE CONFIG (DOT NOT REMOVE!)
    include forge-conf/procobre.com/server/*;

    ## WordPress Multisite
    if (!-e $request_filename) {
        rewrite /wp-admin$ $scheme://$host$uri/ permanent;
        rewrite ^(/[^/]+)?(/wp-.*) $2 last;
        rewrite ^(/[^/]+)?(/.*\.php) $2 last;
    }
    set $cache_uri $request_uri;


    # POST requests and urls with a query string should always go to PHP
    if ($request_method = POST) {
        set $cache_uri 'NULL';
    }
    if ($query_string != "") {
        set $cache_uri 'NULL';
    }
    ### END

  
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt  { access_log off; log_not_found off; }

    access_log off;
    error_log  /var/log/nginx/staging.example.com-error.log error;

    error_page 404 /index.php;

    location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass unix:/var/run/php/php7.0-fpm.sock;
        fastcgi_index index.php;
        include fastcgi_params;
    }

    location ~ /\.ht {
        deny all;
    }
}
# FORGE CONFIG (DOT NOT REMOVE!)
include forge-conf/procobre.com/after/*;

`

**Comment by jlambe** [comment]
I'm no expert on Nginx configuration. This URL can be found: `http://procobre.com/pt/cms/wp-login.php`, so it somehow fetch the correct file at some point. Looking at network result from developers tools, all others files (css, js, images) point to `404` not found error.

Have you read this documentation page on the codex, it has an example of Nginx configuration for multisite with subfolders: https://codex.wordpress.org/Nginx

You might compare it to yours.

**Comment by KevinBatdorf** [comment]
The nginx config looks correct. I would check elsewhere for the issue. Maybe in your config or environment files somewhere.

**Comment by KevinBatdorf** [comment]
Here's an example from gist of someone else's nginx config that you can compare with.

https://gist.github.com/kirkbeard/4f11a1925192c1ddeb49

**Comment by toborinojg** [comment]
Hi,

@KevinBatdorf I followed this git but it doesn`t work anyway. Thanks for your tip.

I`ll change the development to use a language plugin instead of the multisite with subdirectories.
I`ve realized that the multisite installation didn`t created the blogs.dir directories (UR: issues, files issues...) and it will be too painfull to put it in production (I haven`t the proper time to work on it now).

@jlambe thanks for your support!

**Comment by YassineBenaziz** [comment]
For people who still working with the multisite network and have this problem, I had the same issue on Themosis 2.0 beta 3 , and i fixed this problem by adding this rule to my htaccess file : 
`RewriteRule ^([_0-9a-zA-Z-]+/cms/)?(wp-(content|admin|includes).*) cms/$2 [L]`

**Comment by Jaspervv** [comment]
themosis/themosis#255
