### ISSUE TITLE
Coding standard

### ISSUE THREAD

**Issue by szepeviktor** [themosis/framework#481]
Hello!

What is your position on coding style?
Maybe WPCS or a hybrid solution?

@jlambe

**Comment by jlambe** [comment]
@szepeviktor We follow [PSR-2](https://www.php-fig.org/psr/psr-2/) directive. We now use `php-cs-fixer` to automatically set the coding style on our projects.

**Comment by szepeviktor** [comment]
Thank you.
Could you reflect it in Travis?

**Comment by jlambe** [comment]
@szepeviktor we are currently refactoring the overall framework stack. Our Travis configuration is outdated for now but what do you mean by reflecting it into Travis?

**Comment by szepeviktor** [comment]
Running phpcs before tests.

**Comment by jlambe** [comment]
@szepeviktor the develop branch now contains a `php-cs-fixer` configuration for coding style. See [FriendsOfPHP CS Fixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer) repository for installation and the run `php-cs-fixer fix` from your terminal.
