### ISSUE TITLE
Validate register new user

### ISSUE THREAD

**Issue by AdrianKielbasa** [themosis/framework#484]
```
$user = User::addFields([
    Field::text('twitter'),
    Field::number('age')
]);

// Validate our user instance fields...
$user->validate([
    'twitter' => ['textfield', 'min:3'],
    'age'     => ['num']
]);
```

This validation not working on register new user? You can add a user if you enter 2 characters in twitter field.

**Comment by jlambe** [comment]
@AdrianKielbasa this only validates the user meta fields values. This does not prevent WordPress to create the new user. The `validate` methods mainly works as a sanitization method preventing storage of not well formed meta values. So in your case, you do get a new user registered but its `twitter` meta value is empty as it has no more than 3 characters.

**Comment by AdrianKielbasa** [comment]
ok, thanks
