### ISSUE TITLE
Weird routing behaviour when using a home route

### ISSUE THREAD

**Issue by leroy** [themosis/framework#486]
Given i have the following routes setup:

```php
Route::get('home', function()
{
    return view('welcome');
});

Route::get('custom-route', function() {
    return 'test';
});
```

When i visit the route '/' i get the 'welcome' view as expected.
When i visit the route '/custom-route' i should get 'test' as response but get the welcome view instead.

After some research it turns out that Wordpress still thinks we're on a is_home route when it is in fact a 'Themosis route'.

I'd like to discuss the desired behaviour in this issue as the only way to get Themosis routes working is by using a `Route::get('front')` instead of `Route::get('home')` and configuring a static frontpage in Wordpress.

**Comment by jlambe** [comment]
@leroy This is an expected behaviour in fact. Routes are read from top to bottom. The router returns the first route it matches against.

Generally, you always have to put custom routes before WordPress routes.
