### ISSUE TITLE
How to integrate divi builder with themosis?

### ISSUE THREAD

**Issue by rovillesarate** [themosis/framework#488]
Hi! I am trying to integrate the divi builder plugin with themosis. How do i hook the routes to the front end builder. Tried connecting the et_pb_layout post type but cant seem to make it work.

**Comment by jlambe** [comment]
@rovillesarate I don't think you'll find any support for this as this is not related to the framework. I personnaly never used their builder plugin. You have to dig into their code and documentation for this. They probably expect some default WordPress behaviour or hooks in order to work.
