### ISSUE TITLE
how i can access plugin admin controller

### ISSUE THREAD

**Issue by mohamed4shim** [themosis/framework#495]
Dear Sir
thank you for your best solution for wordpress by using your framework,
but
how i can use custom mvc plugin in admin i mean how i can access controllers action in url
eg http://myproject/htdocs/cms/wp-admin/controller/method

when i try to use it by fetching it in routes.php
Route::get('/cms/wp-admin/someroute',' controller@method');
it give me blank view without wordpress admin template

can you help me to using admin urls in plugin page

**Comment by mohamed4shim** [comment]
thanks for your respond but how i can access controller methods in page?
eg when i want to access controller tasks with action add,index,delete,update
how i can create the form url in add and update and accessing it from urls

**Comment by jlambe** [comment]
Well the way you're doing is correct. But you can't assign admin pages requests to a specific class method like on the front-end.

Your composer class can extends the base controller class and leverage auto dependency injection if that could help you.

The WordPress admin is not using a front controller pattern so it's tricky to use it as anywhere else. WordPress is using an `action` trick with `admin-post.php` to manage different type of requests on a page, you should dig into that if you want to better control your admin page.

**Comment by mohamed4shim** [comment]
thanks but when i try to use this
use Themosis\Facades\Action;

Action::add('load_admin.php', 'Sample@load');
in actons.php and create Sample class in controllers folder
it give me an error "Class Sample does not exist"
where i can put my class

**Comment by jlambe** [comment]
You need to provide the full classname (with its namespace) to the `Action::add()` method.

If working from the theme: `Action::add('load_admin.php', 'Theme\Controllers\Sample@load');`
