### ISSUE TITLE
How to override a fields view inside a metabox

### ISSUE THREAD

**Issue by rovillesarate** [themosis/framework#500]
Hi! I am trying to override the infinite field view inside a metabox.

The custom metabox sample provided in the documentation uses..
`
<table class="form-table themosis-metabox">
    <tbody>
        @each('_themosisMetaboxRow', $__fields, 'field') // are there any guide to extend this more?
        // This currently display the view assigned to the metabox but what if i want to customize the fields view
    </tbody>
</table>`

**Comment by jlambe** [comment]
You need to build your own field class then. Your class  can extend the infinite field one and you replace whatever you need to change. Then use the `Field::make()` method to use your custom field.

There are no ways to change the view of a core field at the moment.

**Comment by h-collector** [comment]
A little late, but just wanted to put my 2 cents.
@rovillesarate You can try Laravel style vendor views override.
When registering paths for views, just prepend (not add) Location
```
$theme['view.finder']->prependLocation(
     themosis_path('theme.resources') . 'views'
);
```
Then you can override all views
`resources/views/_themosisMetaboxRow.blade.php`
`resources/Views/metabox/_themosisTextField.blade.php`
