### ISSUE TITLE
Problem adding filter to themosisAdminGlobalObject

### ISSUE THREAD

**Issue by rovillesarate** [themosis/framework#502]
Hi! I am trying to add a filter for the themosisAdminGlobalObject

I created a custom metabox that will use ajax but i need access to the themosis.ajaxurl

For some reason it would not add the values. 

`Filter::add('themosisAdminGlobalObject', function($data) {
    $data['security'] = 'insert_post';
    return $data;
});`

**Comment by jlambe** [comment]
Can you inspect your page and show what output do you have inside your `<head></head>` tag ? (just the script tag used by themosis)

**Comment by rovillesarate** [comment]
I was only successful using this code:
`add_action('admin_head', function() {
    $output = "<script type='text/javascript'>\n\r";
    $output .= "var themosis = {\n\r";
    $output .= "ajaxurl: '/cms/wp-admin/admin-ajax.php',\n\r";
    $output .= "security: 'insert_post'\n\r";
    $output .= "}\n\r";
    $output .= "</script>\n\r";

    // Output the datas.
    echo $output;
});`

but my ajax still wont work. Here is my ajax.php from the admin folder
`    Ajax::listen('insert_post', function(){	
        // Check nonce value
        check_ajax_referer('insert_post', 'security');

        // Run custom code - Make sure to sanitize and check values before
        $result = $_POST['title'];
		
        // "Return" the result
        echo $result;

        // Close
        die();
    });`

This is the custom js
`jQuery(document).ready(function() {
	jQuery('button.insert_post').click(function(){
	    var post_title = jQuery('input[name="test_input"]').val();

		jQuery.ajax({
		    url: themosis.ajaxurl, // Global access to the WordPress ajax handler file
		    type: 'POST',
		    dataType: 'json',
		    data: {
		        action: 'insert_post', // Your custom hook/action name
		        security: 'insert_post', // A nonce value
		        title: post_title // The value you want to send
		    }
		}).done(function(data)
		{	
		    // This should print "4" in the console.
		    console.log(data);
		});
	});
});`

and this is the test metabox that im trying to make. input text when i click the button should fire the ajax script.
`<div class= "obutton feature2" data-id="<?php echo $bookID;?>">
	{!! Themosis\Facades\Form::text('test_input', '', ['class' => 'form-control']) !!}
    <button class="insert_post">Insert Post</button>
</div>`

Once i submit i get a forbidden access error from the console.

I already check and themosis variable is already loaded. I wish it will only load on a specific admin page but i dont know how to do it.
`
<script type="text/javascript">
--
  | //<![CDATA[
  | var themosis = {
  | ajaxurl = 'http://teamgoldcrest.local:8888/wp-admin/admin-ajax.php;'
  | security = 'insert_post';
  | };
  | //]]>
  | </script>

`

**Comment by rovillesarate** [comment]
It worked when I tried to disable the
`// check_ajax_referer('insert_post', 'security');`
maybe its because of the nonce value?

**Comment by rovillesarate** [comment]
I ended up with this instead.

```
<?php
use Themosis\Facades\Ajax;

    // This file is stored in resources/admin/ajax.php
    // This code listens for logged in and logged out users
    Ajax::listen('insert_post', function(){	
        // Check nonce value
        // check_ajax_referer('test-insert-post', 'security');
        wp_verify_nonce( $_POST['security'], 'test-insert-post' );
        // Run custom code - Make sure to sanitize and check values before
        $result = sanitize_text_field( $_POST['title'] );;
		
        $my_post = array(
          'post_title'    => wp_strip_all_tags( $_POST['title'] ),
          'post_status'   => 'publish',
        );
         
        // Insert the post into the database
        wp_insert_post( $my_post );
        // "Return" the result
        echo $result;

        // Close
        die();
    });
?>
```

**Comment by rovillesarate** [comment]
I was able to make the AJAX request on the admin page work but for some reason. After the ajax call, the page will always refresh. I am not able to add the text on the HTML element because of this.

**Comment by jlambe** [comment]
Probably due to your `<button>` element. By default, it is a "submit" type of button, you should define this instead: `<button type="button">Insert Post</button>`

And to be sure, just add a `preventDefault()` on your click event from your javascript code.
