### ISSUE TITLE
Using Facades services (Response or another)

### ISSUE THREAD

**Issue by romainhe** [themosis/framework#507]
Hi, 
I want to use a laravel service like Response class,
When I try  `Response::download($path,$name); ` method but I got an exception : "A facade root has not been set"

I tried the service provider way but I don't know how to manage this...

Very thx for help !

**Comment by jlambe** [comment]
The default HTTP provider coming from the Illuminate package is not registered and its facade not either so you can't call the `Response` facade.

Basically, what you can do, is to register the http provider that registers the response class into the container. Then create your own or register the provided `Response` facade with the php aliases configuration. Something like `Response => 'Illuminate\Support\Facades\Response`.

Once all this is registered, you should be able to access the Response class/facade.
