### ISSUE TITLE
How to use a vanilla-php-view with an existing theme

### ISSUE THREAD

**Issue by twosg** [themosis/framework#509]
I have made my themosis related work (custom post types, metaboxes and the routing) in a plugin, to be able to use an existing wp theme as a base. So I don't need to take care about the default wordpress routes and functionality.

If I do in my controller:
`return View::make('cpt.single')->render();`

The rendering will look like:

1. Output of my view file
2. Theme header
3. Theme content
4. Theme footer

How can I replace the Theme content with my view? Result should be:

1. Theme header
2. Output of my view file
3. Theme footer

I hope you can understand what I try to achieve. Screenshot:
![screenshot](https://user-images.githubusercontent.com/325412/41527914-dd97d9d4-72e8-11e8-859e-cf09241cb90b.png)

**Comment by twosg** [comment]
What works is this:

```
<?php get_header()?>
<h1>Error 404</h1>
<?php get_footer()?>
<?php die()?>
```

But it's ugly somehow :-x

**Comment by jlambe** [comment]
This is expected in fact. Your view is first fully loaded before any theme templates. If your base theme contains a "classic" WordPress template for your request, it is as well loaded after your view.

If your plugin return a view, you have to remove templates in the theme.

On the contrary, you can remove your controller call and instead from a default WordPress template call your view like so:
```php
// post-type-single.php
<?php

echo View::make('cpt.single');
```

**Comment by twosg** [comment]
Thanks for clarification :)
