### ISSUE TITLE
Custom rewrite with route to controller

### ISSUE THREAD

**Issue by twosg** [themosis/framework#511]
Sorry if that is more a support question instead of a framework issue.

I am wondering if it is possible to modify the arguments of the controller method when having a setup like this:

```
add_action('init', function() {
	add_rewrite_tag('%manufacturer%', '([^&]+)');
	add_rewrite_rule('rewriteslug/([^/]+)/?$','index.php?post_type=mycustom&manufacturer=$matches[1]','top');
});

Route::match(['GET', 'POST'], 'postTypeArchive', ['mycustom', 'uses'=>'CustomController@archive']);
```

If I try
`Route::get('/rewriteslug/{manufacturer}', ['mycustom', 'uses' => 'CustomController@archive']);`

I get: "Unresolvable dependency resolving [Parameter #0 [ <required> $post ]] in class WP_Post"

Currently I only see the possibility to get this value by reading the REQUEST_URI.

**Comment by jlambe** [comment]
Generally I would to remove the WordPress rewrite rules and only work with your controller to fetch the entities you need based on passed parameters through the URL.

You need to set the `rewrite` property of your custom post type to `false` to avoid conflicts on your routes. Or put your custom route before any WordPress ones.

**Comment by twosg** [comment]
> You need to set the rewrite property of your custom post type to false to avoid conflicts on your routes. 

That helped, thanks!
