### ISSUE TITLE
Custom PostType with rewrite_rules

### ISSUE THREAD

**Issue by Neidra** [themosis/framework#531]
Hey everyone,
I'm currently trying to customize the routes of my custom PostType.
But with the following code my singular route return 404...

Declaration of the PostType
`
 PostType::make("pt-formations","Formations","Formation")->set([
            'public' => true,
            'rewrite' => ["slug"=>"formations"],
            'query_var' => false
        ]);
`
In wordpress i use rewrite_rules
`
        add_rewrite_rule('formations/%postname%/', '?post_type=pt-formations&p=$matches[1]', 'top');
`
I verified my rules is rewrite

Themosis routes declarations
`
            Route::get('singular', ['pt-formations', function(){
                       return 'Hello world';
            }]);
`

Someone could help me about my mistake?

**Comment by jlambe** [comment]
Hello,
your issue is your parameter to the `query_var`. You should'nt set it to `false`, otherwise WordPress is not able to find your single training post.

Also, your custom rewrite rule is similar a default one provided by WordPress. I suggest you to also erase it.

**Comment by Neidra** [comment]
Thanks for your explication.
Just to add than when we use `query_var` , don't forget to set the `publicly_queryable` variable to true.
