### ISSUE TITLE
Field editor, errror themosisCore.js

### ISSUE THREAD

**Issue by AdrianKielbasa** [themosis/framework#532]
![image](https://user-images.githubusercontent.com/14923258/45774596-ad40aa00-bc4d-11e8-894c-ac748a112b73.png)
![image](https://user-images.githubusercontent.com/14923258/45774644-cf3a2c80-bc4d-11e8-9069-f0a0b741107f.png)
When I add second editor field, it gets error in console.

**Comment by jlambe** [comment]
Hello, currently the editor field cannot be used within an infinite one.

**Comment by AdrianKielbasa** [comment]
Hello,

Ok
