### ISSUE TITLE
Forms: the HTML markup is not rendered on Twig template

### ISSUE THREAD

**Issue by jminguely** [themosis/framework#534]
Hello,

The form markup is rendered escaped when generated from a twig template.

For example:

```
{{ Form.open() }}
   {{ Form.text('name', 'Jean-michel', {'class': 'super'}) }}       
{{ Form.close() }}
```

will returns:

<img width="926" alt="capture d ecran 2018-10-03 a 10 17 54" src="https://user-images.githubusercontent.com/2260030/46398531-a9089800-c6f5-11e8-89ea-c0705573cd6e.png">

I've managed to hotfix my template by adding the `raw` filter:
```
{{ Form.open()|raw }}
    {{ Form.text('name', 'Jean-michel', {'class': 'super'})|raw }}       
{{ Form.close()|raw }}
```

It works perfectly with blade template.

**Comment by jlambe** [comment]
Probably there is a typo in the documentation as it return html string. So if using `{{ }}` symbols, it should indeed be rendered as text. The form documentation illustrates with blade using the unescape syntax. Using the twig `|raw` filter is the correct way to go.

**Comment by jminguely** [comment]
Thanks @jlambe 

I've proposed a fix on the documentation repo. The PR is here: https://github.com/themosis/documentation/pull/62

**Comment by jlambe** [comment]
I'm going to close the issue. I'll update the documentation very soon. Thanks for the PR.
