### ISSUE TITLE
Custom route with parameters not working

### ISSUE THREAD

**Issue by rinseringma** [themosis/framework#535]
Hi!

I'm trying to create a custom route which is returning a view, but I can't get it to work..

Once I've created the route, the route is working until the permalinks are flushed. When the permalinks are flushed, the route URL leads to the homepage. The route cannot be used again, even when I flush permalinks or even when I manually empty the rewrite_rules row in the database.

Here is my route:
`Route::get('component/{name?}/', function ($name = 0) {
	return view('components.'.$name);
});`

So when I visited "domain.tld/component/block-contact-call-us" I would like to get the view.

**Comment by KevinBatdorf** [comment]
@rinseringma Is that route at the top above all the WP routes?

**Comment by rinseringma** [comment]
No, it's below the WP routes. I'll try to move it above those routes

**Comment by rinseringma** [comment]
> @rinseringma Is that route at the top above all the WP routes?

Thanks Kevin! That seems to fix the problem!

**Comment by jlambe** [comment]
@rinseringma Indeed, as mentioned into the documentation, all custom routes must be defined before the WordPress ones. Note that for the next version, it won't matter anymore ;)
