### ISSUE TITLE
Creating checkboxes key/value in loop

### ISSUE THREAD

**Issue by rinseringma** [themosis/framework#536]
How do I create checkboxes with key/value pairs based on post types?

What I have now according to the documentation:
`$services = get_posts(['post_type' => 'diensten', 'posts_per_page' => -1]);
$options = [];
foreach ($services as $key => $service) {
  $options[$service->ID] = $service->post_title;
}
sort($options);
Metabox::make('Diensten', 'producten', ['context' => 'side'])->set([
  Field::checkbox('diensten', $options)
]);`

But that sets the value of the checkbox to a lower case title. I want the value to be an ID of the post so I can used in one of the controllers.

**Comment by jlambe** [comment]
Hi I'm not sure we have supported numeric index correctly on the checkbox field. But I suggest you to use instead the `select` field which does support it. Here is an example:
```php
Field::select('diensten', [$options]);
```

> Note that you need to define an array of array for the options.
