### ISSUE TITLE
Custom post type not showing up in search results

### ISSUE THREAD

**Issue by rinseringma** [themosis/framework#537]
I don't know why, but all posts and pages are showing up, except for the custom post types I've created..

**CP**:
`PostType::make('producten', 'Producten', 'Product')->set([
    'public'        => true,
    'menu_position' => 200,
    'supports'      => ['title', 'editor', 'thumbnail', 'excerpt'],
    'has_archive'   => true,
    'show_in_nav_menus' => true,
]);`

**Routes**:
`// Search route
Route::match(['get', 'post'], 'search', function($post, \WP_Query $query)
{
    return view('search', [
        'title' => pll__('Zoekresultaten'),
        'posts' => $query->get_posts(),
        'searched_terms' => Input::get('s')
    ]);
});`

**View**:
`@extends('layouts.app')

@section('main')

@php global $wp_query; $count = $wp_query->found_posts; @endphp

    <div class="search">
        <div class="search__title">
            <h1>{{ $title }}</h1>
            <p>{!! pll__("Je hebt gezocht naar '{$searched_terms}' dit leverde de volgende {$count} resultaten op:") !!}</p>
        </div>
        <div class="search__results">
            @if(have_posts())
                <div class="search__results-list">

                    @php $i = 0; @endphp
                    @php while(have_posts()) : the_post(); @endphp

                        @if( 2 == $i % 3)
                            <div class="search__results-list__item last">
                        @else
                            <div class="search__results-list__item">
                        @endif 
                            <article class="post">

                                @if(has_post_thumbnail(get_the_ID()))
                                    <div class="post__image">
                                        <a href="{{ get_the_permalink() }}">
                                        <picture>
                                            <source media="(min-width: 640px)" srcset="{{ get_the_post_thumbnail_url( get_the_ID(), 'medium' ) }}">
                                            <source media="(max-width: 640px)" srcset="{{ get_the_post_thumbnail_url( get_the_ID(), 'large' ) }}">

                                            <img src="{{ get_the_post_thumbnail_url( get_the_ID(), 'medium' ) }}" alt="{{ $alt }}">
                                        </picture>
                                        </a>
                                    </div>
                                @endif
                                <div class="post__content">
                                    <h3><a href="{{ get_the_permalink() }}">{{ get_the_title() }}</a></h3>
                                    <a href="{{ get_the_permalink() }}">
                                        @if(has_excerpt())
                                            <p>{!! get_the_excerpt() !!}</p>
                                        @else
                                            <p>{!! strip_tags(substr(get_the_content, 0, 300)) . '...' !!}</p>
                                        @endif
                                    </a>
                                </div>
                            </article>
                        </div>
                        @php $i++ @endphp
                    @endwhile
                </ul>

                <div>

                    @php the_posts_pagination( array(
                        'prev_text'          => pll__( 'Previous page' ),
                        'next_text'          => pll__( 'Next page' ),
                        'before_page_number' => '<span class="meta-nav screen-reader-text">' . pll__( 'Page' ) . ' </span>',
                    ) ); @endphp

                </div>
            @else
                <h2>{{ sprintf('%s "%s"', pll__("We hebben niets gevonden voor:"), $searched_terms) }}</h2>
            @endif
        </div>
    </div>

@endsection`

So all default post types are loading, except for the custom ones. Any idea how to fix this?

**Comment by jlambe** [comment]
Looks like you're looking to have your custom posts in the search query. Have you tried to explicitly set this property on your post type registration: 
```php
'exclude_from_search' => false
```

Also, it is possible something else (plugin) might alter your search query. If you want to be sure about having your custom posts into it, you can hook into the query with the [pre_get_posts](https://developer.wordpress.org/reference/hooks/pre_get_posts/) action. This way you have total control of your global search query.

**Comment by rinseringma** [comment]
I did explicitly set that parameter. I try to debug the query with that function.

**Comment by rinseringma** [comment]
I've found the problem! I've created the post types and created posts. Also I've installed Polylang, but Polylang did not set the default language to the already existing posts. Polylang interfere with the global query searching only in the current language, but since there are no posts in the default language, it cant find any.

Thanks anyway for helping!

**Comment by jlambe** [comment]
Indeed good catch. Glad you solved your issue.
