### ISSUE TITLE
Autoload when installed as plugin

### ISSUE THREAD

**Issue by mclaurent** [themosis/framework#538]
Awesome project, started using a couple of weeks ago and it is a really great framework!

I have installed the framework as a mu-plugin via composer like so:

```json
{
	"name": "me/someproiject",
	"type": "project",
	"license": "proprietary",
	"config": {
		"preferred-install": "dist"
	},
	"prefer-stable": true,
	"repositories": [
		{
			"type": "composer",
			"url": "https://wpackagist.org"
		}
	],
	"require": {
		"johnpbloch/wordpress": "^4.0",
		"themosis/framework": "^1.0",
		"wpackagist-plugin/relevanssi": "4.*"
	},
	"require-dev": {},
	"extra": {
		"wordpress-install-dir": "website",
		"installer-paths": {
			"website/wp-content/mu-plugins/{$name}": [
				"themosis/framework",
				"type:wordpress-muplugin"
			],
			"website/wp-content/plugins/{$name}": [
				"type:wordpress-plugin"
			],
			"website/wp-content/themes/{$name}": [
				"type:wordpress-theme"
			]
		}
	}
}

```

When i install this it will create a composer autoloader and add the following lines into the autoload_static.php
```php
public static $files = array(
        // ... stripped for ease of reading
        '457b350f837f9520e0d22dacd2ad6ba7' => __DIR__ . '/../..' . '/website/wp-content/mu-plugins/framework/src/Themosis/helpers.php',
);
```

This is causing a problem when deployed to a server with a different document root, i.e. "public_html" instead of "website". Since the framework is installed as a plug-in rather than a dependency in the vendor folder, wouldn't it be possible to avoid creating the entries in the composer's autoload files? In particular I am referring to the two lines in your composer.json under "autoload" (https://github.com/themosis/framework/blob/master/composer.json), since there isn't a way to overwrite this from my project as far as I am aware of.

Thanks

**Comment by jlambe** [comment]
You'll need to change the path into your `composer.json` file and replace the  `htdocs` fragment to `public_html` instead. Then run `composer install` so the autoload file points to the corrects directories.

**Comment by mclaurent** [comment]
Thanks @jlambe that makes sense. I wouldn't want to re-install dependencies/regenerate the autoloader for this environment as our CI/CD doesn't allow for it to be re-build between environments. I am considering including the dependencies for the framework within the mu-plugins folder but that's less than ideal because I would need to version all of the wp-content/mu-plugins/framework/vendor/ folder)

**Comment by jlambe** [comment]
Why not setting up your development environment as your prod or CI/CD one? I would definitely avoid tracking dependencies in the `mu-plugins` directory.

**Comment by mclaurent** [comment]
I found a work-around for this for anyone in a similar situation. We could not have our public_html folders changed to match ,and neither did we want to track dependencies in version control. Instead what we ended up doing is configuring our composer.json so that:
* themosis/framework is installed into the vendor folder, rather than mu-plugins or plugins (to avoid our file includes in autoload_files.php referencing the public_html folder)
* manually copy the themosis/framework module into the mu-plugins folder so that is picked up by WordPress. 
We're aware that we're duplicating the library in our application, however it allows for the project to compile properly without having to modify the server environments.

Here's the composer.json, hope that comes in handy for anyone with the same or similar issue:

````json
{
    "name": "sample/project",
    "description": "project",
    "type": "project",
    "license": "proprietary",
    "config": {
        "preferred-install": "dist"
    },
    "repositories": {
        "1": {
            "type": "composer",
            "url": "https://wpackagist.org"
        }
    },
    "prefer-stable": true,
    "require": {
        "slowprog/composer-copy-file": "0.*",
        "wemakecustom/wp-mu-loader": "1.*",
        "composer/installers": "~1.0.12",
        "vlucas/phpdotenv": "2.*",
        "johnpbloch/wordpress": "^4.0",
        "oscarotero/env": "1.*",
        "themosis/framework": "^1.0"
    },
    "extra": {
        "wordpress-install-dir": "website",
        "installer-paths": {
           "vendor/themosis/{$name}": [
                "themosis/framework"
           ],
            "website/wp-content/mu-plugins/{$name}": [
                "wpackagist-plugin/cmb2",
                "wemakecustom/wp-mu-loader",
                "type:wordpress-muplugin"
            ],
            "website/wp-content/plugins/{$name}": [
                "type:wordpress-plugin"
            ],
            "website/wp-content/themes/{$name}": [
                "type:wordpress-theme"
            ]
        },
        "copy-file": {
            "website/wp-content/mu-plugins/mu-loader/mu-require.php": "website/wp-content/mu-plugins/mu-require.php",
            "vendor/themosis/framework": "website/wp-content/mu-plugins/framework"
        }
    },
    "autoload": {
        "exclude-from-classmap": [
            "/public_html"
                ]
    },
    "scripts": {
        "post-install-cmd": [
            "SlowProg\\CopyFile\\ScriptHandler::copy"
        ],
        "post-update-cmd": [
            "SlowProg\\CopyFile\\ScriptHandler::copy"
        ]
    }
}

````
