### ISSUE TITLE
Login not found

### ISSUE THREAD

**Issue by ZeNickos** [themosis/framework#539]
I installed Themosis, and ran through the Setup. I am currently stuck at the last part of the Environment setup, where I needed to login into the WordPress admin screen. The problem is, that the login pages are not found. I tried both  **/login** and **/cms/wp-login.php**.

I already changed the theme folder name, and changed it in the shared.php
Also I included `define('FORCE_SSL_ADMIN' , true);` to force the https.

There could be a problem in my virtual host, here is my Info:

**in the httpd conf:**
<VirtualHost *:80>
    DocumentRoot "D:\xampp\htdocs\ThemosisFramework\htdocs
    ServerName themosis.test
</VirtualHost>

**hosts file:**
127.0.0.1	themosis.test

**.env file:**
```
DB_NAME = "themosisfw"
DB_USER = "user_themosis"
DB_PASSWORD = "test"
DB_HOST = "localhost"
WP_HOME = "https://themosis.test"
WP_SITEURL = "https://themosis.test/cms"
```

I have my environment.php set to `return false;`

**Comment by jlambe** [comment]
Hi, the default login uri is `/cms/wp-login.php`. If permalink structure has not yet been set, the `login` redirect is not working.

Forcing the SSL won't change anything. As its name is suggesting, it forces the `https` protocol which might not work at all on your local setup if your web server does not have a certificate installed.

**Comment by ZeNickos** [comment]
Yea, i tried that. But it seems that the page does not exist?
Could also be a redirect problem

**Comment by jlambe** [comment]
The file `cms/wp-login.php` should be there. If the file exists, it should be reachable.

You should remove the force SSL because you're configuration only listens to port 80. Where https is 443. Set urls back to `http` on your config (env file).

**Comment by ZeNickos** [comment]
Thanks for the help, works like a charm
