### ISSUE TITLE
my themosis route is not considered

### ISSUE THREAD

**Issue by Cedric-locchi** [themosis/framework#541]
hello all, 
I have a problem with my router, I have a route that is removed for the categories '/category/{slug}' which worked very well, I imported in my test database the data of my old site and the route no longer works ... the url is taken into account but it is the home page which is taken into account for each route '/category/'

ps: Sorry for my bad english '^^

**Comment by Cedric-locchi** [comment]
if y save without change my permalink config, my router work again...

**Comment by jlambe** [comment]
Probably that when you imported your old data, the permalink structure was set to default using query strings. Routing always need a permalink rule defined.

**Comment by Cedric-locchi** [comment]
no, even though I define a permalink rule, it does not work all the time
