### ISSUE TITLE
WP CLI - empty execution

### ISSUE THREAD

**Issue by Daisuke-sama** [themosis/framework#547]
Hi,

I've installed the framework, and I am starting it within my docker container. The website works. But the only command of wp cli is db check/create/etc. and core version works correctly. Others, like plugin, theme core, etc. doesn't work and show no errors. --debug stops on (bootstrap) wp-config.php

Same behaviour from docker container run of the wp-cli and directly on the host machine.

Do you have ideas or experience?

**Comment by jlambe** [comment]
Hello,

no nothing like that. Do you have the latest .phar archive of wp-cli installed ?

**Comment by Daisuke-sama** [comment]
Hi Julien,

Yes, I do. 2.0.1. Not the nightly one.
