### ISSUE TITLE
Task Scheduling usage

### ISSUE THREAD

**Issue by TipyTechnique** [themosis/framework#550]
Hi !

I'm reading the 2.0 doc, and i saw that we can use Task Scheduling now.

Can you please explain how to use it ?

I don't know if i can rely on Laravel's doc (5.7) or if you extended their system to fit Wordpress Cron.

Thank you for your time !

**Comment by jlambe** [comment]
Hi,

you can definitely rely on the Laravel docs for the moment. Simply define your tasks in the `app/Console/Kernel.php` class and setup your server cron with the following command:

```bash
* * * * * cd /path-to-your-project && php console schedule:run >> /dev/null 2>&1
```

**Comment by TipyTechnique** [comment]
It works !

Thank you :D
