### ISSUE TITLE
Conflict with Gravity Forms

### ISSUE THREAD

**Issue by TipyTechnique** [themosis/framework#557]
Gravity Forms allow us to make forms on backend, and use them on front-end by adding a shortcode on a page.

This plugin use by default the "post" method when submitting the form, and the target file, is the file itself.

When i'm submitting my form, i have an http 405 error Method not allowed that breaks my site.

I fixed it by adding some routes, all my pages that have a form have a slug that start with "formulaire-", so i added this route : 
```
Route::match(['get', 'post'], '/{gf}', function () {
    //
})->where('gf', '^formulaire-.*');
```

Is there a way to allow the POST method on unhandled routes ?

**Comment by jlambe** [comment]
You can also use the `Route::any('page', function () { ... });`. The `any` method listens to all HTTP protocols. See the [routing documentation](https://framework.themosis.com/docs/2.0/routing/#router-methods) for details.
