### ISSUE TITLE
[BUG] Loading mu-plugins on Windows

### ISSUE THREAD

**Issue by Jaspervv** [themosis/framework#558]
## Problem
Must-use plugins are not being loaded on Windows 10.
I'm using version `2.0-beta2`.

## Error
```
The "C:\xampp\htdocs\my-site\htdocs\content\mu-plugins\C:\xampp\htdocs\my-site\htdocs\content\mu-plugins\advanced-custom-fields-pro" directory does not exist.
```

## Fix
I think it has to do with the `$app->LoadPlugins()` function. Specifically with the `$directories` variable found in [Applications.php line 1180](https://github.com/themosis/framework/blob/ee2e60a2457870750ba2fef3eefbe661ded067a6/src/Core/Application.php#L1180).  

When I tried to echo this variable on my Linux environment, it looks like this:
```php
Array
(
    [0] => advanced-custom-fields-pro
    [1] => wp-soup-plugin
)
```

However, on Windows 10 it looks like this:
```php
Array
(
    [0] => C:\xampp\htdocs\my-site\htdocs\content\mu-plugins\advanced-custom-fields-pro
    [1] => C:\xampp\htdocs\my-site\htdocs\content\mu-plugins\wp-soup-plugin
)
```

**Comment by jlambe** [comment]
Probably, we only need the plugin directory name and not its full path. Thanks for catching this one.
