### ISSUE TITLE
Need Fields to have dependency between them

### ISSUE THREAD

**Issue by ClumsyCoder** [themosis/framework#56]
I have a requirement to have some fields in a metabox be enabled or disabled depending on the value of another field (usually a radio button or checkbox).  From the documentation I cannot find a way to do this without writing my own custom javascript code.  It would be nice to be able to just list this when creating the metabox as part of the options.

ie.

Metabox::make( 'My Meta', 'post', array( 'dependencies' => array( 'fieldA' => array( 'fielB' => 'on') ) )->set( $myFields );

**Comment by tomasvanrijsse** [comment]
I just started working with Themosis in stead of Piklist. This was a feature which we used a lot.
Has it been implemented yet?

Or is it possible to match a metabox to a template? Then I could create a few templates with specific fields for them.

**Comment by jlambe** [comment]
@tomasvanrijsse No, it's not yet implemented.

You can indeed create custom metabox template (view) and custom fields.

Regarding the development of custom fields, it's not documented but the idea is to create a class for your field and then call it using the `FieldFactory` class. For example, you might have a custom field class `My\Custom\Field` (using namespace). Then, from your metabox, you can assign it like so:

```php
Metabox::make()->set([
    Field::make('My\\Custom\\Field', ['atts' => ['class' => 'custom'], 'features' => ['title' => 'Custom field']])
]);
```
I suggest you to look at core fields class in order to build your own.

**Comment by tomasvanrijsse** [comment]
@jlambe I ment to match the page template with a metabox. Then I could create multiple templates each with different metaboxes. Is that feature available?

When I've got some time left I think I'll take a look if I can adjust the metabox to allow dependencies and handle it with Vue.js

**Comment by jlambe** [comment]
@tomasvanrijsse Are you talking about attaching a metabox only if an admin page has a specific template associated or displaying a metabox on the front-end side within a page ?

**Comment by tomasvanrijsse** [comment]
@jlambe we've made metaboxes for pages (with piklist) which only show up if the page has a certain template selected. For example a page template called "Large header" has a metabox specifically for that purpose to define the fields of the header which is only present on that template.

**Comment by jlambe** [comment]
@tomasvanrijsse Well than this is available. Simply define a metabox and in its options, set a `template` key with a value equivalent to a registered template inside your `templates.config.php` file:
```php
Metabox::make('Title', 'page', ['template' => 'large-header'])->set();
```
I've just seen that the documentation is missing for this feature.
