### ISSUE TITLE
Routing Issue and Fix

### ISSUE THREAD

**Issue by TipyTechnique** [themosis/framework#567]
Bonjour !

Je préfère parler en français ici pour m'expliquer :)

J'ai été confronter à un problème au niveau de mes routes. 

```
Route::get(
    'page',
    [
        'formulaire-reglage-instatipy',
        'uses' => 'SumoController@getInstatipySettingsFormAfterWoocommerce'
    ]
);

Route::get(
    'page',
    [
        'formulaire-renseignement-structure',
        'uses' => 'SumoController@getStructureSettingsFormAfterWoocommerce'
    ]
);
```

Lorsque j'utilise plusieurs routes avec la même condition Wordpress, ici "page", seule la dernière route est prise en compte. Donc ma page "formulaire-reglage-instatipy" ne va jamais appeler mon controller. La page "formulaire-renseeignement-structure" elle fonctionne comme il faut.

Voici le resultat de la commande ``` php console route:list ``` : 
```
|        | GET|HEAD                               | page                                                       |                       | App\Http\Controllers\SumoController@getStructureSettingsFormAfterWoocommerce | web        |
```
Un seule route est prise en compte, la dernière.

J'ai réussi à régler le problème, j'ai vu quand dans la version 1.1.3 du framework, Une classe RouteCollection, héritant de celle d'Illuminate, redéfinissait le fonction addToCollections de cette manière : 
```
    /**
     * Add the given route to the arrays of routes.
     *
     * @param \Themosis\Route\Route $route
     */
    protected function addToCollections($route)
    {
        $domainAndUri = $route->getDomain() . $route->uri();

        if ($route->hasCondition() && $route->getConditionParameters()) {
            $domainAndUri .= serialize($route->getConditionParameters());
        }

        foreach ($route->methods() as $method) {
            $this->routes[$method][$domainAndUri] = $route;
        }

        $this->allRoutes[$method . $domainAndUri] = $route;
    }
```

J'ai donc recréé dans le namespace ``` Themosis\Route ``` la classe RouteCollection avec cette fonction, et enfin dans la classe Router de ce même namespace, j'ai définit le constructeur : 
```
    /**
     * Router constructor.
     * @param Dispatcher $events
     * @param Container|null $container
     */
    public function __construct(Dispatcher $events, Container $container = null)
    {
        parent::__construct($events, $container);
        $this->routes = new RouteCollection();
    }
```

Pour que $this->routes contienne ma classe enfant RouteCollection et non celle d'Illuminate.

Maintenant tout fonctionne : 
```
|        | GET|HEAD                               | page                                                       |                       | App\Http\Controllers\SumoController@getStructureSettingsFormAfterWoocommerce | web        |
|        | GET|HEAD                               | page                                                       |                       | App\Http\Controllers\SumoController@getInstatipySettingsFormAfterWoocommerce | web        |

```

Je me suis simplement basé sur votre code de la version 1.1.3.
Je ne suis pas encore habitué à travailler avec github, je vais voir si je peux faire un PR ce sera le premier de ma vie :p 

Merci de votre temps.

**Comment by Jaspervv** [comment]
Apologies if I misunderstood, but isn't it expected behaviour that a route defined with the same key overrides any previously defined ones?

**Comment by TipyTechnique** [comment]
Yes, but in this framework we are using wordpress conditions tags to use Wordpress routes : https://framework.themosis.com/docs/2.0/routing/#wordpress-routes

So by default, Laravel will just see that we are using only 'page' uri multiple times for example, and will override the attached callback.
That's why we need to override the uri to have multiple uri for 'page' tag. So for this route : 
```
Route::get(
    'page',
    [
        'formulaire-renseignement-structure',
        'uses' => 'SumoController@getStructureSettingsFormAfterWoocommerce'
    ]
);
```
I think the changed uri will be 'pageformulaire-renseignement-structure', so it will be unique for Laravel.
This was the behavior on version 1.1.3, not in this one.

**Comment by TipyTechnique** [comment]
Hello @jlambe,

Yes this issue occurs since the 2.0 release, and like i said on my first comment i think it's because there is no more Themosis\Route\RouteCollection.php files, i made changes locally to fix it and i explained a bit how i did this (mostly a copy past from 1.1.3 version). 

So yes it's an issue ^^

**Comment by jlambe** [comment]
@TipyTechnique Ok I'm going to look at this one. Weird this has passed through but I rarely use this personnaly.

**Comment by jlambe** [comment]
@TipyTechnique Bring back your solution fixed the problem. Because all URI were equal, in the default collection, there was only one `page`  route registered so it was no able to try those with custom parameters. Thanks for catching thie one!

**Comment by TipyTechnique** [comment]
Nice :D i really like this framework, i'll try to learn the github workflow (using gitlab most of the time) and contribute to this project !

**Comment by jlambe** [comment]
Thanks! Your fix has been merged into the `master` branch. The workflow is the same. Instead of a merge request (gitlab), it is called pull request on github. Basically take a fork of the repository on your account, then create a branch for a fix and then submit your fix here by opening a pull request.
