### ISSUE TITLE
plugin url

### ISSUE THREAD

**Issue by mohamed4shim** [themosis/framework#573]
how i can access plugin route in both front-end and backend?
such as http://test.com/plugin-name

**Comment by mohamed4shim** [comment]
i just return back to themothis documentation and read route document
"If you define a route from a plugin similar to one of your application routes, the route coming from the plugin will have precedence over the one declared into the root web.php file."
and now i understand it but how i can make mvc plugin ? where i can put plugin models and controllers and views

**Comment by jlambe** [comment]
The default routing is only working for front-end requests as the WordPress administration is not using a front controller pattern.

Accessing a URI like the one defined is just a matter of adding a `Route::get('plugin-name')` inside the application `routes/web.php` file.

Plugins are extending WordPress features. You define routes inside a plugin but such routes will be used/listened only on the front-end side of WordPress and not its administration.

**Comment by Jaspervv** [comment]
First of all you have a typo: `welcone`. The routes are working fine for me in **2.0**, it might be something with your environment.  
Do other pages work besides the homepage (like the WordPress dashboard)?  
Does it possible have something to do with your `.htaccess` file found in `./htdocs/.htaccess`?



I tried with a fresh project, I documented my steps below and it worked fine:

**1. create project & theme**
```shell
$ composer create-project themosis/themosis my-project 2.0-beta3
$ cd my-project
$ php console theme:install my-theme
```

**2. set environment variables**
from the new `my-project` directory, edit the values in the `.env` file according to [this documentation](https://framework.themosis.com/docs/2.0/configuration/#default-configuration).

**3. setup wordpress**
Go to the site URL pointing to the project's `htdocs` folder and follow the WordPress installation.

**4. create route**
Go to `./htdocs/content/themes/my-theme/routes.php` and added the following code:
```php
Route::get('/welcome', function() {
    die('welcome from theme');
});
```

**5. results**
Go to the site's `/welcome` route and got the following result:
![result](https://user-images.githubusercontent.com/35364310/52062206-59858c00-2570-11e9-90b6-6f50378da4f4.png)

**Comment by mohamed4shim** [comment]
thanks very much i follow your steps and now works with me
