### ISSUE TITLE
add menu item point to controller

### ISSUE THREAD

**Issue by mohamed4shim** [themosis/framework#574]
how i can create admin menu which point to a certain controller in version beta 2?

**Comment by mohamed4shim** [comment]
thanks for your answer,but can i create subpages which have multi routes?

**Comment by jlambe** [comment]
You can attach multiple routes to a page:

```php
// Page URL = domain.com/cms/wp-admin/page.php?page=my-custom-page
$page->route('/', function () {});

// Page URL = domain.com/cms/wp-admin/page.php?page=my-custom-page&action=subpage-1
$page->route('subpage-1', function () {});

// Page URL = domain.com/cms/wp-admin/page.php?page=my-custom-page&action=subpage-2
$page->route('subpage-2', function () {});
```

The URI value passed to the `route` method is not really a URI but an `action` value. For pages being request through the GET protocol, you can access those "sub-pages" routes by appeding the action query parameter to the page default URL: `...&action=subpage-1`

It is also possible to register POST routes within the admin page but it is also a "faked" mechanism. POST requests on administration page should be send against the `admin-post.php` file. Register a POST route on a page is in fact attaching an action hook based on the `action` value. Every time you handle a post request from an administration page, you endup doing a redirection to the page. More coming in the documentation soon :)

**Comment by mohamed4shim** [comment]
thanks this is avery nice Feature i love themothis
