### ISSUE TITLE
Routing after Upgrade from 1.3 to 2.0.0-beta2 does not work

### ISSUE THREAD

**Issue by twosg** [themosis/framework#575]
I have defined my routes in /routes/web.php like this:

```php
Route::get('/testroute', function () {
	return view('welcome');
})->name('test');
```

I can see the route with `php console route:list`, along with other routes I defined:

```
+--------+-----------+--------------------------------------+---------------------------+----------------------------------------------------------+------------+
| Domain | Method    | URI                                  | Name                      | Action                                                   | Middleware |
+--------+-----------+--------------------------------------+---------------------------+----------------------------------------------------------+------------+

|        | GET|HEAD  | testroute                            | test                      | Closure                                                  | web        |
```

But when I try to access these routes in frontend, WP just shows the 404 page. How can I debug this further?

- Nothing in /storage/logs/
- Nothing in php error log
- Nothing in Apache log except the 404

**Comment by jlambe** [comment]
Do you have a `404` route defined in your routes as well ?

**Comment by twosg** [comment]
No I did not have a 404 route. I just added it but it changed nothing, also tried the fallback route:

```
+--------+-----------+--------------------------------------+----------------+----------------------------------------------------------+--------------------+
| Domain | Method    | URI                                  | Name           | Action                                                   | Middleware         |
+--------+-----------+--------------------------------------+----------------+----------------------------------------------------------+--------------------+
|        | GET|HEAD  | 404                                  |                | Closure                                                  | web                |
|        | GET|HEAD  | testroute                            | test           | Closure                                                  | web,request.logger |
|        | GET|HEAD  | wp-api/themosis/v1/metabox/{metabox} | metabox.show   | Themosis\Metabox\Controllers\MetaboxApiController@show   | api                |
|        | PUT|PATCH | wp-api/themosis/v1/metabox/{metabox} | metabox.update | Themosis\Metabox\Controllers\MetaboxApiController@update | api                |
|        | GET|HEAD  | {fallbackPlaceholder}                |                | Closure                                                  | web                |
+--------+-----------+--------------------------------------+----------------+----------------------------------------------------------+--------------------+
```

**Comment by jlambe** [comment]
Can you provide me the steps you did for your project ? Did you install a new theme using the `php console theme:install mytheme` command before ?

**Comment by twosg** [comment]
Basically I did the following:

- Composer update to 2.0.0-beta2
- Made sure the new project file structure (themosis/themosis) matches and contents in /htdocs/ are updated, like wp-config.php and the mu-plugin loader.php
- Did run `php console vendor:publish`
- Started to move custom code from the 1.3 plugin to /app code (moved routes, helpers, controllers, hooks..)

I did not use the theme on 1.3, I use the "understrap" theme. So I did not run `php console theme:install ...`

I did run `php console plugin:install ...` to create a new plugin (routes in there are also not working).

**Comment by jlambe** [comment]
I haven't provided an upgrade guide from 1.3 as there are many break changes. You could make sure that the `themosis/framework` is now installed as a package dependency into the `vendor` directory and compare the new theme boilerplate with yours.

Regarding an upgrade, it is best to install a fresh copy of the 2.0 framework and then move the theme views and assets to the new one. Same for plugins as the structure has changed as well.

**Comment by twosg** [comment]
Hey @jlambe thanks for your effort, I think I just missed the migration of the theme code. Routing works now :)
