### ISSUE TITLE
[Feature] Field Labels

### ISSUE THREAD

**Issue by Jaspervv** [themosis/framework#577]
Currently when you create a page with `Fields`, it uses the id for the label. It would be nice to define separate labels and ids.

In 1.3 we could define separate ids and labels by passing `title` to the `$features` like so:
```php
Field::text('company_name', ['title' => 'Bedrijfsnaam'];
```

**Comment by jlambe** [comment]
Labels are handled as well in the new field API, use the `label` option like so:

```php
Field::text('company_name', [
    'label' => 'Bedrijfsnaam'
])
```

More options are available for fields but the docs are not yet updated.

**Comment by Jaspervv** [comment]
Thanks for the quick answer! (:
