### ISSUE TITLE
Twig : Twig::__construct() must be an instance of FileViewFinder

### ISSUE THREAD

**Issue by jminguely** [themosis/framework#578]
Hello,

I've got an issue when trying to use de Twig template engine with the latest version of the Themosis Framework:

Even if I use the code example you give in the Twig section of the document I got this issue:

```
Argument 2 passed to Themosis\View\Engines\Twig::__construct() must be an instance of Themosis\View\FileViewFinder, instance of Illuminate\View\FileViewFinder given, called in /Users/mingus/Sites/mda/vendor/themosis/framework/src/View/ViewServiceProvider.php on line 70
```

Do you have an idea why is it going that way with this template engine?

Thanks for your help !

**Comment by jlambe** [comment]
This issue has been fixed with the `2.0-beta3` release normaly. Update the version for the `themosis-framework` dependency in your `composer.json` file at application root and then run the `composer update` command. Let me know if it fixed your issue.

**Comment by Jaspervv** [comment]
duplicate of #570

**Comment by jminguely** [comment]
Okay, thanks and sorry for missing the resolution !
