### ISSUE TITLE
User issue.

### ISSUE THREAD

**Issue by dgines** [themosis/framework#579]
Milestone : 2.0 beta3

$user = User::make('johndoe', 'asecretpassword', 'john@doe.com');

![image](https://user-images.githubusercontent.com/3456139/52195608-fa1dc980-2858-11e9-882e-9d5257120ff6.png)

and when I fix the route (use Illuminate\Support\Facades\Facade;) ...:

![image](https://user-images.githubusercontent.com/3456139/52195642-1cafe280-2859-11e9-9fc0-842bb7ed403d.png)

**Comment by Jaspervv** [comment]
Looks like the `Themosis\User\UserServiceProvider` is never loaded, I see that it's missing by default in the [config/app.php](https://github.com/themosis/themosis/blob/434b13043922ffe0a501b96332cfccda5276fff8/config/app.php#L91).

**Comment by dgines** [comment]
and then, if I register UserServiceProvider...:
![image](https://user-images.githubusercontent.com/3456139/52201220-25a9af80-286b-11e9-96b5-9c0b4bd8894c.png)

**Comment by Jaspervv** [comment]
It's because the User `views` folder is not being registered in `Themosis\User\UserServiceProvider`.

### Fix
inside the `./vendor/themosis/framework/src/User/UserServiceProvider.php`, replace the following:
```php
$view = $container['view'];
$view = $view->make('_themosisUserCore');
```
with:
```php
$view = $container['view'];
$view->addLocation(__DIR__.'/views');
$view = $view->make('_themosisUserCore');
```

**Comment by Jaspervv** [comment]
[According to Julien](https://github.com/themosis/framework/pull/576#issuecomment-460636919) the User Facade still needs to be refactored, so it shouldn't be available yet.

**Comment by jlambe** [comment]
Indeed, the facade is not defined into the alias as the api needs a refactoring. See #542.

**Comment by dgines** [comment]
Ok, thank you for your support !
