### ISSUE TITLE
app()->environmentPath() returns wrong path

### ISSUE THREAD

**Issue by Jaspervv** [themosis/framework#582]
## Issue
The `environmentPath` method of the `./src/Core/Application.php` doesn't return the path to the `.env` file.

**Command Ran:**  
```php
die( app()->environmentPath() );
```

**Actual Behaviour:** 
echos: `/home/jasper/Projects/themosis-project`.

**Expected Behaviour:**  
echos: `/home/jasper/Projects/themosis-project/.env`.

## Fix
Currently the method looks like this:
```php
public function environmentPath()
{
    return $this->environmentPath ?: $this->basePath();
}
```
It returns the `basePath` as a backup, it should return the `basePath` with `.env` behind it.  
So I think it should be changed to the following:
```php
public function environmentPath()
{
    return $this->environmentPath ?: $this->basePath() .DS. $this->environmentFile;
}
```

**Comment by jlambe** [comment]
In fact this is expected. The `environmentPath()` method should return the directory path where are stored `.env` files. It should not return the `.env` path.
