### ISSUE TITLE
Unable to find settings

### ISSUE THREAD

**Issue by Jaspervv** [themosis/framework#584]
I am unable to get my settings using the `Options::get()` method.

## Creating Page
I simplified the code to the following:
```php
use Themosis\Support\Facades\Page;
use Themosis\Support\Facades\Field;
use Themosis\Support\Section;

// create section
$sections = [];
$sections[] = new Section('my-section', 'My Section');

// create field
$settings = [];
$settings['my-section'] = [
    Field::text('my-field'),
];

// create page
Page::make('my-page', 'My Test Page')
    ->addSections($sections)
    ->addSettings($settings)
    ->set();
```

This, like expected, creates the following settings page:
![image](https://user-images.githubusercontent.com/35364310/52334661-81f20800-2a00-11e9-8d99-855b3e4b9eaa.png)

## Getting option
Now I want to get the value of the `my-field`:
```php
use Themosis\Page\Option;

$my_field = Option::get('my-section', 'my-field');
$my_field2 = Option::get('my-page', 'my-field');
````

### Expected Result
I expect `$my_field` to return a string with "Test value :)".

### Actual Result
Both `$my_field` and `$my_field2` return an empty string, which is the return value for when it can't find an option.

**Comment by jlambe** [comment]
The option class is deprecated actually as it is similar to the core function `get_option`. Use the core function instead.

**Comment by Jaspervv** [comment]
Thanks for the quick answer (:

**Comment by Jaspervv** [comment]
I just want to add to this that I couldn't find my field because I forgot the prefix.
By default fields have a prefix of `th_`, which can be changed with the `->setPrefix(string $prefix)` method.

The following DID work for me:
```php
$my_field = get_option('th_my-field');
```
