### ISSUE TITLE
Lacks in the documentation of version 2.0

### ISSUE THREAD

**Issue by lukogites** [themosis/framework#586]
In the documentation for version 1.3 it is clearly written in which files to register, e.g. Post types. In the documentation for 2.0, it registers in a different way, but I have not found a statement in which file to do it.
Any explanation?

**Comment by Jaspervv** [comment]
You could do it from anywhere but the best place would be in the `./app/hooks` folder,  hookable classes are triggered when the WordPress hook API is loaded.

hooks have to be registered in the `./config/app.php` file, in the `hooks` array.

Here is an example file:
```php
<?php
// ./app/hooks/FAQ.php
namespace App\Hooks;

use Themosis\Hook\Hookable;
use Themosis\Support\Facades\PostType;


/**
 * Frequently Asked Questions Post Type
 */
class FAQ extends Hookable
{
    /**
     * register hook
     *
     * @return void
     */
    public function register()
    {
        PostType::make('faqs', 'questions', 'question')
            ->setArguments(
            [
                'menu_position' => 5,
                'menu_icon' => 'dashicons-editor-help',
                'public' => true,
                'hierarchical' => false,
                'has_archive' => true,
            ])
            ->set();
    }
}
```

And of course don't forget to register it:
```php
// ./config/app.php
...
    'hooks' => [
        App\Hooks\Application::class,
        App\Hooks\Compat::class,
        App\Hooks\Mail::class,  
        App\Hooks\Widgets::class,
        App\Hooks\FAQ::class,
    ],
...
```

**Comment by lukogites** [comment]
I didn't find that explanation in documentation. Thanks a lot!

**Comment by jlambe** [comment]
@lukogites Yes it is actually missing, just briefly mentionned on the new architecture page with the list of directories. You can also generate Hookable class from the new CLI tool like so:

```bash
php console make:hook Faq
```

The command will generate the class for you so you only have to register it inside the `app.php` config file.

**Comment by lukogites** [comment]
I haven't found much information about the new CLI in the documentation either :)
To be honest, I really like your project. I hope that with the release of stable version 2.0 everything will be clearer :)

**Comment by jlambe** [comment]
Yes documentation will be completed with the stable release. I also share information through the Twitter account when a documentation is updated, you should definitely follow us: https://twitter.com/Themosis

Also now, there is a blog where I'll share articles about the framework, this month is a tour of coming features with 2.0 release, you may find more information: https://blog.themosis.com/2019/02/06/state-of-the-themosis-framework/

Finally, if you want to always get notified about framework updates, you can subscribe to our newsletter as well: https://framework.themosis.com/
