### ISSUE TITLE
View Priority (Plugins & Themes)

### ISSUE THREAD

**Issue by Jaspervv** [themosis/framework#594]
## Currently, plugin views have priority over theme views
With "priority" I mean if both your plugin and theme have a `footer.blade.php`, and you `@include('footer')`, it will load the one from the plugin.

**Could we change this?**  
I personally believe themes should have priority over plugins, this would allow you to download plugins and override one of their views if you wish to.

## Why don't themes have priority?
Currently plugins are being registered before a theme is loaded, themes views are also registered using [`->addLocation()`](https://github.com/themosis/framework/blob/806b2b7a4ff058f1a6e92c6e0f73cee42f29ba31/src/Core/ThemeManager.php#L250), adding them at the end of the views location list.

**How could we solve this?**  
You could solve this by replacing the below line in [ThemeManager.php](https://github.com/themosis/framework/blob/806b2b7a4ff058f1a6e92c6e0f73cee42f29ba31/src/Core/ThemeManager.php#L250):
```php
$factory->addLocation($uri);
```
with:
```php
$factory->getFinder()->prependLocation($uri);
```

**Comment by jlambe** [comment]
Strange as I was sure theme has already a priority as they are the last one to register their views directory. I'll take a look at your PR, thanks again ;)

**Comment by Jaspervv** [comment]
[`Illuminate/View/FileViewFinder->findInPaths`](https://github.com/laravel/framework/blob/d4f89f9ca33c70672b0c5eeb0f9523a557841e69/src/Illuminate/View/FileViewFinder.php#L127) method loops through the paths array.
If the theme is registered last, it's location will be put at the end of the array, causing it to get checked last.

That's why using the `prependLocation` method would solve the issue, since it would put the theme's location at the start of the array, causing it to get checked first. :slightly_smiling_face:
