### ISSUE TITLE
Compatibility with Elementor plugin

### ISSUE THREAD

**Issue by nsorosac** [themosis/framework#597]
Hi! Elementor plugin doesn't seem to work when used with Themosis Theme (just in case: Elementor is a well-known and widely-used page builder).

We tried to do a fresh install of themosis 1.3.2 following your documentation, then we installed elementor with `wp plugin install elementor --activate`

In WP admin, we create a new page and choose to edit with Elementor. It launches Elementor editor, failing with this message: 

![image](https://user-images.githubusercontent.com/54878/52964825-a4423900-33a3-11e9-8c58-c5b1fc62c215.png)

If you follow the "learn more" link, you just end up with the usual "disable theme/plugin/whatever" help.

FYI, when the editor is launching, the URL looks like http://domain.tld/cms/wp-admin/post.php?post=5&action=elementor

**Comment by jlambe** [comment]
Can you inspect the administration html, there is probably an error report displayed inside the main `wrap` div element ?

Also, as it seems to be a JS application, perhaps looks on the network tab to see if there are any response with errors on Ajax requests.

Also, can you try to disable the framework error reporting by setting the constant `THEMOSIS_ERROR` to `false` inside your `config/environments/local.php` file (at application root). The framework is catching more errors than WordPress in general and convert them to Exceptions which stop the php process. There might be a bug inside the Elementor plugin.

**Comment by nsorosac** [comment]
Thanks @jlambe for your help.

I disabled debug info from the local environment file, and checked the HTML and Ajax output, but nothing else than "HTTP 200".

I only saw a request to http://domain.tld/test-elementor/?elementor-preview=5&ver=1550509046 (_test-elementor_ is the slug of the page ID 5), which leads to an empty page: 

- Request URL: http://domain.tld/test-elementor/?elementor-preview=5&ver=1550509046
- Status Code: 200 OK
- Content-Length: 0

Maybe something to do with the router?

**Comment by jlambe** [comment]
Not sure to understand, is the editing done inside the WordPress administration or does the plugin load the page front-end request (like the customizer) and display its editing tools there ?

**Comment by nsorosac** [comment]
The editor is loading in the administration, but it loads the front-end in an iframe (like the cutomizer).

**Comment by jlambe** [comment]
How are your routes defined? For example, if your editing a WordPress page, your route should probably handle POST request as well. You define your route like one of the following:

```php
Route::any('page', function () {
    // return your view...
});

// or

Route::match(['get', 'post'], 'page', function () {
    // ...
});
```

**Comment by nsorosac** [comment]
Thanks @jlambe 

It worked perfectly!
