### ISSUE TITLE
[SUGGESTION] Filter support for Hookables

### ISSUE THREAD

**Issue by Jaspervv** [themosis/framework#599]
## Current situation
Currently the [Hookable class](https://github.com/themosis/framework/blob/e23b46f78057b38a3827166103b7dd7429a7e8af/src/Hook/Hookable.php) gets registered by the [Application class](https://github.com/themosis/framework/blob/e23b46f78057b38a3827166103b7dd7429a7e8af/src/Core/Application.php#L1242) as an action, It will run the `register()` method on the given `$hooks` with the given `$priority`.

## Problem
There's no way to register the hook as a Filter hook. Right now the way around this is by just using the `Filter` class in the `register()` yourself, but I think this could be cleaner.

## Suggestion
It would be useful if there was a way to define your Hook to be a filter hook, instead of an action hook.
Maybe with a new class property `$type` which defaults as `'action'`.

**Comment by jlambe** [comment]
This could be a nice feature we can check on. 👍

**Comment by ogorzalka** [comment]
Hi,

Well, basically, action use filter method. So it's already working. An example : 

```
<?php

namespace App\Hooks;

use Themosis\Hook\Hookable;

class TitleHook extends Hookable
{
    public $hook = 'the_title';

    public function register($title)
    {
        return "Title : {$title}";
    }
}
```
Maybe there are some specific cases ?

**Comment by jlambe** [comment]
I totally forgot that filters use the same API 🤦‍♂️ Thanks @ogorzalka for pointing this. There are no specific cases, is just that that you can omit the `$hook` property and it that case, the `register()` method will be called at the `mu-plugins` lifecycle level. 

I'm just wondering if we should be more strict or provide a class name that is more constrained by throwing an error if omitting the hook property... 

By it could also be just a naming convention, like providing the `Action` or `Filter` suffix to the hook class names to help visualize the intent:

```php
class TitleFilter extends Hookable {}

class RegisterBookPostTypeAction extends Hookable {}
```

FYI @Jaspervv .

I'm gonna let this issue open for more thought...

**Comment by jlambe** [comment]
I've decided to leave the Hookable API as is for our next release. I like the idea of being more specific on what the `register` method is supposed to return: `void` for an action, `mixed` ? in the case of a filter ??

So for now, I don't want to introduce a breaking change on this API. This might change for another major release though. 

My advice would be clearly specify the intent of the class by suffixing it with `Action` or `Filter` and return something or not accordingly.
