### ISSUE TITLE
[Question] Is there any procedure for migrating from legacy wordpress to themosis?

### ISSUE THREAD

**Issue by FlickTheManual** [themosis/framework#601]
Hello here,

like I said before, great work :grinning: 

I would have liked to know if there would be any documentation on migrating from a standard wordpress site to themosis 1.3+ ? I looked through your entire repository but found nothing about it.

As I'm becoming a fan of your framework, I would have liked to migrate my entire wordpress sites to themosis.

Thank you in advance for your answer :smile:

**Comment by jlambe** [comment]
No specific procedure. Compared to a classic WordPress, it's a matter of moving files from your theme to appropriate views, define necessary routes. For plugins, simply move them into the `content/plugins` folder.

**Comment by FlickTheManual** [comment]
Ok thank you so much i'll try it and report it another time, thanks for all
team

Le ven. 22 févr. 2019 à 18:24, Julien Lambé <notifications@github.com> a
écrit :
