### ISSUE TITLE
[ERROR] Unresolvable dependency

### ISSUE THREAD

**Issue by Jaspervv** [themosis/framework#606]
### Problem
After setting up a new project I got the following error:
```
Unresolvable dependency resolving [Parameter #0 [ <required> $app ]] in class Illuminate\Support\Manager
```
After reviewing the [full stacktrace](https://www.codepile.net/pile/b8lm4Yxj) I found out the dependency it can't resolve is the `NotificationServiceProvider`.

### Fix
I found a [laravel issue](https://github.com/laravel/framework/issues/26766) which provided the simple solution of registering the `NotificationServiceProvider`.  
I went into the `themosis/framework/src/Application.php` and added the following code to the `registerBaseServiceProviders` method:
```php
 $this->register(new \Illuminate\Notifications\NotificationServiceProvider($this));
```
which fixed it.

**Comment by jlambe** [comment]
Normally adding it to your `config/app.php` file should work. Have you tried ?

**Comment by Jaspervv** [comment]
This fixes it as well. (: 
So this should be added to _themosis/themosis_'s `config/app.php` by default? It seems like a requirement

**Comment by jlambe** [comment]
Yes, I have to check all dependencies for next beta release. As I've worked on the `illuminate/auth` implementation, the Notification service provider is requirement.

**Comment by jlambe** [comment]
I'm closing this issue while I'm preparing the last beta release.
