### ISSUE TITLE
Cannot add custom fields to Taxonomy

### ISSUE THREAD

**Issue by ntsim** [themosis/framework#612]
The documentation [here](https://framework.themosis.com/docs/master/taxonomy/#term-custom-fields) suggests that we can add custom fields to Taxonomies using the `addFields` method.

When you try to do so in `2.0-beta3`, it currently throws as it is an undefined method on `Taxonomy`. 
Looking at the source, it appears like this would also happen with the `sanitize` method as well.

**Comment by jlambe** [comment]
@ntsim Taxonomy fields are not yet available on beta3 release. The upcoming `beta4` release will support term and user fields.

**Comment by ntsim** [comment]
Nice one thanks for clearing that up! Look forward to beta4 :smile:

**Comment by Tronix117** [comment]
Yep, really need the TaxField feature working too :/

I tried this way:
```
TaxField::make('product-types')->set([
      \Field::text('region', [
        'name' => 'Région',
        'info' => 'indo'
      ]),
    ]);
```
 it correctly add the field on the creation form, but the edit page is broken with this error:
```
 FatalThrowableError (E_RECOVERABLE_ERROR)
Argument 1 passed to Themosis\Taxonomy\TaxField::editFields() must be an instance of stdClass, instance of WP_Term given, called in htdocs/cms/wp-includes/class-wp-hook.php on line 288
```

Any idea when this will be working ?

**Comment by Jaspervv** [comment]
I believe these issues are related: #616 #605 

`RC1` just released, I assume there will be no `beta4` anymore?

-----

If you really need custom fields **>now<** you could use the WordPress Plugin [Advanced Custom Fields](https://www.advancedcustomfields.com/).  
Which allows you to create fields like taxonomies using json, their own editor in the WP dashboard or PHP:
```php
acf_add_local_field_group(
[
    'key' => 'group_5c878e892ab61',
    'title' => 'Taxonomy In Post',
    'fields' =>
    [
        [
            'key' => 'field_5c878e8f7826f',
            'label' => 'My Taxonomy',
            'name' => 'my_taxonomy',
            'type' => 'taxonomy',
            'taxonomy' => 'category',
            'field_type' => 'checkbox',
            'add_term' => 1,
            'return_format' => 'id',
        ],
    ],
    'location' =>
    [[[
        'param' => 'post_type',
        'operator' => '==',
        'value' => 'post',
    ]]]
]);

```

**Comment by jlambe** [comment]
Term custom fields is available on the `master` branch and coming release candidate. More information soon on the new API as I still need a bit of time to write the new documentation.

**Comment by Tronix117** [comment]
On the beta.3 there was some issues on this part:

* the $term is not an stdClass, so there was an error within the `editFields` method, a cast to (object) solves the issue here, but it's quick'n'dirty.
* there was an issue in the `parse` method logic, preventing multiple tax fields on the same taxonomy

I patched everything, and don't have time to check that right now, but if it's fixed it's a great news !

**Comment by ntsim** [comment]
Thanks @jlambe. I'll consider this one resolved :smile:
