### ISSUE TITLE
Translation for PostType and Taxonomy labels

### ISSUE THREAD

**Issue by arjendejong12** [themosis/framework#617]
Hey, is it possible to provide translations for the labels in custom post types and taxonomies, so that we won't have to provide translations for every custom post type or taxonomy we register?
I saw #277, where you removed these translations. Would it be possible to restore them?

**Comment by jlambe** [comment]
Well it was the basically the original idea but because we always had to change labels because defaults never fit, I removed them.

If you have ideas to enhance this, we're open to any suggestion ;)

**Comment by arjendejong12** [comment]
Why did you have to change the defaults?
We currently use the below function and haven't had to change the defaults yet:
```php
    function getDefaultTaxonomyLabels($singular, $plural)
    {
        return [
            "menu_name" => $plural,
            "all_items" => sprintf( __( "All %s", WP_SOUP ), $plural ),
            "edit_item" => sprintf( __( "Edit %s", WP_SOUP ), $singular ),
            "view_item" => sprintf( __( "View %s", WP_SOUP ), $singular ),
            "update_item" => sprintf( __( "Update %s", WP_SOUP ), $singular ),
            "add_new_item" => sprintf( __( "Add New %s", WP_SOUP ), $singular ),
            "new_item_name" => sprintf( __( "New %s", WP_SOUP ), $singular ),
            "parent_item" => sprintf( __( "Parent %s", WP_SOUP ), $singular ),
            "parent_item_colon" => sprintf( __( "Parent %s:", WP_SOUP ), $singular ),
            "search_items" => sprintf( __( "Search %s", WP_SOUP ), $plural ),
            "popular_items" => sprintf( __( "Popular %s", WP_SOUP ), $plural ),
            "separate_items_with_commas" => sprintf( __( "Separate %s with commas", WP_SOUP ), $plural ),
            "add_or_remove_items" => sprintf( __( "Add or remove %s", WP_SOUP ), $plural ),
            "choose_from_most_used" => sprintf( __( "Choose from the most used %s", WP_SOUP ), $plural ),
            "not_found" => sprintf( __( "No %s found", WP_SOUP ), $singular ),
            "no_terms" => sprintf( __( "No %s", WP_SOUP ), $plural ),
            "items_list_navigation" => sprintf( __( "%s list navigation", WP_SOUP ), $plural ),
            "items_list" => sprintf( __( "%s list", WP_SOUP ), $plural ),
        ];
    }
```
Which we use like this:
```php
$singular = __( "Word", WP_SOUP );
$plural = __( "Words", WP_SOUP );

Taxonomy::make('taxonomy_id', $singular, $plural)
    ->setLabels( getDefaultTaxonomyLabels( $singular, $plural ) )
```
This way we still translate the **singular** and **plural** individually.

**Comment by jlambe** [comment]
They never fit on all projects we built as we were always defining all labels all over again for specific cases. Plus there was an issue regarding the translations because defaults used framework textdomain and translations couldn't be loaded without overwriting framework translations files per project so in the end we had to pass all labels with project textdomain so we can handle translations from the plugin instead.
