### ISSUE TITLE
@auth and @guest directives

### ISSUE THREAD

**Issue by Jaspervv** [themosis/framework#618]
## @auth and @guest
Laravel Blade provides the following directives:
```blade
@auth
    // The user is authenticated...
@endauth

@guest
    // The user is not authenticated...
@endguest
```
These don't work because they use `auth()->guard()->check()` and `auth()->guard()->guest()`.
Would love to see these overwritten with directives that work with the WordPress users.

### Possible code
Checking if someone is logged in could be done using a WordPress function:
```php
if( is_user_logged_in() )
{
    // logged in
}
```

## @auth() and @guest()
Laravel Blade also lets you enter a parameter to check if the user passes a specific authentication guard like so:
```blade
@auth('admin')
    // The user is authenticated...
@endauth

@guest('admin')
    // The user is not authenticated...
@endguest
```
Maybe we could replace this to check if the user has a specific capability.
### Possible Code
This can be done with the new User Facade like so:
```php
use Themosis\Support\Facades\User;
if( User::current()->can($cap) )
{
    // user has capability
}
```

**Comment by Jaspervv** [comment]
That'd be cool as well. Maybe something like
```blade
{{-- capability check --}}
@can('edit_posts')
@endcan

{{-- role check --}}
@hasrole('Administrator')
@endhasrole
```

**Comment by jlambe** [comment]
The role directive can be simplified I think:

```php
@role('Administrator')
@endrole
```

**Comment by Jaspervv** [comment]
yeah I like `@role` a lot better. (:

Any idea on what to name the `logged-in` & `not logged-in` one?

**Comment by jlambe** [comment]
Perhaps this:

```php
@loggedin
@else
@endloggedin
```

Not sure yet how to implement an `else` directive for custom ones.

**Comment by Jaspervv** [comment]
```blade
@else
```
translates to:
```php
<?php else: ?>
```
Therefor it should work with any `if` directive as long as you define the if statement with a colon instead of a bracket.

for example this:
```blade
@loggedin
    I am logged in
@else
    I am a guest
@endloggedin
```
Would translate to:
```php
<?php if( is_user_logged_in() ): ?>
    I am logged in
<?php else: ?>
   I am a guest
<?php endif; ?>
```

**Comment by Jaspervv** [comment]
We would probably still want a `@loggedout` directive or something. Else if you want something just for guests you'd have to use the else statement
```blade
@loggedin
@else
You are a guest :)
@endloggedin
```
vs
```blade
@loggedout
You are a guest (:
@endloggedout
