### ISSUE TITLE
[QUESTION] Why are directory names used for plugin IDs?

### ISSUE THREAD

**Issue by Jaspervv** [themosis/framework#620]
### Current situation
Currently the plugins get loaded into the Application with their directory as identifier.  
For example if my plugin's directory is named `my-plugin`, then it can be accessed through the application with that as it's ID (which is hella cool):
```php
app('wp.plugin.my-plugin')
```

### Problem
However if our plugin is downloaded with a different directory name, it breaks the plugin because it's part of the logic. Wouldn't it be better to, for example, use the **Plugin Prefix** (an unique constant in the headers)?  

The constant used for the ID of plugins, is something outside of the plugin's control, since an user can name the directory anything.

**Comment by jlambe** [comment]
Good point! Perhaps we can look at existing plugin headers if one may fit or perhaps introduce a new one for this purpose.

For example, the plugin text domain is a constant one but perhaps it can be confused for people.

**Comment by Jaspervv** [comment]
Glad to hear you agree (:  

Plugin **text domain** seem like the best candidate from the existing headers, it already has to be unique, and it uses the `plugin-name` by default.  
I also don't see why one would need a different `text_domain` and `plugin_id`.  

However a new separate header would make it a lot more clear, especially for users familiar with WordPress, they have the expectation of the text domain to just be a text domain.  

I think defining a new header is best, but having it defaulted to the `plugin-name`.

**Comment by jlambe** [comment]
I've just fixed this and define a `Plugin ID` header which takes the plugin name as a value upon installation. I thought it was better to have this fixed before announcing a stable release of the framework 😄 @Jaspervv
