### ISSUE TITLE
WordPress scheduled posts

### ISSUE THREAD

**Issue by jlambe** [themosis/framework#624]
Now that the WordPress cron is disabled by default on new applications, the WordPress default scheduled post feature is deactivated.

Let's look at a console command we can define into the new application tasks scheduler.

**Comment by pagegwood** [comment]
Hey @jlambe I just realized that WP-Cron wasn't disabled by default on a themosis project that we just launched. I searched the Themosis repo and can't find anything that disabled cron: https://github.com/themosis/themosis/search?q=DISABLE_WP_CRON&unscoped_q=DISABLE_WP_CRON

Am I mis-interpreting what you have listed above regarding WordPress cron being disabled by default?

As always, thanks for your great work on Themosis :)

**Comment by jlambe** [comment]
@pagegwood Indeed, I planned it but it is not yet defined in the configuration. A mistake of mine :) If you need to disable it, I suggest you to add the constant definition inside the `config/wordpress.php` file as this is where it is going to be added anyway.

**Comment by jlambe** [comment]
@pagegwood WordPress functions are now supported in custom commands and cron is now disabled by default on the upcoming release in order to leverage the Laravel Artisan tasks scheduler. A `publish:future-posts` command has been added and already programmed to run twice daily in order to publish any scheduled posts for the day (each application instance can change the scheduler frequency as needed). Thanks for your contribution.
