### ISSUE TITLE
Select Field not working

### ISSUE THREAD

**Issue by msufiannasir** [themosis/framework#625]
I am trying to create a select field but it's throwing an error that "select function is not defined". I try to debug it and found in 2.0 version select is replaced with the "choice" method. I have also checked the documentation but can't find the documentation of the choice field seems like the broken part on 2.0 documentation see screenshot http://prntscr.com/mxwqqo

**Comment by jlambe** [comment]
@msufiannasir The documentation has just been updated early today regarding the fields. Try to refresh the page and reset cache. Here is the link to the choice field documentation: https://framework.themosis.com/docs/2.0/field/#choice-field

**Comment by msufiannasir** [comment]
Yes. It's updated and working now thanks
