### ISSUE TITLE
Directory without php file in mu-plugins will broke the loading

### ISSUE THREAD

**Issue by antoscarface** [themosis/framework#628]
If I have a directory inside the `mu-plugins` folder that doesn't contain any PHP file (but only other directories), the framework tries to load it but anything will be added inside the manifest and the site will throw the exception `FatalErrorException`:

`Themosis\Core\Application::registerPlugin(): Failed opening required '/var/www/html/web/wp-content/mu-plugins/kinsta-mu-plugins/' (include_path='.:/usr/local/lib/php')`

This configuration might happen when you have a mu-plugin loaded by its main file that include inside some other php files inside a specific directory. In WordPress it's legit, but the autoloader of the framework is broking this.

**Comment by jlambe** [comment]
PR merged. Thanks for the feedback. Sounds good for me to not force the load of any found directories if main plugin file is missing.
