### ISSUE TITLE
Error page views don't resolve correctly

### ISSUE THREAD

**Issue by ntsim** [themosis/framework#641]
The Themosis theme includes a 404 view, but from what I have seen this doesn't seem to actually be the resolved view when there is a 404. Instead, the default Laravel 404 page is shown instead. A similar thing occurs with other status codes.

This seems to be due to how `Themosis\Core\Exceptions\Handler` implements its `renderHttpException`, which appears to only be looking inside of the root-level view directory (rather than including the theme).

To workaround this, I have included the theme's view directory in the `views` config:

```
'paths' => [
    resource_path('views'),
    themes_path('my-theme/views')
]
```

However, I'm not sure this is the correct way of dealing with this issue as the view resolver is normally able to resolve views from the theme without needing to specify this extra path.

**Comment by jlambe** [comment]
No it's not. The default `404` view file provided by the theme is only there if you want to define a `Route::callback()` in your application.

Otherwise, default Laravel errors views are used and indeed it is handled by the exception handler class. But you can customize the default errors views provided:
- https://framework.themosis.com/docs/2.0/errors/#custom-http-error-pages

Basically you extract core views to the `resources/views/errors` directory of your application and define them there. The `php console vendor:publish --tag=themosis-errors` command extract them for you.

**Comment by ntsim** [comment]
Thanks @jlambe, I think I get where you're coming from, but it seems a little counter-intuitive to me to have error views in the root-level views directory. 

For example, I want to re-use my theme's main layout, which resides in my theme's view directory. To do this my root-level error page has to assume there is a layout existing called 'main' (or whatever) in the theme. However, this doesn't seem like it would always make sense to assume (if you were to swap out themes for example). Surely keeping related views closer together is better?

Sorry if I am getting the wrong end of the stick here. Perhaps it is because I'm not really using any views at the root-level for my project.

On a side note:

- Running `php console vendor:publish --tag=themosis-errors` seems to do nothing for me, not sure why. I have already published Larvel's email templates if that helps.

- The error page documentation (and other docs) suggest that Laravel helpers like `abort` seem to be in scope, however they don't seem to be. I am using the most recent release - 2.0.

**Comment by jlambe** [comment]
Views from your theme are available at the root level as well. You can clearly update the root error view file and change the call to the layout view to yours.

Also, the code is looking after a view namespace of `errors`. I haven't tested this but normally you can define an `errors` directory inside your theme `views` folder and place the different errors views there so everything is running inside your theme.

The console command was added only on the `2.0.0` release. Perhaps you can add the `--force` option to the command call:

```bash
php console vendor:publish --tag=themosis-errors --force
```

**Comment by ntsim** [comment]
> Also, the code is looking after a view namespace of errors. I haven't tested this but normally you can define an errors directory inside your theme views folder and place the different errors views there so everything is running inside your theme.

From what I've seen, defining a `my-theme/views/errors` directory and placing error pages in there doesn't work (it's the reason for this issue).

> The console command was added only on the 2.0.0 release. Perhaps you can add the --force option to the command call:

Adding `--force` doesn't seem to do anything unfortunately :disappointed:

**Comment by jlambe** [comment]
I'm going to look at this and update the framework to solve this issue. I'll come back to you.

As a temporary solution, I can suggest you to define the following route and return your custom error view:

```php
Route::get('fallback', function () {
    return view('errors.custom);
});
```

Set the route as the last one inside your `routes/web.php` file and work your view from the theme.

**Comment by jlambe** [comment]
@ntsim An upcoming fix is coming for this. Just note that if an exception is triggered very early in the process, before theme views could be registered, the exception handler will fallback on core errors views instead.
