### ISSUE TITLE
Session Handling problem.

### ISSUE THREAD

**Issue by maximusblade** [themosis/framework#645]
Hey
I seem to have a problem with Session Handling.
Sessions don't seem to be persistent.

Is there perhaps a step or setting I'm missing?

I have 2 routes 1 controller.
One route is to set a session value
the second is to get a the session values.

Any help here would be great .

```
    Route::get('getsession', 'SandboxController@get_session');
    Route::get('setsession', 'SandboxController@set_session');
```

controller::
```
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;


class SandboxController extends Controller
{
    public function set_session(Request $request)
    {

        $request->session()->put('session_key', "session value");

        dd($request->session()->all() );

    }

    public function get_session(Request $request){
        print 'List All Session Values <br />';

        dd($request->session()->all() ); // no session_key listed

    }

}   

```

**Comment by maximusblade** [comment]
Update on this.

I think i was going about this the wrong way.

I decided to move my session setting to the Theme.
this seems to be working as expected.

**Comment by jlambe** [comment]
@maximusblade Hmm this is still strange, let's keep the issue open because a session is initialized before hitting a controller method so it should work.

Have you try to use the `session()` function helper directly instead of the request method ?

**Comment by maximusblade** [comment]
It is strange indeed.
I shall investigate this further and provide some feedback.

**Comment by jlambe** [comment]
@maximusblade I've juste tested this on current release and the session is working as expected with default session driver set to `file`.

I've defined 2 routes like yours and set the session from a controller stored in the `app/Http/Controllers` directory.

I've also tested with a middleware and the session value is correctly stored. Note that I have to manually register the middleware inside the kernel class within the `web` middleware group and put it as the last item on the list.

Do you find the session files inside the `storage/framework/sessions` directory ? Do you use another driver ?

**Comment by jlambe** [comment]
Here is the code for the routes I tested:

```php
Route::get('session/set', 'SessionTestController@set');
Route::get('session/get', 'SessionTestController@get');
```

The controller:

```php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class SessionTestController extends Controller
{
    public function set(Request $request)
    {
        $request->session()->put('session_key', 'session value');

        return 'Set session...';
    }

    public function get(Request $request)
    {
        $values = $request->session()->all();

        dump($values);

        return 'Get session values...';
    }
}
```

The middleware:

```php
<?php

namespace App\Http\Middleware;

use Closure;

class CustomSessionTest
{
    /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Closure  $next
     * @return mixed
     */
    public function handle($request, Closure $next)
    {
        $request->session()->put('middleware', 'themosis');

        return $next($request);
    }
}
```

If I visit the session get route defined above, all session data is retrieved.

**Comment by maximusblade** [comment]
@jlambe I've have just tried this out of the box and it works.
There must have been something I was missing.
Issue resolved.

**Comment by jlambe** [comment]
@maximusblade Glad it works on your side too 👍
