### ISSUE TITLE
Unable to create dashboard page with custom view

### ISSUE THREAD

**Issue by Jaspervv** [themosis/framework#652]
### Goal
I'm trying to create a dashboard page with a custom view.

### Attempt
My code:
```php
use Themosis\Support\Facades\Page;

$page = Page::make('marginals', 'Marginals')
    ->set();

$page->route('/', function()
{
    dd('Reached page');
    return view('pages.admin.marginals');
});
```

### Result
Now the page does show in the admin and links to `/cms/admin.php?page=marginals` (as expected).
But when I visit it it shows a `404` page.

**Comment by jlambe** [comment]
@Jaspervv Weird, I've just tested it and it works (version 2.0.1). The `dd` function kills the process, I suppose you let it in your example for test.

Here is my code, similar to yours except the name of the view (see screenshot below):

```php
$page = Page::make('marginals', 'Marginals')
            ->set();

$page->route('/', function () {
    return view('admin.test');
});
```

Where have you defined your code ?

<img width="606" alt="page_test" src="https://user-images.githubusercontent.com/1917490/56150986-772f9280-5fb0-11e9-8f04-7029af72fc12.png">

**Comment by Jaspervv** [comment]
The version of the framework was the problem, our sites were still on commit 5a4cab98dbc63da69ba01b3050ac2b22c79ee698.  
I thought this wouldn't be in issue since I saw that `Themosis\Page\*` hadn't been updated in two months, but updating to the latest version fixed the issue.

Thanks for testing it out to ensure it works :)

**Comment by jlambe** [comment]
Well I'm glad your issue is solved 👍
