### ISSUE TITLE
Dynamic/Wildcard routing

### ISSUE THREAD

**Issue by ramon-villain** [themosis/framework#66]
I still don't understand how we work with wildcard in this Route class. Seems more complicated than the Laravel's way.

So instead of dynamic slug/permalink we've to add every post? For example, I created a 'buildings' post-type, and I want to have a 'buildings' page (ex: http://site/buildings), that will list all of my buildings (I suppose this is an ArchiveType), and a building page (ex: http://site/buildings/example), loading the specific content for that building, how we do this?

**Comment by xyNNN** [comment]
When I try to implement a dynamic route like `Route::get('profil/{username}', 'UserController@profile')->name('user.profile');` it resolves to the specified action without any problem but the page title is "Page not found" which is the default behaviour of WordPress that this is a 404 page. 

How can I solve this? 
Thanks in advance!

**Comment by jlambe** [comment]
@xyNNN Hello, please open your own issue so we can better track it the next time. To solve your problem, you can use the `document_title_parts` filter from your controller method:

```php
Filter::add('document_title_parts', function ($parts) {
    $parts['title'] = __('Your Custom Page Title', APP_TD);
    return $parts;
});
```

You can call this from from the controller method. I generally put this in a trait.

**Comment by xyNNN** [comment]
sorry @jlambe - next Time I will create a separate issue for better tracking, sure! Thanks mate, but this hint works perfectly :) 

Where do you think we can add this piece of useful information in the documentation? Perhaps we put this into the Controller part? If you agree I would prepare some pull request in the documentation repository.

**Comment by jlambe** [comment]
@xyNNN The route documentation could be a better place I think as the filter can be run from a closure as well. Thank you for proposing a PR on the docs 👏 Make sure to send a PR against the `2.0` branch ;)

**Comment by xyNNN** [comment]
By the way ... How do you solve it when you mean that you will implement this feature in a trait?

**Comment by xyNNN** [comment]
https://github.com/themosis/documentation/pull/80

Wish you a nice weekend! 
xyNNN
