### ISSUE TITLE
Weglot + Themosis for translation

### ISSUE THREAD

**Issue by Jaspervv** [themosis/framework#660]
Has anyone ever got [Weglot](weglot.com) working with Themosis?
Weglot has both a package for implementation [with Laravel](https://github.com/weglot/translate-laravel) and [with WordPress](https://github.com/weglot/translate-wordpress).

## Laravel Package
With the Laravel package [weglot/translate-laravel](https://github.com/weglot/translate-laravel), none of the content seems to translate for me.  
If I try to render a weglot button with `{{ weglotButtonRender(1) }}`, I get a `route [] not defined` error.  

If you look in their [source code](https://github.com/weglot/translate-laravel/blob/43becc8d5195f190b6cdb30cfcb88485f7b5600b/src/Providers/RouterServiceProvider.php#L24) you can see they loop through the languages, and generate new routes with the language prefix.  For example if you have a route with `/login` they would create new routes with `/en/login` and `/nl/login`.
I'm not sure how this would work (and if this would work) with Themosis's implementation. I personally have no knowledge on how the Themosis WordPress routes work but the issue seems to lie somewhere within the routing.

## WordPress package
After little success with the Laravel package I tried the Wordpress plugin, which can be found on [wordpress.org](https://wordpress.org/plugins/weglot/) or on [GitHub](https://github.com/weglot/translate-wordpress).
Enabling the plugin doesn't cause any errors, I can even show the button by placing `<div id="weglot_here"></div>` in our site.

However, when I try to switch language, it seems to simply add the country code to the URL which just throws a 404. For example if I'm on `localhost/contact` and switch to English it redirects to `localhost/en/contact`, which of course doesn't exist.

**Comment by Jaspervv** [comment]
Weird stuff. Locally I can not get this to work, nor on the staging environment.
But on the production environment the translation actually works using the plugin :confused:  _(except on a multisite setup)_

Honestly the only difference I can think of between the staging and production env is that production runs on `https`.

**Comment by jlambe** [comment]
@Jaspervv I've never worked with weglot but by default I would recommend to work with the WordPress plugin.

Probably that the plugin is adding new rewrite rules on activation. Perhaps flushing the permalink might help. Also I would suggest to define routes using the `any` method as it is the default WordPress behavior.

**Comment by Jaspervv** [comment]
From our tests Weglot translation works fine with the plugin. It didn't work before because of our Weglot settings.
