### ISSUE TITLE
Having problems when installing laravel wallet

### ISSUE THREAD

**Issue by rovillesarate** [themosis/framework#663]
Hi! I am trying to include the laravel wallet package to themosis but i am encountering errors due to Vendor/Illuminate folder being deleted when i do composer req bavix/laravel-wallet.

**Comment by jlambe** [comment]
Well I don't know the `bavix/laravel-wallet` package but it is definitely strange that it removes the `illuminate` directory from the dependencies. Sounds like you should avoid the package or perhaps contact its author as it does not relate to Themosis.
