### ISSUE TITLE
Cocher un Field::checkbox par défaut

### ISSUE THREAD

**Issue by dimitriBouteille** [themosis/framework#666]
Je voulais savoir s'il est possible de cocher un champ checkbox par défaut ?

J'ai testé 2/3 trucs mais sans succès :/

```php
Field::checkbox('delete', [
    'data' => true,
];

Field::checkbox('delete', [
    'data' => 'on',
];

Field::checkbox('delete', [
    'attributes' => ['checked']
];
```

**Comment by jlambe** [comment]
Normalement en placant `on` ou `true` comme valeur par défaut via la propriété `data` aurait dû fonctionner. Il est possible qu'il y ait une erreur ?

Pourrais-tu me fournir un context sur l'utilisation du champs "checkbox", est-ce sur une utilisation au niveau d'un formulaire au niveau du front-end ou depuis une metabox, page d'options ?

**Comment by dimitriBouteille** [comment]
Dans le cas de l'utilisation avec `true` :

```php
Field::checkbox('delete', [
    'label' => 'mon label',
    'data' => true,
])
```

j'ai effectivement une erreur : `A string value is expected.` qui provient de `Forms\Transformers\StringToBooleanTransformer.php`

Avec `on` il n'y a aucune erreur, cependant le code généré place le `on` dans l'attribute `value` du champ :

```html
<input id="th_delete_field" type="checkbox" value="on">
```

J'utilise le champ dans une metabox d'un postType. 

Voici le code simplifié du postType :

```php
namespace App\Hooks\PostType;

class NextTrainings extends Hookable
{

    /**
     * @var string
     */
    public $hook = 'init';

    /**
     * @var string
     */
    public static $_NAME = 'nextTrainings';

    /**
     * Extend WordPress.
     */
    public function register()
    {
        $postType = PostType::make(self::$_NAME, 'Hello', 'Hello')
            ->setLabels([...])
            ->setArguments([...])
            ->set();

        Metabox::make('nextTraining', $postType->getName())
            ->setTitle('Hello')
            ->add(Field::checkbox('delete', [
                'label' => 'My label',
                'data' => 'on',
            ]))
            ->set();
    }
    
}
```

**Comment by jlambe** [comment]
Il y avait bien une erreur de logique au niveau de la récupération des données pour la metabox. Les valeurs acceptées par défaut sont `on`, `yes`, `off`, `no` uniquement. Je me suis trompé en indiquant qu'une valeur booléenne était possible.

Un correctif est en plus sur la branche `2.0` du dépôt si besoin immédiatement. Autrement ce sera disponible sur la version 2.0.2 qui devrait être en place la semaine prochaine normalement.
