### ISSUE TITLE
Field::choice avec clef de type int ne fonctionne pas dans page d'options

### ISSUE THREAD

**Issue by dimitriBouteille** [themosis/framework#668]
Je viens de tester les deux codes suivants : 

Dans un postType : 
```php
Metabox::make('nextTraining', $nextTrainings->getName())
    ->add(Field::choice('training', [
        'label' => 'Formation',
        'choices' => PagesQuery::products()->toArray(),
        'rules' => 'required',
    ]))
  ->set();      
```

Dans une page d'options : 
```php
$page->addSettings([
    'pages' => [
        Field::choice('appJoinUsPageId', [
            'label' => 'Page nous rejoindre',
            'choices' => PagesQuery::pages()->toArray(),
        ]),
    ]
]);
```

Dans le premier cas (pour le postType), le choice fonctionne, sauvegarde le choix et affiche la bonne valeur une fois la page réactualisée.

Dans le second cas (page d'options), le choice fonctionne, sauvegarde le choix mais la valeur n'est pas affichée une fois que la page réactualisée. Visiblement il n'arrive pas ajouter l’attribut `selected` sur la bonne option :( 

Le `toArray()` retourne un tableau du type :

```php
[
    'Page 1' => 30,
    'Page 2' => 623,
    'Page 3' => 5,
]
```

Pour débugguer, j'ai testé de passer le tableau suivant :
```php
[
    'Page 1' => '30',
    'Page 2' => '623',
    'Page 3' => '5',
]
```

et avec ce tableau le choice fonctionne dans les deux cas. 

Est-ce normal que le typage de la valeur pose problème ?

**Comment by jlambe** [comment]
Il semblerait qu'il y ait une erreur de conversion au niveau des pages d'options. Je dois y regarder, il y a vraisemblablement un bug.

**Comment by jlambe** [comment]
@dimitriBouteille Un correctif est dorénavant disponible sur la branche `2.0`.

**Comment by dimitriBouteille** [comment]
@jlambe Merci beaucoup pour le correctif ! Merci également pour la vitesse de réponse :)
