### ISSUE TITLE
Custom Routing for SubMenu Page

### ISSUE THREAD

**Issue by rumur** [themosis/framework#670]
## The Original Issue - https://github.com/themosis/themosis/issues/293

It doesn't work for custom pages when you're trying to use the custom page as a Parent One.

Some Real example:

```php
<?php
/** @var Page $parent_page */
$parent_page = \Page::make('parent-page', __('Parent Settings', APP_TD))->set();

/** @var Page $sub_page */
$sub_page = \Page::make('sub-page-settings', __('Sub Page Settings', APP_TD))
            ->setParent($parent_page->getSlug())
            ->set();

/** @NOTE With Current bug you won't see the custom view !!!  */
$sub_page->route('/', function() {
  return view('replace.with.custom.view');
});

```

### With this bug you won't be able to see the custom view.

Why?

Because: `Themosis\Page\Page::findParentHook` returns `return strtolower($parent->getMenu());`
and in this case it's gonna be `parent settings`, but action for custom routes is listening to `parent-settings`.

### What am I suggesting to do here? 

just return the kebab string `return \Illuminate\Support\Str::kebab(strtolower($parent->getMenu()));`

**Comment by jlambe** [comment]
@rumur The fix is now on the `2.0` stable branch. Thanks for reporting this one 😉
