### ISSUE TITLE
WordpressHeaders Middleware issue

### ISSUE THREAD

**Issue by tipytechnique** [themosis/framework#672]
Hi, i have an issue with the `WordpressHeaders.php` middleware.

I'm using a buyed theme not using the Themosis' structure, so i'm not taking care about all routes.
In this specific case, all Woocommerce's routes are handled by my theme the native way.

But with this piece of code : 
```
public function handle(Request $request, \Closure $next)
    {
        $route = $request->route();
        $response = $next($request);

        if (! $route->hasCondition() && function_exists('is_user_logged_in') && ! is_user_logged_in()) {
            // We're on a custom route. Remove "no-cache" headers added by WordPress:
            // - Cache-Control
            // - Expires
            // - Content-type (provided by the response instance as well)
            @header_remove('Cache-Control');
            @header_remove('Expires');
            @header_remove('Content-Type');
        }

        // Set the response cache control to "public"
        // on pages visited by guest users only.
        if (function_exists('is_user_logged_in') && ! is_user_logged_in()) {
            $response->setPublic();
        }

        return $response;
    }
```

Especially this line : 
`@header_remove('Content-Type');`

When a logged out user try to access the shop page for example, because of the missing header `Content-Type`, browsers set it to `application/octet-stream` and force the download of the page instead of showing it.

For now i just commented the `@header_remove('Content-Type');` to fix this, but there is a better way to solve this without updating your code ?
What is the purpose of this middleware ?

Thx for your time :)

**Comment by jlambe** [comment]
@tipytechnique The middleware is there to fix a general issue with duplicate headers on a default installation with the Themosis theme as we return a Response object instead.

You can remove the middleware in your case. It is defined into the `app/Http/Kernel.php` file under the `web` group. This should fix your issue.

**Comment by tipytechnique** [comment]
Nice that works, thanks for the explanation :)
