### ISSUE TITLE
Metabox Field rules error message not showing up

### ISSUE THREAD

**Issue by cajudayrj** [themosis/framework#673]
I have created a metabox with a field:text that has rules => 'required|email'. The validation works fine but no error message is displaying. Any fix on this? Thanks.

**Comment by jlambe** [comment]
Thanks for reporting the issue. There is indeed an issue with metabox fields validation. If a required field is empty, the metabox should display a "Saved with errors" message and display the error message under the failed field.

Are you up for a PR on this ?

**Comment by jlambe** [comment]
Issue is now fixed and available on the `2.0` branch. Coming on next minor release.

**Comment by cajudayrj** [comment]
Hello, very sorry for the late response. Thanks a lot for the fix! Keep up the good work!
