### ISSUE TITLE
How to properly validate a registration form

### ISSUE THREAD

**Issue by rovillesarate** [themosis/framework#675]
Hi! Guys. How do you validate a registration form?

`    protected function create(FormInterface $form)
    {
        $state = 'customer';
        $confirm = $form->repository()->getFieldByName('tos')->getValue();
        if ( $confirm ) :
            $name = trim($form->repository()->getFieldByName('name')->getValue());
            $last_name = (strpos($name, ' ') === false) ? '' : preg_replace('#.*\s([\w-]*)$#', '$1', $name);
            $first_name = trim( preg_replace('#'.$last_name.'#', '', $name ) );        
            Mailchimp::subscribe(env('MC_LIST_ID'), $form->repository()->getFieldByName('email')->getValue(), ['FNAME' => $first_name, 'LNAME' => $last_name], false);
            return Customer::create([
                'name' => $form->repository()->getFieldByName('name')->getValue(),
                'email' => $form->repository()->getFieldByName('email')->getValue(),
                'password' => Hash::make($form->repository()->getFieldByName('password')->getValue()),
                'tos' => $form->repository()->getFieldByName('tos')->getValue(),
                'country' => $form->repository()->getFieldByName('country')->getValue(),
                'cust_type' => $state,
            ]);
        endif;
    }`

Should I put in if ($form->isValid()) : // then create customer?

**Comment by jlambe** [comment]
You simply call the `handleRequest` method like so from your controller:

```php
public function index(Request $request)
{
    $form = $this->form(new CustomerForm());

    $form->handleRequest($request);

    // Now you can write your logic based on form validation status
    if ($form->isValid()) {
        // Form is valid...do your stuff here
    }
}
```

You can find more information here on the documentation: https://framework.themosis.com/docs/2.0/form/#error-reporting
