### ISSUE TITLE
getting an error when trying to create a secondary registration form

### ISSUE THREAD

**Issue by rovillesarate** [themosis/framework#676]
Hi! I am getting an error after registering.

Getting error:
Target [Themosis\Forms\Contracts\FormInterface] is not instantiable.

**Comment by jlambe** [comment]
Please, could you at least provide some context about your issue! This does not appear on a default installation. So if you would like some help, please post your actual code, give us some explanations about what you're trying to achieve and then we might give you help to resolve this. Thanks

**Comment by rovillesarate** [comment]
I followed the authentication instruction from the documentation.
`php console customer:table` and `php console make:auth` and so on.

The RegisterController works properly but I wanted to create another registration page to handle registration for vendors. I created a controller ShopRegistrationController at app/http/auth/ folder

`<?php

namespace App\Http\Controllers\Auth;

use App\Customer;
use App\Forms\ShopRegistrationForm;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Hash;
use Themosis\Core\Auth\RegistersUsers;
use Themosis\Forms\Contracts\FormInterface;
use Themosis\Support\Facades\Asset;
use Mailchimp;

class ShopRegisterController extends Controller
{
    /**
     * Register Controller
     *
     * This controller handles the registration of new customers as well as their
     * validation and creation. By default, this controller uses a trait to provide
     * this functionality without requiring any additional code.
     */
    use RegistersUsers;

    /**
     * Where to redirect users after registration.
     *
     * @var string
     */
    // protected $redirectTo = '/account/dashboard';
    protected $redirectTo = '/coming-soon';

    /**
     * Create a new customer instance after a valid registration.
     *
     * @param FormInterface $form
     *
     * @return \App\Customer
     */
    protected function create(FormInterface $form)
    {
            $state = 'vendor';
            $name = trim($form->repository()->getFieldByName('name')->getValue());
            $last_name = (strpos($name, ' ') === false) ? '' : preg_replace('#.*\s([\w-]*)$#', '$1', $name);
            $first_name = trim( preg_replace('#'.$last_name.'#', '', $name ) );        
            Mailchimp::subscribe(env('MC_LIST_ID'), $form->repository()->getFieldByName('email')->getValue(), ['FNAME' => $first_name, 'LNAME' => $last_name], false);

            return Customer::create([
                        // 'shop_name' => $form->repository()->getFieldByName('shop_name')->getValue(),
                        'name' => $form->repository()->getFieldByName('name')->getValue(),
                        'email' => $form->repository()->getFieldByName('email')->getValue(),
                        'password' => wp_generate_password(),
                        'tos' => $form->repository()->getFieldByName('tos')->getValue(),
                        'country' => $form->repository()->getFieldByName('country')->getValue(),
                        'cust_type' => $state,
                    ]);



    }

    public function showRegistrationForm() {
        Asset::add('jquery', '//code.jquery.com/jquery-3.4.1.slim.min.js', [], '3.4.1', true)->to();
        Asset::add('bulma', '//cdnjs.cloudflare.com/ajax/libs/bulma/0.7.0/css/bulma.min.css', [], '0.7.0', false)->to();
        Asset::add('fontawesome', '//use.fontawesome.com/releases/v5.0.7/js/all.js', [], '5.8.2', true)->to();
        Asset::add('formvalidator', '//cdnjs.cloudflare.com/ajax/libs/jquery-form-validator/2.3.26/jquery.form-validator.min.js', [], '2.3.26', true)->to();
        return view('auth.shop_register', [
            'form' => $this->form(new ShopRegistrationForm())
        ]);
    }
}
`

The showRegistrationForm Function works properly but when i try to register I get the following errors Target [Themosis\Forms\Contracts\FormInterface] is not instantiable.

**Comment by rovillesarate** [comment]
Finally got it working.

Routes.php
`Route::post('/shop/register', 'Auth\ShopRegisterController@register');`

ShopRegisterController.php
`use App\Forms\Auth\ShopRegistrationForm;
use Illuminate\Auth\Events\Registered;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
    public function register(Request $request)
    {
        $form = $this->form(new ShopRegistrationForm());
        $form->handleRequest($request);

        if ($form->isValid()) {
            event(new Registered($customer = $this->create($form)));
            $this->guard()->login($customer);

            return $this->registered($request, $customer)
                ?: redirect(site_url($this->$redirectTo));
        }

        return $this->showRegistrationForm();
    }

    /**
     * Get the guard used during registration.
     *
     * @return \Illuminate\Contracts\Auth\StatefulGuard
     */
    protected function guard()
    {
        return Auth::guard();
    }

    /**
     * The user has been registered.
     *
     * @param Request $request
     * @param mixed   $customer
     */
    protected function registered(Request $request, $customer)
    {
        //
    }

    protected function create(FormInterface $form)
    {
     // Create User / Customer
     }
`
