### ISSUE TITLE
Where to put in the Page:make function?

### ISSUE THREAD

**Issue by rovillesarate** [themosis/framework#679]
Hi! When creating admin pages? where should I put in the Page:make function?

on the previous version 1.3 you put it in the admin directory.

Do I make a inc folder inside the themes folder? what is the right way of declaring the pages?

**Comment by jlambe** [comment]
You should use the new `Hookable` classes to define code that is meant to customize the WordPress backoffice. You can learn more about Hook in the documentation:

- https://framework.themosis.com/docs/2.0/hooks/

**Comment by rovillesarate** [comment]
Tried doing it this way, nothing happens

`<?php

namespace App\Hooks;

use Themosis\Hook\Hookable;
use Themosis\Support\Section;
use Page;
use Action;

class AdminPages extends Hookable
{
    /**
     * Extend WordPress.
     */
    public function register()
    {
    	Action::add('init', function() {
			$page = Page::make('demo-settings', 'Settings')
			    ->set();

			$page->addSections([
			    new Section('general', 'General'),
			    new Section('social', 'Social')
			]);
		});
    }
}`

**Comment by rovillesarate** [comment]
Got it working now.

**Comment by rovillesarate** [comment]
When creating a Custom Admin Page. How would you use wp_list_table with Themosis to display for example a customer table data
