### ISSUE TITLE
MetaboxApiController uses App\ namespace

### ISSUE THREAD

**Issue by szepeviktor** [themosis/framework#681]
Could it be that MetaboxApiController uses [`App\Http\Controllers\Controller`](https://github.com/themosis/framework/commit/3d76a05678ee8a1e4bd338b7b6caaa6e56d9bc66)?

https://github.com/themosis/framework/blob/2.0/src/Metabox/Controllers/MetaboxApiController.php#L5-L11

`App` seems to be a downstream namespace.

props. @phpstan

**Comment by szepeviktor** [comment]
```bash
composer require --dev phpstan/phpstan-shim
composer require --dev giacocorsiglia/wordpress-stubs
vendor/bin/phpstan analyze -a vendor/giacocorsiglia/wordpress-stubs/wordpress-stubs.php src/
```

**Comment by jlambe** [comment]
Yes it is using it but the controller can omit to extend it in fact. This can be easily fixed. Thanks for noticing.

**Comment by szepeviktor** [comment]
@phpstan showed it to me.

**Comment by szepeviktor** [comment]
@jlambe Would you welcome me fixing PHPDoc blocks and defining all properties?
This would facilitate running deeper static analysis.

**Comment by jlambe** [comment]
@szepeviktor I'm not sure to understand what you would like to fix here with PHPDoc Blocks ? Would you like to show me a sample of what you're trying to achieve ?

**Comment by szepeviktor** [comment]
@jlambe Yes!

1. Feed PHPStan with valid PHPDoc blocks
1. Define properties before usage
1. Run PHPStan on Level 0, 1, 2 ... max
1. Benefit from discovered bugs :)

**Comment by jlambe** [comment]
Well this seems interesting. You can submit a PR against the `2.0` branch. The discussion can continue based on the changes then.

**Comment by szepeviktor** [comment]
@jlambe Very nicely done!!

**Comment by KeironLowe** [comment]
@szepeviktor Hi Viktor, could I ask what your configuration is for PHPStan and Themosis? I've set it up as per https://packagist.org/packages/szepeviktor/phpstan-wordpress, but it reports issues like

Hooks/Application.php
* `Constant APP_TD not found.`
* `Call to an undefined method Illuminate\Contracts\Foundation\Application::outputJavascriptGlobal().`

Http/Middleware/RedirectIfAuthenticated.php
* `Parameter #1 $to of function redirect expects null, string given.`

I know APP_TD is definitely set, so just not sure whether something isn't set up properly?

**Comment by szepeviktor** [comment]
a moment pls...

**Comment by szepeviktor** [comment]
This one which is already included
https://github.com/themosis/framework/pull/688/files#diff-0847156bd64b0de0f4d91da2394ec0e8
looking for the causes ...

**Comment by szepeviktor** [comment]
I couldn't find the files, constants you are referring to.

PHPStan does not run your code - that is why it is called _static_ analysis - o if you use a constant `APP_TD` in your code you should define it in `tests/phpstan/bootstrap.php` and include this file in `autoload_files:`

**Comment by KeironLowe** [comment]
Sorry, that particular constant is set by the themosis/themosis. That makes sense though, I'll have a look at fixing the issues highlighted in by phpstan in that repo and make a PR

**Comment by szepeviktor** [comment]
I see! It comes from `config/wordpress.php` but that file is never included as it is not loaded by Composer but by `ThemeInstallCommand::setAsDefaultTheme()` which will not run during _static_ analysis.
