### ISSUE TITLE
How do you make a file / image upload field on the front-end?

### ISSUE THREAD

**Issue by rovillesarate** [themosis/framework#682]
Hi! How do you make a file / image upload field on the front-end since the media field can only be used on the admin page?

How do you make custom field input with the newer themosis version? everything changed since version 1.3

**Comment by jlambe** [comment]
You would have to define an input with a type of `file` and then handle the logic yourself to store the uploaded image so WordPress can recognize it from the media library.

For building a custom field, the best way to learn it is by looking at the `Themosis\Forms\Types\TextType` class. Basically, you need to extend a `Themosis\Forms\Types\BaseType` class and implement a `FieldTypeInterface`.

When used within a form, you can pass your field instance directly into the form `add()` method.

More granular methods are planned to better handle custom fields use on release `2.1`.
