### ISSUE TITLE
Field choices with associative array: default value doesn't work

### ISSUE THREAD

**Issue by spagi** [themosis/framework#684]
default/saved value doesn't selected, themosis 2,
In case of using exaple values for choices field everything works fine

'choices' => ['red', 'green', 'blue'] //this is works, value is  

 $settings = Page::make('demo-settings', 'PrusaLab Settings')
            ->setParent('options-general.php')
            ->set();

        $settings->addSections([
            new Section('general', 'General'),

        ]);
        $pages = Post::where('post_type', 'page')->where('post_status', 'publish')->get();
        $choices = collect([]);
        foreach ($pages->toArray() as $p) {
            $choices->put($p['post_title'], $p['ID']);
        }
     
        $title->toArray();

        $settings->addSettings([
            'general' => [
                Field::choice('registration_success',
                    [
                        'choices' => $choices->toArray(),

                    ]),
                Field::choice('event_success',
                    [
                        'choices' => $choices->toArray(),

                    ]),
            ],

        ]);
```php

**Comment by jlambe** [comment]
@spagi I've just tested your code and I can't reproduce the issue. Option is selected as expected after save.

My only issue is a duplicate success message.

<img width="860" alt="settings" src="https://user-images.githubusercontent.com/1917490/59912591-9d413b00-9416-11e9-88b7-23782d37cc0e.png">

**Comment by spagi** [comment]
@jlambe I've been using version 2.01, after upgrade to 2.0.3 it works as expected.
