### ISSUE TITLE
Route POST method not working

### ISSUE THREAD

**Issue by tipytechnique** [themosis/framework#685]
Themosis version : 2.0.2

Hi, i have an issue when i'm making routes with the POST method on my route `web.php` file.

here is my `web.php` content :

```
<?php
use Illuminate\Support\Facades\Log;

/**
 * Application routes.
 */
Route::get('/', function () {
    return view('welcome');
});

Route::post('/test', function () {
    Log::debug('test');
});
```
I'm using Insomnia to hit URls and see if it is working.
GET routes are working, but if i hit `http://mysite/test` with the POST method, i get a `419 unknown status` error.

I'm on a fresh install.

**Comment by jlambe** [comment]
@tipytechnique The middleware is looking after a `_token` input into the request containing a csrf value. If none is found, you get a `419` error. You can add your URI to exception list of the `VerifyCsrfToken` middleware:

```php
protected $except = [
    'test'
];
```

**Comment by tipytechnique** [comment]
Oh my bad, totally forgot about this csrf token, thanks a lot :D !!
