### ISSUE TITLE
Packages Services Providers auto-registration

### ISSUE THREAD

**Issue by tipytechnique** [themosis/framework#686]
On the 2.0 changelog, it is writtent that "Services Providers auto-registration" is up with composer.json support.

Is this for our own Services Providers on the `app/Providers` folder, or for required Laravel's packages added on `composer.json` ?

If this is for our own Providers, how it works ?
If this is for Laravel's packages, i think it is not working, tried to require some packages to test, and i must manually set the providers on the `config/app.php` file.

**Comment by jlambe** [comment]
Normally it is just Laravel packages that auto-register their providers but indeed I had too to manually register them on a recent project. There is probably something missing here 🙄

**Comment by tipytechnique** [comment]
I read some posts about it, seems like on `laravel/laravel`, they use the `post-autoload-dump` event from within the main composer.json file :
```
"scripts": {
    "post-autoload-dump": [
        "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
        "@php artisan package:discover"
    ]
}
```
On this post [https://divinglaravel.com/laravels-package-auto-discovery](url) i can read :

> First it calls a postAutoloadDump() static method, this method handles clearing any cached services or previous discovered packages, the other thing is that it runs the package:discover artisan command, and this is where all the magic happens.

`package:discover` command can be found here [https://github.com/laravel/framework/blob/5.8/src/Illuminate/Foundation/Console/PackageDiscoverCommand.php](url)

I'll try this this week end and if it works i'll make a PR :)

**Comment by tipytechnique** [comment]
Hi, coming back after some tests, and i'm facing problems.

### Forks

From `themosis/themosis` : 
[https://github.com/tipytechnique/themosis/tree/feature-add-script-event-to-composer-json](url)
From `themosis/framework` : 
[https://github.com/tipytechnique/framework/tree/feature-service-provider-auto-registration](url)

### What i've done

So Basically, on the `themosis/themosis/composer.json` file, i added those lines under composer scripts : 
```
"post-autoload-dump": [
   "Themosis\\Core\\ComposerScripts::postAutoloadDump",
   "@php console package:discover --ansi"
 ]
```
Then, on `themosis/framework`, added class `ComposerScripts` that clear discovered packages and services after some composer's events, and added the new command `package:discover` that re-run the package manifest build function.

### Issue

Issue appears on `ComposerScripts::postAutoloadDump` : 
   ```
   /**
     * Clear the cached Laravel bootstrapping files.
     *
     * @return void
     */
    protected static function clearCompiled()
    {
        $laravel = new Application(getcwd());

        if (file_exists($servicesPath = $laravel->getCachedServicesPath())) {
            @unlink($servicesPath);
        }

        if (file_exists($packagesPath = $laravel->getCachedPackagesPath())) {
            @unlink($packagesPath);
        }
    }
```
This function removes cached files for `services` and `packages` before rebuilding them with the `package:discover` command.
See this line : 
`$laravel = new Application(getcwd());`
`Themosis\Core\Application` is used here to retrieve those files paths.
Finally here is the Exception triggered : 

```
> Themosis\Core\ComposerScripts::postAutoloadDump
Script Themosis\Core\ComposerScripts::postAutoloadDump handling the post-autoload-dump event terminated with an exception

                                                                                                                             
  [ErrorException]                                                                                                           
  Use of undefined constant WP_CONTENT_DIR - assumed 'WP_CONTENT_DIR' (this will throw an Error in a future version of PHP) 
```

This seems to happen because constants defined on `wp-config.php` file are used on `Themosis\Core\Application`, but on this context, `wp-config.php` is missing.

### Solutions ?

- Stop using `wp-config.php` constants in `Themosis\Core\Application`, instead, may be we can rely only on the basePath, this path is passed on the constructor, represents the Themosis root folder, and all paths would be relatives to it ?
- Import `wp-config.php` constants in this context, paths will may be need to be adapted ?

None of this solutions have been tested yet, the second one seems weird to me.

**Comment by tipytechnique** [comment]
First solution : 

> Stop using wp-config.php constants in Themosis\Core\Application, instead, may be we can rely only on the basePath, this path is passed on the constructor, represents the Themosis root folder, and all paths would be relatives to it ?

I finally didn't use this solution, that was hard to maintain, seems better to keep `wp-config.php` constants event in `ComposerScripts` class context.

**Comment by jlambe** [comment]
@tipytechnique Thanks for fixing this issue. I'll look to the PR a bit later but for what I've seen, it's seems to be good for a merge ;)

Definitely going to need to find a solution to avoid too much duplicates on those `wp-config` constants.
