### ISSUE TITLE
showResetForm doesn't set email

### ISSUE THREAD

**Issue by yanmorinokamca** [themosis/framework#687]
Hi, unless I'm missing something else, it seems like the email from the URL is not handle in the reset password class.

In src/Core/Auth/ResetPasswords.php 
https://github.com/themosis/framework/blob/2.0/src/Core/Auth/ResetPasswords.php

The showResetForm doesn't seem to inject the ?email= parameters from the URL
with
$data->setEmail($request->get('email') ?? '');
So the POST field th_email of the form isn't set.

Link come from
Illuminate\Auth\Notifications\ResetPassword  toMail() function with token and email.
Route rule is in:
Illuminate\Routing\Router resetPassword() function

Thanks You for Themosis.

**Comment by jlambe** [comment]
@yanmorinokamca The email address is not defined into the URL for what is implemented. One form ask the email address and looks into the database if one exists, and if so, send an email with URL containing a token. Then the user goes to a URL using the token and is asking to insert its email address again. Is the default password reset of Laravel including the email automatically ?

**Comment by yanmorinokamca** [comment]
Line 62 of ResetPassword (5.8)
https://github.com/laravel/framework/blob/5.8/src/Illuminate/Auth/Notifications/ResetPassword.php#L62

url(config('app.url').route('password.reset', ['token' => $this->token, 'email' => $notifiable->getEmailForPasswordReset()]

**Comment by jlambe** [comment]
@yanmorinokamca Are you up to to provide a pull request for a change on this ?
