### ISSUE TITLE
Will Themosis support Event Listener

### ISSUE THREAD

**Issue by rovillesarate** [themosis/framework#689]
Hi! Will Themosis be able to handle laravel event listener feature?

**Comment by jlambe** [comment]
Events are handled by the framework. It's just that the default EventServiceProvider is not defined.

But you can add your own and listen to your events like so:

```php
// Create a custom EventsServiceProvider class inside the `app/Providers` directory

use Illuminate\Support\Facades\Event;

public function boot()
{
    Event::listen(YourCustomEvent::class, TheListener::class);
}
```

and inside your code, you can dispatch an event using the `event` helper function like so:

```php
event(new YourCustomEvent());
```
