### ISSUE TITLE
Theme PSR-4 autoloading not working

### ISSUE THREAD

**Issue by Jaspervv** [themosis/framework#690]
Theme Autoloading doesn't seem to work (both me and my co-worker are experiencing this issue).
When I create a class inside a Theme, and try to access that class, it will throw a `Class not Found` error:
```php
Symfony\Component\Debug\Exception\FatalThrowableError Class 'Theme\Hooks\MyHook' not found
```

### Create theme
From a fresh project, setup a theme:
```bash
$ php console theme:install my-theme
```
which creates a theme with the following autoloading config:
```php
// my-theme/config/theme.php
...
    'autoloading' => [
        'Theme\\' => 'resources'
    ],
...
```
### Create Hook
So I create a `Hooks` directory in my theme's `resources` with a Hookable inside it:
```php
<?php
// my-theme/resources/Hooks/MyHook.php

namespace Theme\Hooks;

use Themosis\Hook\Hookable;

class MyHook extends Hookable
{
    public function register()
    {
        dd('registered');
    }
}
```

### Register Hook
And register it by adding it to the `hooks` array in the project's `config/app.php`:
```php
// config/app.php
...
    'hooks' => [
        App\Hooks\Application::class,
        App\Hooks\Compat::class,
        App\Hooks\Mail::class,
        App\Hooks\Widgets::class,
        Theme\Hooks\MyHook::class,
    ],
...
```
And now you should get the error.

**Comment by Jaspervv** [comment]
This has to do with the `config` being initialised before the theme.

**Comment by jlambe** [comment]
@Jaspervv Yes, and I won't recommend you to write a Hook class inside your theme as within a Hook you would want to extend or provide functionnality to your application on a WordPress side. 

Switching theme will also break such code as the class may no longer exists. Theme classes are autoloaded but last in the lifecycle. Theme classes can only be used inside theme's code.

**Comment by Jaspervv** [comment]
With our implementation of Themosis we sadly can't avoid putting functionalities in the themes, I understand that this isn't standard, which is why I closed the issue and will find a workaround myself.
