### ISSUE TITLE
"edit" and "view" Taxonomy category in admin panel is throwing errors

### ISSUE THREAD

**Issue by wontoan** [themosis/framework#692]
Context:
I want to edit/view a taxonomy category that I created from within a plugin.
![all-categories](https://user-images.githubusercontent.com/13013084/59700434-45f65d00-91c1-11e9-98c1-04b8621a7d7b.png)

This is my code for registering the Taxonomy:
```
Taxonomy::make('my_category', 'my_custom_post_type', 'Plural name', 'Singular name')
        ->setArguments([
            'hierarchical'      => false,
            'show_in_quick_edit'=> true,
            'show_ui'           => true,
            'show_admin_column' => true,
        ])
        ->set();
```

Problem: 
1. When I try to "view" a category i receive the following error:
`Trying to get property 'query_var' of non-object`

This is the line of code where the error is thrown:
![github-issue](https://user-images.githubusercontent.com/13013084/59700247-f748c300-91c0-11e9-9f8e-bb3b85bea1b7.png)

2. When i try to "edit" a category I receive a blank page. I'm not sure if this is intended because I didn't have to create a route or template for viewing all categories.

I've been stuck on this for a couple of days now so any help at all would be greatly appreciated!

Btw, this is a fresh 2.0 install with no additional plugins installed.

**Comment by jlambe** [comment]
I'll have to test your taxonomy code on a fresh installation. Are there any filters defined within your plugin that might change the behaviour of your taxonomy ?

No routes are needed for defining custome taxonomies or post types. There are helper classes to customize the back-office of WordPress. Routes are only used on the user-side of the application.

**Comment by wontoan** [comment]
Wow, nice catch! I wrote a filter to output the value of a custom column named "shortcode".

![Screen Shot 2019-06-19 at 10 57 14 AM](https://user-images.githubusercontent.com/13013084/59776677-36d6e400-9281-11e9-8b3c-832a16bdf801.png)

This is the code that's causing "edit" to break:
```
Filter::add(
            'manage_my_category_custom_column', 
            function ($content, $column_name, $term_id) {
                switch ($column_name) {      
                    case 'title':
                        $content = get_the_title();
                    break;
                    case 'my_shortcode':
                        $content = '[my_category category="' . $term_id . '"]';
                    break;
                    default:
                        break;
                }

                return $content;
            }, 
            10, 
            3
        );
```

Is there a way to get this functionality to work with "themosis"? The above code is the solution as seen in the [WP codex](https://codex.wordpress.org/Plugin_API/Filter_Reference/manage_$taxonomy_id_columns).

I'm also still having the query_var issue when "view"ing the taxonomy.

**Comment by jlambe** [comment]
@wontoan I've tested your taxonomy code and on a fresh installation it is working as expected. On the admin site, no errors when trying to edit a taxonomy term. On the front-end side, no errors but yes, you have to define a route for your custom taxonomy like so:

```php
Route::any('tax', ['my_category', function () {
    // Code goes here...
    return view('taxonomy.archive);
}]);
```

Because the framework is converting all warnings and errors to Exceptions, you do get an error report for everyhing. The issue you might have can come from another code sample. Looking at the error message stack, it seems that you call the `get_term_link()` function somewhere and that the passed term is perhaps not a term at all.

**Comment by wontoan** [comment]
Looks like the issue was in my filter for customizing the table headings. It seems like setting a key's value to one of the defaults in $columns is causing the break.

This doesn't work:
```
Filter::add("manage_edit-my_category_columns", function ($columns) {

            $new_columns = [
                'cb' => $columns['cb'],
                'name' => "Name",
                'shortcode' => 'Shortcode',
                'posts' => $columns['posts'],
            ];

            return $new_columns;
        });
```

This does:
```
Filter::add("manage_edit-my_category_columns", function ($columns) {

            $new_columns = [
                'cb' => '<input type="checkbox"/>',
                'name' => 'Name',
                'shortcode' => 'Shortcode',
                'posts' => 'Count'
            ];

            return $new_columns;
        });
```

**Comment by jlambe** [comment]
@wontoan Glad your issue is fixed ;) Thanks for the kind words.
