### ISSUE TITLE
How to use Page API with Form

### ISSUE THREAD

**Issue by wontoan** [themosis/framework#702]
Hi I'm following along with the example as seen [here](https://framework.themosis.com/docs/2.0/page/#handle-post-requests).

How can I take advantage of the framework's Form class' built-in [error-reporting](https://framework.themosis.com/docs/2.0/form/#error-reporting) if I cannot return a view with the form?

```
<?php

use Themosis\Support\Facades\Page;

$page = Page::make('custom-admin-page-slug', 'Custom Page')
            ->set();
$page->route('/', 'App\Http\Controllers\MyController@myGetRoute');
$page->route('create', 'App\Http\Controllers\MyController@myCreateRoute', 'post');
```

```
<?php

namespace App\Forms;

use Themosis\Field\Contracts\FieldFactoryInterface;
use Themosis\Forms\Contracts\FormFactoryInterface;
use Themosis\Forms\Contracts\Formidable;
use Themosis\Forms\Contracts\FormInterface;

class MyForm implements Formidable
{
    /**
     * Build your form.
     *
     * @param FormFactoryInterface  $factory
     * @param FieldFactoryInterface $fields
     *
     * @return FormInterface
     */
    public function build(FormFactoryInterface $factory, FieldFactoryInterface $fields): FormInterface
    {
        $actionField = $fields->hidden('action', [
            'data' => 'custom-admin-page-slug_create',
        ]);
        $actionField->setPrefix('');

        $form = $factory->make(null, [
                'attributes' => [
                    'action' => admin_url('admin-post'),
                ]
            ])
            ->add($actionField)
            ->add($fields->text('name', [
                'rules' => 'required'
            ]))
            ->add($fields->submit('Submit'))
            ->get();

        return $form;
    }
}
```

```
<?php

namespace App\Http\Controllers;

use App\Forms\MyForm;
use Illuminate\Http\Request;
class MyController extends Controller
{
    public function myGetRoute()
    {
        $form = $this->form(new MyForm());

        return view('my-plugin.my-custom-admin-page-view', [
            'form' => $form
        ]);
    }

    public function myCreateRoute()
    {
        $form = $this->form(new MyForm());

        $form->handleRequest(request());

        // ???
        wp_safe_redirect(add_query_arg([
                'page' => 'custom-admin-page-slug',
        ], admin_url('admin.php')));
        exit();
    }
}
```

I've tried creating and listening to a custom POST route instead of `admin-post.php` in order to return the view but that broke the entire admin interface :(

**Comment by jlambe** [comment]
@wontoan One thing that normally fit for this scenario is the use of "flash" session to store temporary data for the time of the next request. Basically, you could call the `Session::flash('varname', 'value')` and after the redirect look after the session data using the `Session::get('varname')` and `Session::has('varname')` methods... but there is an opened issue on this as session do not work correctly on the administration side for now. See #621 

One thing that work though is the use of the WordPress transient API which temporarily store your data inside the database `wp_options` table and that you can retrieve on the next request.

The transient API is for now the best solution until the session package is fully working with the administration back-office.
