### ISSUE TITLE
incorrect route() url on admin pages

### ISSUE THREAD

**Issue by Jaspervv** [themosis/framework#705]
When the `route()` helper is used in the WordPress dashboard, it returns an url relative to it's current path instead of the root.  

## test code
Route:
```php
Route::any('/test/route', 'TestController@test')->name('my_test_route');
```

Code _(I placed it in the `inc`)_:
```php
dd(route('my_test_route'));
```

## example results
On the left is the route I visited, on the right is the result from the `route()` helper above.  
I personally would always expect the result to be `http://themosis.project/test/route`.

| Route | Result |
| -------- | ------- |
| `/` | `http://themosis.project/test/route` |
| `/test-page` | `http://themosis.project/test/route` |
| `/cms/wp-login.php` | `http://themosis.project/cms/wp-login.php/test/route` |
| `/cms/wp-admin` |  `http://themosis.project/cms/wp-admin/test/route` |

**Comment by jlambe** [comment]
@Jaspervv I've just encoutered the same issue using the `asset` helper function. It should definitely stick to the "front" URL. I haven't yet looked at this issue.

**Comment by Jaspervv** [comment]
This has not always been the case though, I noticed the issue while porting a 2/3 month old branch, back then the `route()` helper worked fine on dashboard pages.  

#### root()
The issue itself can be tracked down to the Laravel's Request [`root()`](https://github.com/laravel/framework/blob/5.8/src/Illuminate/Http/Request.php#L87) method (which the helpers make use of), it looks like this:
```php
    public function root()
    {
        return rtrim($this->getSchemeAndHttpHost().$this->getBaseUrl(), '/');
    }
```
and can be tested with:
```php
dd(request()->root());
```

### getBaseUrl()
The root method makes use of Symfony's [`getBaseUrl()`](https://github.com/symfony/http-foundation/blob/6252235640c4d0ff47f1e7ae94724efc47005124/Request.php#L870) method, which is expected to be an empty string, but instead it returns things like `/cms` and `/cms/wp-login.php`.
```php
dd(request()->getBaseUrl());
```

**Comment by Jaspervv** [comment]
@jlambe could you re-open this issue?  
47b7339 does not seem like a solution, the `route()` function is still incorrect and `rootUrl()` is not a replacement since it doesn't make use of route names.  

This is my _(untested)_ suggestion for the `route()` helper:
```php
function route($name, $parameters = [], $absolute = true)
{
    $path = app('url')->route($name, $parameters, false);
    return ($absolute) ? rootUrl($path) : $path;
}
```

**Comment by jlambe** [comment]
@Jaspervv Here it is. You might send a PR with your idea so we can test it ;)

**Comment by Jaspervv** [comment]
I was right about `rootUrl()` returning a double slash, so I altered it to be consistent with the slashes.
