### ISSUE TITLE
Grouped fields do not display a name in the tab

### ISSUE THREAD

**Issue by pvdptje** [themosis/framework#707]
I'm trying to group some fields at a certain post type.
The grouping goes fine but theres no group name displayed in the tab.

My code:
```
                Metabox::make('Openingstijden', self::POST_TYPE)
                ->add(Field::text('monday_open', [
                    'label' => 'Openingstijd maandag',
                    'group' => 'monday',
                ]))
                ->add(Field::text('monday_close', [
                    'label' => 'Sluitingstijd maandag',
                    'group' => 'monday',
                ]))
                ->add(Field::text('tuesday_open', [
                    'label' => 'Openingstijd dinsdag',
                    'group' => 'tuesday'
                ]))
                ->add(Field::text('tuesday_close', [
                    'label' => 'Sluitingstijd dinsdag',
                    'group' => 'tuesday'
                ]))
                ->set()
```

Here is a screenshot of the output in the Wordpress admin:
![image](https://user-images.githubusercontent.com/3110215/60715965-89213180-9f1e-11e9-8941-23c78f87ff23.png)

The tabs do not display anything in it.
Im using themosis 2.0 and Wordpress 5.2.2.

**Comment by jlambe** [comment]
@pvdptje Hello, the syntax is a little different for metabox field groups, see: https://framework.themosis.com/docs/2.0/metabox/#add-custom-fields-groups

The `add` method should accept a `Section` instance and the third argument of a section should be an array of fields:

```php
Metabox::make('Openingstijden', self::POST_TYPE)
    ->add(new Section('monday', 'Monday', [
        Field::text('monday_open'),
        Field::text('monday_close')
        ...
    ]))
```

**Comment by pvdptje** [comment]
Wow, super fast response. Thanks!

This did the trick. Thanks alot!
![image](https://user-images.githubusercontent.com/3110215/60716842-ad7e0d80-9f20-11e9-8fb8-7f76de9ec71e.png)

**Comment by jlambe** [comment]
It's not always fast but there is always generally a response 😄 Glad your issue is solved.
