### ISSUE TITLE
Cannot show and save metaboxes

### ISSUE THREAD

**Issue by antoscarface** [themosis/framework#711]
Hi, I'm trying to add a new metabox, but any field is shown inside the box.

I'm using Themosis Framework 2.0 with the latest version of WordPress.

Here the code I added in a new Hookable class:
```
Metabox::make('landing', ['page'])
    ->setTitle(_x('Landing attributes', 'metabox', 'adespresso'))
    ->setPrefix('lp_')
    ->add(Field::choice('coupon', ['test1', 'tst2']))
    ->set();
```

The Hookable class is added in `app.php` hook list and what happened is that the box appears correctly, but only with the "Save" button and nothing else: 
![Metabox](https://snag.gy/0i8UvJ.jpg)

Furthermore, I saw that the AJAX request that should send the fields (I guess) returns the 404 wordpress page HTML and strangely the status code of the request is 200: 
![Headers](https://snag.gy/SPANmh.jpg)
![Response](https://snag.gy/VpxIiZ.jpg)

What am I missing? Is that a bug or something that I'm doing wrong?
I tried to find something before to open this issue, but I cannot find the reason. The only thing that I found is that the route is hard-coded [here](https://github.com/themosis/framework/blob/2.0/src/Metabox/MetaboxRoutingServiceProvider.php#L22), but I didn't find the position where this request is handled (it's not a custom Rest API because it's not starting with `/wp-json/`).

I hope you can help me.
Thank you.

**Comment by Jaspervv** [comment]
According to [the documentation](https://framework.themosis.com/docs/2.0/field/#choice-field) the choices have to be passed with the key 'choices', they give the following example:
```php
Field::choice('color', [
    'choices' => ['red', 'green', 'blue']
]);
```

So your code should look like this:
```php
Metabox::make('landing', 'page')
    ->setTitle(_x('Landing attributes', 'metabox', 'adespresso'))
    ->setPrefix('lp_')
    ->add(Field::choice('coupon', [
        'choices' =>['test1', 'tst2']
    ]))
    ->set();
```

**Comment by antoscarface** [comment]
That it's another thing that you solved me, thank you.

Actually, the problem is another and it's explained in my main message, the fact that the field is not shown (even with your correction) and the XHR requests are failing.

Anyway, I've just found the reason: I missed the kernel initialization for the frontend, that one placed here: https://github.com/themosis/theme/blob/master/index.php#L15

Adding this it working good now :)

I didn't have those lines yet because I'm not still using the custom routes and I didn't notice that I missed that part.
