### ISSUE TITLE
Dependency injection and validation errors does not work in admin page controllers

### ISSUE THREAD

**Issue by pvdptje** [themosis/framework#714]
Hi again,

I've run into some troubles.
I have made an admin page and registrered the following routes:

```namespace App\Hooks;

use Themosis\Support\Facades\Page;
use Themosis\Hook\Hookable;

class Admin extends Hookable
{

    public function register()
    {
        $this->registerAdminPages();
    }

    protected function registerAdminPages()
    {
        $page = Page::make('arrangements', 'Arrangementen configureren')->set();
        $page->route('/', '\App\Http\Controllers\Admin\ArrangementController@index');
        $page->route('create', '\App\Http\Controllers\Admin\ArrangementController@create');
        $page->route('store', '\App\Http\Controllers\Admin\ArrangementController@store', 'post');
    }

}
```

In the create method, i return a view with a small form. 
```
 return view('admin.arrangement.form', [
            'method' => __METHOD__
        ]);
```
```
<form action="{{ admin_url('admin-post.php') }}" method="post">
        <input type="hidden" name="action" value="arrangements_store"/>
        <div class="form-group">
            <label>Naam arrangement</label>
            <input type="text" name="arrangement_name" />
        </div>
        <input type="submit" class="button button-primary button-large" value="Opslaan" />
    </form>
```

This all works as intended, when i submit the form i reach the Store method on the controller.
Now this is the part where things don't work (i'm probably doing something wrong).

The first problem i encountered was that dependency injection is not working properly.

```
    public function store(Request $request)
    {
       $this->validate($request, [
           'arrangement_name' => 'required'
       ]);

       dd('storing');
    }
```

With the code above, the following exception occurs:
```
Argument 1 passed to App\Http\Controllers\Admin\ArrangementController::store() must be an instance of Illuminate\Http\Request, string given
```
The argument passed into the controller method is indeed an empty string.

The other problem is, when i try to validate the request, it does exactly this, but the errors are not available in the form when it redirects back:

```
    public function store()
    {
       $this->validate(app('request'), [
           'arrangement_name' => 'required'
       ]);

       dd('storing');
    }
```

Ive checked if the middleware ShareErrorsFromSession is working, and this works.
However when i print the $errors variable in the view, it's an empty message bag:
```Illuminate\Support\ViewErrorBag Object
(
    [bags:protected] => Array
        (
        )

) 
```
   
I really hope you can tell me what i'm doing wrong.
I'm using themosis 2.0 and Wordpress 5.2.2

**Comment by pvdptje** [comment]
Maybe this issue is the same:

Implement session full support on administration pages #621

If so, this may be closed.

**Comment by jlambe** [comment]
@pvdptje Hello, this is not really an issue but can look like one... In fact, a controller defined on a WordPress page route does not behave the same as a controller defined within a real route.

The difference here is the controller method is called behind the scene by the `call_user_func` function and so you can't type-hint dependencies on your controller method.

But instead, you can type-hint dependencies on your controller `__construct` method. When working on the administration, I suggest to use "tiny controllers", one controller per "route/action" so you can leverage dependencies with the constructor. For example:

```php
class ArrangementStoreController extends Controller
{
    private $request;

    public function __construct(Request $request)
    {
        $this->request = $request;
    }

    public function store()
    {
       $this->validate($this->request, [
           'arrangement_name' => 'required'
       ]);

       dd('storing');
    }
}
```

**Comment by pvdptje** [comment]
Thanks again for your fast response!
I'll go for that approach. 

The session issue, is that related to #621 ?

**Comment by pvdptje** [comment]
Closing this one!
