### ISSUE TITLE
child&parent page behave different depending on order

### ISSUE THREAD

**Issue by Jaspervv** [themosis/framework#717]
I don't know if this is expected behaviour; but admin pages behave different depending on which page you create first.

## First parent, then child
```php
$parent = Page::make('parent-page', 'Parent Page')
    ->set();

$child = Page::make('child-page', 'Child Page')
    ->setParent('parent-page')
    ->set();
```
results in both the parent & child page existing:
![image](https://user-images.githubusercontent.com/35364310/61617480-0f51ad80-ac6b-11e9-879d-008d10cedd61.png)

The child page links to `/cms/wp-admin/admin.php?page=child-page` which contains the expected page.

## First child, then parent
```php
$child = Page::make('child-page', 'Child Page')
    ->setParent('parent-page')
    ->set();

$parent = Page::make('parent-page', 'Parent Page')
    ->set();
```
Results in only the child page existing, but under the parent's name:
![image](https://user-images.githubusercontent.com/35364310/61617528-28f2f500-ac6b-11e9-8a88-bb4ec363422e.png)

The child page now links to: `/cms/wp-admin/child-page`,  which returns a 404.  
Going to `/cms/wp-admin/admin.php?page=child-page` also results in a 404.

**Comment by jlambe** [comment]
@Jaspervv This is weird but is it a framework issue or already a WordPress behavior ? Not sure to dig into this as it doesn't make sense to first define a child page and then its parent.
