### ISSUE TITLE
fields not showing in metaboxes

### ISSUE THREAD

**Issue by spider-mane** [themosis/framework#719]
I'm unable to get any fields to show up inside metaboxes. I even copy and pasted an example from the documentation and nothing happens

`
$postType = PostType::make('locations', 'Locations', 'Location')
            ->setArguments([
                'public' => true,
                'supports' => 'title',
            ])
            ->setTitlePlaceholder('Insert Location name here')
            ->set();

        $metabox = Metabox::make('info', $postType->getName())
            ->setTitle('Info')
            ->setContext('normal')
            ->setPriority('default')
            ->add(Field::choice('languages', [
                'choices' => [
                    'css',
                    'html',
                    'javascript',
                    'php'
                ],
                'expanded' => true,
                'multiple' => true
            ]))
            ->set();
`

that's the code i'm trying to run. I get the post type and metabox, but not fields. The installation is new, this is the only code I've added.

**Comment by jlambe** [comment]
@spider-mane Is there any errors on the browser console ?

Also, as this is a fresh installation, perhaps core assets are not loaded (this is generally done automatically upon installation but it already happened on some environments that the scripts didn't run). Try to run this from the console: 

```bash
php console vendor:publish --tag=themosis --force
``` 

Do you run your code from a [Hookable class](https://framework.themosis.com/docs/2.0/hooks/) or from another location ?

**Comment by spider-mane** [comment]
Don't know why I didn't think of checking the console. Turns out I was getting a status 500 because I hadn't installed the theme. With the theme installed, everything is working fine. Thanks for your quick response and mind-blowingly detailed product :-)
