### ISSUE TITLE
Form Transformer not working

### ISSUE THREAD

**Issue by xyNNN** [themosis/framework#724]
I want to convert a choice field into a comma-separated string before it will persists into the database. Normally I can use for this case a Data Transformer to solve this issue.

```
$interests = $fields->choice('interests', [
            'label'      => __('Interessen'),
            'choices'    => Customer::INTERESTS,
            'multiple'   => true,
        ]);
        
$transformer = new ArrayToStringTransformer();
$interests->setTransformer($transformer);
```

The main problem is that the transformer is not called. The documentation for this part is missing, so I don't how to handle this kind of feature.

Any hints?
Thanks!

**Comment by jlambe** [comment]
@xyNNN Generally the `setTransformer` is set internally on the field class. For example, if you look at the code for the `TextType`, the `setTransformer` is defined inside the `parseOptions` method.

The transformer should be attached before any execution, so perhaps using it on an instance receive by the factory is too late. Have you tried to create the field manually like so:

```php
$interestsField = (new ChoiceType('interests'))
    ->setTransformer(new ArrayToStringTransfomer())
    ->setLocale(app()->getLocale())
    ->setViewFactory(app('view'))
    ->setOptions([
        'label' => __('Interessen'),
        'choices' => Customer::INTERESTS,
        'multiple' => true
    ]);

return $factory->make()
    ->add($interestsField)
    ->get();
```

Hope this helps.

**Comment by xyNNN** [comment]
Thanks for your help @jlambe. I've tried your example out and it's not working for me.
After I've implement your example in one of my forms the data transformer is not call, even when I render the page or submit the form - Normally the method transform() or reverseTransform() is called.

**Comment by jlambe** [comment]
@xyNNN I'm going to look at this transformer issue, it would be great to be able to define one at runtime. If you have any suggestion regarding this, let me know!

**Comment by xyNNN** [comment]
Thanks @jlambe! Let me know, when I should test something.

**Comment by xyNNN** [comment]
Any ideas on this topic @jlambe? Perhaps we can solve this, to only set the default transformer in *parseOptions* when no transformer is defined? If this could be a way for you, I would provide a pull request for this.

**Comment by romainhe** [comment]
Hi @xyNNN, something has been done for that ? :o

**Comment by jlambe** [comment]
This is now supported on the upcoming release 3.0.
