### ISSUE TITLE
How do I run the framework on an existing WordPress installation

### ISSUE THREAD

**Issue by Sid-Development** [themosis/framework#727]
I was given a wordpress site developed using the themosis framework but I am struggling to put it to run on my local environment.

If I already have an existing wordpress installation, how do I run another theme that was build with themosis?

**Comment by maximusblade** [comment]
@Sid-Development  I once tried that. minimal success.
Try installing a fresh instance of themosis..
Then move your plugins...and migrate your project slowly.
Start with your routing.

**Comment by jlambe** [comment]
@Sid-Development You can't or at least not without losing your hair :) The Themosis framework is a stack of librairies and dependies including WordPress. Basically you just have to set your local HTTP server to point on the project `htdocs` directory and that's it.

Now if you have what I call a classic WordPress installation and simply copy/paste the theme from the Themosis project, you'll get errors for non existing functions, classes, ...

You probably inherited a project from version `1.2` or `1.3` of the framework. You might want to look at the getting started docs (installation) for those versions here:

- [1.3](https://framework.themosis.com/docs/1.3/introduction/)
- [1.2](https://framework.themosis.com/docs/1.2/introduction/)
