### ISSUE TITLE
Front-end ajax error

### ISSUE THREAD

**Issue by Neidra** [themosis/framework#729]
Hey everyone,

I already use the Ajax in my Admin Dashboard with any problem.
I'm currently working on contact form which use Ajax for sending my email (and doing other stuff).
So i tried the documentation example.

```
$.ajax({
   url: themosis.ajaxurl, // Global access to the WordPress ajax handler file
   type: 'POST',
   dataType: 'json',
   data: {
      action: 'my-custom-action', // Your custom hook/action name
      security: 'add-posts', // A nonce value
      number: 2 // The value you want to send
   },
   error: function (request, error) {
      console.log('Ajax error');
   }
}).done(function (data) {
   console.log(data);
});
```
So my action don't return 4 but "Ajax error"

I use the same Ajax function in the backend.

Thanks for you help.
AD

Edit: I forgot to specify i'm still (for the moment) on themosis 1.3

**Comment by jlambe** [comment]
What does the browser console say and is the `themosis.ajaxurl` value is the URL to `admin-ajax.php` ?

**Comment by Neidra** [comment]
Like i said the console just log `Ajax error`. So about `themosis.ajaxurl` that return `http://development.loc/cms/wp-admin/admin-ajax.php`.
I don't what coulid i do.. i have some ajax function used on my back office working well.. But in the front that sucks.

**Comment by jlambe** [comment]
Instead of doing `console.log('Ajax error')`, you might consoel the `error` object instead. Also, when running the ajax request, from browser "Network" developper tool, can you check the `xhr` request/response for your code ? You might get more detailed information about your issue.

Finally, from the code sample, the `security` property should in fact a nonce value, so the output should be:

```php
// ajax object filter...
$data['security'] = wp_create_nonce('add-posts'),
```

**Comment by Neidra** [comment]
Hey @jlambe ,
Thanks for your message, i just found my mistake (but i need some explanations).
In my previous message i was executing the server code in the ``init`` action hook, so i just put it outside of any hook and the code is ok.
So i will change my source code for integrating this issue.
