### ISSUE TITLE
Can't change field prefix for TaxonomyField

### ISSUE THREAD

**Issue by MoiseScalzo** [themosis/framework#732]
I was trying to add a custom field for a custom taxonomy term.
This the code:
```php
$author = Taxonomy::make('author', 'my-custom-post-type-name', 'Authors', 'Author')
    ->set();

$urlField = Field::text(
	'link',
	[
		'label'       => 'Url',
		'data_type'   => 'string',
		'rules'       => 'url'
	])->setPrefix('_custom');

TaxonomyField::make($author)
	->add($urlField)
	->set();
```
During tests I noticed that the `->setPrefix` isn't working and the field name still remain like `th_link` instead of `_custom_link`.

All the environment is working with last framework version.

**Comment by jlambe** [comment]
Hmm I need to look for this, you might have find a code issue ;) Would you like to search for this and propose a PR ?

**Comment by Bartiff** [comment]
I also encounter the problem

**Comment by jlambe** [comment]
@MoiseScalzo Sorry for this late answer but in fact, you can define the prefix for your taxonomy fields globally from the `TaxonomyField` class by passing an `$options` array as a second parameter of the `make()` method like so:

```php
$author = Taxonomy::make('author', 'my-custom-post-type-name', 'Authors', 'Author')
    ->set();

$urlField = Field::text('link', [
    'label'       => 'Url',
    'data_type'   => 'string',
    'rules'       => 'url'
]);

TaxonomyField::make($author, [
        'prefix' => '_custom_'
    ])
    ->add($urlField)
    ->set();
```

I'll try to update the documentation for this. The `prefix` will be applied to all attached fields.
