### ISSUE TITLE
themosisGlobal is not defined

### ISSUE THREAD

**Issue by guramsutidze** [themosis/framework#733]
![image](https://user-images.githubusercontent.com/10806739/64159910-fdf3e780-ce4b-11e9-9b64-0c29523ff6ce.png)

This error appears on every page of the admin panel

**Comment by jlambe** [comment]
Hello @guramsutidze,

which version of the framework are you using ? Is it happening on a fresh installation ?
Normally the global variable is defined inside the `app/Hooks/Application.php` file. Do you have that hook class loaded from your `config/app.php` file under the `hooks` property ?
