### ISSUE TITLE
Wordpress Permalink Interrogation

### ISSUE THREAD

**Issue by Neidra** [themosis/framework#735]
Hey,
I have an interrogation about Wordpress more than Themosis. I'm thinking about the possibility in Wordpress to build a Custom post type permalink like that :
```
/products                [archives]
/products/<taxo-slug>           [taxonomy]
/products/<taxo-slug>/<product-name>          singular]
/products/<product-name>          [singular]
```
So if my product has a taxo, I use the `taxo-slug` on the permalink if not i push my `product-name` just after my root.
Another question is  about the root link `/products` how i determine my route like a template ?
Thanks for your help.
Ad

**Comment by jlambe** [comment]
Hello @Neidra,

indeed this is a WordPress thing, perhaps this article can help you: https://wordpress.stackexchange.com/questions/108642/permalinks-custom-post-type-custom-taxonomy-post

**Comment by Neidra** [comment]
Hey @jlambe ,
Just to specify i used the following ressources  which explain the utility of ``do_parse_request`` filter : 
[(https://roots.io/routing-wp-requests/)]
