### ISSUE TITLE
Custom route - page title

### ISSUE THREAD

**Issue by vasikgreif** [themosis/framework#737]
I defined a custom route:

```
Route::any('/contact','Contact@contact');
```

The page is displayed fine including the content, but the page title says "Page not found". I don't see in the docs how to set the custom route title..?

**Comment by jlambe** [comment]
Can you post your current implementation of the above snippet within the controller ?

**Comment by vasikgreif** [comment]
Hello, it started magically to work now, sorry..:) Thanks!

**Comment by BenceSzalai** [comment]
Note: For anyone facing similar issue, note that Yoast SEO may override the page title to "Page not found" when the page only exist in the route definitions, but not in WordPress. I'll try to find a solution and post it here, but so far I haven't got the time, beside creating a dummy page in WordPress with the same slug used in the routes, so Yoast can pick up a proper Title.

**Comment by Bartiff** [comment]
```php
Filter::add('wpseo_title', function ($title) use ($post) {
    $title = $post->post_title;
    return $title;
});
```
