### ISSUE TITLE
Forms - fields with arrays

### ISSUE THREAD

**Issue by vasikgreif** [themosis/framework#739]
I need to build a form to enter multiple visitors data. I wanted to use the arrays, so I tried something along these lines:

```php
		for ( $i = 0; $i < $user->actual_partner->remaining_tickets; $i ++ ) {

			$form->add( $fields->text( 'visitor[' . $i . ']first_name',
					'placeholder' => __( 'First name', 'brokerkongres' ),
					'label'       => __( 'First name', 'brokerkongres' ),
					'group' => $i
				] ) )
			     ->add( $fields->text( 'visitor[' . $i . ']last_name',
				     [
					     'placeholder' => __( 'Last name', 'brokerkongres' ),
					     'label'       => __( 'Last name', 'brokerkongres' ),
					     'group' => $i
				     ] ) );
        }
```
That does not work for some reason, the data is not passed to the `$_POST ` correctly. Is there any way to do this, and also, is there any way to validate each group of fields?

**Comment by jlambe** [comment]
Hmm seems it is working but the `name` attribute syntax is not correct somehow. You do get 8 `th_visitor` fields but the data is not split has you expected. What happens with this `name` attribute value instead: `visitor[]['first_name']`, `visitor[]['last_name']`, ... ?
