### ISSUE TITLE
assets not loaded in themosis

### ISSUE THREAD

**Issue by Mohammed-Alama** [themosis/framework#741]
I have install themosis corectlly on valet and it is work now but the problem is the assets never loaded and wp-admin is work but with out any css or js effects

**Comment by jlambe** [comment]
@Mohammed-Alama Not sure I can help you on this as we haven't documented Valet with the framework but for what I can assume is that your Valet configuration is missing a way to handle static files like .css and .js files. Our recommandation for now would be to use Homestead.

**Comment by Mohammed-Alama** [comment]
I try to get it , Thanks
