### ISSUE TITLE
Support Wordpress shutdown lifecycle

### ISSUE THREAD

**Issue by ntsim** [themosis/framework#748]
Currently Themosis delegates the final response output to Laravel's `Response` class by calling `Response.send()`. Whilst this isn't immediately a problem, some WordPress plugins such as Query Monitor rely on WordPress' `shutdown` hook to render their HTML.

This hook is executed by `register_shutdown_function` which only executes _after_ the HTML has already been sent off to the user. Consequently, the user will not see any of this output. This basically causes such plugins to break.

It would be good if Themosis could actually support the `shutdown` hook in some way, although I'm not entirely sure how feasible this is given how `Response.send()` works.

### Potential solution

One thing I've done in `Application.manage()` to get around this:

```php
$response = $kernel->handle($request);

shutdown_action_hook(); // This calls the `shutdown` hook

$response->send();
```

Unfortunately, this _can_ cause a flash of unstyled HTML as the output from WordPress gets flushed (as is the case when Query Monitor is installed). This is probably not optimal as WordPress will eventually call `shutdown` again when `register_shutdown_function` eventually kicks in.

I'm also not sure if this could lead to other undesirable output from WordPress, but from what I've seen this doesn't seem to be the case.

**Comment by jlambe** [comment]
This is something to test indeed. While the framework is using the `Response` class to render its content, in the end, it is mainly just a `echo $response->send()`.

Perhaps we need to look at the shutdown function registered by the framework. I'm wondering if we can register multiple functions on this or not, that's probably the issue 🤔 if the framework is taking precedence over the one registered by WordPress.

**Comment by ntsim** [comment]
> I'm wondering if we can register multiple functions on this or not, that's probably the issue thinking if the framework is taking precedence over the one registered by WordPress.

It seems that `Response.send` closes the request and sends off the response immediately. See the following:

```php
if (\function_exists('fastcgi_finish_request')) {
    fastcgi_finish_request();
} elseif (!\in_array(\PHP_SAPI, ['cli', 'phpdbg'], true)) {
    static::closeOutputBuffers(0, true);
}
```

This prevents any additional output from being sent in the response which is the culprit.

I've played around with this a little more and to circumvent this, we can just manually call the `Response` output methods (instead of `Response.send`) i.e.

```php
$response = $kernel->handle($request);
$response->sendHeaders();
$response->sendContent();
```

This allows WordPress to then finish running its own shutdown and echo its output naturally. This nicely avoids the flash of unstyled HTML I mentioned earlier as well.

I think this might be the best solution as it hands off output responsibility to WordPress.

**Comment by LukeAbell** [comment]
@ntsim @jlambe thanks for your work on this. I'm working on implementing this in a fork. Do I also need to remove the `$kernel->terminate($request, $response);` or is that safe to keep?

**Comment by ntsim** [comment]
No problem @LukeAbell, don't think you need to remove `terminate` as it just runs Laravel's own cleanup cycle.
