### ISSUE TITLE
Comment Edit in Admin Panel Error

### ISSUE THREAD

**Issue by msufiannasir** [themosis/framework#749]
- Themosis Version: 2.0
- WordPress Version: 5.2.4
- PHP Version: 7.2.0

### Description
When I edit comment from the admin panel it shows an error on edit screen see screenshot https://i.imgur.com/mL6PkzL.png

### Steps to reproduce
WP Admin>> comments >> Edit any comment

### Expected behavior
It should allow comments editing without any error

**Comment by jlambe** [comment]
Hello @msufiannasir, by testing this on a fresh installation, I was not able to reproduce your issue.

Sounds like you might have defined a custom metabox at some point that might trigger this issue. Could you provide a code sample of your metabox so I can also try that scenario ?
Thanks

**Comment by msufiannasir** [comment]
Yes I defined custom metabox for different post types but not for Comments. Here is an example how i defined metabox.
//custom Field Registration for Custom Post Type 'Group Areas'
Metabox::make('Areas-Fields', 'areas')
        ->add(Field::choice('region', [
                    'choices' => $regions,
                    'rules' => 'required',
        ]))
        ->add(Field::text('rss_title'))
        ->add(Field::collection('button_icon', [
                    'label' => 'Group Icon',
                    'limit' => 1,
        ]))
        ->set();

**Comment by msufiannasir** [comment]
Did you check my sample code?

**Comment by jlambe** [comment]
@msufiannasir Yes, I've just tested and indeed there is an issue here when we try to edit the comment.

The issue is because the expected type is a `WP_Post` for a metabox which is not the provided one when editing a comment.

Nice catch! Do you think you could check for this and submit a PR?
