### ISSUE TITLE
WP functions not defined inside Scheduler

### ISSUE THREAD

**Issue by vaclavgreif** [themosis/framework#750]
I wanted to use the Scheduler to manage my cron jobs, but when I define a test function:

```php
    /**
     * Define the application's command schedule.
     *
     * @param Schedule $schedule
     */
    protected function schedule(Schedule $schedule)
    {
	    $schedule->call(function () {
		    get_post_meta(1,'test',true);
	    })->daily();
    }

```

and start the scheduler `php console schedule:run`, I end up with ` Call to undefined function get_post_meta()`. 

Any chance to fix this?

**Comment by jlambe** [comment]
This is probably the same issue we currently have with custom commands. I'm pretty sure a fix is possible. We need to load WordPress.

I don't have a solution yet for you but pretty sure a similar mecanism can be put in place based on the [fix](https://github.com/themosis/framework/pull/706) for the command API. I'll probably put the load of WordPress as optional, depending on the developer needs.

**Comment by vasikgreif** [comment]
Well, I can also schedule commands. Are you going to merge the PR request for fixing the command API soon? Thanks!

**Comment by jlambe** [comment]
@vaclavgreif WordPress functions can now be supported in commands. The feature is coming with next release 3.0 but you can already try using the `main` branch of the project.
