### ISSUE TITLE
Custom status not working

### ISSUE THREAD

**Issue by guramsutidze** [themosis/framework#751]
- Themosis Version: 2.0.4
- WordPress Version: 5.3
- PHP Version: 7.1.32

### Description
Add custom status not working.

### Steps to reproduce
       PostType::make('excursion', 'Excursions', 'Excursion') -> setArguments([
            'public'        => true,
            'menu_position' => 5,
            'supports'      => ['title', 'editor', 'excerpt', 'author', 'thumbnail'],
            'has_archive'   => false,
            'menu_icon'     => 'dashicons-location-alt'
        ]) -> set() -> status('expired);

**Comment by jlambe** [comment]
@guramsutidze It seems there is an error on the documentation.

The `status()` method should be called before the `set()` method. Try to first define the custom status and then later register everything by calling the `set()` method on your custom post type like so:

```php
PostType::make('excursion, 'Excursions', 'Excursion')
    ->setArguments([...])
    ->status('expired')
    ->set();
```

**Comment by guramsutidze** [comment]
It still does't works

**Comment by jlambe** [comment]
@guramsutidze The following code snippet is working on a new installation as expected:

```php
PostType::make('excursion', 'Excursions', 'Excursion')
    ->status('expired')
    ->set();
```
