### ISSUE TITLE
How does Themosis Framework work with WordPress CMS?

### ISSUE THREAD

**Issue by joelataylor** [themosis/framework#76]
Basic question, wasn't sure where else to ask.

If I create a page in WordPress - do I also have to create the route & view in the theme? I must be missing something, as what would be the point of having WordPress CMS?

**Comment by joelataylor** [comment]
Nm. :) I played a lil more and figured out that if you have a default route (for any page like your documentation states) : 
```
Route::get('page', function(){

    return View::make('static-page');

});
```
Then have a view: static-page.scout.php
```
@loop
<h1>{{ Loop::title() }}</h1>
    <div>
        {{ Loop::content() }}
    </div>
@endloop
```
Everything works. :)

**Comment by jlambe** [comment]
Hi,

I will still answer your question :)) First, some context, Themosis framework is just a WordPress plugin. So when you say you're working with the Themosis framework, you're just stating that you're working with WordPress. The Themosis framework is useless without WordPress.

So what this implies is that you can do typical WordPress development with the Themosis framework. The Themosis framework only gives a code structure and some APIs that are shortcuts to existing WordPress APIs or new ones.

By default, the `theme` only contains the `index.php` file  to listen for the requests. And in place of adding files at the root of your theme (page.php, sidebar.php, archive.php, ...), you only define some rules inside the `app/routes.php`. The route class is a more granular way of using the default WordPress conditionnal functions.

I'm glad you figured out how it works. If you want to learm more on how to work with the framework, the code of the documentation website in public under the `themosis/website` repository. Don't hesitate to look at it ;)

**Comment by joelataylor** [comment]
Yep I think it was just a lil jarring when I tried to access the WP sample page, and I was given a route error. Maybe a generic route for all pages should be added during the install? Also, is there a way to auto select the Themosis theme on installation? That caught me off guard as well. Got the white screen of death until I switched theme.

**Comment by jlambe** [comment]
Adding a generic page route at install might be a good idea.
Yes, it will be great to auto-activate the theme, any ideas how ?

**Comment by joelataylor** [comment]
I'm super impressed with your responsiveness! :) 
WP has a theme switching function: http://codex.wordpress.org/Function_Reference/switch_theme

**Comment by jlambe** [comment]
The thing with this function is that you need to specify the theme folder name which by default is `themosis-theme`. But as suggested in the docs, you can rewrite the theme folder name to match your project so... It might not be the right solution.

As there is only one theme inside the themes directory, I would like WordPress to auto-activate the only one available (when there is only one actually). I'm still confusing about why it is always looking by default to their own `twenty-something` theme.

About support responsiveness :) it depends, it sometimes take longer but as a user first, I don't like asking questions and wait too long so I'm doing my best to answer back as fast as I can :)

**Comment by joelataylor** [comment]
You're right, it would be nice of WordPress to activate the only theme available! After thinking about this, I think you could just keep it simple. During setup the theme is named `themosis-theme` so you could activate it.

You tell people to activate the theme in your docs (which I didn't read haha!) but on the next page: http://framework.themosis.com/docs/framework/ where you tell people to rename the theme folder, you can also remind them they'll need to reactivate the theme.

This is by no-means a big issue, I just didn't read the docs properly, so when I got WP setup and visited the URL, I got a white screen. If I had followed directions and activated the theme, THEN looked at the frontend, everything would've worked as expected.

**Comment by jlambe** [comment]
Well that's probably a good catch. Can you open another issue for this so I can review it later ? Thanks.
