### ISSUE TITLE
Add rescue() helper function

### ISSUE THREAD

**Issue by jlambe** [themosis/framework#764]
Add the `rescue()` helper function to core. This helper function is part of the illuminate foundation and might be requested by third party packages.

[See issue](https://github.com/themosis/themosis/issues/326)

**Comment by jlambe** [comment]
Done.

**Comment by ogorzalka** [comment]
It would be great to have the illuminate/testing package too. There's many package which requires it (ex. Livewire, Laravel response cache by Spatie).
