### ISSUE TITLE
Field Editor parameters

### ISSUE THREAD

**Issue by dgines** [themosis/framework#765]
- Themosis Version: 2.0.5
- WordPress Version: 5.3.2
- PHP Version: 7.3

Hello, I´m trying to show more buttons in custom editor fields like in documentation says, but It doesn't work.

Field::editor('description', [
                    'label' => 'Description',
                    'teeny'=>true, 'textarea_rows'=>5, 'editor_class'=>'csec_text', 'textarea_name'=>'csec_text', 'wpautop'=>false,
                    'tinymce'=>array('plugins' => "table,lists,link,textcolor,hr",
                        'toolbar1'=>"fontsizeselect,forecolor,backcolor,bold,italic,underline,strikethrough,alignleft,aligncenter,alignright,alignjustify",
                        'toolbar2'=>"blockquote,hr,table,bullist,numlist,undo,redo,link,unlink")
                ]),

**Comment by jlambe** [comment]
Hello, sorry but this repository is no longer used for support. For help, you can subscribe to [our support platform](https://support.themosis.com) or perhaps ask your issue on the [Gitter room chat](https://gitter.im/themosis/framework).
