### ISSUE TITLE
Error on spatie/laravel-medialibrary package installation

### ISSUE THREAD

**Issue by NicoGill** [themosis/framework#766]
- Themosis 2.0.5
- WordPress Version: 5.3.2
- PHP Version: 7.3

### Description

I would like to use **spatie/laravel-medialibrary v7** package in my project but it's throw an error on installation : 

`In ImageServiceProvider.php line 69 : 
Class "Illuminate\Foundation\Application' not found.` 

It's the same issue with [#326 on themosis/themosis](https://github.com/themosis/themosis/issues/326) but I'm wondering if there is a solution ?

Thank you,

**Comment by jlambe** [comment]
@NicoGill unfortunately the package is not compatible because it requests a Laravel only class. If the package would have used the `Container` interface, it could have been compatible. Perhaps check with the package author for a PR on this.
