### ISSUE TITLE
Field input max-width conflict

### ISSUE THREAD

**Issue by jlambe** [themosis/framework#769]
- Themosis Version: 2.0.5
- WordPress Version: 5.3.3
- PHP Version: 7.3

### Description

By default, Themosis field inputs have a `max-width` CSS property set to `260px`. The CSS rule should only target fields inputs displayed on a `side` context within a metabox.

### Steps to reproduce

Create a metabox with a `Field::text()` like so and renders it outside the sidebar:

```php
Metabox::make('test', 'page')
    ->add(Field::text('something'))
    ->set();
```

### Expected behavior

The input width should not be controlled by a `max-width` CSS property, at least not outside the sidebar. Users can fix this temporarily by providing a custom CSS `class` attribute to the field.

**Comment by reneroboter** [comment]
Is this issue already open @jlambe ?
