### ISSUE TITLE
How to use PhpStorm for class methods

### ISSUE THREAD

**Issue by joelataylor** [themosis/framework#77]
I'm using PhpStorm and I'm trying to get it to recognize the available methods on the Themosis classes, but I guess due to some abstraction in the 'Facades' - it can't recognize methods. So something like this in the theme/app/admin/application.php file doesn't work:

```
use \Themosis\Facades\PostType as PostType;
PostType::make('slug-books', 'Books', 'Book')->set();
```

Any suggestions?

**Comment by jlambe** [comment]
Hi,

I'm using also PhpStorm for development. As you said, because of the 'facades' abstraction, PhpStorm can't give code completion. This is the same issue as with the Laravel framework. To get this working, we need to add at the root of the projet a `ide_helper` file that contains all the classes and methods of the framework so we'll be able to get code completion.

I still didn't have the time to generate this file. If you know a way to automate this process, I'll be glad ;)

**Comment by joelataylor** [comment]
Does this generator package look like it'd help? https://github.com/barryvdh/laravel-ide-helper

Unfortunately I haven't used Laravel before so I'm not fully understanding the readme.

**Comment by jlambe** [comment]
Yes that's exactly what we need but I still haven't had the time to try it or probably install it by default with the framework.

**Comment by girvo** [comment]
:+1: I'd absolutely love this feature. The IDE Helper (https://github.com/barryvdh/laravel-ide-helper#automatic-phpdoc-generation-for-laravel-facades) can generate the helper based on the PHPDoc data, so perhaps it's possible to configure it to work with Themosis?

**Comment by jlambe** [comment]
Probably but I haven't had the time to explore the class as I need to focus on finishing latest issues for release 1.2.0. Is this something you could look at?

**Comment by piszczek** [comment]
Hello
Is there any progress about that?

**Comment by jlambe** [comment]
Not but as next version is using more illuminate packages, we already gain a better auto-completion. But a ide helper is still needed for full completion.

**Comment by rumur** [comment]
Hi!

Can anybody help me with this file?
How can I generate it? 

Please guide me.

Thanks.

**Comment by jlambe** [comment]
Hi @rumur, I haven't yet looked at it personally, sorry. Will add this feature request for a minor release perhaps and try to improve into the auto-completion field here.

**Comment by jlambe** [comment]
Moved currently to release 1.4.0.

**Comment by jlambe** [comment]
@joelataylor Sounds like the upcoming release 2.0 has better support for the `laravel-ide-helper` package. I mark this as fixed for now and I encourage you to share issues with @effectjared as I personnaly haven't tried yet that package.
