### ISSUE TITLE
is_main_query returns false inside the pre_get_posts Action hook

### ISSUE THREAD

**Issue by ligne13** [themosis/framework#772]
- Themosis Version: 2.0.5
- WordPress Version: 5.3.2
- PHP Version: 7.2

### Description
I'm trying to use the `pre_get_posts` action hook inside the `ArchiveController` to modify the `posts_per_page` value. 
The problem is that the check for `is_main_query` returns false.
However, if I test the `is_main_query` outside the hook callback, on the global `$wp_query` object, I get true.

### Steps to reproduce
```
class ArchiveController extends Controller
{
    public function index()
    {
        Action::add(
          'pre_get_posts',
          function ($query) {
            var_dump($query->is_main_query()); // returns false
            if (!is_admin() && $query->is_main_query()) {
             $query->set('posts_per_page', 12);
            }
          }
        );
        global $wp_query;
        var_dump($wp_query->is_main_query()); // returns true
    }
}
```

### Expected behavior
`$query->is_main_query()` should return true inside the hook.

**Comment by jlambe** [comment]
This is expected as a `pre_get_posts` hook is triggered before the controller. At the time you call it from a controller, the main query is already done. Actions should be only defined inside a Hook class.

**Comment by ligne13** [comment]
OK thanks Julien !
