### ISSUE TITLE
Laravel v7/v8 Support

### ISSUE THREAD

**Issue by LukeAbell** [themosis/framework#774]
I know Laravel v6 support is in the master branch which hasn't been released yet - any plans to work on upgrading to Laravel V7?

**Comment by LukeAbell** [comment]
I've started adding support for Laravel 7 in a fork - not sure how much is remaining, but things are at least functional https://github.com/blueoceanideas/themosis-framework/tree/laravel-7

**Comment by tavo1987** [comment]
Hello @LukeAbell  @jlambe  there is some progress on this. I would like to help with this upgrade to Laravel 7.

Since Laravel 5.8 is no longer supported, the latest security updates according to the release notes were only until February 26th, 2020

https://laravel.com/docs/master/releases#support-policy

**Comment by rovillesarate** [comment]
When would the upgrade be ready?

**Comment by BenceSzalai** [comment]
Meanwhile Laravel v8 is out.

Probably first the situation would need to be clarified. The `master` branch relies on v5.8 packages. There is another branch called [`laravel-6`](https://github.com/themosis/framework/tree/feature/laravel-6) with Illuminate packages bumped to v6.6. But it is not clear if it is ready for prime time, or what is blocking it to become the next release version?

On one hand the logical approach seem to be to follow a step-by-step upgrade path: v5.8 -> v6(.6) -> v7 -> v8.

@LukeAbell: did you base your Laravel 7.3 fork on `master` or `laravel-6`?

More info: 

We can see there is v2.1 milestone tracked here for the framework: https://github.com/themosis/framework/milestone/17

We can also find a 3.0 project here: https://github.com/themosis/framework/projects/3

I couldn't find any mention of updating Laravel or Illuminate packages under any of them.

If the Framework features and fixes block the release cycle, than the Framework updates will fall behind Laravel too bad sooner than later. Probably Laravel version bumps should enjoy higher priority than Themosis Framework features...?

**Comment by LukeAbell** [comment]
@BenceSzalai https://github.com/blueoceanideas/themosis-framework/tree/laravel-7 is stable. We've been using it in production for months now with a huge application. We based it on the 2.0 branch and merged in most of the feature branches + the laravel-6 branch during the upgrade process.

**Comment by BenceSzalai** [comment]
That sounds great!

Github says it is 11 commits behind this repo though. Are those irrelevant due to differences between Laravel 6 and 7 or why is that? Don't get me wrong, I'm just curious.

**Comment by armycoder** [comment]
How many deprecated features does themosis actually use?

**Comment by LukeAbell** [comment]
@BenceSzalai I've completely upgraded to Laravel 8 in [this branch](https://github.com/blueoceanideas/themosis-framework/tree/laravel-8-with-core-upgrade). I've also completely updated the foundation (core folder in Themosis) folder to match Laravel 8. We've been using this in production for about a month on a **very** large application and it's working great.

I think @jlambe is going to review it and get Themosis officially upgraded at some point. Feel free to use it and let me know if you're seeing any issues.

**Comment by armycoder** [comment]
@LukeAbell do you have a record of what you changed on the themosis/themosis side? Various classes are moved and missing.

**Comment by armycoder** [comment]
@LukeAbell in particular my current problem is the console facade is missing

**Comment by robertbossaert** [comment]
@armycoder in your config/app.php

```
'Console' => Themosis\Core\Support\Facades\Console::class,
```

becomes

```
'Artisan' => Themosis\Support\Facades\Artisan::class,
```

**Comment by armycoder** [comment]
Yeah I figured that out. Now my only problem is content is repeated twice no matter what I do. I keep checking my code to see if it's mine and I don't think it is. I tried a fresh install and it still does it.

**Comment by robertbossaert** [comment]
Can you check what happens when you remove the lines that were added [here](https://github.com/blueoceanideas/themosis-framework/commit/6179496df5c1b63db8d19dc034dd9b7efa50f7e1)?

**Comment by armycoder** [comment]
If I remove `$response->send intent();` then it doesn't repeat.

**Comment by armycoder** [comment]
Any updates?

**Comment by jlambe** [comment]
Laravel 8 support is currently in progress on the `themosis/framework` `master` branch. No release date scheduled but you can already test it if you feel adventurous 😃 
I'm going to close this issue as work as started on this.

**Comment by armycoder** [comment]
I was more wondering about the duplicate content. That's what is stopping me from using the dev branch
