### ISSUE TITLE
When to load Action::add()

### ISSUE THREAD

**Issue by edwinsiebel** [themosis/framework#779]
Hi,

I'm trying to look `Action::add('hook', 'callback');` from a service provider, instead of the hook-section in `app.php`:

```php
<?php

namespace App\Search;

use Illuminate\Support\ServiceProvider;

class SearchServiceProvider extends ServiceProvider
{
    public function register()
    {
        $this->app->registerHook(\App\Search\Hooks\FacetWPResultCount::class);
    }
}
```

However, it complains about:

`Symfony\Component\Debug\Exception\FatalThrowableError (E_ERROR)
Call to undefined function add_action()`.

It sounds like the function `add_action` is not loaded yet.

Am I calling the `registerHook` wrong?

**Comment by jlambe** [comment]
Hi,

yes, WordPress hooks should not be registered inside a service provider but inside a `Hookable` class instead. See the Hooks documentation for details:
 - https://framework.themosis.com/docs/2.0/hooks

If you need more support for your Themosis implementation, make sure to check our dedicated platform: https://support.themosis.com

We only use GitHub issues for framework source code bugs.

**Comment by edwinsiebel** [comment]
I understand that. But how to execute the class which extends `Hookable`? Can it only be executed in the `app.php`?

**Comment by jlambe** [comment]
Yes only there. But would you suggest another idea to instantiate those classes ?

**Comment by edwinsiebel** [comment]
Well, in stead of having every hook registered in `app.php`, I'm turning into more [Domain oriented components](https://stitcher.io/blog/laravel-beyond-crud-01-domain-oriented-laravel).
This states that all logic for a specific domain, is grouped into one "group", "module"; some people call them "service".

It would be pretty nice to use a `Hookable` class in a serviceprovider as such:

```php
Action::fire(HookableClass::class);
```
or
```php
Filter::fire(HookableClass::class);
```

The `fire` method is arbitrary and could be named anything.
