### ISSUE TITLE
On install activate default theme

### ISSUE THREAD

**Issue by joelataylor** [themosis/framework#78]
If some users *cough cough* don't follow the install instructions and _forget_ to activate the Themosis theme, and visit the frontend of their new WP install, they'll get a white screen of death.

Suggest to call out stronger the need for users to activate the only theme installed. Or even better, perhaps auto activate the default theme. If auto-activating, you'll need to remind users that if they change the theme folder they may need to reactivate the theme.

**Comment by aguidis** [comment]
:+1: 
I just met the " white screen of death."... Indeed at the end of the instructions, when I saw "install WordPress", I continued to follow the guide in my browser so I didn't read the sentence : "Log in your WordPress administration and activate the Themosis theme." It was my fault but I suggest to emphasise this sentence or  auto activate the default theme like @joelataylor

**Comment by jlambe** [comment]
Yes I'm aware of this user experience but I actually haven't figured it out.
One issue is if people rename the theme folder they still have to re-activate their theme. I'm looking to solve this for release 1.2 normally.

**Comment by jlambe** [comment]
Still haven't found any solution for this except displaying in LARGE text the notice on docs.

**Comment by ramon-villain** [comment]
@jlambe This could be wrong, but I defined
```
define('WP_DEFAULT_THEME', 'themosis-theme' );
```
In my shared.php file and it's working…

**Comment by jlambe** [comment]
@ramon-villain Didn't know about that constant. Then I suppose we can add it and specify in the docs to change its value if theme folder name has changed.

Will add it for this release but will try to find a way to automate this process of renaming the `themosis-theme` at installation. Thanks @ramon-villain !

**Comment by jlambe** [comment]
After some thoughts, I will add this for release 1.3.0 where we'll be able to create plugins as well and separate the application logic from the theme.

**Comment by ramon-villain** [comment]
:100: 
1.3 will arrive 2016 early?

**Comment by jlambe** [comment]
I can't give you a date for release 1.3.0. but note that before hitting that release there will be also a revamped documentation website ;)

**Comment by jlambe** [comment]
Added the constant on main themosis repository. It should save some forum issues 😜  If people rename their theme and they **MUST/SHOULD** do it, the constant will not be affected or act as when there was no constant defined.
