### ISSUE TITLE
wp-cli media : no images found

### ISSUE THREAD

**Issue by ligne13** [themosis/framework#780]
- Themosis Version: 2
- WordPress Version: 5
- PHP Version: 7.3

### Description
WP CLI returns the message "Warning: No images found." when running "wp media regenerate all".

I guess WP CLI does not know the path to uploads in the Themosis directory structure.

Is there a way to fix this ?

**Comment by ligne13** [comment]
Sorry, my mistake...

**Comment by movergan** [comment]
What was the reason?
