### ISSUE TITLE
Trying to integrate InertiaJs but having problems due to missing illuminate foundation

### ISSUE THREAD

**Issue by rovillesarate** [themosis/framework#785]
Themosis Version: 2.0.2
WordPress Version: 5.4.2
PHP Version: 7.4.7

### Description
Trying to integrate InertiaJs but having problems due to missing illuminate foundation
### Steps to reproduce
composer require inertia js <- went ok
one of the requirements in the app service provider require league/glide package
tried installing league glide but it require illuminate foundation and illuminate translation

tried installing illuminate foundation and illuminate translation but it keeps on install version 1.2 and is having problem coz the illuminate packages are locked at version 5.8 up

### Expected behavior

Be able to integrate inertiaJs to speedup development using vue or react without SPA setup.

**Comment by jlambe** [comment]
If the package is requesting classes from the `illuminate/foundation` package, then there is no way to fix this as this is not a standalone package. You have to ask the inertiajs author to stop referencing Laravel foundations classes in order to use their package outside a Laravel application.
