### ISSUE TITLE
Any plans on updating to the latest Illuminate package versions?

### ISSUE THREAD

**Issue by rovillesarate** [themosis/framework#787]
Hi! Is there any plans to upgrading the Themosis Illuminate package versions to the latest version?

In doing so we could use the spatie media library since it only requires latest illuminate packages.

**Comment by jlambe** [comment]
Yes it is planned but no release date defined right now. The master branch is holding compatibility with version 6 already but it is probably going to be pushed to directly support version 8 of Illuminate package in the future.
