### ISSUE TITLE
[Question] Themosis in wordpress plugin

### ISSUE THREAD

**Issue by jeremynikolic** [themosis/framework#788]
I've made some research and could not be certain regarding plugins. Found main info [in the doc](https://framework.themosis.com/docs/2.0/plugin)

A client of mine has a "classic" wordpress site for which I would like to develop some custom features using Themosis. I was wondering if there is some way to use  themosis inside a wordress plugin ? 
Which would allow me to not touch the current install, create the plugin and work in the nice context that Themosis provide.

Apologies if this as already been answered somewhere.

**Comment by marcell-ferenc** [comment]
@jeremynikolic you can install [themosis 1.3](https://framework.themosis.com/docs/1.3) as a must-used plugin in a classic wordpress environment, considering the latest themosis [version](https://framework.themosis.com/docs/2.0/introduction) (>2) i am not sure about that.
See the notes [in the installation guide](https://framework.themosis.com/docs/1.3/installation) and [Setup for Shared Hosting Environments?](https://github.com/themosis/themosis/issues/72#issuecomment-193906773).

**Comment by pagegwood** [comment]
We run 1.3 as an MU plugin on a variety of sites. Would love to know if anyone has tried to do the same with a 2.x version.

**Comment by jeremynikolic** [comment]
@marcell-ferenc Thanks for getting back to me. 
In the end it was chosen not to go with a wordpress plugin but will keep your recommendation for future work and give it a try.
