### ISSUE TITLE
Paginated route for 'home' return 404

### ISSUE THREAD

**Issue by ligne13** [themosis/framework#790]
- Themosis Version: 2.0.7
- WordPress Version: 5.4
- PHP Version: 7.3

### Description
I have two routes to display my blog:
```php
// Route for home blog
Route::any('home', 'ArchiveController@index');
// Route for categories
Route::any('archive', 'ArchiveController@index');
```
My 'home' route works: http://mysite.com/blog/
My paginated 'home' route return a 404: http://mysite.com/blog/page/2
My 'archive' routes (default and paginated) work: http://mysite.com/blog/category1/ and http://mysite.com/blog/category1/page/2

Why does the paginated 'home' route fails and return a 404 ?

thanks !

**Comment by ligne13** [comment]
Hi,

I'm still having this issue. Any help appreciated.

thanks !

**Comment by edwinsiebel** [comment]
I guess a bit more information what's in the `index` method of the `ArchiveController` could help your issue.
