### ISSUE TITLE
Composer 2 breaking change

### ISSUE THREAD

**Issue by simnom** [themosis/framework#800]
- Themosis Version: 2.0
- PHP Version: 7.2.33

Composer 2 has now been released but this introduces some breaking changes.  This affects the package autodiscovery within Themosis due to the `installed.json` file structure changing as detailed at: [https://github.com/composer/composer/blob/2.0.0/UPGRADE-2.0.md#for-integrators-and-plugin-authors](https://github.com/composer/composer/blob/2.0.0/UPGRADE-2.0.md#for-integrators-and-plugin-authors)

I've created a PR for this at #799 for review etc :-)

**Comment by SanderMuller** [comment]
I have this issue as well, thanks for the PR.

**Comment by jlambe** [comment]
@simnom Is this change a breaking change for users keeping composer v1.x ? I can allow the PR but I would like to be sure that it's not going to break for users not updating composer.

If this is a breaking change, I might only merge this on version 3 of the framework. Please let me know.

**Comment by SanderMuller** [comment]
@jlambe I think it's backwards compatible, see a similar change in core Laravel merged by Taylor: https://github.com/laravel/framework/pull/32331/files

Looking at #799 it will default pack to `$packages` if `'packages'` doesn't exist as a key on the array, which should be the composer 1 behaviour

**Comment by simnom** [comment]
@jlambe Yes this should be backwards compatible.  As @SanderMuller points out there's a similar change in the Laravel core.  I'm just checking for the new array key in the composer packages, using it if it exists, otherwise falling back to the v1 format.

**Comment by jlambe** [comment]
@simnom Your PR has been merged and Themosis framework release 2.0.9 has been released.
