### ISSUE TITLE
Update Themosis to Laravel 8

### ISSUE THREAD

**Issue by araeuchle** [themosis/framework#802]
Hi guys, 
i wonder by any chance if its possible to upgrade Themosis from Laravel 5.8 to laravel 8 or at least laravel 6 LTS. 
Is this possible?

if so how can we achieve this?

Best Regards!

**Comment by robertbossaert** [comment]
There is a discussion on upgrading to Laravel 7 going on here: https://github.com/themosis/framework/issues/774

**Comment by emanueljacob** [comment]
+1

although it seems like this is already in progress: see https://github.com/themosis/framework/issues/774#issuecomment-758578534

**Comment by jlambe** [comment]
@araeuchle @robertbossaert @emanueljacob An upgrade to Laravel 8 is in progress. You can follow the `master` branch for latest changes. I'm closing this issue. For a release date, it will be announced on our [Twitter account](https://twitter.com/themosis).
