### ISSUE TITLE
Helper for creating end points

### ISSUE THREAD

**Issue by nathanaelphilip** [themosis/framework#81]
Are there plans for creating a helper class to make new endpoints? 

I think it would be a nice feature, so we don’t have to create subpages for everything if we don’t need to edit the content on those pages/routes.

**Comment by jlambe** [comment]
Was thinking about this recently. Currently there is no API ground set for this as I would like to see the WP-JSON API fully integrated into WordPress core.

Then it will be great to synthesize the current WordPress endpoints/Rewrite API and the JSON API into one clear API.

**Comment by jonsource** [comment]
Currently it is possible to hijack the 404 route and do some custom routing on your own by examining the $_SERVER["REQUEST_URI"] variable. Here is a simple example:

```php
Route::any('404', function($post){
    $custom_routes = array(
        '/about'=> 'CustomController@about',
        '/about/more'=> function() { return View::make('templates.about-more'); },
    );

    $parts = explode('?',$_SERVER["REQUEST_URI"]);
    $path = $parts[0];
    if(array_key_exists($path, $custom_routes))
    {
        status_header(200);
        if(is_string($custom_routes[$path]))
        {
            $call_parts = explode('@',$custom_routes[$path]);
            $controller = new $call_parts[0];
            return $controller->$call_parts[1](null,null);
        }
        else if(is_callable($custom_routes[$path]))
        {
            return $custom_routes[$path](null, null);
        }
    }
    return View::make('404',array('path'=>$path));
});
```

**Comment by jlambe** [comment]
Nice tip, this might be useful at some point.

**Comment by jlambe** [comment]
We can now use the Illuminate Routing package for custom routes. Probably need to flush rewrite rules of WordPress the first time you defined your custom routes.
