### ISSUE TITLE
Infinite fields in infinite fields is broken

### ISSUE THREAD

**Issue by zoontek** [themosis/framework#82]
Hello Julien. When you create an infinite field inside an infinite field, it renders well, but do very weird stuff on add / delete (create, like, 5 fields, delete the wrong one, etc)

``` php
Metabox::make('Books', 'library', [
    'context'   => 'normal',
    'priority'  => 'high'
])->set([
    Field::infinite('books', [
        Field::text('title'),
        Field::textarea('excerpt'),
        Field::media('cover-image'),
        Field::infinite('edition', [
            Field::text('name')
        ])
    ])
]);
```

**Comment by jlambe** [comment]
Hi,

yes this issue is known. Currently you can't nest infinite fields but a fix is planned on next release. The issue is about DOM selection.

**Comment by jlambe** [comment]
Fix selectors but this is going to be reported to version 1.4.0 with the rewrite of the field API.
