### ISSUE TITLE
Support to PHP 8

### ISSUE THREAD

**Issue by f-liva** [themosis/framework#822]
Using PHP 8 and trying access /cms/wp-admin I get this error:

`Fatal error: Uncaught ErrorException: Method ReflectionParameter::getClass() is deprecated in /app/vendor/illuminate/container/Container.php:853 Stack trace: #0 /app/vendor/illuminate/container/Container.php(853): Themosis\Core\Bootstrap\ExceptionHandler->handleError(8192, 'Method Reflecti...', '/app/vendor/ill...', 853) #1 /app/vendor/illuminate/container/Container.php(816): Illuminate\Container\Container->resolveDependencies(Array) #2 /app/vendor/illuminate/container/Container.php(667): Illuminate\Container\Container->build('App\\Exceptions\\...') #3 /app/vendor/illuminate/container/Container.php(265): Illuminate\Container\Container->resolve('App\\Exceptions\\...', Array, false) #4 /app/vendor/illuminate/container/Container.php(785): Illuminate\Container\Container->Illuminate\Container\{closure}(Object(Themosis\Core\Application), Array) #5 /app/vendor/illuminate/container/Container.php(667): Illuminate\Container\Container->build(Object(Closure)) #6 /app/vendor/illuminate/container/Container.php(615): Illuminate\Container\Container->resolve('Illuminate\\Cont...', Array) #7 /app/vendor/themosis/framework/src/Core/Application.php(1099): Illuminate\Container\Container->make('Illuminate\\Cont...', Array) #8 /app/vendor/themosis/framework/src/Core/Bootstrap/ExceptionHandler.php(148): Themosis\Core\Application->make('Illuminate\\Cont...') #9 /app/vendor/themosis/framework/src/Core/Bootstrap/ExceptionHandler.php(138): Themosis\Core\Bootstrap\ExceptionHandler->getExceptionHandler() #10 /app/vendor/themosis/framework/src/Core/Bootstrap/ExceptionHandler.php(75): Themosis\Core\Bootstrap\ExceptionHandler->renderHttpResponse(Object(ErrorException)) #11 [internal function]: Themosis\Core\Bootstrap\ExceptionHandler->handleException(Object(ErrorException)) #12 {main} thrown in /app/vendor/illuminate/container/Container.php on line 853`

Downgrading to PHP 7.4 all works fine.

Any plans to add support to PHP 8?

**Comment by jlambe** [comment]
Support to PHP 8 is coming with the next iteration. Current only the master branch is compatible with PHP 8 but not yet stable.

**Comment by goigarg** [comment]
can we use PHP 8 now?
