### ISSUE TITLE
Assets don't get enqueued - Fluent Forms Pro

### ISSUE THREAD

**Issue by wpinfusion** [themosis/framework#858]
- Themosis Version: 1.3
- WordPress Version: 5.8.3
- PHP Version: 7.4.1

### Description
Fluent Forms Pro assets won't enqueue. The pro version required the free base plugin which is installed. The base plugin's assets get enqueued fine. But the pro addon which adds file uploads (using jQuery) has several JS scripts that just don't get loaded at all.

The result is that file uploads in Fluent Forms simply don't work. And perhaps other features as well.

I've contacted Fluent Forms support but they said it was an issue with Themosis.

#### Query Monitor
On a non-Themosis demo site:
![image](https://user-images.githubusercontent.com/56922068/169032620-63e16087-f81e-470b-9da9-23952584526a.png)

On the Themosis site:
![image](https://user-images.githubusercontent.com/56922068/169033085-a19db2ea-eacc-48d0-b35c-37e8faac111f.png)

### Steps to reproduce
Install Fluent Forms and the Pro addon. Add a form with a file upload field.

### Expected behavior
The ability to upload files.

**Comment by jlambe** [comment]
Thanks for submitting the issue but we don't provide support for external and commercial plugins.
