### ISSUE TITLE
FieldBuilder missing

### ISSUE THREAD

**Issue by adrix71** [themosis/framework#869]
Hello,
studying the source code of the framework I realized that the `Themosis\Forms\Contracts\FormFactoryInterface`  using a class that does not exist and to be precise the `FormBuilder` class which should be in `Themosis\Field\Fields`

Is this a bug or is it a feature that will be implemented in the future?

Thanks so much for the replies.
Adriano

**Comment by jlambe** [comment]
@adrix71 Thanks for catching this one. It's incorrect, the default class to use is `Themosis\Forms\FormBuilder`. Going to update it now 😄

**Comment by adrix71** [comment]
Thanks jlambe for response and fix
