### ISSUE TITLE
 Metabox Field rules error message not showing up 

### ISSUE THREAD

**Issue by adrix71** [themosis/framework#872]
I re open the problem because just today I am experiencing the error message does not appear and the problem is not solved.

Mi installation is:
WordPress Version: 6.0.2
Themosis Framework Version: 2.1.0
PHP Version: 8.0.1

The step to reproduce the problem is the same as described in this post: https://github.com/themosis/framework/issues/673

Thanks in advanced for assistence.
Adriano

**Comment by jlambe** [comment]
Unfortunately I can't reproduce the error... Please note that pressing the default "save/update" button of a post does not save the custom fields and do not perform any validation. You can only save custom fields using the metabox save button located at the bottom of the box.

Note the upcoming release do handle custom fields save using default button.

**Comment by adrix71** [comment]
You wrote in the guide that saving or updating a post or other content does not affect themosis metaboxes, but here we are beyond.  We are in non-functioning.  It is evident that themosis is an academic project, immature like Laravel and totally inadequate.

**Comment by jlambe** [comment]
Unless you can spot what could cause your issue in order to help us improve the project, you are free to find our project inadequate and choose another tool for your own good. Thank you for your contribution.
