### ISSUE TITLE
Adding custom menu items not working

### ISSUE THREAD

**Issue by johnnypea** [themosis/framework#88]
I can't add the menu items because the accordion with item groups is not working/opening. It seems to be some JS conflict because it only appears in "production" where I have SCRIPT_DEBUG set to FALSE. I found out that /wp-admin/js/accordion.js script is loaded after "themosis-core-scripts" when SCRIPT_DEBUG debug is ON. I tried to load "themosis-core-scripts" in the header ($mixed => false) and everything was fine.

I had no time to further investigate this and I just want to know if you can reproduce this. Thanks.

**Comment by jlambe** [comment]
I don't really understand what you're trying to achieve. Are you talking about adding menu locations using the `menus.config.php` file? If not, give more explanation and also share all the code you have that could reproduce this issue so I can test it. Thanks ;)

**Comment by johnnypea** [comment]
I mean http://codex.wordpress.org/Appearance_Menus_Screen

There is no need for any code because it's just not working for me when I have themosis-framework mu-plugin loaded as is.

**Comment by jlambe** [comment]
On a clean installation, I can't reproduce this issue. Do you have other plugins activated? Also, what's happening when you enqueue media files using this code:

```php
// Inside admin/application.php
add_action('admin_enqueue_scripts', function()
{
    wp_enqueue_media();
});
```

Does it fix your problem?

**Comment by johnnypea** [comment]
Did you set `define('SCRIPT_DEBUG', false);`? Because it's working with `define('SCRIPT_DEBUG', true)`;.

Enqueueing `wp_enqueue_media()` did help too.

**Comment by jlambe** [comment]
Yes it does work with `SCRIPT_DEBUG` set to `false` or `true`. The issue you have is that a core js script is not loaded or loaded after the framework js script. But I don't understand how it can affect menu creation. Everything is working fine with or without `wp_enqueue_media()` function.

Do you have other plugins installed? Which version of WordPress do you use? Do you the latest framework plugin version (1.1.2)?

**Comment by johnnypea** [comment]
Completely clean install following this http://framework.themosis.com/docs/installation/

For some reason "accordion" script responsible for opening boxes on the left at /wp-admin/nav-menus.php is not loaded so they're not working.

WP 4.1
Apache 2.2.29 (Unix)
PHP 5.5.18
MySQL 5.5.38

**Comment by jlambe** [comment]
Alright, I got the same bug :)) Took me some time but you're right there is an issue with this.
Sorry for this, I was focusing on creating menus and not the accordion panel on the left :(

Currently the only solution I have is to by default, load the media scripts/files so this work as expected. I'll probably add this by default in a theme package update.
