### ISSUE TITLE
Themosis throws ErrorException for deprecations

### ISSUE THREAD

**Issue by reneroboter** [themosis/framework#880]
- Themosis Version: 3.0.0
- WordPress Version: 6.1.1
- PHP Version: 8.1.6

### Description

I use a third-party WordPress plugins from Yoast which has still deprecation warnings. Themosis throw a `ErrorException` for deprecation warnings when debugging is enabled. The reason is the custom registered error handler at `Themosis\Core\Bootstrap`. The `handleError` method doesn't consider custom `error_reporting` levels.

### Steps to reproduce

- Enable debugging with `APP_DEBUG=true` in your `.env`
- Force a deprecation warning e.g. with [`FILTER_SANITIZE_STRING`](https://www.php.net/manual/en/filter.filters.sanitize.php)

### Expected behavior

- The error handler understand custom error_reporting settings
- The error handler don't throw a exception for deprecations cause even WordPress had a ton of warnings

### Further informations

- https://www.php.net/manual/en/function.set-error-handler.php
- https://wordpress.org/support/topic/deprecation-warnings-php-8-1/

**Comment by jlambe** [comment]
@reneroboter Thanks for reporting this issue. I haven't yet a fix ready for you but a solution is on its way where we can filter out deprecations from the `handleError` method.

My only recommandation for now is to turn off direct reporting by setting the `APP_DEBUG` variable to `false`. Errors are still logged in the `storage/logs` directory but at least you won't be annoyed by error exception rendering.

**Comment by jlambe** [comment]
@reneroboter [Deprecations support](https://github.com/themosis/framework/blob/265b054162475e41e3c2ca236ec75bde7592e39f/src/Core/Bootstrap/ExceptionHandler.php#L60) is now merged into the `3.0` branch. It's going to be released very soon.
