### ISSUE TITLE
themosis stores the node folder in the database

### ISSUE THREAD

**Issue by havasjeancarlostrabajo** [themosis/framework#882]
- Themosis Version: 2.1
- WordPress Version: 6.1
- PHP Version: 7.4

### Description
themosis is storing the content of the node folder in the database

![image](https://user-images.githubusercontent.com/96260366/203168056-f3a46d0d-5c7d-4f0a-841e-774bf53c591c.png)

I can't find how to avoid this, since it occupies a lot of weight in my database.

I found that it stores the theme

wp-content/themes/my_theme/node_modules/

**Comment by jlambe** [comment]
The Themosis core and bootstrapped theme do not contain code that parses the `node_modules` directory. There is no code performing any SQL queries on behalf of the user as well.
I think the issue you have might be related to one of your installed plugins. Re-install WordPress using a fresh database and activate your plugins one by one to find which one is doing this.

**Comment by havasjeancarlostrabajo** [comment]
the plugin is "wordfence" thanks jlambe
