### ISSUE TITLE
Php artisan don't working after upgrade

### ISSUE THREAD

**Issue by Bartiff** [themosis/framework#885]
- Themosis Version: 3.0
- WordPress Version: 6.1.1
- PHP Version: 8.0.25

### Description
I'm trying to upgrade a project from themosis 2 to 3 by following the instructions here: https://framework.themosis.com/docs/3.0/upgrade#upgrade-from-20-to-30

The ```php artisan``` command does not seem to work I get this error:

```
> Themosis\Core\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi
PHP Fatal error:  Uncaught ReflectionException: Class "env" does not exist in /pathtofolder/vendor/illuminate/container/Container.php:877
```

### Steps to reproduce
Follow the instructions in the documentation then do ```composer update``` or ```php artisan``` directly.

**Comment by Bartiff** [comment]
Ok I succeeded.
You must check changes in files of the config folder and don't forget to add the new files ```BroadcastServiceProvider.php``` and ```EventServiceProvider.php``` to upgrade your Themosis.

**Comment by jlambe** [comment]
Thanks for your feedback, will try to update the notes on the upgrade guide.

**Comment by danieldunderfelt** [comment]
I have followed the upgrade instructions, still getting the error after composer install:

Fatal error: Uncaught ReflectionException: Class "env" does not exist

**Comment by Bartiff** [comment]
Try to compare  files and directories with fresh install of Themosis 3.1 in particular in config files.

**Comment by danieldunderfelt** [comment]
Okay whew, I got it working! I thought I had checked everything but a few things were left over.
