### ISSUE TITLE
Problem with connection after "vagrant up" command

### ISSUE THREAD

**Issue by WebCraftersStudio** [themosis/framework#895]
Hello,

I'm working on macOS (Ventura) with M1 and after "vagrant up" command I see this error:

<img width="549" alt="Zrzut ekranu 2023-04-9 o 11 01 08" src="https://user-images.githubusercontent.com/55295218/230763812-454ad39e-53af-46bc-9657-3127ea3fe53b.png">

My version of VirtualBox is Developer preview for macOS / Arm64 (M1/M2) hosts

Copy of all process:

Bringing machine 'webcrafters-studio' up with 'virtualbox' provider...
==> webcrafters-studio: Checking if box 'laravel/homestead' version '13.0.0' is up to date...
==> webcrafters-studio: Clearing any previously set forwarded ports...
==> webcrafters-studio: Clearing any previously set network interfaces...
==> webcrafters-studio: Preparing network interfaces based on configuration...
    webcrafters-studio: Adapter 1: nat
    webcrafters-studio: Adapter 2: hostonly
==> webcrafters-studio: Forwarding ports...
    webcrafters-studio: 80 (guest) => 8000 (host) (adapter 1)
    webcrafters-studio: 443 (guest) => 44300 (host) (adapter 1)
    webcrafters-studio: 22 (guest) => 2222 (host) (adapter 1)
==> webcrafters-studio: Running 'pre-boot' VM customizations...
==> webcrafters-studio: Booting VM...
==> webcrafters-studio: Waiting for machine to boot. This may take a few minutes...
    webcrafters-studio: SSH address: 127.0.0.1:2222
    webcrafters-studio: SSH username: vagrant
    webcrafters-studio: SSH auth method: private key
    webcrafters-studio: Warning: Connection reset. Retrying...
The guest machine entered an invalid state while waiting for it
to boot. Valid states are 'starting, running'. The machine is in the
'aborted' state. Please verify everything is configured
properly and try again.

If the provider you're using has a GUI that comes with it,
it is often helpful to open that and watch the machine, since the
GUI often has more helpful error messages than Vagrant can retrieve.
For example, if you're using VirtualBox, run `vagrant up` while the
VirtualBox GUI is open.

The primary issue for this error is that the provider you're using
is not properly configured. This is very rarely a Vagrant issue.

**Comment by jlambe** [comment]
Sorry but I'm not mastering Vagrant and the issue you have is not related to the framework itself. I suggest you describe your issue on [stackoverflow](https://stackoverflow.com/) for help on setting up your environment with Vagrant.
