### ISSUE TITLE
Custom Rewrite Rules

### ISSUE THREAD

**Issue by nathanaelphilip** [themosis/framework#90]
Is there a way to use rewrite rules with Themosis?

I’ve tried this:

```
        # admin/application.php
	add_action( 'init', 'tm_rewrite_add_rewrites' );

	function tm_rewrite_add_rewrites()
	{
		add_rewrite_rule(
			'^account/(\d+)/?$', // p followed by a slash, a series of one or more digits and maybe another slash
			'index.php?account=$matches[1]',
			'top'
		);
	}

	add_filter( 'query_vars', 'tm_rewrite_add_var' );
	
	function tm_rewrite_add_var( $vars )
	{
		$vars[] = 'account';
		return $vars;
	}

       # admin/routing.php
	function is_variable($variable)
	{	
	    // Some logic that returns true or false.
	    return true;
	}
```

But I’m not seeing the account variable being set in query_vars. I’ve tried this on a normal WP install, and it works, but I’m just unsure on how to do the same for Themosis.

**Comment by jlambe** [comment]
Hi,
normally there is no conflict but I have not tested it.

For custom query var, I normally use the rewrite API function `add_rewrite_tag()` with the function `add_rewrite_rule`. So for your example, replace your `add_filter` call with this code inside an `init` action hook:

```php
add_action('init', function()
{
    add_rewrite_tag('%account%', '([^&]+)');
});
```
There is also a Todo List application I've written as an example that demonstrates the use of the Rewrite API, check this file for reference:
- https://github.com/themosis/todo/blob/master/htdocs/content/themes/tasks/app/admin/tasks.php

I hope this resolves your issue.

**Comment by nathanaelphilip** [comment]
I think so! I’m still new to rewrites. I’ll look over your ToDo application to see if I can figure it out. Thanks!
