### ISSUE TITLE
Add a "required" validation rule

### ISSUE THREAD

**Issue by jlambe** [themosis/framework#96]
In the validation class, add a required rule so the value must exists.

**Comment by cdarken** [comment]
How is this supposed to work? I'm using dev-master in my composer.json and I added a 'required' validation rule for a metabox field, but in the wp-admin it does not show an error if I don't fill the field.

**Comment by jlambe** [comment]
Currently, there is no admin "messages" if a validation failed. At the moment, the data return is an empty string if a validation fails. I'm still working on unifying form/validation and custom fields API so this is coming on a future release.

**Comment by cdarken** [comment]
I could live without admin messages for a while. The thing is that is does not appear to prevent the saving of the post if the required field is not filled.

**Comment by jlambe** [comment]
No it's not indeed. Will definitely come soon ;)

**Comment by cdarken** [comment]
Ok, thanks. I'm waiting for it!
Any idea when release 1.1.3 will be out?
And great job with this framework, you've made Wordpress enjoyable to work on.

**Comment by jlambe** [comment]
The release is planned this thursday. But if you use "dev-master" branch on your composer.json file, you already get the same features as 1.1.3. It's a minor update which do not need any change in your code. More features will come for the major update 1.2.0 which is next ;) and thanks!
