### ISSUE TITLE
Fields to use custom template feature

### ISSUE THREAD

**Issue by rovillesarate** [themosis/framework#97]
Hi! Is there a way to apply custom templates for fields?
like this * Field::text('name', array('title' => 'Name', 'info'=> 'Info', 'default'=> 'Default', 'template')),

so instead of displaying the field this way
Name [                                     ]
you can display it with
Name
[                                ]

being able to specify a template for the field will be useful. so you can use columns and better formatting for the metabox.

**Comment by ramon-villain** [comment]
:+1:

**Comment by jlambe** [comment]
Hi,

currently you can't change the look of the fields. There is an API in progress in order to create your own fields where you'll be able to specify your own view but it's not yet ready.

As for custom template for existing fields, it could be a nice feature but there is no plan yet for that.
