### ISSUE TITLE
Route Filter

### ISSUE THREAD

**Issue by fabianmarz** [themosis/framework#98]
Is there a way to attach route filters like it's possible in Laravel? I want to check if a user is logged in before he has access to a specific route.

Currently I'm solving this by checking this in the resolved controllers method.

**Comment by jlambe** [comment]
Currently, there are no filters available. Your method is the way to go. Check any condition inside a route closure or a controller method.

Another way might be a View::composer as well depending on the scenario.

**Comment by fabianmarz** [comment]
Okay, thanks for response!

Julien Lambé <notifications@github.com> schrieb am Di., 3. März 2015 07:42:
